activemerchant/active_merchant

Gemfile
Gemfile_common
lib/active_merchant/billing/gateways/quickbooks.rb
test/fixtures.yml
test/remote/gateways/remote_quickbooks_test.rb
test/unit/gateways/quickbooks_test.rb

Adds QuickBooks Payments gateway integration. 
Increments of work done:

QuickBooks Payments 

---

CHANGELOG
CONTRIBUTORS
README.md

Updates appropriate literature.
@j-mutter /cc @ivanfer @ntalbott

update CHANGELOG, README and CONTRIBUTORS to reflect addition of QuickBooks Payments adapter

---

CONTRIBUTING.md
README.md
RELEASING

Add a **CONTRIBUTING.md** file, which will be displayed when people open new issues or pull requests.
I moved some stuff from README and other files into this file.
@Shopify/payments @ntalbott do you agree with the guidelines in here?

Add CONTRIBUTING.md

---

lib/active_merchant/billing/gateways/pay_gate_xml.rb
test/remote/gateways/remote_pay_gate_xml_test.rb
test/unit/gateways/pay_gate_xml_test.rb

Merge commit function and commit_capture

[PayGate] Accept :email and :ip to authorization

---

CHANGELOG
lib/active_merchant/version.rb

Last version before we drop ruby 1.9
@ntalbott @wvanbergen @girasquid any open PRs that you can think of that should go in before we do this?

Version 1.47.0

---

CHANGELOG
lib/active_merchant/billing/gateway.rb
lib/active_merchant/billing/gateways/pay_conex.rb
test/fixtures.yml
test/remote/gateways/remote_pay_conex_test.rb
test/unit/gateways/pay_conex_test.rb

PayConex: Add gateway

---

lib/active_merchant/billing/gateways/stripe.rb
test/remote/gateways/remote_stripe_test.rb
test/unit/gateways/stripe_test.rb

Add decrypted apple pay support for Stripe
@rwdaigle @bizla for review please, thanks!
cc @louiskearns

Add apple pay support for Stripe

---

CHANGELOG
lib/active_merchant/billing/gateways/ogone.rb
test/remote/gateways/remote_ogone_test.rb
test/unit/gateways/ogone_test.rb

Also: Refactor signature calculation
@rwdaigle can I get a review here?

Ogone: Add additional 3d-secure parameters

---

lib/active_merchant/billing/gateways/moneris.rb

fix spacing

---

CONTRIBUTING.md

Update "Gateway Placement within Shopify" section to reflect our current stance.
@louiskearns @lyverovski @ntalbott

Update placement within Shopify

---

CHANGELOG
lib/active_merchant/billing/gateways/jetpay.rb
test/remote/gateways/remote_jetpay_test.rb

JetPay: Adjust refund and void transaction types

---

CHANGELOG
lib/active_merchant/billing/gateways/wepay.rb
test/remote/gateways/remote_wepay_test.rb
test/unit/gateways/wepay_test.rb

```
$ RUBYOPT=W0 be rake test:remote TEST=test/remote/gateways/remote_wepay_test.rb 
Started
.....................
Finished in 188.314914 seconds.
21 tests, 35 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
0.11 tests/s, 0.19 assertions/s
```

WePay: Add scrub method

---

test/remote/gateways/remote_authorize_net_test.rb

Mandatory email and billing address was breaking a bunch of tests which is fixed in this commit.
---
```
$ RUBYOPT=W0 be rake test:remote TEST=test/remote/gateways/remote_authorize_net_test.rb 
Finished in 63.271614 seconds.
55 tests, 190 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
0.87 tests/s, 3.00 assertions/s
```

ANet: Fix remote tests

---

CHANGELOG
lib/active_merchant/billing/gateways/jetpay.rb

XML changes to talk to JetPay 2.2
---
```
$ RUBYOPT=W0 be rake test:remote TEST=test/remote/gateways/remote_jetpay_test.rb 
Finished in 31.89078 seconds.
16 tests, 88 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
0.50 tests/s, 2.76 assertions/s
```

JetPay: Update API 2.2

---

CHANGELOG
lib/active_merchant/billing/gateways/global_collect.rb
test/unit/gateways/global_collect_test.rb

Adds boolean flag for pre-authorization.
Remote Tests:
15 tests, 35 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
Unit Tests:
14 tests, 64 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed

Global Collect: Adds pre-authorization

---

CHANGELOG
lib/active_merchant/billing/gateways/cardprocess.rb
test/fixtures.yml
test/remote/gateways/remote_cardprocess_test.rb
test/unit/gateways/cardprocess_test.rb

Implement Cardprocess Gateway
Furthers ENRG-6967

Implement CardProcess Gateway

---

CHANGELOG

Update to changelog
Closes 2680

iATS: Fix Messages with Failure on iATS Server

---

test/remote/gateways/remote_payment_express_test.rb

Unit tests:
33 tests, 238 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote tests:
1 tests, 3 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Payment Express: Fix remote tests

---

CHANGELOG
lib/active_merchant/billing/gateways/card_connect.rb
test/fixtures.yml
test/remote/gateways/remote_card_connect_test.rb
test/unit/gateways/card_connect_test.rb

Adds a new gateway card_connect to Active Merchant
Loaded suite test/remote/gateways/remote_card_connect_test
...................
19 tests, 45 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Loaded suite test/unit/gateways/card_connect_test
16 tests, 74 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

CardConnect: Add new gateway

---

CHANGELOG

Barclaycard Smartpay 3DS implementation changelog

Changelog Update

---

CHANGELOG
lib/active_merchant/billing/gateways/payeezy.rb
test/remote/gateways/remote_payeezy_test.rb
test/unit/gateways/payeezy_test.rb

This updates the store method based on changes in the Payeezy
documentation taking effect at the end of March.
Loaded suite test/remote/gateways/remote_payeezy_test
...........................
27 tests, 98 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Loaded suite test/unit/gateways/payeezy_test
................................
32 tests, 153 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Payeezy: Update Store

---

CHANGELOG
lib/active_merchant/billing/gateways/worldpay.rb

Updates the Country list for Worldpay
.....................................
37 tests, 210 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

WorldPay: Update Country List

---

lib/active_merchant/billing/gateways/realex.rb
test/unit/gateways/realex_test.rb

Updates Country List for Realex to include Spain.
Loaded suite test/unit/gateways/realex_test
21 tests, 439 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
------
Loaded suite test/remote/gateways/remote_realex_test
20 tests, 108 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Realex: Update Country List

---

CHANGELOG
lib/active_merchant/billing/gateways/moneris_us.rb
test/remote/gateways/remote_moneris_us_test.rb
test/unit/gateways/moneris_us_test.rb

Adds ACH capabilities to Moneris US Gateway
One failing test for CVV verification that are unrelated to these
changes.
Loaded suite test/remote/gateways/remote_moneris_us_test
Failure: test_cvv_no_match_when_enabled(MonerisUsRemoteTest)
30 tests, 118 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
Loaded suite test/unit/gateways/moneris_us_test
33 tests, 164 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Moneris US: Add ACH

---

CONTRIBUTING.md

I feel it's time we make this more explicit instead if keeping PRs unmerged for months on end.

Update contributing document regarding gateways

---

.rubocop.yml

This is counterproductive when it comes to tests.

Do not care about test module/class lengths

---

CHANGELOG
lib/active_merchant/billing/gateways/firstdata_e4_v27.rb
test/unit/gateways/firstdata_e4_v27_test.rb

Unit: 30 tests, 139 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 23 tests, 92 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

FirstData E4 v27: Support WalletProviderID

---

CHANGELOG
lib/active_merchant/billing/gateways/worldpay.rb
test/remote/gateways/remote_worldpay_test.rb
test/unit/gateways/worldpay_test.rb

Unit: 38 tests, 217 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 1 of 1 passed so far; each test takes like a minute

Worldpay: support instalments

---

CHANGELOG
lib/active_merchant/billing/gateways/global_collect.rb
test/remote/gateways/remote_global_collect_test.rb

Unit: 17 tests, 78 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 16 tests, 38 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Global Collect: allow partial captures

---

CHANGELOG
lib/active_merchant/billing/gateways/adyen.rb
test/remote/gateways/remote_adyen_test.rb
test/unit/gateways/adyen_test.rb

Unit: 23 tests, 109 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 35 tests, 88 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Adyen: add Maestro and Electron support

---

CHANGELOG
lib/active_merchant/billing/gateways/conekta.rb
lib/active_merchant/billing/gateways/openpay.rb

Unit: 3927 tests, 68207 assertions, 0 failures, 0 errors, 0 pendings, 2 omissions, 0 notifications
100% passed

Enable Carnet for Conekta and Openpay

---

.rubocop.yml
.rubocop_todo.yml
lib/active_merchant/billing/gateways/card_connect.rb
lib/active_merchant/billing/gateways/cardprocess.rb
lib/active_merchant/billing/gateways/cashnet.rb
lib/active_merchant/billing/gateways/firstdata_e4.rb
lib/active_merchant/billing/gateways/firstdata_e4_v27.rb
lib/active_merchant/billing/gateways/migs.rb
lib/active_merchant/billing/gateways/mundipagg.rb
lib/active_merchant/billing/gateways/paymentez.rb
lib/active_merchant/billing/gateways/world_net.rb

This is dramatically the smaller of the two possibilties.
trailing: 10 files changed, 43 insertions(+), 43 deletions(-)
leading: 127 files changed, 699 insertions(+), 699 deletions(-)

RuboCop: fix Layout/DotPosition

---

.rubocop.yml
.rubocop_todo.yml
lib/active_merchant/billing/credit_card_formatting.rb
lib/active_merchant/billing/gateway.rb
lib/active_merchant/billing/gateways/authorize_net.rb
lib/active_merchant/billing/gateways/authorize_net_cim.rb
lib/active_merchant/billing/gateways/balanced.rb
lib/active_merchant/billing/gateways/braintree_blue.rb
lib/active_merchant/billing/gateways/card_stream.rb
lib/active_merchant/billing/gateways/clearhaus.rb
lib/active_merchant/billing/gateways/eway_managed.rb
lib/active_merchant/billing/gateways/firstdata_e4.rb
lib/active_merchant/billing/gateways/moneris.rb
lib/active_merchant/billing/gateways/moneris_us.rb
lib/active_merchant/billing/gateways/netbanx.rb
lib/active_merchant/billing/gateways/omise.rb
lib/active_merchant/billing/gateways/pac_net_raven.rb
lib/active_merchant/billing/gateways/payflow.rb
lib/active_merchant/billing/gateways/payment_express.rb
lib/active_merchant/billing/gateways/paymill.rb
lib/active_merchant/billing/gateways/sage_pay.rb
lib/active_merchant/billing/gateways/trust_commerce.rb
lib/active_merchant/billing/response.rb

Fixes some issues with indention and alignment with cases and elses.

Rubocop: Layout/CaseIndention and Layout/ElseAlignment

---

CHANGELOG
lib/active_merchant/billing/gateways/adyen.rb
test/remote/gateways/remote_adyen_test.rb
test/unit/gateways/adyen_test.rb

Returns the result of avs and cvc in the response if it is provided.
Loaded suite test/unit/gateways/adyen_test
........................
24 tests, 115 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
----------------------------------------------------------------------------------------
....................................
36 tests, 90 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Adyen: Return AVS and CVC Result

---

test/fixtures.yml

Remote: 29 tests, 114 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Moneris: fix remote test creds

---

CHANGELOG
lib/active_merchant/billing/gateways/optimal_payment.rb
test/remote/gateways/remote_optimal_payment_test.rb

Adds verify to optimal payment.
Loaded suite test/remote/gateways/remote_optimal_payment_test
Started
16 tests, 73 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Loaded suite test/unit/gateways/optimal_payment_test
...................
19 tests, 75 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Optimal Payment: Add verify capabilities

---

CHANGELOG
lib/active_merchant/billing/gateways/clearhaus.rb
test/unit/gateways/clearhaus_test.rb

Unit: 22 tests, 110 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 23 tests, 70 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Clearhaus: update submission data format

---

CHANGELOG

Forgot to add that to my release 🤦‍♂️

Missing CHANGELOG release title

---

lib/active_merchant/billing/gateways/trust_commerce.rb
test/unit/gateways/trust_commerce_test.rb

ENE-64
Unit:
10 tests, 34 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
16 tests, 56 assertions, 5 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
68.75% passed
- Failures existing on earlier commits, not related to change made in
this commit.

TrustCommerce: Scrubs password from transcript

---

CHANGELOG
lib/active_merchant/billing/gateways/adyen.rb
test/remote/gateways/remote_adyen_test.rb
test/unit/gateways/adyen_test.rb

This reverts commit 81625443efcab62809f4296e2363eb047c28c320.

Revert "Adyen: Idempotency for non-purchase requests"

---

CHANGELOG
lib/active_merchant/billing/gateways/d_local.rb
test/unit/gateways/d_local_test.rb

ECS-246
Unit:
100% passed
Remote:
21 tests, 59 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

DLocal: Send country as string

---

lib/active_merchant/billing/gateways/credorax.rb
lib/active_merchant/billing/gateways/cyber_source.rb
lib/active_merchant/billing/gateways/kushki.rb
lib/active_merchant/billing/gateways/paypal.rb
test/unit/gateways/paypal_test.rb

Updates supported countries for Credorax, CyberSource, Kushki, Paypal

---

CHANGELOG
lib/active_merchant/billing/gateways/nmi.rb
test/unit/gateways/nmi_test.rb

Accounts for the possibility of symbols in passwords rather than just
letters/digits and scrubs accordingly
ECS-317
Unit:
45 tests, 342 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
Remote:
41 tests, 151 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed

NMI: Scrub symbols from passwords

---

lib/active_merchant/billing/gateways/payflow.rb
test/remote/gateways/remote_payflow_test.rb
test/unit/gateways/payflow_test.rb

Still needed: 
~[x] L2 implementation or refactor~
~[x] Line item management~ -- For expediency's sake, this can be done as per the original "like Stripe" idea, only passing a blob of XML instead of JSON.
~[3/3] Remote tests~
[] Unit tests (make sure we're sending all the XML we think we are)
Known issues: 
Not obvious whether all L2/L3 fields are supported or only those documented in XMLPay.
Remote tests pass, but don't (so far) include any info about whether the fields were received/understood.

Payflow: support arbitrary L2/L3 fields

---

CHANGELOG

Re-add removed entry in https://github.com/activemerchant/active_merchant/pull/3007/files

Re-add removed changelog entry

---

CHANGELOG
lib/active_merchant/billing/gateways/stripe.rb

[CE-122](https://spreedly.atlassian.net/browse/CE-122)
Unit tests:
135 tests, 722 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote tests:
100% passed

Stripe: add countries to supported list

---

.rubocop_todo.yml
CHANGELOG
lib/active_merchant/billing/avs_result.rb
lib/active_merchant/billing/gateways/exact.rb
lib/active_merchant/billing/gateways/hps.rb
lib/active_merchant/billing/gateways/merchant_ware.rb
lib/active_merchant/billing/gateways/metrics_global.rb
lib/active_merchant/billing/gateways/optimal_payment.rb
lib/active_merchant/billing/gateways/payflow/payflow_express_response.rb
lib/active_merchant/billing/gateways/so_easy_pay.rb
test/remote/gateways/remote_barclaycard_smartpay_test.rb
test/remote/gateways/remote_braintree_orange_test.rb
test/remote/gateways/remote_efsnet_test.rb
test/remote/gateways/remote_eway_test.rb
test/remote/gateways/remote_inspire_test.rb
test/remote/gateways/remote_merchant_e_solutions_test.rb
test/remote/gateways/remote_netbilling_test.rb
test/remote/gateways/remote_orbital_test.rb
test/remote/gateways/remote_paymentez_test.rb
test/remote/gateways/remote_quickbooks_test.rb
test/unit/gateways/barclaycard_smartpay_test.rb
test/unit/gateways/braintree_blue_test.rb
test/unit/gateways/linkpoint_test.rb
test/unit/gateways/orbital_test.rb
test/unit/gateways/pago_facil_test.rb
test/unit/gateways/payflow_express_test.rb
test/unit/gateways/paypal_express_test.rb

Ensures that closing hash braces are symmetrical to their opening braces.

Rubocop: Layout/MultilineHashBraceLayout

---

lib/active_merchant/billing/gateways/card_connect.rb
test/remote/gateways/remote_card_connect_test.rb

CardConnect: always include additional_data in purchase

---

CHANGELOG
lib/active_merchant/billing/gateways/card_connect.rb
test/remote/gateways/remote_card_connect_test.rb

CE-169
Remote tests:
24 tests, 57 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit tests:
22 tests, 92 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

CardConnect: Add user_fields GSF

---

test/remote/gateways/remote_ixopay_test.rb
test/unit/gateways/ixopay_test.rb

Covering any follow-up items from https://github.com/activemerchant/active_merchant/pull/3412.

CE-137 follow-up

---

CHANGELOG
lib/active_merchant/billing/gateways/ixopay.rb
test/fixtures.yml
test/remote/gateways/remote_ixopay_test.rb
test/unit/gateways/ixopay_test.rb

This is an integration branch for Ixopay code that has already been reviewed and approved. The purpose of this PR is visibility and CI while squashing the Ixopay commits and updating the changelog.

Ixopay gateway adapter

---

lib/active_merchant/billing/gateways/ixopay.rb

Refactored the `capture` transaction for the new Ixopay gateway in order
to correctly use the Nokogiri::XML::Builder syntax for method names.
This greatly simplies the code while still passing all of the remote and
unit tests.
For more details, see the Nokogiri::XML::Builder documentation:
https://www.rubydoc.info/github/sparklemotion/nokogiri/Nokogiri/XML/Builder
Unit:
15 tests, 68 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
Remote:
16 tests, 57 assertions, 0 failures, 0 errors, 0 pendings, 1 omissions,
100% passed

Ixopay: Refactor capture

---

.rubocop_todo.yml
CHANGELOG
lib/active_merchant/billing/gateway.rb
lib/active_merchant/billing/gateways/authorize_net.rb
lib/active_merchant/billing/gateways/balanced.rb
lib/active_merchant/billing/gateways/card_stream.rb
lib/active_merchant/billing/gateways/cecabank.rb
lib/active_merchant/billing/gateways/clearhaus.rb
lib/active_merchant/billing/gateways/culqi.rb
lib/active_merchant/billing/gateways/eway_rapid.rb
lib/active_merchant/billing/gateways/firstdata_e4.rb
lib/active_merchant/billing/gateways/moneris_us.rb
lib/active_merchant/billing/gateways/ogone.rb
lib/active_merchant/billing/gateways/optimal_payment.rb
lib/active_merchant/billing/gateways/orbital.rb
lib/active_merchant/billing/gateways/pac_net_raven.rb
lib/active_merchant/billing/gateways/pay_junction.rb
lib/active_merchant/billing/gateways/payu_in.rb
lib/active_merchant/billing/gateways/sage_pay.rb
lib/active_merchant/billing/gateways/trust_commerce.rb
lib/active_merchant/billing/gateways/usa_epay_advanced.rb
lib/active_merchant/billing/response.rb
lib/active_merchant/connection.rb

Fixes alignment errors where `end` statements were not correctly aligned
with the associated `if` or `case` statements.
Unit:
4340 tests, 70985 assertions, 0 failures, 0 errors, 0 pendings,
100% passed
RuboCop:

RuboCop: Fix Layout/EndAlignment

---

lib/active_merchant/billing/gateways/ixopay.rb
test/remote/gateways/remote_ixopay_test.rb
test/unit/gateways/ixopay_test.rb

CE-144
Also filled out the `test_invalid_login` remote test. 
Remote: 23 tests, 95 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit: 22 tests, 108 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Ixopay: Implement extraData GSF

---

CHANGELOG
Gemfile
lib/active_merchant/billing/gateways/blue_snap.rb
test/remote/gateways/remote_blue_snap_test.rb
test/unit/gateways/blue_snap_test.rb

CE-188
Unit:
30 tests, 142 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 
40 tests, 122 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Bluesnap: include fraud data in response message

---

CHANGELOG
Gemfile
lib/active_merchant/billing/gateways/global_collect.rb
test/remote/gateways/remote_global_collect_test.rb
test/unit/gateways/global_collect_test.rb

CE-252
Unit:
21 tests, 96 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
18 tests, 42 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Ingenico Global Collect: support airline_data GSFs

---

CHANGELOG
lib/active_merchant/billing/gateways/credorax.rb
test/remote/gateways/remote_credorax_test.rb
test/unit/gateways/credorax_test.rb

Remote: 39 tests, 144 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit: 61 tests, 293 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
CE-292

Credorax: authorization_type and multiple_capture_count GSFs

---

CHANGELOG

This adds a missing changelog from #3495.

add missing changelog from #3495

---

lib/active_merchant/billing/gateways/hps.rb
test/fixtures.yml
test/remote/gateways/remote_hps_test.rb
test/unit/gateways/hps_test.rb

CE-205
Unit:
36 tests, 179 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
All remote tests pass between existing credentials and new credentials, but some things aren't yet turned on for new credentials (I've sent an email).

HPS: support check payments

---

CHANGELOG
lib/active_merchant/billing/gateways/kushki.rb
test/remote/gateways/remote_kushki_test.rb
test/unit/gateways/kushki_test.rb

Some notes inline. :)
Unit: 15 tests, 98 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 13 tests, 42 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
CE-463

Kushki: support preAuthorize and capture

---

CHANGELOG

CHANGELOG cleanup related to CE-189
77 tests, 345 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
test/remote/gateways/remote_cyber_source_test.rb contains 5 pre-existing, unrelated test failures:
- test_successful_3ds_validate_authorize_request
- test_successful_3ds_validate_purchase_request
- test_successful_pinless_debit_card_puchase
- test_successful_tax_calculation
- test_successful_validate_pinless_debit_card
76 tests, 389 assertions, 5 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
93.4211% passed

CyberSource: Add support for MerchantInformation

---

.rubocop_todo.yml
CHANGELOG
lib/active_merchant/billing/gateways/adyen.rb
lib/active_merchant/billing/gateways/authorize_net.rb
lib/active_merchant/billing/gateways/beanstream/beanstream_core.rb
lib/active_merchant/billing/gateways/borgun.rb
lib/active_merchant/billing/gateways/cardknox.rb
lib/active_merchant/billing/gateways/checkout.rb
lib/active_merchant/billing/gateways/efsnet.rb
lib/active_merchant/billing/gateways/element.rb
lib/active_merchant/billing/gateways/fat_zebra.rb
lib/active_merchant/billing/gateways/firstdata_e4.rb
lib/active_merchant/billing/gateways/firstdata_e4_v27.rb
lib/active_merchant/billing/gateways/forte.rb
lib/active_merchant/billing/gateways/iridium.rb
lib/active_merchant/billing/gateways/litle.rb
lib/active_merchant/billing/gateways/maxipago.rb
lib/active_merchant/billing/gateways/mercado_pago.rb
lib/active_merchant/billing/gateways/nmi.rb
lib/active_merchant/billing/gateways/orbital.rb
lib/active_merchant/billing/gateways/payeezy.rb
lib/active_merchant/billing/gateways/quantum.rb
lib/active_merchant/billing/gateways/quickbooks.rb
lib/active_merchant/billing/gateways/redsys.rb
lib/active_merchant/billing/gateways/sage.rb
lib/active_merchant/billing/gateways/trans_first.rb
lib/active_merchant/billing/gateways/trust_commerce.rb
lib/active_merchant/billing/gateways/visanet_peru.rb
test/remote/gateways/remote_authorize_net_test.rb

Removed the RuboCop to-do item to fix [Style/TrailingUnderscoreVariable](https://docs.rubocop.org/rubocop/cops_style.html#styletrailingunderscorevariable).
4517 tests, 72070 assertions, 0 failures, 0 errors, 0 pendings, 0
100% passed

RuboCop: Fix Style/TrailingUnderscoreVariable

---

lib/active_merchant/billing/credit_card_methods.rb
test/unit/credit_card_methods_test.rb

Missed a test, and by extension, an implementation detail. 😅

Alia: Skip Luhn validation

---

CHANGELOG
lib/active_merchant/billing/gateways/payu_latam.rb
test/remote/gateways/remote_payu_latam_test.rb

@curiousepic take a look when you have a chance.

Payu Latam: fix store method

---

lib/active_merchant/billing/gateways/netbanx.rb
test/remote/gateways/remote_netbanx_test.rb
test/unit/gateways/netbanx_test.rb

**Update refund logic** - If the transactions that are pending, API call needs to be Cancellation
**Updated logic to verify** - Do a Verification with AVS prior to Auth + Settle

Update refund logic & Verification with AVS prior to Auth + Settle

---

CHANGELOG
lib/active_merchant/billing/gateways/cyber_source.rb
test/remote/gateways/remote_cyber_source_test.rb
test/unit/gateways/cyber_source_test.rb

4524 tests, 72130 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote tests:
82 tests, 412 assertions, 5 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
93.9024% passed
Remote test failures:
test_successful_3ds_validate_authorize_request
test_successful_3ds_validate_purchase_request
test_successful_pinless_debit_card_puchase
test_successful_tax_calculation
test_successful_validate_pinless_debit_card 
CE-579

Cybersource: Pass reconciliation_id

---

CHANGELOG
lib/active_merchant/billing/gateways/adyen.rb
test/remote/gateways/remote_adyen_test.rb
test/unit/gateways/adyen_test.rb

This will support the Shopify integration using the right values. fix for #3590

Change shopper_email to email and shopper_ip to ip

---

CHANGELOG
lib/active_merchant/billing/gateways/cyber_source.rb

Remote: 
82 tests, 412 assertions, 5 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
93.9024% passed
(All failures known & unrelated)
Unit:
89 tests, 416 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
CE-698

CyberSource: conditionally find stored credentials

---

lib/active_merchant/billing/gateways/netbanx.rb
test/remote/gateways/remote_netbanx_test.rb
test/unit/gateways/netbanx_test.rb

**Update purchase logic** - added verification in the purchase function.

Add verification in purchase

---

CHANGELOG
lib/active_merchant/billing/gateways/openpay.rb

Openpay: Add Colombia to supported countries

---

.rubocop_todo.yml
CHANGELOG
lib/active_merchant/billing/gateways/authorize_net.rb
lib/active_merchant/billing/gateways/payeezy.rb
lib/active_merchant/billing/gateways/paymill.rb
lib/active_merchant/billing/gateways/redsys.rb
lib/active_merchant/billing/gateways/sage_pay.rb

Fixes the RuboCop to-do for [Naming/PredicateName](https://docs.rubocop.org/rubocop/0.85/cops_naming.html#namingpredicatename).
4543 tests, 72248 assertions, 0 failures, 0 errors, 0 pendings, 0
100% passed

RuboCop: Fix Naming/PredicateName

---

CHANGELOG
lib/active_merchant/billing/gateways/stripe.rb
test/unit/gateways/stripe_payment_intents_test.rb

Stripe Payment Intents: `on_behalf_of` can be passed independently

---

.rubocop_todo.yml
CHANGELOG
lib/active_merchant/billing/gateways/beanstream/beanstream_core.rb
lib/active_merchant/billing/gateways/eway.rb
lib/active_merchant/billing/gateways/iridium.rb
lib/active_merchant/billing/gateways/pac_net_raven.rb
lib/active_merchant/billing/gateways/smart_ps.rb
lib/active_merchant/billing/gateways/stripe.rb
lib/active_merchant/billing/gateways/webpay.rb

Fixes the RuboCop to-do for [Style/AndOr](https://docs.rubocop.org/rubocop/0.85/cops_style.html#styleandor).
4565 tests, 72404 assertions, 0 failures, 0 errors, 0 pendings, 0
100% passed

RuboCop: Fix Style/AndOr

---

CHANGELOG
lib/active_merchant/billing/gateways/elavon.rb
test/unit/gateways/elavon_test.rb

Unit:
36 tests, 206 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
31 tests, 136 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Elavon: remove ampersand character

---

CHANGELOG
lib/active_merchant/billing/gateways/redsys.rb
test/remote/gateways/remote_redsys_sha256_test.rb
test/remote/gateways/remote_redsys_test.rb
test/unit/gateways/redsys_sha256_test.rb

Support 3DS2 Fields, adding an embedded JSON document in node DS_MERCHANT_MPIEXTERNAL
ECS-1427
Unit:
40 tests, 140 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
23 tests, 72 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Redsys: Add 3DS2 Integration Support

---

lib/active_merchant/billing/gateways/litle.rb
test/unit/gateways/litle_test.rb

CE-1170
Unit: 49 tests, 215 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 45 tests, 193 assertions, 13 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
71.1111% passed
Failing remote tests are also failing on main branch

Litle: Create overridable third URL for PostLive endpoint

---

CHANGELOG
lib/active_merchant/billing/gateways/adyen.rb
test/remote/gateways/remote_adyen_test.rb
test/unit/gateways/adyen_test.rb

Unit: 
71 tests, 372 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 
93 tests, 357 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
CE-1190

Adyen: add subSeller fields

---

lib/active_merchant/billing/gateways/decidir.rb
test/remote/gateways/remote_decidir_test.rb
test/unit/gateways/decidir_test.rb

Local
4600 tests, 72884 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit
34 tests, 165 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote
22 tests, 78 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Decidir: Update nesting for device_unique_identifier field

---

CHANGELOG
lib/active_merchant/billing/gateways/payment_express.rb
test/remote/gateways/remote_payment_express_test.rb
test/unit/gateways/payment_express_test.rb

Remote:
16 tests, 75 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
35 tests, 256 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
CE-1219

Payment Express: support validate/verify

---

lib/active_merchant/billing/gateways/eway_rapid.rb
test/remote/gateways/remote_eway_rapid_test.rb
test/unit/gateways/eway_rapid_test.rb

add 3ds field when do direct payment for the gateway of eway.

feat: eway -> add 3ds field when do direct payment

---

CHANGELOG

Add changelog for eway update.

Add changelog for eway update

---

CHANGELOG
lib/active_merchant/billing/credit_card.rb
lib/active_merchant/billing/credit_card_methods.rb
test/unit/credit_card_methods_test.rb

Unit tests: 
4630 tests, 73042 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
CE-1295

Support Creditel cardtype

---

CHANGELOG
lib/active_merchant/version.rb

Release 1.119.0

---

CHANGELOG
lib/active_merchant/billing/gateways/orbital.rb
test/remote/gateways/remote_orbital_test.rb
test/unit/gateways/orbital_test.rb

rake test:local                                             
Finished in 7.84327 seconds.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
4634 tests, 73065 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
590.83 tests/s, 9315.63 assertions/s
Started
..........................................................................................................
Finished in 0.36499 seconds. …

Adding retry_logic to params

---

CHANGELOG
lib/active_merchant/billing/gateways/stripe.rb
test/unit/gateways/stripe_test.rb

Unit:
138 tests, 739 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
71 tests, 325 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Stripe: ensure potentially nested data is scrubbed

---

CHANGELOG
generators/gateway/templates/gateway.rb
generators/gateway/templates/gateway_test.rb
generators/gateway/templates/remote_gateway_test.rb

The existing gateway skeleton templates generated skeletons that are not
Rubocop-compliant as of 19386a2d7c0531ea81eb8a4ef1abb7981cec0c7f.
Compare 203149a19aabe20848b2e716677b1dbbf1b40025 for the updates required by
a generated skeleton.
See also #3895.

Update gateway skeleton templates

---

CHANGELOG
lib/active_merchant/billing/gateways/orbital.rb
test/remote/gateways/remote_orbital_test.rb
test/unit/gateways/orbital_test.rb

bundle exec rake script test:local
4685 tests, 73323 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Inspecting 696 files
696 files inspected, no offenses detected
116 tests, 683 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
100% passed

Orbital: $0 PreNote authorize & ECP force_capture

---

lib/active_merchant/billing/gateways/qvalent.rb
test/unit/gateways/qvalent_test.rb

EC-1337
Unit:
27 tests, 128 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
27 tests, 128 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Qvalent: Add customer reference number

---

CHANGELOG

[EC-1337](https://spreedly.atlassian.net/browse/CE-1337)
Unit:
27 tests, 128 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
27 tests, 128 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Qvalent: Update Changelog for fix PR

---

CHANGELOG
lib/active_merchant/billing/credit_card_methods.rb
test/unit/credit_card_methods_test.rb

CE-669
Local Tests:
4698 tests, 73371 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Update JCB BIN Range

---

CHANGELOG
Gemfile
lib/active_merchant/billing/gateways/vpos.rb
test/fixtures.yml
test/remote/gateways/remote_vpos_test.rb
test/unit/gateways/vpos_test.rb

Pending: better remote tests, any unit tests, ~implementation of `scrub`~.
Currently, we don't get a successful transaction response, even using their specified test cards, which makes some response attributes challenging to establish. 😅

vPOS: add gateway

---

CHANGELOG
lib/active_merchant/billing/gateways/vpos.rb

Unit: 
5 tests, 15 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 
7 tests, 21 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
PS-165

vPOS: Convert values to string

---

CHANGELOG
lib/active_merchant/billing/gateways/vpos.rb
test/remote/gateways/remote_vpos_test.rb
test/unit/gateways/vpos_test.rb

Unit:
5 tests, 15 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
7 tests, 21 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

vPOS: handle shop_process_id correctly

---

CHANGELOG
lib/active_merchant/billing/credit_card.rb
lib/active_merchant/billing/credit_card_methods.rb
test/unit/credit_card_methods_test.rb

Unit tests:
4775 tests, 73688 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
CE-1727

Confiable: support card type

---

CHANGELOG
lib/active_merchant/billing/gateways/safe_charge.rb
test/remote/gateways/remote_safe_charge_test.rb
test/unit/gateways/safe_charge_test.rb

CE-1638
Unit:
24 tests, 132 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote(2 unrelated failures):
28 tests, 74 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
92.8571% passed

Nuvei: Add 3ds2 parameter

---

lib/active_merchant/billing/gateways/adyen.rb
test/remote/gateways/remote_adyen_test.rb

Adyen returns references to transactions in compound and non-compound formats, that can look a few different ways:
* `"#883623883719135C#"` (non-compound)
* `"883623883719135C"` (non-compound)
* `"883623883719135C#863623883721426D#"` (compound)
Previously we employed some complex logic to parse this string and select the correct reference. This caused a bug when `cancelOrRefund` was called with a compound reference, because it would select the second reference (`863623883721426D` in the example above) instead of the first (`883623883719135C`).
This PR simplifies the parsing of adyen references and adds some tests demonstrating the `cancelOrRefund` call selects the correct reference across a variety of situations.
CE-1543
Rubocop
Unit
4776 tests, …

Adyen: select correct reference for `cancelOrRefund`

---

CHANGELOG
lib/active_merchant/billing/gateways/elavon.rb
test/remote/gateways/remote_elavon_test.rb
test/unit/gateways/elavon_test.rb

Properly handle encoding and decoding of special characters and string truncation to avoid invalid XML and max length exceeded errors, according to gateway specifications.
Remote:
36 tests, 164 assertions, 3 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
- Failed on test_successful_purchase_with_custom_fields: not setup on account
- Failed on test_successful_purchase_with_level_3_fields: not setup on account
- Failed on test_successful_purchase_with_shipping_address_and_l3: not setup on account
Unit:
45 tests, 237 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
ECS-1894

Elavon: Add support for special characters

---

CHANGELOG
lib/active_merchant/billing/gateways/payflow.rb
test/unit/gateways/payflow_test.rb

CE-1798
Rubocop:
Local:
4840 tests, 73920 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
38 tests, 169 assertions, 8 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
78.9474% passed

Payflow: Define store method

---

lib/active_merchant/billing/gateways/stripe_payment_intents.rb
test/remote/gateways/remote_stripe_payment_intents_test.rb
test/unit/gateways/stripe_payment_intents_test.rb

Adds a way to send in a network_transaction_id outside of the stored credentials hash for Stripe Payment Intents. Stripe PI accepts network_transaction_id and ds_transaction_id via mit field under card.
Remote:
56 tests, 267 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
24 tests, 144 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

NTID field for Stripe Payment Intents

---

CHANGELOG

Changelog was not properly updated with https://github.com/activemerchant/active_merchant/pull/4060

Updates Changelog

---

CHANGELOG
lib/active_merchant/billing/gateways/monei.rb

Modify regular expressions in the scrub method
ECS-1695
4846 tests, 73941 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
17 tests, 61 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
23 tests, 59 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Monei: Improve Scrub Regex

---

CHANGELOG
lib/active_merchant/version.rb

Release 1.122.0

---

CHANGELOG
test/remote/gateways/remote_ct_payment_test.rb

Remote tests:
20 tests, 58 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit tests:
14 tests, 48 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Local:
4697 tests, 73368 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Remove hard coded test card expiration date for CT Payments

---

CHANGELOG
lib/active_merchant/billing/credit_card_methods.rb
test/unit/credit_card_methods_test.rb

Unit tests:
4889 tests, 74139 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
CE-1884

Synchrony: support cardtype

---

CHANGELOG
lib/active_merchant/billing/credit_card_methods.rb
test/unit/credit_card_methods_test.rb

Unit tests:
4890 tests, 74158 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
CE-1911

Maestro: pull out bins with no checksum

---

CHANGELOG
lib/active_merchant/billing/gateways/monei.rb

ECS-1694
Unit:
17 tests, 61 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
100% passed

Monei: Typo Correction on Billing Details

---

CHANGELOG
lib/active_merchant/version.rb

Release v1.123.0

---

CHANGELOG

[CE-1885](https://spreedly.atlassian.net/browse/CE-1885)

Routex: cardtype changelog fix

---

CHANGELOG
lib/active_merchant/billing/gateways/paysafe.rb
test/remote/gateways/remote_paysafe_test.rb

- Add test for split pay
Local:
100% passed
Rubocop:
Unit:
15 tests, 72 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
100% passed

Paysafe: Update supported countries

---

CHANGELOG
lib/active_merchant/billing/gateways/ipg.rb
test/fixtures.yml
test/remote/gateways/remote_ipg_test.rb
test/unit/gateways/ipg_test.rb

Added `ipg` gateway to AM build along with unit and remote tests.
CE-2039
Unit Test:
4955 tests, 74454 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote Test:
11 tests, 20 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Rubocop:
719 files inspected, no offenses detected

IPG: Add Gateway

---

CHANGELOG
lib/active_merchant/billing/gateways/priority.rb
test/fixtures.yml
test/remote/gateways/remote_priority_test.rb
test/unit/gateways/priority_test.rb

* Submits external contributor's code to Active Merchant
100% passed
100% passed
100% passed
719 files inspected, no offenses detected

Adding Priority gateway

---

CHANGELOG
lib/active_merchant/billing/gateways/global_collect.rb
test/remote/gateways/remote_global_collect_test.rb
test/unit/gateways/global_collect_test.rb

Expand support to add a comprehensive set of information for lodgingData
with GlobalCollect.
CE-2053
Unit:
Remote: 26 tests, 62 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
96.1538% passed

GlobalCollect: Support for Lodging Data

---

CHANGELOG
lib/active_merchant/billing/gateways/wompi.rb
test/remote/gateways/remote_wompi_test.rb

Unit:
9 tests, 38 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
10 tests, 24 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Rubocop:
722 files inspected, no offenses detected

Wompi: option for installments

---

CHANGELOG
lib/active_merchant/billing/gateways/wompi.rb
test/remote/gateways/remote_wompi_test.rb

Remote:
11 tests, 25 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
9 tests, 38 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Rubocop:
CE-2172

Wompi: do not pass CVV if not provided

---

CHANGELOG
lib/active_merchant/billing/check.rb

Unit tests:
5002 tests, 74820 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Rubocop:
CE-2200

Add Canadian institution number for check

---

CHANGELOG
lib/active_merchant/billing/gateways/wompi.rb
test/remote/gateways/remote_wompi_test.rb
test/unit/gateways/d_local_test.rb
test/unit/gateways/wompi_test.rb

Unit Tests:
13 tests, 52 assertions, 0 failures, 1 errors, 0 pendings, 0 omissions, 0 notifications
92.3077% passed
Remote Tests:
16 tests, 40 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
87.5% passed

Wompi: Add support for Auth and Capture

---

lib/active_merchant/billing/gateways/priority.rb

4999 tests, 74808 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
12 tests, 127 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
20 tests, 56 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Priority: update source and billing address checks

---

lib/active_merchant/billing/gateways/orbital.rb
test/remote/gateways/remote_orbital_test.rb

Updated google pay cards validations for orbital implementation
CE-1822
Unit:
5009 tests, 74848 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Rubocop:
Remote:
76 tests, 345 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Orbital: Update google pay validations

---

CHANGELOG
lib/active_merchant/billing/gateways/airwallex.rb
test/fixtures.yml
test/remote/gateways/remote_airwallex_test.rb
test/unit/gateways/airwallex_test.rb

Unit: 16 tests, 57 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 16 tests, 43 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Rubocop: 731 files inspected, no offenses detected

Airwallex: Support gateway

---

CHANGELOG
lib/active_merchant/billing/gateways/airwallex.rb
test/remote/gateways/remote_airwallex_test.rb
test/unit/gateways/airwallex_test.rb

Fix some bugs uncovered in Airwallex QA.
Remote:
16 tests, 43 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
22 tests, 82 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Rubocop:
736 files inspected, no offenses detected

Airwallex: QA

---

CHANGELOG
lib/active_merchant/billing/gateways/airwallex.rb
test/remote/gateways/remote_airwallex_test.rb
test/unit/gateways/airwallex_test.rb

CE-2530
Rubocop:
Unit:
5145 tests, 75476 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
Remote:
Loaded suite test/remote/gateways/remote_airwallex_test
18 tests, 46 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications

Airwallex: Add `descriptor` field

---

CHANGELOG
lib/active_merchant/billing/gateways/airwallex.rb
test/remote/gateways/remote_airwallex_test.rb
test/unit/gateways/airwallex_test.rb

CE-2300
Unit:
28 tests, 105 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
22 tests, 50 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Airwallex: Add Stored Credential support

---

lib/active_merchant/billing/gateways/priority.rb

Adds the unusued `options` argument to the `verify` method so that the
method accepts two arguments, according to ActiveMerchant standards.
Rubocop:
Unit:
5159 tests, 75564 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
27 tests, 81 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Priority: Update `verify` method signature

---

CHANGELOG
lib/active_merchant/version.rb

Release v1.126.0

---

CHANGELOG
lib/active_merchant/billing/gateways/monei.rb
test/remote/gateways/remote_monei_test.rb
test/unit/gateways/monei_test.rb

CE-2615
Unit:
19 tests, 69 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
100% passed

Monei: Support `lang` field

---

CHANGELOG
lib/active_merchant/billing/gateways/kushki.rb
test/remote/gateways/remote_kushki_test.rb
test/unit/gateways/kushki_test.rb

Remote:
16 tests, 51 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit: 
17 tests, 109 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Rubocop:
CE-2576

Kushki: add USD to extra_taxes

---

lib/active_merchant/billing/gateways/plexo.rb
test/fixtures.yml
test/remote/gateways/remote_plexo_test.rb
test/unit/gateways/plexo_test.rb

Added plexo gateway implementation along with remote and unit test
cases.
CE-2536
Unit:
5201 tests, 75845 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Rubocop:
742 files inspected, no offenses detected
Remote:
15 tests, 43 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Plexo: Add new gateway

---

CHANGELOG
lib/active_merchant/billing/gateways/vpos.rb
test/fixtures.yml
test/remote/gateways/remote_vpos_test.rb
test/remote/gateways/remote_vpos_without_key_test.rb
test/unit/gateways/vpos_test.rb

Unit: 
7 tests, 22 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 
11 tests, 36 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
Failing test: `test_failed_credit` (seems to have an updated error)
Rubocop: 
742 files inspected, no offenses detected
CER-9

VPOS: Reuse encryption key

---

CHANGELOG
lib/active_merchant/billing/gateways/vanco.rb
test/remote/gateways/remote_vanco_test.rb
test/unit/gateways/vanco_test.rb

Test Summary
Local: 5215 tests, 75910 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit: 12 tests, 60 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 15 tests, 34 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Vanco: Purchase with session id from request

---

CHANGELOG
lib/active_merchant/billing/gateways/shift4.rb

Send verify transactions to the correct endpoint, with the required card
data.
https://myportal.shift4.com/index.cfm?action=development.shift4api#tag/Cards
SER-170
Unit: 16 tests, 85 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 17 tests, 36 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Shift4: Verify Endpoint Fix

---

CHANGELOG
lib/active_merchant/billing/gateways/stripe.rb
test/remote/gateways/remote_stripe_test.rb
test/test_helper.rb
test/unit/gateways/stripe_test.rb

This reverts commit aca5f66b4b9eff1288dc880bcdd473a54fb12ef2.
Test Summary
Local: 5263 tests, 76133 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit: 142 tests, 750 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Revert "Stripe: Add shipping address"

---

CHANGELOG
lib/active_merchant/billing/gateways/shift4.rb

Shift4 Time Zone
[Ticket](https://spreedly.atlassian.net/browse/SER-231)
Unit Test:
5193 tests, 75672 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
64.86 tests/s, 948.72 assertions/s
Inspecting 742 files
742 files inspected, no offenses detected
Remote Test:
13 tests, 29 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Shift4 Time Zone

---

Gemfile
lib/active_merchant/billing/gateways/alelo.rb
test/remote/gateways/remote_alelo_test.rb
test/unit/gateways/alelo_test.rb

This PR adds code to handle Alelo's access_token, encryption key and request body encription

Add authorization code to handle access_token and encription key

---

CHANGELOG
lib/active_merchant/billing/gateways/shift4.rb

Shift4 Time/Timezone offset
[Ticket](https://spreedly.atlassian.net/browse/SER-273)
5292 tests, 76267 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
126.77 tests/s, 1827.04 assertions/s
Inspecting 746 files
Remote:
17 tests, 39 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Shift4 Time/Timezone offset

---

lib/active_merchant/billing/gateways/shift4.rb

Shift4 Update Invoice Numbering Generation
[Ticket](https://spreedly.atlassian.net/browse/SER-302)
5333 tests, 76509 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
94.70 tests/s, 1358.63 assertions/s
Inspecting 749 files

Shift4 Update Invoice Numbering Generation

---

CHANGELOG
lib/active_merchant/billing/gateways/priority.rb
test/fixtures.yml
test/unit/gateways/priority_test.rb

Unit:
20 tests, 117 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 
100% passed
Remote:
30 tests, 87 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 
Failing: test_failed_purchase_missing_card_verification_number, also failing on master
Rubocop: 749 files inspected, no offenses detected
EVS-1315

Priority: Adjust credential name

---

CHANGELOG
lib/active_merchant/billing/gateways/merchant_e_solutions.rb
test/remote/gateways/remote_merchant_e_solutions_test.rb
test/unit/gateways/merchant_e_solutions_test.rb

The fields are being added to enable recurring transactions.
SER-309-310
Unit: 21 tests, 109 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote: 19 tests, 81 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed

MerchantE: Add support for recurring transactions

---

test/remote/gateways/remote_borgun_test.rb

Added test cases to verify implementation for frictionless transcations.
SER-346
Remote:
23 tests, 46 assertions, 5 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 78.2609% passed
Unit:
5357 tests, 76645 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Rubocop:

Borgun: Add 3ds frictionless tests

---

lib/active_merchant/billing/gateways/reach.rb
test/remote/gateways/remote_reach_test.rb

Description
This integration support the following payment operations:
Verify
Void
Refund
Unit test
Finished in 35.278047 seconds.
5370 tests, 76698 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
152.22 tests/s, 2174.10 assertions/s
Remote test
Finished in 11.168364 seconds.
12 tests, 27 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
1.07 tests/s, 2.42 assertions/s
Rubocop
Inspecting 753 files

Reach - PSP Integration - Verify / Void / Refund

---

CHANGELOG
lib/active_merchant/billing/gateways/cyber_source.rb
test/remote/gateways/remote_cyber_source_test.rb
test/unit/gateways/cyber_source_test.rb

CER-296
This PR updates the installment data method to better handle when only certain fields are added.
Remote Tests:
119 tests, 607 assertions, 3 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 97.479% passed
*3 failing tests also failing on master
Unit Tests:
124 tests, 592 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Local Tests:
5410 tests, 76913 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed

CyberSource: Update installment data method

---

CHANGELOG
lib/active_merchant/billing/gateways/decidir.rb
test/remote/gateways/remote_decidir_test.rb
test/unit/gateways/decidir_test.rb

Get payment status by payment id.
Unit
39 tests, 190 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote
25 tests, 88 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 96% passed

Decidir: Add transaction inquire request

---

lib/active_merchant/billing/gateways/reach.rb
test/remote/gateways/remote_reach_test.rb
test/unit/gateways/reach_test.rb

Reverts activemerchant/active_merchant#4656

Revert "Reach: Fixing store credentials and Exception issues"

---

CHANGELOG
lib/active_merchant/billing/gateways/stripe_payment_intents.rb
test/remote/gateways/remote_stripe_payment_intents_test.rb
test/unit/gateways/stripe_payment_intents_test.rb

Remote:
79 tests, 346 assertions, 9 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 88.6076% passed
Unit:
43 tests, 219 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed

Stripe PI: Add Level 3 support

---

CHANGELOG
lib/active_merchant/billing/gateways/mastercard.rb
lib/active_merchant/billing/gateways/tns.rb
test/unit/gateways/citrus_pay_test.rb
test/unit/gateways/tns_test.rb

Update test URL to be only secure.uat.tnspayments.

Tns: update test URL

---

CHANGELOG
lib/active_merchant/billing/gateways/checkout_v2.rb
test/fixtures.yml
test/remote/gateways/remote_checkout_v2_test.rb
test/unit/gateways/checkout_v2_test.rb

This reverts commit e769cdb908d4a8543bc68f13a4f7aa04c60daf59.

Revert "CheckoutV2: Add store/unstore (#4677)"

---

CHANGELOG
lib/active_merchant/billing/gateways/blue_snap.rb
test/remote/gateways/remote_blue_snap_test.rb
test/unit/gateways/blue_snap_test.rb

Local:
5457 tests, 77095 assertions, 0 failures, 19 errors, 0 pendings, 0 omissions, 0 notifications 99.6518% passed
Unit:
45 tests, 269 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote:
53 tests, 171 assertions, 9 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 83.0189% passed

CER-460 Add descriptor phone number to blue_snap

---

lib/active_merchant/billing/gateways/commerce_hub.rb

Changes reference details to properly send `referenceTransactionDetails` on capture requests.
Finished in 290.029817 seconds.
23 tests, 64 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Finished in 47.993895 seconds.
5463 tests, 77178 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

CommerceHub: adjusting reference details

---

lib/active_merchant/billing/gateways/orbital.rb

GWI-567
Remote:
122 tests, 509 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Unit:
144 tests, 817 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Rubocop:

Orbital: dismiss CardSecValInd restriction

---

lib/active_merchant/billing/gateways/cyber_source_rest.rb

Description
Update message response on error in order to get a more redeable response
GWI-571
Unit test
Finished in 30.871357 seconds.
5476 tests, 77239 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote test
177.38 tests/s, 2501.96 assertions/s
Rubocop

Cybersource Rest - update message response on error

---

CHANGELOG
lib/active_merchant/billing/gateways/ebanx.rb
test/remote/gateways/remote_ebanx_test.rb
test/unit/gateways/ebanx_test.rb

Get transaction by authorization.
Remote:
27 tests, 73 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 96.2963% passed
Unit:
20 tests, 89 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed

Ebanx: Add transaction inquire request

---

CHANGELOG
lib/active_merchant/billing/gateways/checkout_v2.rb
test/remote/gateways/remote_checkout_v2_test.rb
test/unit/gateways/checkout_v2_test.rb

Local:
5477 tests, 77201 assertions, 0 failures, 19 errors, 0 pendings, 0 omissions, 0 notifications
99.6531% passed
Unit:
54 tests, 300 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
89 tests, 213 assertions, 4 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
95.5056% passed

Checkout_v2: update idmepotency_key names

---

lib/active_merchant/billing/gateways/shift4.rb

Change `Content-type` value to `applicaiton/json` instead of xml
Unit: 23 tests, 147 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote: 24 tests, 56 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 91.6667% passed

Shift4: Fix `Content-type` value

---

CHANGELOG
lib/active_merchant/billing/gateways/mit.rb
test/unit/gateways/mit_test.rb

This reverts commit 6e3cd4b431fdd521e955d80fa3133f6dc2653899.

Revert "Mit: Changed how the payload was sent to the gateway"

---

CHANGELOG
lib/active_merchant/billing/gateways/stripe_payment_intents.rb
test/remote/gateways/remote_stripe_payment_intents_test.rb
test/unit/gateways/stripe_payment_intents_test.rb

Start sending address, shipping, phone and email when creating a customer.
Remote Tests
84 tests, 396 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Unit Tests
42 tests, 224 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed

Stripe PI: Update paramters for creating of customer

---

CHANGELOG
lib/active_merchant/billing/gateways/stripe.rb
test/unit/gateways/stripe_payment_intents_test.rb
test/unit/gateways/stripe_test.rb
test/unit/gateways/webpay_test.rb

Stripe Unit:
145 tests, 765 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Stripe Remote:
77 tests, 362 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Stripe PI Unit:
42 tests, 224 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Stripe PI Remote:
83 tests, 391 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed

Stripe & Stripe PI: Validate API Key

---

CHANGELOG
lib/active_merchant/billing/gateways/stripe_payment_intents.rb
test/remote/gateways/remote_stripe_payment_intents_test.rb
test/unit/gateways/stripe_payment_intents_test.rb

Start sending address, shipping, phone and email when creating a customer.
Remote Tests
84 tests, 396 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Unit Tests
42 tests, 224 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed

Stripe PI: Update parameters for creation of customer

---

CHANGELOG
lib/active_merchant/billing/gateways/payway_dot_com.rb

The gateway has advised to direct traffic to their failover .net endpoint
LOCAL
5542 tests, 77550 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
UNIT
16 tests, 64 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
REMOTE
16 tests, 43 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed

PaywayDotCom: Update live url

---

CHANGELOG
lib/active_merchant/billing/gateways/airwallex.rb
lib/active_merchant/billing/gateways/alelo.rb
lib/active_merchant/billing/gateways/checkout_v2.rb
lib/active_merchant/billing/gateways/pay_trace.rb
lib/active_merchant/billing/gateways/quickbooks.rb
lib/active_merchant/billing/gateways/simetrik.rb
lib/active_merchant/errors.rb
test/remote/gateways/remote_airwallex_test.rb
test/remote/gateways/remote_alelo_test.rb
test/remote/gateways/remote_checkout_v2_test.rb
test/remote/gateways/remote_pay_trace_test.rb
test/remote/gateways/remote_quickbooks_test.rb
test/remote/gateways/remote_simetrik_test.rb
test/unit/gateways/airwallex_test.rb
test/unit/gateways/alelo_test.rb
test/unit/gateways/checkout_v2_test.rb
test/unit/gateways/pay_trace_test.rb
test/unit/gateways/quickbooks_test.rb
test/unit/gateways/simetrik_test.rb

This reverts commit 00fd53ff9b9fb59ec5e0ad244947e93bcfa0ba4a.

Revert "Adding Oauth Response for access tokens"

---

CHANGELOG
lib/active_merchant/billing/gateways/ebanx.rb
test/remote/gateways/remote_ebanx_test.rb
test/unit/gateways/ebanx_test.rb

Update Verify to use verifycard endpoint.
Unit:
19 tests, 85 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote:
32 tests, 88 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 96.875% passed

Ebanx: Update Verify

---

CHANGELOG
lib/active_merchant/billing/credit_card.rb
lib/active_merchant/billing/credit_card_methods.rb
lib/active_merchant/billing/gateways/rapyd.rb
test/unit/credit_card_methods_test.rb

This change add new credit card brand Verve and tests related to it.

SER-728 Create Verve Card Type. 

---

CHANGELOG
lib/active_merchant/billing/gateways/sum_up.rb
test/fixtures.yml
test/remote/gateways/remote_sum_up_test.rb
test/unit/gateways/sum_up_test.rb

Description
Setup, scrub and purchase method to SumUp Gateway adapter with the basic information needed.
This are the relevant links to review the initial implementation:
- [SumUp REST API](https://developer.sumup.com/docs/api/sum-up-rest-api/) 
- [Make a payment with a card entered by a customer](https://developer.sumup.com/docs/online-payments/guides/single-payment/) 
- [Checkouts](https://developer.sumup.com/docs/api/checkouts/)
Tickets for Spreedly reference
SER-764
SER-712
SER-711
Unit test
Finished in 37.342409 seconds.
5606 tests, 78027 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
Remote test
100% passed
150.12 tests/s, 2089.50 assertions/s
Rubocop …

SumUp - Setup, Scrub and Purchase build

---

CHANGELOG
lib/active_merchant/billing/gateways/ogone.rb
test/remote/gateways/remote_ogone_test.rb

[SER-695](https://spreedly.atlassian.net/browse/SER-695)
Unit tests
Finished in 0.129019 seconds.
49 tests, 207 assertions, 0 failures, 0 errors,
100% passed
Remote tests
Finished in 288.734817 seconds
33 tests, 127 assertions, 3 failures,
1 errors, 0 pendings, 0 omissions, 0 notifications 87.8788% passed
Notice: Errors not related with changes

Ogone: Add gateway specific 3ds option with default options mapping

---

CHANGELOG
lib/active_merchant/billing/gateways/adyen.rb
test/remote/gateways/remote_adyen_test.rb
test/unit/gateways/adyen_test.rb

This reverts commit 2165af890b15d2993674b889970d3aec597408a2.

Revert "Adyen: Update MIT flagging for NT"

---

CHANGELOG
lib/active_merchant/billing/gateways/braintree/token_nonce.rb
test/remote/gateways/remote_braintree_token_nonce_test.rb
test/unit/gateways/braintree_token_nonce_test.rb

This reverts commit af6cd39c4e13dea1fd2960f62f33818fd62ae873.

Revert "Revert "Braintree: Create credit card nonce (#4897)" (#4915)"

---

CHANGELOG
lib/active_merchant/billing/gateways/nmi.rb
test/unit/gateways/nmi_test.rb

LOCAL
5650 tests, 78243 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
UNIT
56 tests, 454 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
REMOTE
51 tests, 184 assertions, 3 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
94.1176% passed
*also failing on master branch

NMI: Update supported countries list

---

CHANGELOG
lib/active_merchant/billing/gateways/safe_charge.rb
test/remote/gateways/remote_safe_charge_test.rb
test/unit/gateways/safe_charge_test.rb

Remote:
34 tests, 96 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Unit:
29 tests, 160 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed

SafeCharge: Support tokens

---

CHANGELOG
lib/active_merchant/billing/gateways/shift4_v2.rb
test/remote/gateways/remote_shift4_v2_test.rb
test/unit/gateways/shift4_v2_test.rb

Description
[SER-847](https://spreedly.atlassian.net/browse/SER-847)
This commit add unstore function for shift4 v2
Unit test
Finished in 0.066295 seconds.
38 tests, 209 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
573.20 tests/s, 3152.58 assertions/s
Remote test
Finished in 95.92829 seconds.
37 tests, 133 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
0.39 tests/s, 1.39 assertions/s
Rubocop
778 files inspected, no offenses detected

Shift4 V2:  Add unstore function

---

CHANGELOG
lib/active_merchant/billing/gateways/redsys.rb
test/remote/gateways/remote_redsys_sha256_test.rb
test/remote/gateways/remote_redsys_test.rb
test/unit/gateways/redsys_sha256_test.rb
test/unit/gateways/redsys_test.rb

Remote:
22 tests, 54 assertions, 3 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 86.3636% passed
Unit:
34 tests, 117 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed

Redsys: Update to $0 verify

---

CHANGELOG
lib/active_merchant/billing/gateways/litle.rb
test/remote/gateways/remote_litle_test.rb
test/unit/gateways/litle_test.rb

Update how stored credential transactions are handle.
Unit:
58 tests, 257 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote:
57 tests, 251 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed

Litle: Update stored credentials

---

CHANGELOG
lib/active_merchant/billing/gateways/xpay.rb
test/fixtures.yml
test/remote/gateways/remote_xpay_test.rb
test/unit/gateways/xpay_test.rb

Description
[SER-703](https://spreedly.atlassian.net/browse/SER-703)
This commit add NexiXpay gateway with its basic operations

NexiXpay:  Add basic operation through 3ds

---

lib/active_merchant/billing/gateways/sage_pay.rb
test/remote/gateways/remote_sage_pay_test.rb
test/unit/gateways/sage_pay_test.rb

ECS-3325
Adds support for the required 3DS2 parameters on
authorize and purchase requests to allow the gateway to decide if 3DS2 is needed or not.
Remote:
40 tests, 119 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed

SagePay: Add 3DS2 preauth params

---

lib/active_merchant/billing/gateways/xpay.rb

Summary: 
Fix Nexi Headers for capture and refund transactions
Remote Tests:
..
Finished in 3.613772 seconds.
------------------------------------------------
2 tests, 6 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
------------------------------------------------

SER-705 NexiXpay Fix headers for capture and refund

---

lib/active_merchant/billing/gateways/cecabank/cecabank_json.rb

Description
This commit add a small fix when the transcript is empty
[SER-1050](https://spreedly.atlassian.net/browse/SER-1050)
Unit test
Finished in 0.073935 seconds.
14 tests, 71 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
189.36 tests/s, 960.30 assertions/s
Remote test
Finished in 30.299275 seconds.
16 tests, 54 assertions, 3 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 81.25% passed
0.53 tests/s, 1.78 assertions/s
Rubocop

Cecabank: Fix scrubbing

---

CHANGELOG
lib/active_merchant/billing/gateways/hi_pay.rb
lib/active_merchant/billing/gateways/rapyd.rb
test/remote/gateways/remote_hi_pay_test.rb
test/unit/gateways/hi_pay_test.rb
test/unit/gateways/rapyd_test.rb

SER-776
--------
Summary:
-----------
Adding the parameters required to perform 3ds transactions, including unit and remote tests.
Tests
---------
Remote Test:
Finished in 155.128258 seconds.
18 tests, 76 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Unit Test:
21 tests, 54 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
RuboCop:

HiPay: Add 3ds params

---

CHANGELOG
lib/active_merchant/billing/gateways/kushki.rb
test/remote/gateways/remote_kushki_test.rb
test/unit/gateways/kushki_test.rb

This will add the product_details field
Local:
5807 tests, 78885 assertions, 0 failures, 26 errors, 0 pendings, 0 omissions, 0 notifications
99.5523% passed
Unit:
19 tests, 122 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
25 tests, 68 assertions, 4 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
84% passed

Kushki: add the product_details field

---

CHANGELOG
lib/active_merchant/billing/gateways/quickbooks.rb
test/remote/gateways/remote_quickbooks_test.rb
test/unit/gateways/quickbooks_test.rb

This reverts commit 833952552d96b3de6d7ef993c35d8b2fcaec778c.

Revert "Quickbooks: Update scrubbing logic"

---

CHANGELOG
lib/active_merchant/billing/gateways/redsys_rest.rb
test/remote/gateways/remote_redsys_rest_test.rb
test/unit/gateways/redsys_rest_test.rb

Unit:
23 tests, 101 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote:
18 tests, 38 assertions, 8 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 55.5556% passed

RedsysRest: Add support for 3DS

---

CHANGELOG
lib/active_merchant/billing/gateways/global_collect.rb
test/remote/gateways/remote_global_collect_test.rb
test/unit/gateways/global_collect_test.rb

Worldline (FKA Global Collect) is updating its API endpoint and this updates the gateway to match.
Unit test result:
46 tests, 235 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
remote test result: 
55 tests, 144 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Update Worldline URLS

---

CHANGELOG
lib/active_merchant/billing/gateways/quickbooks.rb
test/remote/gateways/remote_quickbooks_test.rb

Update scrub method to accomdate all card types
including AMEX.

Quickbooks: Update scrub method

---

lib/active_merchant/billing/gateways/elavon.rb
test/remote/gateways/remote_elavon_test.rb
test/unit/gateways/elavon_test.rb

This reverts commit ebcb303d507ea90ac9deddbdf2622a8fd1dfbb46.

Revert "Elavon: Update Stored Credential behavior"

---

CHANGELOG
lib/active_merchant/billing/gateways/first_pay/first_pay_json.rb
test/remote/gateways/remote_first_pay_json_test.rb
test/unit/gateways/first_pay_json_test.rb

Description
Spreedly reference:
[SER-1099](https://spreedly.atlassian.net/browse/SER-1099)
[SER-1100](https://spreedly.atlassian.net/browse/SER-1100)
This commit contains:
- Add Google Pay
- Add Apple Pay
- Add unit and remote tests
Unit test
Finished in 26.44884 seconds.
5826 tests, 79142 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 99.9657% passed
220.27 tests/s, 2992.27 assertions/s
Remote test
Finished in 26.44884 seconds.
5826 tests, 79142 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 99.9657% passed
220.27 tests/s, 2992.27 assertions/s
Rubocop

FirstPay rest support for ApplePay GooglePay

---

CHANGELOG
lib/active_merchant/billing/gateways/sage_pay.rb
test/remote/gateways/remote_sage_pay_test.rb
test/unit/gateways/sage_pay_test.rb

Remote:
41 tests, 127 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Unit:
44 tests, 164 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed

SagePay: Update test and live URLs

---

CHANGELOG
lib/active_merchant/billing/credit_card_methods.rb
test/unit/credit_card_methods_test.rb

Adds sodexo bins and small tweaks
Local:
5828 tests, 79068 assertions, 4 failures, 27 errors, 0 pendings, 0 omissions, 0 notifications
99.4681% passed
Unit:
67 tests, 646 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Bin Update: Add sodexo bins

---

CHANGELOG
lib/active_merchant/billing/gateways/adyen.rb
test/unit/gateways/adyen_test.rb

This reverts commit 74c2edc9bf5d8b853ed389c8b29c69e4cf9a1d7f.

Revert "Adyen: Update failed for network token cryptogram"

---

lib/active_merchant/billing/gateways/xpay.rb
test/remote/gateways/remote_xpay_test.rb

Fix rubocop offenses for Xpay gateway

Fix rubocop offenses for Xpay gateway

---

CHANGELOG
lib/active_merchant/billing/credit_card_methods.rb
test/unit/credit_card_methods_test.rb

Adds new routex bin to AM
Local:
5842 tests, 79165 assertions, 1 failures, 26 errors, 0 pendings, 0 omissions, 0 notifications
99.5378% passed
Unit:
67 tests, 648 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Add new routex bin

---

lib/active_merchant/billing/gateways/shift4_v2.rb
test/remote/gateways/remote_shift4_v2_test.rb
test/unit/gateways/shift4_v2_test.rb

This PR enables bank account payment method on the Shift4v2
[SER-1143](https://spreedly.atlassian.net/browse/SER-1143)
Finished in 56.316066 seconds.
40 tests, 143 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Finished in 36.406 seconds.
5842 tests, 79270 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Shift4v2: Adding bank account support

---

.github/workflows/ruby-ci.yml
gemfiles/Gemfile.rails71
gemfiles/Gemfile.rails_master
lib/active_merchant/billing/gateways/rapyd.rb
lib/active_merchant/billing/gateways/shift4_v2.rb

This PR enables the test pipeline on Github by removing the Gemfiles that points to Rails master and that creates a dependency issue related with Ruby 3.
Finished in 35.615298 seconds.
5846 tests, 79285 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Fixing test CI pipeline

---

.github/workflows/ruby-ci.yml
gemfiles/Gemfile.rails71
gemfiles/Gemfile.rails_master
lib/active_merchant/billing/gateways/rapyd.rb
lib/active_merchant/billing/gateways/shift4_v2.rb

Reverts activemerchant/active_merchant#5096

Revert "Fixing test CI pipeline"

---

CHANGELOG
lib/active_merchant/billing/gateways/cyber_source.rb
test/remote/gateways/remote_cyber_source_test.rb
test/unit/gateways/cyber_source_test.rb

This reverts commit 39603dec4dccf6109d139a110aa67afd399f286c.

Revert "Cybersource: Update NT flow"

---

CHANGELOG
lib/active_merchant/billing/gateways/worldpay.rb
test/unit/gateways/worldpay_test.rb

This reverts commit 0c953610f51fa00a012258339a8f112d26c78b1f.

Revert "Worldpay: Encyrpted ApplePay and GooglePay"

---

lib/active_merchant/billing/gateways/hi_pay.rb
test/unit/gateways/hi_pay_test.rb

Description
This commit fix a issue for set the payment method brand for payment_product when is mastercard
Unit test
Finished in 1.799922 seconds.
24 tests, 64 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
13.33 tests/s, 35.56 assertions/s
Remote test
Finished in 132.781957 seconds.
18 tests, 76 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
Rubocop

HiPay: Fix mastercard brand mapping

---

lib/active_merchant/billing/gateways/flex_charge.rb
test/remote/gateways/remote_flex_charge_test.rb
test/unit/gateways/flex_charge_test.rb

This PR adds the Inquire call to FlexCharge adapter
[SER-1153](https://spreedly.atlassian.net/browse/SER-1153)
Finished in 38.700031 seconds.
16 tests, 43 assertions, 0 failures, 0 errors, 0 pendings, 1 omissions, 0 notifications
100% passed
Finished in 40.844376 seconds.
5848 tests, 79304 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

FlexCharge: Adding Inquire support

---

lib/active_merchant/billing/gateways/adyen.rb
test/unit/gateways/adyen_test.rb

Update the error_code_from method to grab and alpha_numeric characters

---

lib/active_merchant/billing/gateways/datatrans.rb
test/remote/gateways/remote_datatrans_test.rb
test/unit/gateways/datatrans_test.rb

Description
SER-1323
Unit test
25 tests, 136 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote test
Remote test
23 tests, 57 assertions, 2 failures, 0 errors, 0 pendings, 1 omissions, 0 notifications 90.9091% passed

Datatrans:  Fix InvalidCountryCodeError

---

lib/active_merchant/billing/gateways/flex_charge.rb

Changes FlexCharge to add support for the void operation.
[SER-1327](https://spreedly.atlassian.net/browse/SER-1327)
Finished in 70.477035 seconds.
19 tests, 54 assertions, 0 failures, 0 errors, 0 pendings, 1 omissions, 0 notifications
100% passed
Finished in 60.782586 seconds.
5956 tests, 79948 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

SER-1327 enabling void call

---

lib/active_merchant/billing/gateways/flex_charge.rb
test/unit/gateways/flex_charge_test.rb

Description
SER-1339
Unit test
17 tests, 81 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote test
5923 tests, 79804 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
RuboCop:

FlexCharge - NoMethodError: nil CreditCard#number

---

lib/active_merchant/billing/gateways/flex_charge.rb
test/remote/gateways/remote_flex_charge_test.rb
test/unit/gateways/flex_charge_test.rb

Change FlexCharge transactionType to a new placement.
[SER-1400](https://spreedly.atlassian.net/browse/SER-1400)
Finished in 79.263845 seconds.
20 tests, 56 assertions, 0 failures, 0 errors, 0 pendings, 1 omissions, 0 notifications
100% passed
Finished in 38.175694 seconds.
5963 tests, 79998 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

FlexCharge: change transactionType placement

---

CHANGELOG
lib/active_merchant/billing/gateways/elavon.rb
test/remote/gateways/remote_elavon_test.rb
test/unit/gateways/elavon_test.rb

To satisfy new Elavon API requirements, including recurring_flag, approval_code for non-tokenized PMs, installment_count and _number, and situational par_value and association_token_data fields.
Remote
40 tests, 178 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 95% passed
Unit
60 tests, 356 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed

Elavon: Update Stored Credentials

---

lib/active_merchant/billing/gateways/mercury.rb
test/fixtures.yml
test/remote/gateways/remote_mercury_test.rb
test/unit/gateways/mercury_test.rb

Remote
20 tests, 66 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
95% passed

Repair to mercury

---

CHANGELOG
lib/active_merchant/billing/gateways/checkout_v2.rb
test/remote/gateways/remote_checkout_v2_test.rb

Remote
112 tests, 278 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed

CheckoutV2: Add inquire method

---

CHANGELOG
lib/active_merchant/billing/gateways/braintree/braintree_common.rb
lib/active_merchant/billing/gateways/decidir.rb
test/remote/gateways/remote_decidir_test.rb
test/unit/gateways/braintree_blue_test.rb

Braintree Remote:
123 tests, 662 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Decidir Remote:
28 tests, 99 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed

Decidir & Braintree: Scrub cryptogram and number

---

CHANGELOG
lib/active_merchant/billing/gateways/iveri.rb
test/remote/gateways/remote_iveri_test.rb
test/unit/gateways/cecabank_test.rb

This reverts commit 89ddf5322565d8bd7530b547c2f6cf3633b22f5d.

Revert "Iveri: Add AuthReversal for Authorizations"

---

CHANGELOG
lib/active_merchant/billing/gateways/nuvei.rb
test/remote/gateways/remote_nuvei_test.rb
test/unit/gateways/nuvei_test.rb

Summary:
Include 3ds Gateway Specific fields to support this functionality
[SER-1353](https://spreedly.atlassian.net/browse/SER-1353)
Unit tests
Finished in 0.027336 seconds.
11 tests, 55 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote tests
Finished in 32.629558 seconds.
20 tests, 58 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Rubocop
801 files, no offenses detected

Nuvei: Add 3DS GS

---

lib/active_merchant/billing/gateways/redsys_rest.rb

Remote tests:
26 tests, 91 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
96.1538% passed
Unit Tests:
27 tests, 113 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
^^ Same remote failure is seen on master.

Redsys: update decoding to catch Json errors and try to urlsafe_decode

---

CHANGELOG
lib/active_merchant/billing/gateways/cyber_source.rb
test/remote/gateways/remote_cyber_source_test.rb

Update order of XML fields to prevent XML
errors
Remote:
137 tests, 681 assertions, 7 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 94.8905% passed

CyberSource: Update order of XML fields

---

CHANGELOG
lib/active_merchant/billing/gateways/adyen.rb
test/remote/gateways/remote_adyen_test.rb
test/unit/gateways/adyen_test.rb

Remote
146 tests, 468 assertions, 12 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 91.7808% passed

Adyen: Remove cryptogram flag

---

CHANGELOG
lib/active_merchant/billing/gateways/nuvei.rb
test/remote/gateways/remote_nuvei_test.rb
test/unit/gateways/nuvei_test.rb

Description
This commit add Google and Apple pay support for Nuvei
[SER-1344](https://spreedly.atlassian.net/browse/SER-1344)
Unit test
Finished in 0.010805 seconds.
14 tests, 47 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
1295.70 tests/s, 4349.84 assertions/s
Remote test
Finished in 73.320303 seconds.
24 tests, 73 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
0.33 tests/s, 1.00 assertions/s
Rubocop

Nuvei: Add Google and Apple pay

---

CHANGELOG
lib/active_merchant/billing/gateways/versa_pay.rb
test/fixtures.yml
test/remote/gateways/remote_versa_pay_test.rb
test/unit/gateways/versa_pay_test.rb

This commit includes the basic layout, test and live urls, supported countries, currency, supported card types, scrub, etc.
Also, the basic operations, purchase, authorize, capture and verify. And the respective unit and remote tests.
[SER-1332](https://spreedly.atlassian.net/browse/SER-1332)
[SER-1333](https://spreedly.atlassian.net/browse/SER-1333)
Unit Tests:
Finished in 0.036982 seconds.
14 tests, 31 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote Tests:
Finished in 33.285413 seconds.
15 tests, 69 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Rubocop
804 files inspected, no offenses detected

Versapay: First Implementation

---

CHANGELOG
lib/active_merchant/billing/gateways/paysafe.rb
test/remote/gateways/remote_paysafe_test.rb
test/unit/gateways/paysafe_test.rb

Add profile, merchantDescriptor and billing address.
Remote
32 tests, 95 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed

Paysafe: Update fields in standalonecredits

---

CHANGELOG
lib/active_merchant/billing/gateways/cyber_source.rb
test/remote/gateways/remote_cyber_source_test.rb
test/unit/gateways/cyber_source_test.rb

This reverts commit 2d1abfacdd9cb6d95a99b2a06132ddc9d4e15384.

Revert "Cybersouce: Update brand to be symbol"

---

CHANGELOG
lib/active_merchant/billing/gateways/versa_pay.rb
test/remote/gateways/remote_versa_pay_test.rb
test/unit/gateways/versa_pay_test.rb

This includes the support
for extra operations, Void, Refund, and Credit
with the necessary unit and remote tests.
[SER-1334](https://spreedly.atlassian.net/browse/SER-1334)
Unit Tests
Finished in 0.070284 seconds.
24 tests, 124 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote Tests
Finished in 72.628972 seconds.
22 tests, 104 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Rubocop
804 files inspected, no offenses detected

Versapay: Void, Refund, Credit

---

CHANGELOG
lib/active_merchant/billing/gateways/mit.rb

Description
Update the URL of the test environment
Unit tests
6089 tests, 80732 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote tests
8 tests, 21 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 87.5% passed
Failures not related to the changes.
Rubocop
804 files inspected, no offenses detected

MIT: Change test URL

---

CHANGELOG
lib/active_merchant/billing/gateways/commerce_hub.rb

Unit:
28 tests, 194 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote:
35 tests, 94 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 94.2857% passed

CommerceHub: Update Production URL

---

CHANGELOG
lib/active_merchant/billing/check.rb
lib/active_merchant/billing/gateways/commerce_hub.rb
test/remote/gateways/remote_commerce_hub_test.rb
test/unit/gateways/commerce_hub_test.rb

Remote
36 tests, 96 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 94.4444% passed
Unit
29 tests, 205 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed

CommerceHub: Add Network Token support

---

lib/active_merchant/billing/gateways/ebanx.rb
test/remote/gateways/remote_ebanx_test.rb

Fix processing_type header
Spreedly reference: OPPS-220

Ebanx: Fix processing_type header

---

CHANGELOG
lib/active_merchant/billing/gateways/worldpay.rb
test/remote/gateways/remote_worldpay_test.rb
test/unit/gateways/worldpay_test.rb

[OPPS-225](https://spreedly.atlassian.net/browse/OPPS-225)
Unit tests
Finished in 0.425922 seconds.
135 tests, 745 assertions, 0 failures, 0 errors, 
100% passed
316.96 tests/s, 1749.15 assertions/s
Remote tests
Finished in 145.612455 seconds.
114 tests, 491 assertions, 0 failures, 0 errors, 
100% passed
0.78 tests/s, 3.37 assertions/s

Worldpay: Idempotency key fix

---

CHANGELOG
lib/active_merchant/billing/gateways/stripe.rb
lib/active_merchant/billing/gateways/stripe_payment_intents.rb
test/remote/gateways/remote_stripe_payment_intents_test.rb
test/unit/gateways/stripe_payment_intents_test.rb

This reverts commit 320b2ecea9df186c05b476b67bf30d5d99576fbd.

Revert "StripePI: Update version to 2022-11-15"

---

.github/workflows/ruby-ci.yml
.rubocop.yml
CHANGELOG
activemerchant.gemspec
circle.yml
gemfiles/Gemfile.rails_master
test/unit/gateways/braintree_token_nonce_test.rb
test/unit/gateways/versa_pay_test.rb

This reverts commit b53cc908cec90230ba3ef0f68c4c0e3eca037fea.

Revert "Update required Ruby version to 3.2.0"

---

CHANGELOG
lib/active_merchant/billing.rb
lib/active_merchant/billing/gateway.rb
lib/active_merchant/billing/gateways/adyen.rb
lib/active_merchant/billing/gateways/barclaycard_smartpay.rb
lib/active_merchant/billing/gateways/braintree_blue.rb
lib/active_merchant/billing/gateways/fat_zebra.rb
lib/active_merchant/billing/gateways/forte.rb
lib/active_merchant/billing/gateways/global_collect.rb
lib/active_merchant/billing/gateways/hps.rb
lib/active_merchant/versionable.rb
test/unit/gateways/adyen_test.rb
test/unit/gateways/barclaycard_smartpay_test.rb
test/unit/gateways/braintree_blue_test.rb
test/unit/gateways/fat_zebra_test.rb
test/unit/gateways/forte_test.rb
test/unit/gateways/global_collect_test.rb
test/unit/gateways/hps_test.rb
test/unit/versionable_test.rb

Summary:
This change centralizes version management at the class level, creating a consistent and reusable way to define and access API versions.
Unit Tests:
6103 tests, 80806 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
RuboCop:

Normalize API versions

---

CHANGELOG
Gemfile
lib/active_merchant/billing/gateways/safe_charge.rb
test/remote/gateways/remote_safe_charge_test.rb

Remote
37 tests, 102 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 94.5946% passed

SafeCharge: Add Australia & Canada as supported countries

---

CHANGELOG
lib/active_merchant/billing/gateways/ebanx.rb
test/unit/gateways/ebanx_test.rb

Now including: Costa Rica, Dominican Republic, Guatemala, Panama, Paraguay, Uruguay
CER-2035
LOCAL
6169 tests, 81063 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
REMOTE
43 tests, 98 assertions, 7 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 83.7209% passed
(these failures also exist on the master branch)
UNIT
29 tests, 146 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed

EBANX: Update list of supported countries

---

CHANGELOG
lib/active_merchant/country.rb
test/unit/country_test.rb

CER-2034
6169 tests, 81065 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed

Add alternate spelling for Vietnam

---

CHANGELOG
lib/active_merchant/billing/gateways/cyber_source.rb
test/remote/gateways/remote_cyber_source_test.rb
test/unit/gateways/cyber_source_test.rb

Update 3DS fields to pass browser_info in the request.

Cybersource: Update 3DS fields

---

lib/active_merchant/billing/gateways/nuvei.rb
test/remote/gateways/remote_nuvei_test.rb
test/unit/gateways/nuvei_test.rb

Description
[SER-1583](https://spreedly.atlassian.net/browse/SER-1583)
This commit update the money format in order to send the correct amount to nuvei gateway.
Unit test
Finished in 1.534697 seconds.
32 tests, 169 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
20.85 tests/s, 110.12 assertions/s
Remote test
Finished in 109.96803 seconds.
43 tests, 139 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
0.39 tests/s, 1.26 assertions/s
Rubocop

Nuvei: Fix money format

---

lib/active_merchant/billing/gateways/cecabank/cecabank_json.rb
test/remote/gateways/remote_cecabank_rest_json_test.rb
test/unit/gateways/cecabank_rest_json_test.rb

Summary
This fix eci value on three_d_secure
[SER-1628](https://spreedly.atlassian.net/browse/SER-1628)
Unit Tests
Finished in 0.032173 seconds.
23 tests, 125 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote Tests
Finished in 27.168569 seconds.
21 tests, 74 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
Rubocop

Cecabank: Server Error - No ECI

---

CHANGELOG
lib/active_merchant/billing/gateways/checkout_v2.rb
test/unit/gateways/checkout_v2_test.rb

6209 tests, 81274 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed

Checkout: Improve payout handling with blank sender data

---

CHANGELOG
lib/active_merchant/billing/gateways/checkout_v2.rb
test/remote/gateways/remote_checkout_v2_test.rb
test/unit/gateways/checkout_v2_test.rb

https://www.checkout.com/docs/payments/authenticate-payments/verify-a-card#Request_an_account_name_inquiry
CER-2131
LOCAL
6216 tests, 81347 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
UNIT
74 tests, 506 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
REMOTE
118 tests, 268 assertions, 19 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 83.8983% passed
(also failing on master branch)

CheckoutV2: Add account name inquiry

---

lib/active_merchant/billing/gateways/vpos.rb
test/remote/gateways/remote_vpos_test.rb
test/unit/gateways/vpos_test.rb

Description
[SER-1590](https://spreedly.atlassian.net/browse/SER-1590)
This commit add transaction sync for VPOS Gateway, additionally it update the `generate_token` method
Unit test
8 tests, 32 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
24.70 tests/s, 98.81 assertions/s
Remote test
13 tests, 47 assertions, 3 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
76.9231% passed
0.20 tests/s, 0.50 assertions/s
Rubocop

VPOS: Add transaction sync

---

lib/active_merchant/billing/gateways/commerce_hub.rb
test/remote/gateways/remote_commerce_hub_test.rb

Spreedly reference: [OPPS-371](https://spreedly.atlassian.net/browse/OPPS-371)
Remote tests
Finished in 70.933066 seconds.
36 tests, 97 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
97.2222% passed
0.51 tests/s, 1.37 assertions/s
Unit tests
Finished in 50.661584 seconds.
6228 tests, 81395 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
122.93 tests/s, 1606.64 assertions/s
Rubocop

Commerce Hub update merchantInvoiceNumber GSF for Credits

---

CHANGELOG
lib/active_merchant/billing/gateways/ebanx.rb
test/remote/gateways/remote_ebanx_test.rb
test/unit/gateways/ebanx_test.rb

Summary
handle special characters in email for Ebanx 
[OPPS-376](https://spreedly.atlassian.net/browse/OPPS-376)
Unit Tests
Finished in 0.00819 seconds.
35 tests, 172 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
4273.50 tests/s, 21001.22 assertions/s
Remote Tests 
Finished in 48.986671 seconds.
46 tests, 113 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
0.94 tests/s, 2.31 assertions/s
Rubocop

OPPS-376 handle special characters in email for Ebanx

---

lib/active_merchant/billing/gateway.rb
lib/active_merchant/billing/gateways/mercado_pago.rb
lib/active_merchant/billing/gateways/orbital.rb
test/remote/gateways/remote_mercado_pago_test.rb
test/remote/gateways/remote_orbital_test.rb
test/unit/gateways/gateway_test.rb
test/unit/gateways/mercado_pago_test.rb

Orbital keep only A-Za-z characters

Orbital keep only A-Za-z characters

---

lib/active_merchant/billing/gateways/loan_payment_pro.rb
test/fixtures.yml
test/remote/gateways/remote_loan_payment_pro_test.rb
test/unit/gateways/loan_payment_pro_test.rb

This PR introduces the initial implementation of the AM adapter
for [LoanPaymentPro gateway](www.loanpaymentpro.com) with support
for:
* Authorize
* Purchase
* Capture
* Void
* Verify
* Refund
18 tests, 44 assertions, 0 failures, 0 errors, 0 pendings,  1 omissions, 0 notifications
100% passed
Finished in 43.722285 seconds.
6255 tests, 81546 assertions, 0 failures, 0 errors, 0 pending, 0 omissions, 0 notifications
100% passed
812 files inspected, no offenses detected

LoanPaymentPro: Initial implementation

---

CHANGELOG
lib/active_merchant/billing/gateways/payeezy.rb
lib/active_merchant/billing/gateways/paymentez.rb
lib/active_merchant/billing/gateways/paymill.rb
test/remote/gateways/remote_paymentez_test.rb
test/unit/gateways/payeezy_test.rb
test/unit/gateways/paymentez_test.rb
test/unit/gateways/paymill_test.rb

Normalized API versions for Payeezy, Paymentez, and Paymill
Ticket: [OPPS-199](https://spreedly.atlassian.net/browse/OPPS-199)
6242 tests, 81486 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
809 files inspected, no offenses detected

Normalized API versions for Payeezy, Paymentez, and Paymill

---

CHANGELOG
lib/active_merchant/billing/gateways/pin.rb
test/remote/gateways/remote_pin_test.rb
test/unit/gateways/pin_test.rb

Scrub sensitive data from transcript related to NT based payment methods

Pin Payments: Scrub sensitive data from transcript

---

CHANGELOG
lib/active_merchant/billing/gateways/credorax.rb
test/unit/gateways/credorax_test.rb

This reverts commit d0cfe459279415cad7346bafe62f5fd286417bf7.

Revert "Fixed sign_request for Credorax gateway (#5463)"

---

CHANGELOG
lib/active_merchant/billing/gateways/credorax.rb
test/remote/gateways/remote_credorax_test.rb
test/unit/gateways/credorax_test.rb

Fixed error `At least one of input parameters is malformed. Package has not been authorized` due to sign request from Credorax gateway
Remote Tests
60 tests, 210 assertions, 7 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
88.3333% passed
Unit Tests
88 tests, 448 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Credorax: Fixed request signature

---

CHANGELOG
lib/active_merchant/billing/gateways/nab_transact.rb
lib/active_merchant/billing/gateways/optimal_payment.rb
lib/active_merchant/billing/gateways/orbital.rb
test/unit/gateways/nab_transact_test.rb
test/unit/gateways/optimal_payment_test.rb
test/unit/gateways/orbital_test.rb

Normalize API versions for NabTransact, OptimalPayment and Orbital
Remote Test:
NabTransact:
> 22 tests, 84 assertions, 3 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
>   86.3636% passed
OptimalPayment:
> 20 tests, 97 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
>   100% passed
Orbital:
> 140 tests, 563 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
>   100% passed

Summary: Normalize API versions for NabTransact, OptimalPayment and Orbital
