activemerchant/active_merchant

lib/active_merchant/billing/gateways/braintree_blue.rb

This was producing a warning when running on 2.2

Fix duplicate hash key in braintree blue gateway

---

test/test_helper.rb
test/unit/gateways/cashnet_test.rb
test/unit/gateways/quickpay_test.rb
test/unit/gateways/sage_vault_test.rb

The default year used in the test_helper's `#credit_card` is `Time.now.year + 1` which broke a few of these tests.
I'm running all of the remotes locally right now to check them as well, but they're slooooowwwww
Also, Sublime nuked a bunch of whitespace, so you might want to `?w=1` or whatever this diff.
@ntalbott @girasquid

Fixes tests with new 2016 expiration dates

---

lib/active_merchant/billing/gateways/quickbooks.rb
test/remote/gateways/remote_quickbooks_test.rb

Confronted during remote testing.
QuickBooks API returns an HTTP 400 status code for any failed transaction, even if the request is well-formed. :disappointed: 
Because active_utils raises an `ActiveMerchant::ResponseError` for HTTP status codes outside 200-300, legit-but-failed transactions are interpreted as any other bad request. 
This code captures `ResponseError`s and re-raises if there exists no JSON in its `response.body`, otherwise the JSON -- which includes the necessary error data -- is parsed and an `ActiveMerchant::Response` is constructed as usual. 
@ivanfer @j-mutter /cc @Shopify/active-merchant

[QuickBooks Payments] Fix: Handle HTTP 400 status codes on failed transactions

---

test/unit/gateways/adyen_test.rb
test/unit/gateways/braintree_blue_test.rb
test/unit/gateways/bridge_pay_test.rb
test/unit/gateways/litle_test.rb
test/unit/gateways/network_merchants_test.rb
test/unit/gateways/nmi_test.rb
test/unit/gateways/stripe_test.rb
test/unit/gateways/usa_epay_transaction_test.rb

- When using mocha's `with` parameter matcher, you should not use assertions inside the block, but return true or false.
- Using uninitialized instance variables has different effect in different ruby versions. Make sure `@options` is set before using it in `@gateway.verify(@credit_card, @options)` calls.
Currently, these issues do not make the test suit fail due to the magic Ruby + mocha + test-unit/minitest version combination, but it fails when I change those.
@Shopify/payments @ntalbott for review

Clean up some tests

---

init.rb

`init.rb` is only needed for people that have installed activemerchant in Rails 2 as a rails plugin, and are not using bundler.

Drop init.rb

---

.travis.yml
Gemfile.rails32
Gemfile.rails40
Gemfile.rails41
Gemfile.rails42
Gemfile_rails40
activemerchant.gemspec
test/test_helper.rb
test/unit/gateways/litle_test.rb
test/unit/gateways/realex_test.rb

This updates the Travis CI build matrix.
- Also test against Ruby 2.2
- Tests more explicitly specified versions of Rails / ActiveSupport.
CircleCI will test against the latest dependency versions that meet the gemspec. We should see if we can open source this project there; I think this is now supported.
@j-mutter @girasquid @aprofeit @ntalbott for review.

Update Travis CI build matrix

---

lib/active_merchant/billing/gateways/hps.rb
lib/active_merchant/billing/gateways/skip_jack.rb
lib/active_merchant/billing/gateways/wirecard.rb

When hash keys are redefined, the last occurrence will be kept.
- For skipjack, I kept the one that I could find in their docs: http://imgserver.skipjack.com/imgServer/5293710/AVS%20and%20CVV2.pdf
- WireCard and HPS were just duplicates, so I removed the last occurrence.
@ntalbott @Shopify/payments for review

Remove duplicate hash keys that were causing warnings

---

activemerchant.gemspec
test/test_helper.rb
test/unit/gateways/hdfc_test.rb
test/unit/gateways/jetpay_test.rb

Bump test-unit and mocha versions, as discussed in #1516.

Bump test/unit and mocha

---

lib/active_merchant.rb

It ships with Ruby 1.9 and up.

Remove base64 strict backport as it is no longer needed

---

lib/active_merchant/posts_data.rb

It has been deprecated, in lieu of `class_attribute`.

Use class_attribute instead of superclass_delegating_accessor in posts_data

---

Gemfile
lib/active_merchant/billing/gateways/quickbooks.rb
test/remote/gateways/remote_quickbooks_test.rb

Upon inspection of the `oauth` gem at https://github.com/oauth-xx/oauth-ruby, we noticed [the default HMAC-SHA1 mechanism](https://github.com/oauth-xx/oauth-ruby/blob/master/lib/digest/hmac.rb) used to sign requests is [officially discouraged](http://www.ruby-doc.org/stdlib-2.0/libdoc/digest/rdoc/Digest/HMAC.html) and thus unacceptable for deployment in a PCI environment. 
This removes the gem dependency and isolates OAuth 1.0a request signing into the QuickBooks Payments adapter, and uses the OpenSSL implementation of HMAC instead, as suggested by the official Ruby documentation.
@girasquid @ntalbott /cc @Shopify/active-merchant

[QuickBooks Payments] remove oauth gem, implement OAuth request signing in QuickbooksGateway

---

lib/active_merchant/billing/gateways/authorize_net.rb

- When generating XML, use parentheses when calling tag methods
- Do not use parentheses around if clauses.
In certain Ruby versions, some of these lines were causing warnings because the interpretation is ambiguous without parentheses.

[authorize.net] Fix ambiguous use of parenthesis in authorize.net gateway

---

lib/active_merchant/billing/gateways/beanstream.rb
lib/active_merchant/billing/gateways/beanstream_interac.rb
lib/active_merchant/billing/gateways/braintree.rb
lib/active_merchant/billing/gateways/braintree_blue.rb
lib/active_merchant/billing/gateways/braintree_orange.rb
lib/active_merchant/billing/gateways/elavon.rb
lib/active_merchant/billing/gateways/finansbank.rb
lib/active_merchant/billing/gateways/ideal/ideal_base.rb
lib/active_merchant/billing/gateways/ideal_rabobank.rb
lib/active_merchant/billing/gateways/migs.rb
lib/active_merchant/billing/gateways/modern_payments.rb
lib/active_merchant/billing/gateways/orbital.rb
lib/active_merchant/billing/gateways/payflow.rb
lib/active_merchant/billing/gateways/payflow_express.rb
lib/active_merchant/billing/gateways/payflow_express_uk.rb
lib/active_merchant/billing/gateways/payflow_uk.rb
lib/active_merchant/billing/gateways/paypal.rb
lib/active_merchant/billing/gateways/paypal/paypal_recurring_api.rb
lib/active_merchant/billing/gateways/paypal_ca.rb
lib/active_merchant/billing/gateways/paypal_digital_goods.rb
lib/active_merchant/billing/gateways/paypal_express.rb
lib/active_merchant/billing/gateways/sage.rb
lib/active_merchant/billing/gateways/sage/sage_bankcard.rb
lib/active_merchant/billing/gateways/sage/sage_virtual_check.rb
lib/active_merchant/billing/gateways/secure_pay.rb
test/remote/gateways/remote_inspire_test.rb

A library shouldn't use relative requires. You can/should assume that the dependency manager (e.g. bundler) has set the `$LOAD_PATH` correctly to include `lib` (and `test` in test mode). Using relative requires can cause double loading of files in some cases, which can be a subtle source of bugs and warnings. 
If you really need to require a file relative to the current file, use `require_relative`, but we don't need it in this gem.

Don't use relative requires

---

lib/active_merchant/billing/gateways/paymill.rb
test/unit/gateways/paymill_test.rb

Paymill returns a string `response_code` for refunds in production environment which causes refunds to be categorized as unsuccessful. This PR fixes this and ensures a string "20000" code still returns successful.
@girasquid @aprofeit

Fix paymill refunds

---

lib/active_merchant/billing/gateways/firstdata_e4.rb
test/unit/gateways/firstdata_e4_test.rb

Another continuation of https://github.com/Shopify/active_merchant/pull/1566 for FirstData E4.
There's no way to test this without doing a live test (they don't have sandbox verification for it). I definite confirmation from FirstData that this is the format they expect this data in and that it will work without issue.
This can be merged as soon as https://github.com/Shopify/active_merchant/pull/1566 in in.
@girasquid @bizla for review please, thanks!
cc @markabe @rwdaigle @ntalbott

Adds apple pay support for FirstData E4

---

lib/active_merchant/billing/gateways/authorize_net.rb
test/remote/gateways/remote_authorize_net_test.rb
test/unit/gateways/authorize_net_test.rb

Added applicable authorize.net error codes defined [here](http://www.authorize.net/support/ReportingGuide_XML.pdf).
@j-mutter @aprofeit for review
@ntalbott

Add standard error codes for auth.net

---

lib/active_merchant/billing/gateways/firstdata_e4.rb
test/remote/gateways/remote_firstdata_e4_test.rb
test/unit/gateways/firstdata_e4_test.rb

Adding standard error codes for First Data. Did my best to fit standard error codes into their model. Note I was not able to find a response parameter that contained only the ecommerce error code so I am extracting it out of the response message. 
Bank codes: https://firstdata.zendesk.com/entries/471297-First-Data-Global-Gateway-e4-Bank-Response-Codes
Ecommerce codes: https://firstdata.zendesk.com/entries/451980-ecommerce-response-codes-etg-codes
@j-mutter @aprofeit

Adding standard error codes for firstdata

---

CHANGELOG
lib/active_merchant/billing/credit_card.rb
test/unit/credit_card_test.rb

@rwdaigle @duff @jasonwebster wondering if any of you had thoughts?
---
When a credit card name is set using `name=` method, the first and last
names will be split into their respective fields. For example-
```ruby
card = ActiveMerchant::Billing::CreditCard.new name: "John"
card.first_name # => ""
card.last_name # => "John"
```
The issue is if we call `name` again on the card, we get a leading space-
```ruby
card.name # => " John"
```
This update will remove any leading or trailing whitespaces when calling
the name method regulardless of the value of first and last name or how
it was originally set.
```ruby
card = ActiveMerchant::Billing::CreditCard.new name: "John"
card.first_name # => ""
card.last_name # => "John"
card.name # => "John"
```

Remove leading or trailing whitespace from CreditCard name

---

CHANGELOG
lib/active_merchant/billing/gateways/global_collect.rb
test/fixtures.yml
test/remote/gateways/remote_global_collect_test.rb
test/unit/gateways/global_collect_test.rb

GlobalCollect has fairly flexible field lengths for most of their request fields, however the `firstName` field is maxed at 15 characters which is just short enough that it could be an issue. There aren't that many first names more than 15 characters, but some are and formatting of a first name could also play a role. This truncates it to 15 characters so requests for ease of use sake.
`lastName` is also truncated at 70 characters but that's less because of it being an issue and more for consistency truncating name fields than need.
Additionally, while running the remote tests to verify the change it appears as though some of the error response formats have change so this updates those tests as well.
Here is the full remote test output to validate it passes-
```
➜ ruby -Itest …
```

GlobalCollect: Truncate firstName field to 15 characters

---

CHANGELOG
lib/active_merchant/billing/gateways/global_collect.rb
test/unit/gateways/global_collect_test.rb

It should be noted that Global Collect requires 24 hours for purchase to
settle before attempting a refund so remote tests for refunds are not
easily reproducible. Furthermore, forcing a REJECTED response in a
refund is not covered in the docs which is why this is lacking a remote
tests. However the unit test does take into account the response as shown
in the docs.
Closes #2365

GlobalCollect: Set REJECTED refunds as unsuccessful transactions

---

CHANGELOG
lib/active_merchant/billing/gateways/jetpay.rb
test/remote/gateways/remote_jetpay_test.rb

Capture responses do not return the token used during the authorize and
without a token, it's not possible to refund the capture without sending
in the original credit card number. This passes down the payment method
token returned in the authorization response to the capture's concatenated
authorization. This allows the token to be passed when refunding a
capture which negates the need to send in a credit card number.
Previously, this discrepency bubbled up as a failed refund with the
error message being that the credit card number is missing.

JetPay: Pass down authorization payment method token to refund a capture

---

lib/active_merchant/posts_data.rb

Saw a bunch of these warnings that did not make sense because it was connecting to a https endpoint. An URI object is valid to pass in for `Connection#initialize`.
```ruby
URI('https://foo.com') =~ /^https:/
=> nil # would trigger warning
```

Fix 'posting to plaintext endpoint, which is insecure' warning

---

.travis.yml
Gemfile.rails32
Gemfile.rails40
Gemfile.rails41
Gemfile.rails42
Gemfile.rails50
Gemfile.rails51

- Add Ruby 2.4 to the test matrix
- Use latest Rubies
- Use release version of Active Support 5
- Add a canary build of Active Support 5.1 that is in the RC stage before release

Travis update

---

.travis.yml
Gemfile.rails51
activemerchant.gemspec

[Rails 5.1 final is out](http://weblog.rubyonrails.org/2017/4/27/Rails-5-1-final/)!
This fixes the CI setup for the Rails 5.1 final release and loosens the gemspec dependency to support it.

Add Rails 5.1 support

---

test/unit/gateways/authorize_net_test.rb

Travis is failing on a particular build and it looks like the test is actually trying to make an HTTP request. Since it's a unit test, it should be stubbed out like all of the other tests around it.
```
Started
...............................................................................
......../home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/http.rb:895: warning: instance variable @npn_protocols not initialized
/home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/http.rb:895: warning: instance variable @npn_select_cb not initialized
E
===============================================================================
Error: test_duplicate_window_class_attribute_deprecated(AuthorizeNetTest): ActiveMerchant::ConnectionError: The remote server reset the connection …
```

Stub Authorize.Net unit test to fix Travis build failure

---

CHANGELOG
lib/active_merchant/billing/gateways/opp.rb
test/remote/gateways/remote_opp_test.rb
test/unit/gateways/opp_test.rb

Lotsa automatically trimmed trailing spaces showing up in the diff. Sorry about that. Minor changes to keep options in-line with other AM adapters.
Some portions of the implementation is different from typical adapters. The way stored tokens are handled needs some change. I guess that can happen when there's a need for `store` to be added. Right now focus is on minimal changes.
In addition to the diffs, please review transaction success criteria as defined in
`def success_from(raw_response)` 
It's deciding based on http response code. Should it actually be looking at `result.code` within the response. I can make that change once reviewer confirms.
ref: https://docs.acaptureservices.com/

Opp: Clean up options

---

test/remote/gateways/remote_beanstream_test.rb

No need to use offensive terms in our codebase, let's try to be inclusive and welcoming instead.
@elfassy

Rename invalid province in remote beanstream test

---

lib/active_merchant/billing/gateways/cyber_source.rb
test/unit/gateways/cyber_source_test.rb

Use the top level `ResponseCode` from the XML response
In cases where a `c:ccAuthReply` was provided, we would recursively append its data to the response. The problem is that the `c:ccAuthReply` data also contained a different `ResponseCode`. This could lead to situations where we had a response code for success (100) but a `decision` which was `REJECT`. 
Cybersource confirmed with me over the phone that the authorization (AuthReply) can be a success but the merchant rules (Decision Manager) can still reject the transaction. https://support.cybersource.com/cybskb/index?page=content&id=C156&impressions=false

cybersource handle nested AuthReply with different reasonCode

---

CHANGELOG
lib/active_merchant/billing/gateways/nmi.rb
test/remote/gateways/remote_nmi_test.rb

**UPDATED**
```
$ RUBYOPT=W0 be rake test:remote TEST=test/remote/gateways/remote_nmi_test.rb 
33 tests, 106 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
```
---
```
$ RUBYOPT=W0 be rake test:units TEST=test/unit/gateways/nmi_test.rb 
27 tests, 192 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
```

NMI: Add Network Tokenization support

---

CHANGELOG
lib/active_merchant/billing/gateways/jetpay_v2.rb
test/fixtures.yml
test/remote/gateways/remote_jetpay_v2_test.rb
test/unit/gateways/jetpay_v2_test.rb

New adapter that talks to [JetPay Host XML Specification V2.03.01.pdf](https://github.com/activemerchant/active_merchant/files/1030427/JetPay.Host.XML.Specification.V2.03.01.pdf)
---
```
$ RUBYOPT=W0 be rake test:remote TEST=test/remote/gateways/remote_jetpay_v2_test.rb 
19 tests, 86 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
```
```
$ RUBYOPT=W0 be rake test:units TEST=test/unit/gateways/jetpay_v2_test.rb 
17 tests, 66 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
```

JetPay V2: Add new gateway

---

CHANGELOG
lib/active_merchant/billing/gateways/jetpay_v2.rb
test/remote/gateways/remote_jetpay_v2_test.rb
test/unit/gateways/jetpay_v2_test.rb

```
$ be rake test:units
3560 tests, 66457 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
```
```
$ be rake test:remote TEST=test/remote/gateways/remote_jetpay_v2_test.rb 
20 tests, 93 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed …
```

JetPay V2: Add optional tax data to capture calls

---

CHANGELOG

Some items were mistakenly added to the changelog for release 1.66.0 after the release was created. This just moves them into 1.67.0.
[1.66.0 release](https://github.com/activemerchant/active_merchant/releases/tag/v1.66.0)
[1.67.0 release](https://github.com/activemerchant/active_merchant/releases/tag/v1.67.0)

Move changelog entries to the correct release

---

CHANGELOG
lib/active_merchant/billing/gateways/jetpay_v2.rb
test/remote/gateways/remote_jetpay_v2_certification_test.rb
test/remote/gateways/remote_jetpay_v2_test.rb

- Support `store`
- Modify other transactions to accept stored tokens
- Commit certification tests to the repo
---
```ruby
$ be rake test:units TEST=test/unit/gateways/jetpay_v2_test.rb 
17 tests, 66 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
```
```ruby
$ be rake test:remote TEST=test/remote/gateways/remote_jetpay_v2_test.rb 
------------------------------------------------------------------------------------------------------------------------------------- …
```

JetPay V2: Support `store` and token based payments

---

CHANGELOG
lib/active_merchant/billing/gateways/cyber_source.rb

Docs: http://apps.cybersource.com/library/documentation/dev_guides/CC_Svcs_SO_API/html/wwhelp/wwhimpl/js/html/wwhelp.htm#href=app_card_types.html

Cybersource: update supported card types

---

CHANGELOG
lib/active_merchant/billing/gateways/authorize_net.rb
test/unit/gateways/authorize_net_test.rb

Removed in https://github.com/activemerchant/active_merchant/pull/2496
Turns out (surprise!) Authorize.net docs have some contradictory advice.
http://developer.authorize.net/api/reference/#payment-transactions-charge-a-credit-card
For `billTo.state` says:
> State of customer’s billing address. Required only when using a European Payment Processor.

Authorize.net: Restore default state value for non-US addresses

---

CHANGELOG
lib/active_merchant/billing/gateways/braintree_blue.rb

#2565 introduced a requirement on braintree-ruby gem version 2.78.0. While the Gemfile was updated with the correct version for tests, the version check at the top of the gateway class was not updated, meaning apple pay transactions will fail if you're not running version 2.78.0.
This PR explicitly requires version 2.78.0 of braintree-ruby to be able to load the class.

Explicitly require braintree-ruby gem version 2.78.0

---

CHANGELOG
lib/active_merchant/billing/gateways/netbanx.rb

The previous implementation for basic auth was only using the api_key. According to https://developer.paysafe.com/en/cards/api/#/introduction/authentication,
we should be sending the account_number followed by the api_key.

Fix basic auth for netbanx by sending the account_number and api_key

---

CHANGELOG
lib/active_merchant/billing/gateways/barclaycard_smartpay.rb
test/remote/gateways/remote_barclaycard_smartpay_test.rb
test/unit/gateways/barclaycard_smartpay_test.rb

Although using a regex has worked for *most* of the needed address
parsing, there are still a few exceptions. Due to the unusual address
structure, this allows some require fields to
come through in the options hash: `:street`, `:shipping_street`,
`:house_number`, and `:shipping_house_number`.
Unit Tests:
17 tests, 59 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
Remote Tests:
24 tests, 48 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed

Barclaycard Smartpay: Refactors address parsing.

---

lib/active_merchant/billing/gateways/barclaycard_smartpay.rb
test/remote/gateways/remote_barclaycard_smartpay_test.rb

Unit tests:
22 tests, 95 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
Remote tests:
26 tests, 52 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed

Barclaycard Smartpay: Allows purchase with no address

---

lib/active_merchant/connection.rb
lib/active_merchant/network_connection_retries.rb

The monotonic clock can only move forward and is not subject to changes of the system clock, e.g. corrections due to NTP or VM adjustments.
This is what `Benchmark.realtime` uses too and it's a bit faster than using `Time`: https://bugs.ruby-lang.org/issues/10165

Use monotonic clock to measure elapsed time

---

CHANGELOG
lib/active_merchant/billing/gateways/firstdata_e4.rb
test/unit/gateways/firstdata_e4_test.rb

This is an upstream patch for something we've been doing at Shopify for a long time now.

FirstData E4 (Payeezy): Ensure numeric ECI values are zero padded

---

lib/active_merchant/billing/gateways/barclaycard_smartpay.rb
test/remote/gateways/remote_barclaycard_smartpay_test.rb
test/unit/gateways/barclaycard_smartpay_test.rb

Barclays Smartcard will be requiring credits that lack a PSP to include four additional pieces of information: the date-of-birth, entity type, nationality, and full name of the person requesting the credit. This change enables including them.

Support extra data for Barclay Smartcard credits

---

CHANGELOG
lib/active_merchant/billing/gateways/payu_latam.rb
test/unit/gateways/payu_latam_test.rb

1) Adds `partnerId`.
2) Ensures phone_number is passed to 'buyer.contactPhone' and prefers
billing phone over shipping phone.
3) Sends empty field for 'ip_address' when none supplied.
4) Ensures 'creditCard.secutiryCode' node is not included when there is
no 'cvv'.
Remote Tests:
(Includes 5 failing tests on master: 2 'INTERNAL_PAYMENT_PROVIDER_ERROR'
and 3 'DECLINED_TEST_MODE_NOT_ALLOWED'.)
18 tests, 45 assertions, 5 failures, 0 errors, 0 pendings, 0 omissions,
72.2222% passed
Unit Tests:
24 tests, 94 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed

PayU Latam: Four small updates

---

test/remote/gateways/remote_barclaycard_smartpay_test.rb
test/unit/gateways/barclaycard_smartpay_test.rb

The intent in the tests was clearly to create a *distinct* options array, but what actually happened is that the original options array was modified. This patch causes the code to do the intended behavior. (Interestingly, this doesn't alter any test passes or failures, because having extra data doesn't upset either the unit tests or remote tests.)

Shallow copy the options hash for Barclays tests

---

lib/active_merchant/billing/gateways/payu_latam.rb

Remote Tests:
(Includes 5 failing tests on master: 2 'INTERNAL_PAYMENT_PROVIDER_ERROR'
and 3 'DECLINED_TEST_MODE_NOT_ALLOWED'.)
18 tests, 45 assertions, 5 failures, 0 errors, 0 pendings, 0 omissions,
72.2222% passed
Unit Tests:
24 tests, 94 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed

Payu Latam: Changes partnerID to partner_id in options

---

CHANGELOG
lib/active_merchant/billing/gateways/cyber_source.rb
test/remote/gateways/remote_cyber_source_test.rb
test/unit/gateways/cyber_source_test.rb

'subscriptionID' is required to authorize store. Previously 'requestID'
was used to populate the 'subscriptionID'. In the sandbox, they yield
identical values. In production, however, they are two different values.
This correctly captures the 'subscriptionID' separately from the
'requestID'.
Remote Tests:
(Includes 2 failing tests on master regarding pinless_debit_cards. The
code for pinless_debit_cards does not currently run.)
39 tests, 181 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions,
94.8718% passed
Unit Tests:
44 tests, 212 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed

Cyber Source: Correctly identifies 'subscriptionID' for store

---

test/unit/gateways/payeezy_test.rb

Payeezy uses the :ssl_request method to store CCs.
https://github.com/activemerchant/active_merchant/blob/23c38dd7f5758360fca02b6099254b31211d7573/lib/active_merchant/billing/gateways/payeezy.rb#L276-L285
The problem is, the `stub_comms` method defaults to stubbing the `ssl_post` method.
https://github.com/activemerchant/active_merchant/blob/23c38dd7f5758360fca02b6099254b31211d7573/test/comm_stub.rb#L43-L46
This means that these tests were making remote requests every single time they run, causing flakyness in CI runs.

Stop making remote requests for payeezy store unit tests

---

CHANGELOG
lib/active_merchant/billing/gateways/netbanx.rb
test/remote/gateways/remote_netbanx_test.rb
test/unit/gateways/netbanx_test.rb

Paysafe does not allow you to send this information for captures and
purchases. Therefore we shouldn't include them even if they're passed in
the options. The remote tests would previously fail if you included the
options field for captures or refunds, but they now pass.

Only send currency and billing_details for auths and sales for Netbanx

---

CHANGELOG
lib/active_merchant/billing/gateways/netbanx.rb

This reverts commit a838219a497144abc2bd72f16729e9d9b07a495c. The
previous change needed to be reverted because I had misunderstood that
the account number and username are different values. By reverting the
last PR, the api_key needs to be in the basic auth format already
(`<username>:<password>`).

Revert "Fixes basic auth for netbanx by sending the account_number and api_key"

---

lib/active_merchant/connection.rb
test/unit/connection_test.rb

The wiredump_device setter takes an object that quacks like an IO stream (e.g. File or String) and passes it along to Net:HTTP#set_debug_output where it is used by the private `D` method for appending log messages, as seen here: https://github.com/ruby/ruby/blob/c91cb76f8d84b2963f6ede2ef445ad46a6104216/lib/net/http.rb#L1567
If the device is set to an empty string literal (i.e. "") and the frozen string literal magic comment is added to the file, this causes `RuntimeError: can't modify frozen String` exceptions. The stacktrace can be confusing since setting up the gateway object and using it usually happens in different places in the application code.
This PR aims to fail early if such a situation occurs and provide a stacktrace that clearly points to the cause of the error.

Prevent frozen objects being assigned as wiredump device

---

CHANGELOG
lib/active_merchant/billing/gateways/safe_charge.rb
test/remote/gateways/remote_safe_charge_test.rb
test/unit/gateways/safe_charge_test.rb

The documentation and sandbox indicate that Safe Charge has an internal
method for determining 3DS status/flow. This adds an explicit 3DS flag
when/if there are issues with that internal mechanism.
Unit Tests:
17 tests, 76 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
Remote Tests:
21 tests, 62 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed

Safe Charge: Adds 3DS flag

---

CHANGELOG
lib/active_merchant/billing/gateways/mercado_pago.rb

An access token provided that was not validly URL-encoded (e.g., had
spaces) could cause ActiveRecord to crash, since it could result in a
malformed URL. This ensures that even a malformed access token can be
passed through, avoiding a crash and allowing normal error handling
to take place.

Mercado Pago: protect against invalid access tokens

---

lib/active_merchant/billing/gateways/iats_payments.rb
test/unit/gateways/iats_payments_test.rb

Authorization Result is not returned if there is a status failure. Can't
depending on having this result passed
Loaded suite test/unit/gateways/iats_payments_test
17 tests, 166 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Loaded suite test/remote/gateways/remote_iats_payments_test
12 tests, 46 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications

iATS: Fix Messages with Failure on iATS Server

---

test/unit/gateways/safe_charge_test.rb

These assertions had hard coded years in the credit card expiry, which
isn't how the test helpers work. Let's assert against what the card
object actually contains.

Fix tests failing due to new year

---

lib/active_merchant/billing/gateways/payflow.rb
test/fixtures.yml
test/remote/gateways/remote_payflow_test.rb

Currently $0 authorization is only supported for AVS. This changes the
verify method for amex cards to be a $1 auth and void.
Tests failures are unrelated to these changes.
Loaded suite test/remote/gateways/remote_payflow_test
27 tests, 99 assertions, 10 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
62.963% passed
----------------------------------------------------------------------------------------
0.60 tests/s, 2.18 assertions/s
Loaded suite test/unit/gateways/payflow_test
44 tests, 192 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Payflow: Change Verify Method for Amex Cards

---

lib/active_merchant/billing/gateways/barclaycard_smartpay.rb
test/remote/gateways/remote_barclaycard_smartpay_test.rb
test/unit/gateways/barclaycard_smartpay_test.rb

Adds 3DS Support
Loaded suite test/unit/gateways/barclaycard_smartpay_test
24 tests, 110 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Loaded suite test/remote/gateways/remote_barclaycard_smartpay_test
28 tests, 59 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Barclaycard Smartpay: 3DS Implementation

---

lib/active_merchant/billing/gateways/ogone.rb
test/remote/gateways/remote_ogone_test.rb

Add the field ORIG if sent
Two failing tests unrelated to this change
Loaded suite test/remote/gateways/remote_ogone_test
Failure:
test_successful_credit(RemoteOgoneTest)
"Refunds are not allowed for your PSPID. Please contact helpdesk."},
Error: test_successful_store_generated_alias(RemoteOgoneTest): NoMethodError: undefined method `name' for nil:NilClass
27 tests, 99 assertions, 1 failures, 1 errors, 0 pendings, 0 omissions, 0 notifications
Loaded suite test/unit/gateways/ogone_test
48 tests, 206 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Ogone: Add field ORIG

---

lib/active_merchant/billing/gateways/global_collect.rb
test/remote/gateways/remote_global_collect_test.rb

Adds creator fields to all transactions if present.
Loaded suite test/remote/gateways/remote_global_collect_test
...............
15 tests, 35 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Loaded suite test/unit/gateways/global_collect_test
16 tests, 72 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Global Collect: Add Creator Info Fields

---

CHANGELOG
lib/active_merchant/billing/network_tokenization_credit_card.rb
test/unit/network_tokenization_credit_card_test.rb

Adds Google Pay to list of allowed sources.
- Updated `NetworkTokenizedCard::SOURCES` to include `:google_pay`

Adds support for Google Pay sourced cards

---

CHANGELOG
lib/active_merchant/billing/gateways/orbital.rb
test/remote/gateways/remote_orbital_test.rb
test/unit/gateways/orbital_test.rb

Level 2 tax amount may be passed in as a string, which was throwing an
error. This will now convert tax data to an integer format.
Remote Tests:
22 tests, 137 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
Unit Tests:
69 tests, 418 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed

Orbital: Handles level 2 tax data correctly

---

CHANGELOG
lib/active_merchant/billing/gateways/payeezy.rb

Although 'store' does not officially require a 'transaction_type', it is
used here to determine the correct endpoint for a 'store' request.
Unit Tests:
32 tests, 153 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
Remote Tests:
27 tests, 98 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed

Payeezy: Changes assessment of store endpoint

---

CHANGELOG
lib/active_merchant/billing/gateways/mercado_pago.rb
test/remote/gateways/remote_mercado_pago_test.rb

Allows binary_mode to be set to a value rather than the current default
of true.
Loaded suite test/unit/gateways/mercado_pago_test
Started
...................
19 tests, 95 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Loaded suite test/remote/gateways/remote_mercado_pago_test
Started
.................
17 tests, 46 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Mercado Pago: Allow binary_mode to be changed

---

CHANGELOG
lib/active_merchant/billing/gateways/litle.rb
test/remote/gateways/remote_litle_test.rb
test/unit/gateways/litle_test.rb

Adds the optional `affiliate`, `campaign` and `merchantGroupingId`
elements as children of the `merchantData` element.
Unit:
33 tests, 142 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
31 tests, 126 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Vantiv: Add support for merchantData elements

---

CHANGELOG
lib/active_merchant/billing/gateways/merchant_warrior.rb
test/unit/gateways/merchant_warrior_test.rb

Makes the Province/State field optional for Merchant Warrior.
When no province/state is provided, the value "N/A" will be used instead.

[Merchant Warrior] Adds default for empty state field

---

CHANGELOG
lib/active_merchant/billing/gateways/stripe.rb
test/remote/gateways/remote_stripe_test.rb
test/unit/gateways/stripe_test.rb

Adds the `pickup_card` decline code to the `STANDARD_ERROR_CODE_MAPPING`
hash. This also fixes two failing remote tests by updating the
expiration dates on card track data.
Remote:
59 tests, 258 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
123 tests, 658 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Stripe: Support pickup_card decline code

---

CHANGELOG
lib/active_merchant/billing/gateways/citrus_pay.rb
lib/active_merchant/billing/gateways/dibs.rb
lib/active_merchant/billing/gateways/first_pay.rb
lib/active_merchant/billing/gateways/global_transport.rb
lib/active_merchant/billing/gateways/netbilling.rb
lib/active_merchant/billing/gateways/ogone.rb
lib/active_merchant/billing/gateways/tns.rb

Most of these were added years ago as workarounds. They were never revisited to see if gateways had fixed their SSL setup. By removing the pinned version requirement, the highest supported version will be negotiated between the client and the server.
TLS 1.0 is old with [known vulnerabilities that require server mitigations](https://en.wikipedia.org/wiki/Transport_Layer_Security#cite_note-rfc5746-37) to be properly configured. Version 1.2 was released in 2008 and is considered secure with most cipher configurations.
The PCI DSS v3.2 disallows TLS 1.0 unless existing implementations have applied for an exception. However, this exception is [not valid after June 30, 2018](https://blog.pcisecuritystandards.org/are-you-ready-for-30-june-2018-sayin-goodbye-to-ssl-early-tls). I have verified …

Remove all TLS 1.0 version pins

---

CHANGELOG
lib/active_merchant/billing/gateways/litle.rb
test/remote/gateways/remote_litle_certification_test.rb
test/remote/gateways/remote_litle_test.rb
test/unit/gateways/litle_test.rb

Adds support for Echeck and tests for certification.
Loaded suite test/remote/gateways/remote_litle_test
...................................
35 tests, 136 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Loaded suite test/unit/gateways/litle_test
Started
...................................
35 tests, 151 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
------------------------------------------------------------------- …

Litle: Add Support for Echeck

---

CHANGELOG
lib/active_merchant/billing/gateways/litle.rb
test/remote/gateways/remote_litle_certification_test.rb
test/remote/gateways/remote_litle_test.rb

Adds the ability to store ehecks if merchant has enabled the
tokenization feature.
Loaded suite test/remote/gateways/remote_litle_test
.....................................
37 tests, 145 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Loaded suite test/unit/gateways/litle_test
...................................
35 tests, 151 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
------------------------------------------------------------------- …

Litle: Add store for echecks

---

CHANGELOG
lib/active_merchant/billing/gateways/psigate.rb
test/remote/gateways/remote_psigate_test.rb

Update the test url and the test card number for Psigate.
Loaded suite test/remote/gateways/remote_psigate_test
......
6 tests, 20 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Loaded suite test/unit/gateways/psigate_test
...........
11 tests, 28 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
------------------------------------------------------------------------------------------------------------------------- …

Psigate: Update Test URL and Card

---

lib/active_merchant/billing/gateways/stripe.rb
test/unit/gateways/stripe_test.rb

This adds support for the optional `exchange_rate` parameter during
capture and purchase. This specifies an exchange rate to be used during
a transaction, and if incorrect or stale, Stripe will return a 400
`invalid_request_error` with an `invalid_exchange_rate` code. The
response also contains the updated rate in the event of a failure in the
`new_rate` parameter.
This is currently a preview feature.
Ref: https://stripe.com/docs/api#capture_charge
Unit:
126 tests, 667 assertions, 0 failures, 0 errors, 0 pendings, 0
100% passed
Remote:
64 tests, 291 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed

Stripe: Add `exchange_rate` parameter

---

CHANGELOG
lib/active_merchant/billing/credit_card_methods.rb
lib/active_merchant/billing/gateways/mundipagg.rb
lib/active_merchant/connection.rb
test/fixtures.yml
test/remote/gateways/remote_mundipagg_test.rb
test/unit/connection_test.rb
test/unit/credit_card_methods_test.rb
test/unit/gateways/mundipagg_test.rb

Adds new gateway Mundipagg. Adds two new vouchers as credit cards
(Sodexo and VR). Allows delete requests to pass body parameters.
Loaded suite test/unit/gateways/mundipagg_test
...............
15 tests, 66 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Loaded suite test/remote/gateways/remote_mundipagg_test
Started
....................
20 tests, 50 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed …

Mundipagg: New Gateway Implementation

---

CHANGELOG
lib/active_merchant/connection.rb
test/unit/connection_test.rb

Net::Http has a slightly odd constructor semantics that aren't
immediately obvious. If no proxy parameters are sent then, by default, it
looks up the proxy from the standard HTTP_PROXY/http+proxy environment
variables. To set no proxy at all, ignoring the environment variable, you can pass nil
as the p_address parameter.
ActiveMerchant::Connection was always passing proxy parameters
to Net::Http.new even when a proxy had not been set, meaning that
the default environment variable configuration behaviour was never respected.
This commit ensures that if you do not explicitly set proxy parameters
on your Gateway the default behaviour of Net::Http to retrieve proxy
settings from the environment applies. Proxy parameters can still explicitly
set to nil to avoid environment variable …

Fix ENV based configuration of Net::Http for proxies

---

CHANGELOG
lib/active_merchant/billing/gateways/borgun.rb

Batch is part of Borgun's response but is not needed for the
request. This removes it from the `add_reference` method adding it to
the request but maintains its place in the response.
Unit tests:
8 tests, 37 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
Remote tests:
20 tests, 47 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed

Borgun: Remove batch from request parameters

---

CHANGELOG
lib/active_merchant/billing/gateways/worldpay.rb
test/remote/gateways/remote_worldpay_test.rb
test/unit/gateways/worldpay_test.rb

Inquiries need at least 5 minutes after initial transaction in order to
be reliable. This removes inquiries from verify requests.
Errors are also caused by timeouts. Successful tests can be achieved by
adding a sleep, but doesn not produce consistent results.
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
37 tests, 210 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
------------------------------------------------------------------------------------------------------------- …

Remove Inquiry requests in verify transactions

---

CHANGELOG
lib/active_merchant/billing/gateways/braintree/braintree_common.rb
lib/active_merchant/billing/gateways/braintree_blue.rb
lib/active_merchant/billing/gateways/smart_ps.rb
test/unit/gateways/braintree_orange_test.rb

Adds list of non-fractional currencies and ulitizes them when adding the
amount field to transactions.
Loaded suite test/remote/gateways/remote_braintree_blue_test
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
60 tests, 349 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Loaded suite …

Braintree: Remove decimal for non-fractional currencies

---

CHANGELOG
lib/active_merchant/billing/gateways/paymentez.rb
test/remote/gateways/remote_paymentez_test.rb

The 5 test failures are due to using credentials from Ecuador which
does not permit `authorize` and does not recoginize the `declined_card`
test number.
Remote Tests:
15 tests, 28 assertions, 5 failures, 0 errors, 0 pendings, 0 omissions,
66.6667% passed
Unit Tests:
15 tests, 44 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed

Paymentez: Add tax_percentage optional parameter

---

CHANGELOG
lib/active_merchant/billing/gateways/braintree_blue.rb
test/remote/gateways/remote_braintree_blue_test.rb

Remote tests:
61 tests, 353 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
Unit tests:
6 tests, 6 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed

Braintree: Add boolean for skip_advanced_fraud_checking

---

CHANGELOG
lib/active_merchant/billing/gateways/realex.rb
test/fixtures.yml
test/remote/gateways/remote_realex_test.rb

Adds support for apple pay and updates card numbers as they are now
publicly available.
Loaded suite test/remote/gateways/remote_realex_test
20 tests, 106 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
95% passed
Loaded suite test/unit/gateways/realex_test
21 tests, 439 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Realex: Add ApplePay Support

---

CHANGELOG
lib/active_merchant/billing/gateways/worldpay.rb
test/remote/gateways/remote_worldpay_test.rb

Adds 3DS ability to Worldpay
Errors are caused by authorize calls requiring time to be captured
24 tests, 75 assertions, 5 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
79.1667% passed
37 tests, 210 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

WorldPay: Add 3DS

---

lib/active_merchant/billing/gateways/braintree_blue.rb
test/remote/gateways/remote_braintree_blue_test.rb
test/remote/gateways/remote_braintree_orange_test.rb
test/unit/gateways/braintree_blue_test.rb

This is simply adding support to `:three_d_secure_pass_thru` params for
Braintree, documented here: https://developers.braintreepayments.com/reference/request/transaction/sale/ruby#three_d_secure_pass_thru

Adding 3D Secure pass thru capabilities to Braintree

---

CHANGELOG
lib/active_merchant/billing/gateways/paymentez.rb
test/unit/gateways/paymentez_test.rb

Extends parsing messages on failure. Messages can be returned that are not included in the error
field.
Loaded suite test/unit/gateways/paymentez_test
16 tests, 48 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Loaded suite test/remote/gateways/remote_paymentez_test
16 tests, 39 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Paymentez: Read messages on Failure with no error

---

CHANGELOG
lib/active_merchant/billing/gateways/usa_epay_transaction.rb
test/remote/gateways/remote_usa_epay_transaction_test.rb
test/unit/gateways/usa_epay_transaction_test.rb

Adds the ability to set a flag to return emailed receipts as well as the
template to use when sending the receipt.
Loaded suite test/unit/gateways/usa_epay_transaction_test
Started
.............................................
45 tests, 263 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
Loaded suite test/remote/gateways/remote_usa_epay_transaction_test
.........................
25 tests, 98 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed

Add ability to send email receipt

---

CHANGELOG
lib/active_merchant/billing/gateways/mundipagg.rb
test/remote/gateways/remote_mundipagg_test.rb
test/unit/gateways/mundipagg_test.rb

Removes the `billing_address` object if no address is sent.
Loaded suite test/unit/gateways/mundipagg_test
...............
15 tests, 65 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Loaded suite test/remote/gateways/remote_mundipagg_test
....................
20 tests, 50 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Mundipagg: Remove Billing Address if no Address Sent

---

CHANGELOG
lib/active_merchant.rb
lib/active_merchant/connection.rb
lib/active_merchant/net_http_ssl_connection.rb

On June 30 the PCI DSS mandates TLS 1.1 or better for securely transmitting payment data. This refinement to Net::HTTP allows us to get the required details within the scope of the ActiveMerchant::Connection class, without monkey patching globally.
Example output:
```
irb(main):004:0> gw.authorize(100, "test")
I, [2018-05-30T11:22:44.565084 #44620]  INFO -- : [ActiveMerchant::Billing::PayflowGateway] connection_http_method=POST connection_uri=https://payflowpro.paypal.com
I, [2018-05-30T11:22:45.165265 #44620]  INFO -- : [ActiveMerchant::Billing::PayflowGateway] connection_ssl_version=TLSv1.2 connection_ssl_cipher=ECDHE-RSA-AES128-GCM-SHA256
```

Add logging of SSL connection details

---

lib/active_merchant/connection.rb
test/unit/connection_test.rb

With b20ad8a287567, the connection logic changed such that keep-alives would suddenly be used, where previously, Connection: close would be sent. This patch reverts to the old behavior. Keep-alives can still be manually requested by passing the relevant header.
I'm not 100% sure this is the right fix, and I'd love a regression test, but this resolves some issues we were seeing over at Spreedly with integrating this version of AM.

Prevent keepalives by default

---

lib/active_merchant/net_http_ssl_connection.rb

Since Webmock [overrides the Net::HTTP#start
method](https://github.com/bblimke/webmock/blob/master/lib/webmock/http_lib_adapters/net_http.rb#L144)
to simulate HTTP requests, unsafe usage of `@socket` in ActiveMerchant's
`Net::HTTP#ssl_connection` refinement caused cryptic errors in tests
that used VCR along with ActiveMerchant:
```
MyProject::TotallyFabulousIntegrationTest#test_fabulosity:
NoMethodError: undefined method `io' for nil:NilClass
test/test_helper.rb:44:in `use_cassette'
.../gems/activemerchant-1.79.0/lib/active_merchant/net_http_ssl_connection.rb:6:in `ssl_connection'
.../gems/activemerchant-1.79.0/lib/active_merchant/connection.rb:78:in `block (2 levels) in request'
...
```

Fix WebMock regression in 1.79.2

---

CHANGELOG
lib/active_merchant/billing/gateways/forte.rb
test/unit/gateways/forte_test.rb

This strictly speaking should not be necessary, but we're seeing
enough of this happening that it seems worth doing (and is otherwise
harmless).
Unit: 18 tests, 61 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 18 tests, 45 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Forte: strip location_id and account_id for URLs

---

lib/active_merchant/billing/gateways/payflow/payflow_common_api.rb

Paypal need both address lines to be passed through for the AVS check to work properly.
This PR adds the missing address lines.
🎩 that the XMLPayRequest contain a `Street2` field inside address.

Add Street2 to payflow fields for avs

---

.travis.yml

Several additional settings were introduced to work around Travis bug 8978, but that has since been resolved.
Additionally, also remove a fully redundant `script` line.

Remove redundant lines from .travis.yml

---

CHANGELOG
lib/active_merchant/billing/gateways/visanet_peru.rb
test/fixtures.yml
test/remote/gateways/remote_visanet_peru_test.rb
test/unit/gateways/visanet_peru_test.rb

When transactions are not yet settled a refundSingleTransaction needs to
be called. This tries to use this method if a cancelDeposit fails. If
both calls are made the messages from both transactions are captured. .
Loaded suite test/unit/gateways/visanet_peru_test
.............
13 tests, 67 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Loaded suite test/remote/gateways/remote_visanet_peru_test
.................
17 tests, 56 assertions, …

Visanet Peru: Refund on unsettled transactions

---

CHANGELOG
lib/active_merchant/connection.rb
lib/active_merchant/posts_data.rb
test/unit/connection_test.rb

Ruby supports setting this from version 2.5, I backported this for 2.3 and 2.4 with the [min_max_ssl](https://github.com/bdewater/min_max_ssl) gem. Also see https://github.com/activemerchant/active_merchant/pull/2775
For more details about the deadline: https://blog.pcisecuritystandards.org/are-you-ready-for-30-june-2018-sayin-goodbye-to-ssl-early-tls

Default SSL min_version to TLS 1.1 to comply with PCI DSS deadline

---

test/unit/connection_test.rb

The test introduced in 262b65c45bf9 was not properly stubbed, and
would attempt to make connections. This fixes it.
Unit: 3866 tests, 67888 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Prevent connections being made in unit tests

---

.rubocop_todo.yml
generators/gateway/gateway_generator.rb
test/test_helper.rb
test/unit/fixtures_test.rb
test/unit/gateways/firstdata_e4_test.rb
test/unit/gateways/payeezy_test.rb

.load can deserialize arbitrary Ruby classes. Currently, we only use YAML for
fixtures and other patently safe purposes, but leaving them sets a bad
precedent, and prevents us using RuboCop's security linter for YAML properly.
Enable the linter and fix the usages.

Convert all YAML calls from .load to .safe_load

---

CHANGELOG
lib/active_merchant/billing/gateways/firstdata_e4_v27.rb
test/fixtures.yml
test/remote/gateways/remote_firstdata_e4_v27_test.rb
test/schema/firstdata_e4/v27.xsd
test/unit/gateways/firstdata_e4_v27_test.rb

This is based off of existing gateway [firstdata_e4](https://github.com/activemerchant/active_merchant/blob/master/lib/active_merchant/billing/gateways/firstdata_e4.rb). v27 diverges significantly from existing v11 in terms of additional credentials for HMAC and multiple field changes including address & cvv fields. 
---
```
$ RUBYOPT=W0 be rake test:remote TEST=test/remote/gateways/remote_firstdata_e4_v27_test.rb 
.......................
Finished in 53.177556 seconds.
----------------------------------------------------------------------------------------------------------------------
23 tests, 92 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
----------------------------------------------------------------------------------------------------------- …
```

Firstdata E4 (GGE4) v27: Add new gateway

---

CHANGELOG
lib/active_merchant/billing/gateways/stripe.rb
test/unit/gateways/stripe_test.rb

- When processing a contactless magstripe transaction if `icc_data` on the credit card is present, stripe gateway does not set `read_method` on the `post` to `contactless_magstripe_mode`
Resolves https://github.com/activemerchant/active_merchant/issues/2916
- Set `contactless_magstripe_mode` if the read method is contactless magstripe.
- Activemerchant does have a test to make sure that `contactless_magstripe_mode` flag is set when it is part of EMV data. But these tests did not assert that the check is valid.

Set contactless_magstripe_mode when transaction is contactless magstripe. Fix silently failing tests.

---

CHANGELOG
lib/active_merchant/billing/gateways/ct_payment.rb
test/fixtures.yml
test/remote/gateways/remote_ct_payment_certification_test.rb
test/remote/gateways/remote_ct_payment_test.rb
test/unit/gateways/ct_payment_test.rb

Adds a new gateway (ct_payment) along with a certicication test file
Loaded suite test/unit/gateways/ct_payment_test
14 tests, 48 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Loaded suite test/remote/gateways/remote_ct_payment_test
20 tests, 56 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

CT Payment: Add new gateway

---

.travis.yml
Gemfile
Gemfile.rails42
Gemfile.rails50
Gemfile.rails51
Gemfile.rails52
Rakefile
lib/active_merchant/billing/gateways/mercury.rb

Right now, each Gemfile has a *huge* amount of redundancy, so any change to dependencies requires altering a minimum of five files. On top of that, we run RuboCop way too much.
These patches do two things:
- Clean up the Gemfiles to remove redundancy
- Clean up Travis to only do RuboCop once, not every build
- Demonstrate the two working together by upgrading RuboCop only once, not for every Gemfile

Clean up the build process

---

.travis.yml
gemfiles/Gemfile.rails42
gemfiles/Gemfile.rails50
gemfiles/Gemfile.rails51
gemfiles/Gemfile.rails52

As @varyonic [pointed out in a comment](https://github.com/activemerchant/active_merchant/pull/2928#pullrequestreview-137126136), `eval_gemfile` is a more standard way to do [what I did](https://github.com/activemerchant/active_merchant/commit/f20dfab46920874a9317643bd2392437421106f4) to make our multiple `Gemfile`s work cleanly. But that version has an advantage, which is that it allows shoving these only-used-by-Travis `Gemfile`s into their own directory as well. So both switch to `eval_gemfile` and immediately reap its rewards.
Again, hat-tip @varyonic for the suggestion.

Shove Rails-specific Gemfiles into their own directory

---

.rubocop.yml
.rubocop_todo.yml

These are great restrictions in theory, but the running design pattern in our gateways means that basically *all* of them violate these rules. Given most of the tests do also, let's just kill these entirely.

Disable Metrics/ClassLength and ModuleLength

---

lib/active_merchant/billing/gateways/beanstream.rb
lib/active_merchant/billing/gateways/beanstream/beanstream_core.rb
test/fixtures.yml
test/remote/gateways/remote_beanstream_test.rb
test/unit/gateways/beanstream_test.rb

Beanstream is requiring that users that connect via username and
password also supply a api key. 2 echeck tests are failing unrelated to
this change.
Loaded suite test/remote/gateways/remote_beanstream_test
41 tests, 185 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
95.122% passed
Loaded suite test/unit/gateways/beanstream_test
23 tests, 108 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Beanstream: Update to use api key with login credentials

---

CHANGELOG
lib/active_merchant/billing/gateways/cyber_source.rb
test/unit/gateways/cyber_source_test.rb

Sometimes, CyberSource will 500, and return an HTML response body. But that's a problem, because we assume all responses are XML. There was a previous attempt to handle this situation in ba586a28b4d1, but it won't work if an exception (e.g. a 400 or 500) is thrown as part of the response, since the rescue block will be catching at the wrong scope. Instead, capture the response or the exception, and then parse that as a separate step, so we can be sure to catch the XML parse error regardless.
Unit: 46 tests, 222 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: didn't bother due to [the comment in `fixtures.yml`](https://github.com/activemerchant/active_merchant/blob/master/test/fixtures.yml#L235-L237)

CyberSource: do not raise on HTML responses

---

CHANGELOG
lib/active_merchant/billing/gateways/first_pay.rb
test/remote/gateways/remote_first_pay_test.rb
test/unit/gateways/first_pay_test.rb

Updates fields for recurring payment and adds a new field for recurring
type.
Loaded suite test/remote/gateways/remote_first_pay_test
Started
.............
13 tests, 29 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Loaded suite test/unit/gateways/first_pay_test
...........
11 tests, 116 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

FirstPay: Update Fields For Recurring Payments

---

CHANGELOG
lib/active_merchant/billing/gateways/barclaycard_smartpay.rb

This currently shouldn't change any behavior, but preps for handling third-party payouts and also serves as a marker that the API package should run cleanly on v30 of the API.
Unit: 25 tests, 114 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 29 tests, 61 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Barclaycard Smartpay: bump API to v30

---

lib/active_merchant/billing/gateways/payflow/payflow_express_response.rb
test/unit/gateways/payflow_express_test.rb
test/unit/gateways/payflow_express_uk_test.rb

This has a _potential_ backward compatibility issue, where people would expect `full_name` to be used. But this is causing a awkward UX for buyers. If you have Payflow Express, the buyer select a shipping address, the name on that Shipping address is different from the account owner, when selected, we would receive/use the account owner name, not the shipping address name.

Use SHIPTONAME instead of `full_name` for Payflow Express

---

CHANGELOG
lib/active_merchant/billing/gateways/blue_snap.rb
test/unit/gateways/blue_snap_test.rb

With increase in visa regulations, merchants must pass a `storeCard`
value which shows if a user has authorized their card to be stored. One
test failing in remote unrelated to these changes.
Loaded suite test/unit/gateways/blue_snap_test
19 tests, 73 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
Loaded suite test/remote/gateways/remote_blue_snap_test
25 tests, 72 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
96% passed

BlueSnap: Add StoreCard Field

---

CHANGELOG
lib/active_merchant/billing/gateways/paymentez.rb
test/remote/gateways/remote_paymentez_test.rb
test/unit/gateways/paymentez_test.rb

Note, the remote tests that fail do actually include the new noe, but just with "The partial refund is not supported by carrier", which means everything is happening correctly; they just misconfigured stuff on their side.
Unit: 19 tests, 77 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 17 tests, 44 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
88.2353% passed

Paymentez: add support for partial refunds

---

lib/active_merchant/billing/gateways/payflow/payflow_common_api.rb
lib/active_merchant/billing/gateways/payflow_express.rb
test/remote/gateways/remote_payflow_test.rb

By default Payflow will consider the first capture the final one, by passing
`CAPTURECOMPLETE=N` it lets us capture again later on.
[Docs](https://developer.paypal.com/docs/classic/payflow/integration-guide/#paypal-credit-card-transaction-request-parameters)
Remote: (Failures related to ACH and recurring billing)
32 tests, 137 assertions, 8 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
75% passed
Unit:
46 tests, 208 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Allow setting CAPTURECOMPLETE on Payflow capture transactions

---

CHANGELOG
lib/active_merchant/billing/gateways/ct_payment.rb

Adds city and state to the address information passed in
`CardHolderAddress`. Also allows for verify method to send address
information.
Loaded suite test/unit/gateways/ct_payment_test
..............
14 tests, 48 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Loaded suite test/remote/gateways/remote_ct_payment_test
....................
20 tests, 58 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

CT Payment: Update How Address is Passed

---

CHANGELOG
lib/active_merchant/billing/gateways/adyen.rb
test/remote/gateways/remote_adyen_test.rb
test/unit/gateways/adyen_test.rb

With visa updates, Adyen now requires the type of recurring processing
model for all recurring transactions. This adds the neccessary field.
..................................
34 tests, 86 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Loaded suite test/unit/gateways/adyen_test
......................
22 tests, 102 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Adyen: Add RecurringProcessingModel

---

CHANGELOG
generators/gateway/gateway_generator.rb

When I fixed YAML, I accidentally committed this script with parens in the wrong place. Fix that.

Fix typo in gateway generator

---

lib/active_merchant/billing/gateways/ct_payment.rb
test/unit/connection_test.rb
test/unit/gateways/firstdata_e4_v27_test.rb
test/unit/gateways/paymentez_test.rb

This patch contains four quick fixes, all for ambiguous code or unused variables. Specifically, the following issues are rectified:
- test/unit/connection_test.rb:51: warning: assigned but unused variable - response
- test/unit/gateways/firstdata_e4_v27_test.rb:56: warning: ambiguous first argument; put parentheses or a space even after `/' operator
- test/unit/gateways/paymentez_test.rb:121: warning: ambiguous first argument; put parentheses or a space even after `/' operator
- lib/active_merchant/billing/gateways/ct_payment.rb:210: warning: assigned but unused variable - final_response

Remove unused variables and fix ambiguous invocations

---

CHANGELOG
lib/active_merchant/billing/gateways/clearhaus.rb

Clearhaus now allows $0 auths, allowing us to tweak verify to use a
$0 transaction.
Unit: 22 tests, 110 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 23 tests, 70 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Clearhaus: use $0 for verification tests

---

.rubocop_todo.yml
CHANGELOG
lib/active_merchant/billing/gateways/braintree_blue.rb
test/remote/gateways/remote_braintree_blue_test.rb
test/unit/gateways/braintree_blue_test.rb

Adds support for processing GooglePay payment methods. It appears that
Braintree treats GooglePay in the same manner as AndroidPay. Even their
documentation (linked below) claims that GooglePay cards are represented
as AndroidPay cards. As such, the only way to get the GooglePay remote
test to pass is to pass the payment information in as `android_pay`.
Ref: https://developers.braintreepayments.com/guides/google-pay/server-side/ruby
Remote:
63 tests, 361 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
50 tests, 124 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Braintree: Add support for GooglePay

---

CHANGELOG
lib/active_merchant/billing/gateways/adyen.rb
test/unit/gateways/adyen_test.rb

Note that this can't really be tested in the sandbox (it's changing how Adyen processes the card, so the sandbox doesn't do anything with it), so remote tests are omitted.
Also note that this depends on/incorporates #2968 (since they both need to muck with `adddionalData`), so please take a look at that first/in addition to this.

Adyen: add support for customRoutingFlag

---

CHANGELOG
lib/active_merchant/billing/gateways/adyen.rb
test/remote/gateways/remote_adyen_test.rb
test/unit/gateways/adyen_test.rb

Unit:
24 tests, 113 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
36 tests, 90 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Adyen: Add support for GooglePay

---

CHANGELOG
lib/active_merchant/billing/gateways/barclaycard_smartpay.rb
test/remote/gateways/remote_barclaycard_smartpay_test.rb
test/unit/gateways/barclaycard_smartpay_test.rb

Unit:
25 tests, 115 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
30 tests, 63 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Barclaycard: Pass device_fingerprint when specified

---

CHANGELOG
lib/active_merchant/billing/gateways/braintree_blue.rb
test/unit/gateways/braintree_blue_test.rb

Reflect correct test mode in Braintree responses. 
The request was using the correct environment for test transactions (sandbox) but the response object returned did not include which mode was used. 
Set `test` option, as per template https://github.com/activemerchant/active_merchant/blob/85c57a6c2d15ae86ab3713120bf9d2277260cd26/generators/gateway/templates/gateway.rb#L92-L101
---
```
Finished in 99.933189 seconds.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
63 tests, 357 assertions, 3 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
95.2381% passed
------------------------------------------------------------------------- …
```

Reflect correct test mode in Braintree responses

---

CHANGELOG
lib/active_merchant/billing/credit_card.rb
lib/active_merchant/billing/gateways/axcessms.rb
lib/active_merchant/billing/gateways/card_save.rb
lib/active_merchant/billing/gateways/card_stream.rb
lib/active_merchant/billing/gateways/data_cash.rb
lib/active_merchant/billing/gateways/dibs.rb
lib/active_merchant/billing/gateways/iridium.rb
lib/active_merchant/billing/gateways/optimal_payment.rb
lib/active_merchant/billing/gateways/payflow/payflow_common_api.rb
lib/active_merchant/billing/gateways/payflow_uk.rb
lib/active_merchant/billing/gateways/paypal.rb
lib/active_merchant/billing/gateways/psl_card.rb
lib/active_merchant/billing/gateways/realex.rb
lib/active_merchant/billing/gateways/sage_pay.rb
lib/active_merchant/billing/gateways/so_easy_pay.rb
lib/active_merchant/billing/gateways/telr.rb
test/remote/gateways/remote_payflow_uk_test.rb
test/unit/credit_card_test.rb
test/unit/gateways/data_cash_test.rb
test/unit/gateways/payflow_test.rb
test/unit/gateways/payflow_uk_test.rb
test/unit/gateways/payment_express_test.rb
test/unit/gateways/psl_card_test.rb
test/unit/gateways/realex_test.rb

This is the continuation of #2990, and finishes removing Solo and Switch fully from the code base. It was kept separate because it's riskier (in particular, some of the remote tests were using Switch and Solo cards, and I have a hunch this breaks them--though they haven't been touched in forever and I can't imagine how they were working previously, anyway, given the cards have been sunset for *years*), but I still believe it's safe to land.

Remove the rest of Solo and Sripe support

---

lib/active_merchant/billing/credit_card_methods.rb

We honestly should be doing this anyway; now, enforce it, and take advantage of it to cut down on string conversions.
Follow-up to conversation in #2983
3926 tests, 68184 assertions, 0 failures, 0 errors, 0 pendings, 2 omissions, 0 notifications
100% passed

Assume CC numbers are strings

---

CHANGELOG
lib/active_merchant/billing/credit_card_methods.rb
test/unit/credit_card_methods_test.rb

Carnet is only used in Mexico, and the only test number I could find I found by googling for pictures of Carnet cards until I found someone with one who didn't blur out the number (although the test number here was mutated to be in the same bin range but have different subsequent digits).

Add support for Carnet

---

lib/active_merchant/billing/gateway.rb
lib/active_merchant/billing/gateways/card_save.rb
lib/active_merchant/billing/gateways/card_stream.rb
lib/active_merchant/billing/gateways/cyber_source.rb
lib/active_merchant/billing/gateways/payflow.rb
lib/active_merchant/billing/gateways/payment_express.rb
lib/active_merchant/billing/gateways/psl_card.rb
lib/active_merchant/billing/gateways/sage_pay.rb
lib/active_merchant/billing/gateways/wirecard.rb
lib/active_merchant/billing/gateways/worldpay.rb
lib/active_merchant/billing/gateways/worldpay_online_payments.rb

When examining changes required on the Spreedly side for the Switch/Solo changes, we realized a few gateways still supported Switch. This in turn led me to find a bit of extra functionality we could ditch. This PR solves both issues (as separate commits).
3923 tests, 68177 assertions, 0 failures, 0 errors, 0 pendings, 2 omissions, 0 notifications
100% passed

Remove last bits of Switch and Solo functionality

---

CHANGELOG
lib/active_merchant/billing/gateways/payeezy.rb
test/remote/gateways/remote_payeezy_test.rb
test/unit/gateways/payeezy_test.rb

The `reversal_id` field can be added to any auth or purchase
transaction. In the event of a timeout, the same `reversal_id` can then
be specified via `void` to reverse the transaction. According to
Payeezy's documentation, this API is only available in production, but
the remote tests demonstrate that the API may function on the sandbox.
Ref: https://developer.payeezy.com/payeezy-api/apis/post/transactions-1
Unit:
33 tests, 156 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
33 tests, 131 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Payeezy: Add reversal_id in support of timeout reversals

---

CHANGELOG
lib/active_merchant/billing/gateways/stripe.rb
test/remote/gateways/remote_stripe_test.rb
test/unit/gateways/stripe_test.rb

This reverts commit d4d927e42a6ac7c0ce15be7e9a14f6c2f00a0ff5. As-written, this could cause transaction to fail in some situations: Stripe will validate *all* shipping parameters if *any* are present, so attempting a purchase with some but not all shipping params could cause the entire purchase to be rejected. The proper fix is to not include any shipping details unless all are present, but for now, simply remove the functionality entirely.

Revert "Stripe: support shipping info in purchases"

---

CHANGELOG
lib/active_merchant/billing/gateways/usa_epay_transaction.rb
test/remote/gateways/remote_usa_epay_transaction_test.rb
test/unit/gateways/usa_epay_transaction_test.rb

Remote:
26 tests, 101 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
46 tests, 270 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

UsaEpayTransaction: Support UMcheckformat option for echecks

---

.rubocop_todo.yml
CHANGELOG
lib/active_merchant/billing/gateways/global_collect.rb
test/unit/gateways/global_collect_test.rb

Ingenico returns HTML when it has a 500 error, which this gateway has
not handled and would crash on a JSON parse error. New rescue provides a
more informative error and prevents crashing in this situation.
Remote:
16 tests, 38 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
19 tests, 85 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Global Collect: handle internal server errors

---

CHANGELOG
lib/active_merchant/billing/gateways/barclaycard_smartpay.rb
test/remote/gateways/remote_barclaycard_smartpay_test.rb
test/unit/gateways/barclaycard_smartpay_test.rb

This is fully opt-in and requires additional account parameters to operate correctly.
Unit: 26 tests, 127 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 31 tests, 64 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Barclaycard Smartpay: add third-party payout support

---

CHANGELOG
lib/active_merchant/billing/gateways/beanstream/beanstream_core.rb
test/remote/gateways/remote_beanstream_test.rb
test/unit/gateways/beanstream_test.rb

Remote:
42 tests, 189 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
95.2381% passed
Unit:
23 tests, 108 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Beanstream: Switch `recurringPayment` flag from boolean to integer

---

lib/active_merchant/billing/gateways/swipe_checkout.rb

Not sure if it's even up after finding https://theregister.co.nz/news/2015/12/man-behind-swipe-hq-mobile-payments-saga but at least the domain resolves.

Update Swipe HQ endpoint

---

.rubocop_todo.yml
lib/active_merchant/billing/compatibility.rb
lib/active_merchant/billing/gateways/adyen.rb
lib/active_merchant/billing/gateways/authorize_net_cim.rb
lib/active_merchant/billing/gateways/beanstream/beanstream_core.rb
lib/active_merchant/billing/gateways/blue_pay.rb
lib/active_merchant/billing/gateways/braintree_blue.rb
lib/active_merchant/billing/gateways/bridge_pay.rb
lib/active_merchant/billing/gateways/ct_payment.rb
lib/active_merchant/billing/gateways/cyber_source.rb
lib/active_merchant/billing/gateways/elavon.rb
lib/active_merchant/billing/gateways/first_pay.rb
lib/active_merchant/billing/gateways/hps.rb
lib/active_merchant/billing/gateways/jetpay.rb
lib/active_merchant/billing/gateways/jetpay_v2.rb
lib/active_merchant/billing/gateways/linkpoint.rb
lib/active_merchant/billing/gateways/litle.rb
lib/active_merchant/billing/gateways/optimal_payment.rb
lib/active_merchant/billing/gateways/orbital.rb
lib/active_merchant/billing/gateways/pay_junction_v2.rb
lib/active_merchant/billing/gateways/payeezy.rb
lib/active_merchant/billing/gateways/payex.rb
lib/active_merchant/billing/gateways/quickbooks.rb
lib/active_merchant/billing/gateways/securion_pay.rb
lib/active_merchant/billing/gateways/stripe.rb
lib/active_merchant/billing/gateways/telr.rb
lib/active_merchant/connection.rb
lib/active_merchant/network_connection_retries.rb
lib/active_merchant/posts_data.rb
test/comm_stub.rb

This actually has some *solid* readability improvements, especially around the pattern
```ruby
foobar.each do |a, b|
...
...
...
end if foobar
```
which is _far_ easier to miss than
```ruby
foobar&.each do |a, b|
...
...
...
end
```

RuboCop: fix Style/SafeNavigation

---

CHANGELOG
lib/active_merchant/billing/gateways/payflow/payflow_express_response.rb
test/unit/gateways/payflow_express_test.rb

Get phone number from Payflow Express response payload
This provides feature parity with Paypal Express.
In Paypal Express, we fetch this information from elsewhere, since payload is different, but we simply don't set this info when the integration is with Payflow.
https://github.com/activemerchant/active_merchant/blob/master/lib/active_merchant/billing/gateways/paypal/paypal_express_response.rb#L49

[Payflow Express] Use phone returned from payload on Response

---

lib/active_merchant/billing/gateways/mercado_pago.rb
test/unit/gateways/mercado_pago_test.rb

Mercado Pago now infers the card brand from BIN, so it no longer needs to be passed in for normal operations. Instead, they've asked for us to expose `payment_method_id` and `issuer_id` directly. So, that's exactly what I've done.
There are two commits in this series. The first one does nothing other than change the tests specifically so they'd _break_ on the second commit without further changes. It might make it easier to see what I'm doing.

MercadoPago: change how card brand is passed

---

lib/active_merchant/billing/gateways/netbanx.rb

This field is needed for certain transaction that could get declined
because of the gateway "Risk Management department"
I manually tested that the field get send, but didn't do a test transaction (I had no test credential).
This gateway tests were passing before with a state defined [code is here](https://github.com/activemerchant/active_merchant/blob/master/test/test_helper.rb#L231)
and are still passing after with it defined.
Please tell me if more tests are needed
Cheers!

Add state to the netbanx payload

---

CHANGELOG
lib/active_merchant/billing/gateways/barclaycard_smartpay.rb
test/remote/gateways/remote_barclaycard_smartpay_test.rb
test/unit/gateways/barclaycard_smartpay_test.rb

The error handling was not exposing detailed error codes and messages in
the response. This returns those codes and messages where appropriate.
This also adds and updates several tests.
Unit tests:
27 tests, 133 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
Remote tests:
33 tests, 69 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions,
This failure is for "Invalid credentials" for
`test_successful_third_party_payout` and is
unrelated.

Barclaycard Smartpay: Improves Error Handling

---

CHANGELOG
lib/active_merchant/billing/gateways/realex.rb
test/remote/gateways/remote_realex_test.rb
test/unit/gateways/realex_test.rb

Add verify method by making an Open to Buy (OTB) request:
https://developer.realexpayments.com/#!/api/process-payment/otb
Remote (1 unrelated failure from `test_realex_purchase_then_refund`):
23 tests, 122 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
95.6522% passed
Unit:
22 tests, 526 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Realex: Add verify

---

lib/active_merchant/billing/gateways/visanet_peru.rb

This reverts a RuboCop correction by adding parentheses back the `method` method.

Visanet Peru: Corrects Method method

---

CHANGELOG
lib/active_merchant/billing/gateways/paymentez.rb
test/remote/gateways/remote_paymentez_test.rb

Adds user.phone field for Paymentez and updates remote test.
Unit tests:
100% passed
Remote tests:
17 tests, 33 assertions, 6 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
64.7059% passed
These failures due to `The method authorize is not supported by carrier`.
Country credentials used for testing do not support `authorize`. Unrelated.

Paymentez: Adds support for user.phone field

---

CHANGELOG
lib/active_merchant/billing/gateways/paymentez.rb
test/remote/gateways/remote_paymentez_test.rb

Unit tests:
100% passed
Remote tests:
18 tests, 34 assertions, 7 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
61.1111% passed
These failures due to The method authorize is not supported by carrier.
Country credentials used for testing do not support authorize. Unrelated.

Paymentez: Does not send nil for empty parameter phone

---

lib/active_merchant/billing/gateways/mercado_pago.rb
test/unit/gateways/mercado_pago_test.rb

This is a re-application of d9c5a1a0.
Allow the card type to be passed in explicitly instead via the
:payment_method_id option. Additionally, allow sending the :issuer_id.
Unit: 19 tests, 93 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
We've now done explicit reviews with Mercado Pago, and the code as-is works properly.
Remote: 17 tests, 46 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Mercado Pago: do not infer card type

---

CHANGELOG
lib/active_merchant/billing/gateways/paymentez.rb
test/remote/gateways/remote_paymentez_test.rb

Unit tests:
100% passed
Remote tests:
18 tests, 34 assertions, 7 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
61.1111% passed
These failures due to `The method authorize is not supported by carrier`.
Country credentials used for testing do not support authorize. Unrelated.

Paymentez: Does not send phone parameter unless it is defined

---

CHANGELOG
lib/active_merchant/billing/gateways/credorax.rb
test/unit/gateways/credorax_test.rb

Unit: 20 tests, 92 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Credorax: add submerchant_id support

---

CHANGELOG
lib/active_merchant/billing/gateways/moneris.rb
test/remote/gateways/remote_moneris_test.rb
test/unit/gateways/moneris_test.rb

This allows Credential On File information to be passed in the options
hash. `cof_enabled` must be set to `true`. Values for the three
CoF fields: `issuer_id`, `payment_indicator`, and `payment_information`
must also be included.
Unit Tests:
37 tests, 188 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
Remote Tests:
29 tests, 114 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed

Moneris: Adds Credential On File Logic

---

CHANGELOG
lib/active_merchant/billing/gateways/paymentez.rb
test/remote/gateways/remote_paymentez_test.rb

Unit:
100% passed
Remote:
19 tests, 35 assertions, 6 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
68.4211% passed
These failures due to `The method authorize is not supported by carrier`.
Country credentials used for testing do not support authorize. Unrelated.

Paymentez: Supports phone field, does not send if empty

---

lib/active_merchant/billing/gateways/moneris.rb
test/remote/gateways/remote_moneris_test.rb

Adds a bypass for transactions without credential-on-file details when @cof_enabled is
true.
Unit Tests:
37 tests, 188 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
Remote Tests:
31 tests, 119 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions,
93.5484% passed
(The two failing tests are not related and appear to be timing-based.)

Moneris: Allows cof_enabled gateway to process non-cof transactions

---

CHANGELOG
lib/active_merchant/billing/gateways/forte.rb
test/remote/gateways/remote_forte_test.rb

Forte uses different transaction id's for captures. When trying to void
a capture this results in a error. This saves the original auth
transaction id and authorization id in the capture authorization so the original auth will be voided
or refunded.
Loaded suite test/unit/gateways/forte_test
20 tests, 67 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Loaded suite test/remote/gateways/remote_forte_test
21 tests, 59 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 …

Forte: Allow void on capture

---

lib/active_merchant/billing/gateways/braintree_blue.rb
test/remote/gateways/remote_braintree_blue_test.rb
test/unit/gateways/braintree_blue_test.rb

Previously, on Battlestar Galactica, we only filtered out the address if the fields were `nil`. But some of our library consumers like to pass in empty strings, which we treated as actual data, whereas Braintree Blue weirdly insists `""` is not a valid address. We now instead treat empty strings the same as `nil` values.
Unit: 57 tests, 150 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 66 tests, 378 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Braintree Blue: actually, really, truly fix nil address fields

---

.travis.yml
activemerchant.gemspec
gemfiles/Gemfile.rails_master

- During every ActiveSupport major bump, this gemspec needs to be updated,
I think we are being too conservative and having an upperbound limit
doesn't help.
If we wanted to be really conservative we would have to add a
upperbound constraint on the minor version as well (`< 5.x`) since
Rails doesn't follow semver and minor version can introduce breaking
changes.
What I think is better is to remove the upperbound constraint,
and test AM directly on ActiveSupport edge.
Looking at the commit rates on this project, CI would run
largely enough to cover us. But we can also add another safety net
and run travis on a schedule.
For 👀@bdewater @filipebarcos

Remove the upperbound constraint on ActiveSupport:

---

CHANGELOG
lib/active_merchant/billing/gateways/worldpay.rb
test/remote/gateways/remote_worldpay_test.rb
test/unit/gateways/worldpay_test.rb

MasterCard and Visa credits do not work the same way, so we were erroneously counting MasterCard credits as failed. Count them as successful.
Unit: 40 tests, 227 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 28 tests, 111 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Worldpay: support MasterCard credits

---

CHANGELOG
lib/active_merchant/billing/gateways/worldpay.rb
test/unit/gateways/worldpay_test.rb

Unit: 41 tests, 231 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Worldpay: set name to 3D when 3DS attempted

---

CHANGELOG
lib/active_merchant/billing/gateways/authorize_net.rb
test/unit/gateways/authorize_net_test.rb

Refunds for bank accounts require a different structure than credit
cards. The routing number, account number and account type must also be
passed in the request.
Loaded suite test/unit/gateways/authorize_net_test
................................................................................................
96 tests, 565 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Loaded suite test/remote/gateways/remote_authorize_net_test
.....................................................................
69 tests, 238 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Authorize.Net: Support refunds for bank accounts

---

CHANGELOG
lib/active_merchant/billing/gateways/trust_commerce.rb
test/fixtures.yml
test/remote/gateways/remote_trust_commerce_test.rb
test/unit/gateways/trust_commerce_test.rb

TrustCommerce supports ach transactions for purchase and credit. This
also adds the `aggregator_id` which will become mandatory.
Loaded suite test/remote/gateways/remote_trust_commerce_test
.......
15 tests, 59 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Loaded suite test/unit/gateways/trust_commerce_test
.........
9 tests, 22 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

TrustCommerce: Add ACH Ability

---

CHANGELOG
lib/active_merchant/billing/gateways/payeezy.rb

Payeezy allows $0 authorization. Updating from $1 verify
to $0 to resolve failures for customer.
ENE-59
Unit Tests:
33 tests, 156 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote Tests:
33 tests, 131 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Payeezy: Support $0 for verify transactions

---

CHANGELOG
lib/active_merchant/billing/gateways/adyen.rb
test/remote/gateways/remote_adyen_test.rb
test/unit/gateways/adyen_test.rb

Allows for 3DS implementation on Adyen gateway.
.....................................
37 tests, 97 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Loaded suite test/unit/gateways/adyen_test
.........................
25 tests, 124 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Adyen: Implement 3DS

---

CHANGELOG
lib/active_merchant/billing/gateways/payeezy.rb
test/remote/gateways/remote_payeezy_test.rb
test/unit/gateways/payeezy_test.rb

Adds params for `stored_credentials` to support compliance with Visa/MC.
Loaded suite test/remote/gateways/remote_payeezy_test
..................................
34 tests, 134 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Loaded suite test/unit/gateways/payeezy_test
..................................
34 tests, 162 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Payeezy: Add `stored_credentials`

---

lib/active_merchant/billing/credit_card.rb
test/unit/credit_card_test.rb

This change is allowing users to pass `cvv: blank` and pass validation
even when `CreditCard.require_verification_value = true` for maestro,
since cvv length is 0.
I believe this was some backward compatibility issue when we changed maestro card validations to include the new/correct numbers.

Does not fail validation for blank cvv on maestro cards

---

lib/active_merchant/billing/gateways/trust_commerce.rb
test/unit/gateways/trust_commerce_test.rb

Allows for `application_id` to be used as `aggregatorID`. 3 failing
remotes test unrelated to this change.
- test_store_failure
- test_unstore_failure
- test_recurring_failure
Loaded suite test/unit/gateways/trust_commerce_test
Started
..........
10 tests, 34 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Loaded suite test/remote/gateways/remote_trust_commerce_test
Finished in 32.663168 seconds.
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
16 tests, 59 assertions, 3 failures, 0 …

TrustCommerce: Use `application_id`

---

CHANGELOG
lib/active_merchant/billing/gateways/stripe.rb
test/remote/gateways/remote_stripe_3ds_test.rb
test/unit/gateways/stripe_test.rb

Adds 3DS to the Stripe gateway. Remote tests for 3DS are in their own
file.
Loaded suite test/unit/gateways/stripe_test
.....................................................................................................................................
133 tests, 713 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Loaded suite test/remote/gateways/remote_stripe_3ds_test
.....
5 tests, 21 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Loaded suite test/remote/gateways/remote_stripe_test
...................................................................
100% passed

Stripe: Add 3DS

---

lib/active_merchant/billing/gateways/worldpay.rb
test/remote/gateways/remote_worldpay_test.rb

Pull out the appropriate values from the response.
.............................
29 tests, 116 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
.........................................
41 tests, 231 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

WorldPay: Pull CVC and AVS Result from Response

---

CHANGELOG
lib/active_merchant/billing/gateways/worldpay.rb

Somehow in the process of squashing, the map needed to add avs and cvc
mapping was lost.
29 tests, 116 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
41 tests, 231 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Worldpay: Add AVS and CVC Mapping

---

CHANGELOG
lib/active_merchant/billing/gateways/paymentez.rb

Simpler method to add JSON object to request in extra_params, and fixes buggy behavior.
ENE-80
Unit Tests:
100% passed
Remote Tests:
20 tests, 47 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
Failures unrelated to this change, have to do with country-specific allowances for
partial capture/ refund.

Paymentez: Fixes extra_params field

---

lib/active_merchant/billing/gateways/usa_epay_transaction.rb
test/unit/gateways/usa_epay_transaction_test.rb

This is potentially a breaking change. The :invoice: option now points to the invoice field in the gateway. This field has limitations, but is required. The :order_id: option now points to the orderid field in the gateway, which is much larger and used for additional reference and is optional. This is the correct way to integrate with the gateway.

Fix usaepay transaction invoice

---

CHANGELOG
lib/active_merchant/billing/gateways/adyen.rb
test/remote/gateways/remote_adyen_test.rb
test/unit/gateways/adyen_test.rb

Sends N/A if state field is not populated. Resolves validation errors from sending blank state field.
ECS-102
Remote:
39 tests, 100 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
26 tests, 127 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Adyen: Handles blank state address field

---

CHANGELOG
lib/active_merchant/billing/gateways/openpay.rb
test/unit/gateways/openpay_test.rb

Some Openpay transaction response objects are including an error_code
field that was previously only present in error responses. Now we will
check for the existence of the error_code field and a non-nil/blank
error code.
ECS-97
Remote:
24 tests, 80 assertions, 4 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
83.3333% passed
Unit:
20 tests, 103 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
@activemerchant/spreedly-connect 4 Remote tests are failing for unrelated reasons.
* `test_successful_purchase_with_card_stored` fails due to invalid source_id
*  Failures due to a different response message (I believe this was triggered by multiple test runs): 
* `test_unsuccessful_authorize`
* `test_unsuccessful_purchase`
* …

Openpay: Fix successful transaction(s) marked as failed

---

CHANGELOG
lib/active_merchant/billing/gateways/braintree_blue.rb
test/remote/gateways/remote_braintree_blue_test.rb
test/unit/gateways/braintree_blue_test.rb

Braintree has deprecated the recurring field in lieu of the transaction_source parameter which allows a 'recurring' value. For now, Braintree still allows both fields to be sent.
ECS-97
Remote:
69 tests, 389 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
58 tests, 151 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Braintree: Adds support for transaction_source

---

CHANGELOG
lib/active_merchant/billing/gateways/blue_snap.rb
test/remote/gateways/remote_blue_snap_test.rb

Adds fields to enable Level 2/ Level 3 data, with existing
Nokogiri-Builder request structure for this gateway.
ENE-61
Unit:
19 tests, 73 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
26 tests, 76 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
92.3077% passed
- Unrelated failures, caused by updated error messages and store functionality.

Blue Snap: Supports Level 2/3 data

---

CHANGELOG
lib/active_merchant/billing/gateways/blue_snap.rb
test/remote/gateways/remote_blue_snap_test.rb
test/unit/gateways/blue_snap_test.rb

Add support for GSF personal_identification_number, which is required
for transactions in Brazil.
Expand supported countries to include LATAM countries supported by Blue
Snap.
ECS-110
Unit:
19 tests, 73 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
25 tests, 74 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

BlueSnap: Support personal_identification_number

---

lib/active_merchant/billing/gateways/cecabank.rb
test/unit/gateways/cecabank_test.rb

Pursuant to [ECS-96](https://spreedly.atlassian.net/browse/ECS-96) and in lieu of https://github.com/spreedly/core/pull/3527.

Append error messages to Cecabank response

---

lib/active_merchant/billing/gateways/adyen.rb
test/unit/gateways/adyen_test.rb

Adding more mappings to AVSResult makes me a little ⁉️but it didn't look like there were good explicit corresponding options for the codes Adyen is returning.

Map AVS codes for Adyen

---

CHANGELOG
lib/active_merchant/billing/gateways/trust_commerce.rb
test/unit/gateways/trust_commerce_test.rb

Support sending full name for ACH transactions in require name field.
ECS-137
Unit:
10 tests, 35 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
16 tests, 59 assertions, 3 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
81.25% passed
Unrelated remote test failures.

TrustCommerce: Send full name on ACH transactions

---

CHANGELOG
lib/active_merchant/billing/gateways/worldpay.rb
test/remote/gateways/remote_worldpay_test.rb

Previously the new/beta normalized stored credential hash was using a
boolean value to indicate if a transaction was part of a recurring
transaction or not. However, this did not allow for the case of gateways
(like Worldpay) to take into account transactions that are part of an
installment. This adjusts the previously "recurring" field to use the
name "transaction_type" which accepts a string of either:
- "installment"
- "recurring"
- "unscheduled"
This should allow more flexibility to for other gateways that also have
the notion of a payment that is part of an installment.
Note that this normalized hash is still in "beta" use. The hash
structure itself may change and until there is solid use around it
across multiple gateways, it will likely be a defined-yet-not-enforced
hash rather …

Worldpay: Adjust use of normalized stored credentials hash

---

CHANGELOG
lib/active_merchant/billing/gateways/adyen.rb
test/remote/gateways/remote_adyen_test.rb

Allows for initiating Dynamic 3DS by passing browserInfo without
executeThreeD. Merchant account must be set up for Dynamic 3DS.
ECS-131
Unit:
27 tests, 130 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
41 tests, 111 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Adyen: Enable Dynamic 3DS

---

lib/active_merchant/billing/gateways/netbanx.rb

Changes made to the add_order_id method to send a uuid in place of order number. This is expected to fix the multiple partial refunds problem for Merrco payments.

Merrco partial refunds fix

---

CHANGELOG
lib/active_merchant/billing/gateways/blue_snap.rb
test/remote/gateways/remote_blue_snap_test.rb
test/remote/gateways/remote_fat_zebra_test.rb
test/unit/gateways/blue_snap_test.rb

Add support for ACH/ECP/echeck payments. We only support vaulting and using 1 ACH account per customer (<= v2.0). Support for multiple ACH accounts (v3.0) was not included at this time.
ECS-60
Unit:
33 tests, 103 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
25 tests, 97 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

BlueSnap: Support ACH/ECP payments

---

CHANGELOG
lib/active_merchant/billing/gateways/payment_express.rb
test/remote/gateways/remote_payment_express_test.rb
test/unit/gateways/payment_express_test.rb

Adds support for the ClientInfo field used to send the IP address.
ECS-124
Unit:
34 tests, 249 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
15 tests, 70 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

PaymentExpress: Support client_info field

---

CHANGELOG
lib/active_merchant/billing/gateways/blue_pay.rb
test/remote/gateways/remote_blue_pay_test.rb
test/unit/gateways/blue_pay_test.rb

@activemerchant/spreedly-connect I did not add the IP address to recurring billing requests because they are marked as `deprecated`. I can add them if the team feels it's worthwhile.
Add the IP address to all Blue Pay requests when available.
ECS-165
Unit:
26 tests, 125 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
15 tests, 73 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

BluePay: Add IP address to all requests

---

CHANGELOG
lib/active_merchant/billing/gateways/payment_express.rb
test/remote/gateways/remote_payment_express_test.rb
test/unit/gateways/payment_express_test.rb

Use the built in ip field instead of a gateway specific field for
sending the ip address with requests.
ECS-124
Unit:
34 tests, 249 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
15 tests, 70 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

PaymentExpress: Use ip field for client_info

---

CHANGELOG
lib/active_merchant/billing/gateways/adyen.rb
test/remote/gateways/remote_adyen_test.rb
test/unit/gateways/adyen_test.rb

Support of Idempotency-Key for all actions except purchase, due to
multi-key requirement (design still pending).
ECS-166
Unit:
29 tests, 139 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
43 tests, 120 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Adyen: Idempotency for non-purchase requests

---

CHANGELOG
lib/active_merchant/billing/gateways/mercado_pago.rb
test/remote/gateways/remote_mercado_pago_test.rb
test/unit/gateways/mercado_pago_test.rb

Unit Tests:
22 tests, 111 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
Remote Tests:
22 tests, 61 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions,
(Two failures, for partial capture and processing mode, are unrelated.)

Mercado Pago: Adds Elo card type

---

CHANGELOG
lib/active_merchant/billing/gateways/litle.rb
test/remote/gateways/remote_litle_test.rb
test/unit/gateways/litle_test.rb

Trying the draft pull request feature. I have a little bit more I want to do before making this a real pull request (expand/refine the remote new remote tests for stored credentials in Litle), but I *think* I'm close. Thought I'd push up what I have for some early feedback.

Ecs 138 vantiv litle stored credential

---

CHANGELOG
lib/active_merchant/billing/gateways/paymentez.rb
test/remote/gateways/remote_paymentez_test.rb
test/unit/gateways/paymentez_test.rb

Adds Elo card type.
Unit Tests:
23 tests, 95 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
Remote Tests:
26 tests, 60 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions,
92.3077% passed
(Both of these failures are unrelated to the changes included. They have
to do with `capture` and succeed when run individually.)

Paymentez: Adds Elo

---

CHANGELOG
lib/active_merchant/billing/gateways/worldpay.rb
test/remote/gateways/remote_worldpay_test.rb
test/unit/gateways/worldpay_test.rb

This adds `elo` to `supported_cardtypes`.
Unit Tests:
44 tests, 242 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
Remote Tests:
33 tests, 138 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed

WorldPay: Adds Elo

---

CHANGELOG
lib/active_merchant/billing/gateways/worldpay.rb
test/remote/gateways/remote_worldpay_test.rb

WorldPay's XML DTD requires that the `session` comes after
`storedCredentials`. When using stored credential options with a 3DS
request we were ending up with the elements being generated in the wrong
order. This fixes the issue and ensures `storedCredentials` precede
`session` when both are to be included in the request document.
ECS-219
Unit:
44 tests, 242 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote
35 tests, 154 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

WorldPay: Fix element order for 3DS + stored cred

---

CHANGELOG
lib/active_merchant/billing/gateways/braintree_blue.rb
test/remote/gateways/remote_braintree_blue_test.rb
test/unit/gateways/braintree_blue_test.rb

Explicitly add the risk data fields to the active merchant response, if
they are provided.
ECS-210
Unit:
59 tests, 158 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
71 tests, 407 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Braintree: Add risk data fields to response

---

CHANGELOG
lib/active_merchant/billing/gateways/adyen.rb
test/remote/gateways/remote_adyen_test.rb
test/unit/gateways/adyen_test.rb

Adding capability to send Idempotency-Key on the MultiResponse purchase
action. Modifies a single key so it can be re-used for the capture
request. User can safely re-try `purchase` with the original key since
both requests are idempotent and the key is modified in a fixed way.
Unit:
30 tests, 144 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
50 tests, 146 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
ECS-198

Adyen: Support idempotency on purchase

---

lib/active_merchant/billing/gateways/worldpay.rb
test/remote/gateways/remote_worldpay_test.rb
test/unit/gateways/worldpay_test.rb

Add parameters that we receive after doing 3DS with an external MPI in order to pass them to Worldpay.
Related documentation: https://beta.developer.worldpay.com/docs/wpg/reference/3ds2withexternalmpi

Add 3DS parameters to Worldpay

---

lib/active_merchant/billing/gateways/quickpay/quickpay_v10.rb
test/remote/gateways/remote_quickpay_v10_test.rb
test/unit/gateways/quickpay_v10_test.rb

Add support for 3DSecure for QuickPay v10. 
From the documentation : https://learn.quickpay.net/tech-talk/api/services/#POST-payments--id-authorize---format-

QuickPay v10: Add 3DS params

---

lib/active_merchant/billing/gateways/paypal_express.rb
test/unit/gateways/paypal_express_test.rb

PayPal has logic in their javascript to determine if a visitor should see the sign-in page or the guest checkout page.
This kicks in only when the `landing_page` parameter is not sent and the logic is based off cookies.

Allow to pass empty `landing_page` parameter

---

CHANGELOG
lib/active_merchant/billing/gateways/d_local.rb
lib/active_merchant/billing/gateways/mundipagg.rb
test/unit/gateways/d_local_test.rb
test/unit/gateways/mundipagg_test.rb

NilClass errors noted in attempted transactions for DLocal and Mundipagg gateways,
due to absent objects. Made small fixes that will avoid this error.
Mundipagg Unit tests:
17 tests, 76 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
DLocal Unit tests:
16 tests, 48 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Fix partial or missing address exceptions

---

CHANGELOG
lib/active_merchant/billing/gateways/adyen.rb
test/remote/gateways/remote_adyen_test.rb
test/unit/gateways/adyen_test.rb

Adapter already supports defining shopperInteraction and
recurringProcessingModel directly. Adding ability to define these fields
using the normalized hash (which can be overidden by passing the fields
directly). Maintains using verification value or Network Tokenization
cards to define shopperInteraction.
ECS-213
Unit:
32 tests, 152 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
52 tests, 149 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Adyen: Update to support normalized stored credential fields

---

lib/active_merchant/billing/gateways/realex.rb
test/remote/gateways/remote_realex_test.rb
test/unit/gateways/realex_test.rb

Add support for ECI, XID and CAVV on the XML request for 3D Secure. Following: https://developer.globalpay.com/#!/api/3d-secure-two#3ds2-authorization
```xml
<mpi>
<cavv>AAACBllleHchZTBWIGV4AAAAAAA=</cavv>
<xid>crqAeMwkEL9r4POdxpByWJ1/wYg=</xid>
<eci>5</eci>
</mpi>
```
New remote test passes:
```
Loaded suite test/remote/gateways/remote_realex_test
Started
.
Finished in 0.991542 seconds.
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
1 tests, 3 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
-------------------------------------------------------------------------------------------------------------------------------------------- …
```

Realex: Add 3DS

---

CHANGELOG
lib/active_merchant/billing/gateways/visanet_peru.rb
test/remote/gateways/remote_visanet_peru_test.rb
test/unit/gateways/visanet_peru_test.rb

@nfarve could you check my thinking on this draft pull request? I'm working on a ticket (ECS-173) where I need to modify this adapter to add extra information to messages, but the existing message extraction logic is a bit tricky and I can't quite tell if it was doing what we expected or not.
-----
**VisaNet Peru: Ensure msg kept on bad cancelDeposit**
Looking at:
https://github.com/activemerchant/active_merchant/pull/2772#discussion_r174914253
It seems our intent is to stash the errorMessage in options so it can be added
to a follow up request if the follow up request fails (this would only happen
when the user has opted to force a full refund for an unsettled refund, if I'm
understanding the logic correctly).
However, when I went to add a test ensuring my understanding is correct it …

VisaNet Peru: Always include DSC_COD_ACCION

---

CHANGELOG
lib/active_merchant/billing/gateways/cyber_source.rb
test/remote/gateways/remote_cyber_source_test.rb
test/schema/cyber_source/CyberSourceTransaction_1.153.xsd
test/unit/gateways/cyber_source_test.rb

There are still a few failing remote tests; these seem to fail in the current version as well.

Support stored credentials in Cybersource

---

CHANGELOG
lib/active_merchant/billing/gateways/stripe.rb
test/unit/gateways/stripe_test.rb

Fixes https://github.com/activemerchant/active_merchant/issues/3116
When specifying the `refund_fee_amount` on a Refund using the Stripe
gateway, Active Merchant makes three different API requests:
1. Issue the actual refund against the charge
2. Fetch the charge to get the application fee identifier
3. Issue the application fee refund against the original application fee
Currently, if either 2 or 3 fail while 1 succeeds, the `#refund`
method's response is a failure, which is not true. This process is not
transactional. The refund had succeeded and is not rolled back, which
isn't possible to do anyway.
This addresses this problem by always responding with the status
of the refund, regardless of what happened with the fee refund.
There is no way to make this process transactional. You may …

Do not consider a refund unsuccessful if only refunding the fee failed

---

CHANGELOG
lib/active_merchant/billing/gateways/stripe.rb
test/remote/gateways/remote_stripe_3ds_test.rb

Don't send the Stripe connect account id when creating webhooks. Instead
indicate the webhook should receive events from the connected
account, if the stripe account is present.
ECS-242
Unit:
134 tests, 719 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
100% passed
Remote 3DS Tests:
7 tests, 26 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote Connect Tests:
4 tests, 14 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Stripe: Fix webhook creation for connected account

---

lib/active_merchant/billing/gateways/adyen.rb
test/remote/gateways/remote_adyen_test.rb

The primary driver behind this is to ensure that we can use this
adapater for 3DS 2.0 transactions given the appropriate fields are in
place. However, considering this is quite a major jump in version
support it deserves it's own commit.
Note that the two remote tests that have been changed are because the
Adyen API no longer seems to return errors for a blank state or country
in the billing address. However I should note that looking at the Adyen
API reference for billingAddress, it appears as though country is
required. Though that may be a typo in their documentation.
https://docs.adyen.com/api-explorer/#/Payment/v40/authorise
Remote Test Run:
➜ ruby -Itest test/remote/gateways/remote_adyen_test.rb
Started …

Adyen: Upgrade to v40 API

---

CHANGELOG
lib/active_merchant/billing/credit_card_methods.rb
test/remote/gateways/remote_mundipagg_test.rb
test/unit/credit_card_methods_test.rb

When first implemented, we were under the impression that these card
types only supported 14 digits. After some production usage and confirmation
from the card issuers, it turns out they only support 16 digits. This
modifies the brand detection mechanism ensure 16 digit numbers are
supported.
Unit:
4044 tests, 69009 assertions, 0 failures, 0 errors, 0 pendings, 2 omissions, 0 notifications
100% passed
Mundipagg Remote:
23 tests, 58 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Fix number lengths for both VR and Sodexo

---

CHANGELOG
lib/active_merchant/billing/gateways/stripe.rb
test/remote/gateways/remote_stripe_3ds_test.rb

Add support for listing and showing webhook endpoints.
ECS-289
Unit:
134 tests, 718 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
100% passed
Remote Stripe 3DS:
10 tests, 50 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Stripe: Support show and list webhook endpoints

---

CHANGELOG
lib/active_merchant/billing/gateways/card_connect.rb
test/unit/gateways/card_connect_test.rb

Add `frontendid` parameter to request bodies using the gateway's
application_id as the value. This enables CardConnect to internally
account for their costs by attributing transactions to the originating
application / platform associated with the frontendid.
ECS-287
Closes #3198 
Unit:
22 tests, 92 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
23 tests, 55 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

CardConnect: Add frontendid parameter to requests

---

CHANGELOG
lib/active_merchant/billing/gateways/adyen.rb
test/remote/gateways/remote_adyen_test.rb
test/unit/gateways/adyen_test.rb

With the upgrade of Adyen to version 40, the billing address was removed
from the card object. This corrects the format and returns the two tests
that fail when you pass an incorrect country or state. In order to see
AVS results you may need to make some configuration changes to your
account.
https://docs.adyen.com/developers/api-reference/payments-api#paymentresultadditionaldata
........................................................
56 tests, 166 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Loaded suite test/unit/gateways/adyen_test
Started
..................................
34 tests, 161 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Adyen: Correct formatting of Billing Address

---

CHANGELOG
lib/active_merchant/billing/gateways/stripe.rb
test/remote/gateways/remote_stripe_3ds_test.rb

@activemerchant/spreedly-connect This code change is to support charging a 3DS source in the `redirect` step of the Stripe 3DS 1.0 workflow. The existing approach attempts to charge a source even if the source is not `chargeable`, which would ultimately fail a transaction if the source is not yet chargeable, i.e. `pending`. Instead, we will use `show_source` to check if the source can be charged, and only attempt the charge if it is chargeable.
Add support for showing a payment source such as a card or 3DS payment
source.
Unit:
134 tests, 718 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
100% passed
Remote Stripe 3DS:
11 tests, 57 assertions, 0 …

Stripe: Show payment source

---

CHANGELOG
lib/active_merchant/billing/gateways/adyen.rb
test/remote/gateways/remote_adyen_test.rb
test/unit/gateways/adyen_test.rb

In an effort to begin supporting the intiation of 3DS 2.0 transactions,
this introduces another normalized hash for web browser data that can be
mapped to the fields a gateway is expecting. Similarly to stored
credentials, this hash should be used across all gateways in which 3DS
2.0 browser data is meant to be submitted so there is a single interface
for the client/device data.
Eventually I suspect this hash should also support mobile app information
by changing out the "channel" field and doing additional logic around that,
but for now we're starting with web browsers only.
The structure of the hash is as follows:
```ruby
three_ds_2: {
channel: "browser",
browser_info: {
accept_header: "unknown",
depth: 100,
java: false,
language: "US",
height: 1000,
width: 500,
timezone: "-120", …
```

Adyen: Add normalized hash of 3DS 2.0 data fields from web browsers

---

CHANGELOG
lib/active_merchant/billing/gateways/stripe.rb
test/unit/gateways/stripe_test.rb

This was a regression made in adc5a88c485e8de8cf30c064233fbe7bc927bf86
which was trying to make the App Fee refunds not impact the overall
status of the Refund response. That was achieved, but it also made the
unintentional change of always trying to refund the application fee
regardless of the refund succeeding or not. There was previously no test
coverage of this behaviour.

Do not attempt application fee refund if refund was not successful

---

CHANGELOG
lib/active_merchant/billing/gateways/elavon.rb
test/fixtures.yml
test/remote/gateways/remote_elavon_test.rb

Elavon returns an error for any API request that includes a currency
UNLESS the merchant's terminal is setup for multi-currency. Previously
we NEVER sent the currency, so only the default currency worked. Now, we
only send the `ssl_transaction_currency` field if the currency is not
the default currency (USD).
Elavon Multi-Currency Conversion (MCC) documentation:
https://developer.elavon.com/#/api/eb6e9106-0172-4305-bc5a-b3ebe832f823.rcosoomi/documents?converge-integration-guide/book/processing_options/../../book/processing_options/mcc.html
ECS-272
Closes #3201 
Unit:
29 tests, 141 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
24 tests, 105 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Elavon: Send ssl_transaction_currency if not USD

---

CHANGELOG
lib/active_merchant/billing/gateways/elavon.rb
test/fixtures.yml
test/remote/gateways/remote_elavon_test.rb
test/unit/gateways/elavon_test.rb

Send the currency in the ssl_transaction_currency field only if the
user has specified they are using multi-currency. The multi-currency
flag can be set with either a gateway or transaction level field.
Using multi-currency depends on the merchant's multi-currency terminal
setting at Elavon.
ECS-272
Unit:
31 tests, 150 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
26 tests, 115 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Elavon: Multi-currency support

---

CHANGELOG
lib/active_merchant/billing/gateways/cyber_source.rb
test/remote/gateways/remote_cyber_source_test.rb
test/unit/gateways/cyber_source_test.rb

Adds Elo card type to list of supported cardtypes.
Closes #3213
Remote:
54 tests, 241 assertions, 5 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
90.7407% passed
The 5 failures listed above are unrelated and pre-existing to this change.
Unit:
57 tests, 277 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Cybersource: Adds Elo Card Type

---

CHANGELOG
lib/active_merchant/billing/gateways/qvalent.rb
test/remote/gateways/remote_qvalent_test.rb
test/unit/gateways/qvalent_test.rb

Includes ECI, posEntryMode, storedCredentialUsage, and authTraceID fields,
for Qvalent's requirements for use of stored Visa and Mastercards.
Mastercard will not accept all fields required by Visa.
Unit:
23 tests, 120 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
100% passed
ECS-174

Qvalent: Adds support for standard stored credential framework

---

lib/active_merchant/billing/gateways/cyber_source.rb
test/unit/gateways/cyber_source_test.rb

Currently it will send tokenization data for MasterCard when the card
type is `:mastercard` which is an invalid card type. This commit makes it
so it will send tokenization data when the card type is `:master` and not
`:mastercard`.
Right now, all tokenized mastercard are failing on Cybersource (at least for us).
Tests seem to only fail for the `SoEasyPay` which are unrelated to those changes
```
4069 tests, 69102 assertions, 1 failures, 7 errors, 0 pendings, 0 omissions, 0 notifications
99.8034% passed
```

[Gateways::Cybersource] Send tokenization data when card is :master

---

lib/active_merchant/billing/gateways/blue_snap.rb
test/remote/gateways/remote_blue_snap_test.rb
test/unit/gateways/blue_snap_test.rb

ECS-329
Per Bluesnap, state codes are not supported for countries other than
the US and Canada.
Unit:
26 tests, 102 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
34 tests, 105 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

 Bluesnap: only send state code for US and Canada

---

CHANGELOG
lib/active_merchant/billing/gateways/trans_first_transaction_express.rb
test/remote/gateways/remote_trans_first_transaction_express_test.rb

If a user passes in an empty string for the address2 field, their 
transaction will fail on this gateway. This PR ensures that address2 
only gets passed through if it is present and not blank. Additionally 
it cleans up some remote test failures. test_successful_verify still 
fails in the remote tests, but failure is unrelated to change.
Unit:
21 tests, 103 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
33 tests, 107 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications

TransFirst Express: Fix blank address2 values

---

CHANGELOG
lib/active_merchant/billing/gateways/worldpay.rb
test/remote/gateways/remote_worldpay_test.rb
test/unit/gateways/worldpay_test.rb

We are only supporting shopper-scoped tokens right now, and not
implementing delete/unstore, saving a token along with an authorize or
purchase call, overriding token details on use, or setting the token
lifetime.
The design of the opaque token authorization string we return from
`store` has been intentionally designed to be flexible enough to extend
in a backwards-compatible way should any of the above features need to
be implemented.
Unit:
59 tests, 329 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
50 tests, 219 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
96% passed
The two failing remote tests are concerning 3DS parameter pass through
which the test credentials I'm using does not have permission to use …

Implement Worldpay store

---

CHANGELOG
lib/active_merchant/billing/avs_result.rb
lib/active_merchant/billing/gateways/adyen.rb
test/unit/gateways/global_transport_test.rb

Map additional Adyen AVS result codes to Active Merchant AVS result
codes.
ECS-301
Unit:
37 tests, 179 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
60 tests, 187 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Adyen: Support for additional AVS code mapping

---

CHANGELOG
lib/active_merchant/billing/avs_result.rb
test/remote/gateways/remote_merchant_e_solutions_test.rb
test/remote/gateways/remote_moneris_test.rb
test/remote/gateways/remote_moneris_us_test.rb
test/unit/gateways/authorize_net_test.rb
test/unit/gateways/blue_pay_test.rb
test/unit/gateways/merchant_e_solutions_test.rb
test/unit/gateways/metrics_global_test.rb
test/unit/gateways/moneris_test.rb
test/unit/gateways/moneris_us_test.rb

Update AVS result message for alpha code 'A' to be more generic. The
previous message was causing confusion for merchants processing Canadien
cards with 6 digit postal codes.
ECS-56
Unit:
Authorize.net
96 tests, 565 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Blue Pay
26 tests, 125 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Merchant eSolutions
20 tests, 99 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Metrics Global
22 tests, 93 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Moneris
37 tests, 188 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Moneris US
34 tests, 169 assertions, 0 …

Update AVS result message

---

CHANGELOG
lib/active_merchant/billing/gateways/usa_epay_transaction.rb
test/remote/gateways/remote_usa_epay_transaction_test.rb

USAePay returns a ton of different error codes and currently the usaepay support in active merchant returns a nil for all of the error codes not specifically mapped, which is not useful. So we are defaulting to processing_error for any errors not defined in the standard_error_code_mapping.

Default usaepay errors to processing_error & handle a couple more codes

---

CHANGELOG
lib/active_merchant/billing/gateways/braintree_blue.rb
test/remote/gateways/remote_braintree_blue_test.rb
test/unit/gateways/braintree_blue_test.rb

Added `skip_avs` and `skip_cvv` gateway specific fields to the
Braintree gateway along with unit and remote tests.
ECS-328 / ECS-394
Remote:
73 tests, 415 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
Unit:
61 tests, 162 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed

Braintree: Add skip_avs and skip_cvv fields

---

CHANGELOG
lib/active_merchant/billing/gateways/nmi.rb
test/remote/gateways/remote_nmi_test.rb
test/test_helper.rb
test/unit/gateways/nmi_test.rb

Unit:
45 tests, 342 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
41 tests, 151 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
ECS-258
Closes #3243

NMI: Add support for stored credentials

---

CHANGELOG
lib/active_merchant/billing/gateways/spreedly_core.rb
test/remote/gateways/remote_spreedly_core_test.rb
test/unit/gateways/spreedly_core_test.rb

Consolidates purchase and authorization requests down to 1.
See issue: https://github.com/activemerchant/active_merchant/issues/3078

Spreedly one request + Add support for bank accounts

---

lib/active_merchant/billing/gateways/checkout_v2.rb
test/unit/gateways/checkout_v2_test.rb

Formatting + 2 fixes
- Card on File: the way we were sending that value was wrong/misplaced.
- Phone numbers: Checkout.com does not support non-digit chars for the `source: { phone: { number: '' }}}` field

Fixes checkout v2 integration

---

CHANGELOG
lib/active_merchant/billing/gateways/barclaycard_smartpay.rb
test/remote/gateways/remote_barclaycard_smartpay_test.rb
test/unit/gateways/barclaycard_smartpay_test.rb

This preps Barclaycard Smartpay for 3DS2 integration. The api version
is bumped up to 40 to get relevant 3DS2 functionality, and additional 
browser_info is captured. The parse method is also updated so that it 
can return a nested hash with an additionalData field for 3DS2.
Unit:
28 tests, 142 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
34 tests, 76 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
97.0588% passed
(failed `test_successful_third_party_payout` - unrelated invalid credentials error)

Barclaycard Smartpay: 3DS2 Support

---

CHANGELOG
lib/active_merchant/billing/gateways/adyen.rb
test/unit/gateways/adyen_test.rb

Adds localized_amount to determine amount, to allow correct handling of
non-fractional currencies.
Includes a what_amount method which will protect customers already transacting on
Adyen from a sudden change in their transaction amounts. what_amount
will be removed after coordinating.
ECS-420
Unit:
40 tests, 189 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
60 tests, 187 assertions, 4 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
93.3333% passed
Failures due to error message change, unrelated

Adyen: Add support for non-fractional currencies

---

CHANGELOG
lib/active_merchant/billing/gateways/decidir.rb
test/fixtures.yml
test/remote/gateways/remote_decidir_test.rb
test/unit/gateways/decidir_test.rb

Add support for the Decidir gateway. This implementation sends card data
inline with purchase and authorize requests rather than creating payment
method tokens.
ECS-374
Unit:
18 tests, 104 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
17 tests, 60 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Decidir: Add new gateway

---

CHANGELOG
lib/active_merchant/billing/gateways/checkout_v2.rb
test/unit/gateways/checkout_v2_test.rb

Reapplying this after the change in 9c7663b
Context: https://github.com/activemerchant/active_merchant/commit/9c7663b8041791eded8f35666cd11a2a5c83466e#commitcomment-34092185
Remote:
28 tests, 67 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
22 tests, 99 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Checkout V2: Re-apply Update stored card flag

---

CHANGELOG
lib/active_merchant/billing/gateways/blue_snap.rb
test/remote/gateways/remote_blue_snap_test.rb
test/unit/gateways/blue_snap_test.rb

ECS-430
Unit:
26 tests, 106 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
35 tests, 109 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

BlueSnap: Send amount in capture requests

---

CHANGELOG
lib/active_merchant/billing/credit_card.rb
lib/active_merchant/billing/credit_card_methods.rb
lib/active_merchant/billing/gateways/mundipagg.rb
test/remote/gateways/remote_mundipagg_test.rb
test/unit/credit_card_methods_test.rb
test/unit/gateways/mundipagg_test.rb

This change set adds support for the Alelo voucher card, including a Mundipagg implementation. Adyen Support has indicated that Alelo will be supported using elodebit rails for merchants that have a Cielo agreement. However, Adyen does not provide any Alelo test cards, and will not recognize generated cards as Alelo, so no Adyen-specific code has been added.
Some refactoring has been done in the Mundipagg remote tests to keep the code DRY now that a new card type is being tested.

Mundipagg: Add Alelo card support

---

CHANGELOG
lib/active_merchant/billing/gateways/adyen.rb
test/remote/gateways/remote_adyen_test.rb
test/unit/gateways/adyen_test.rb

After safe switchover is coordinated with customer who needed
transition step during update of Adyen to use localized_amount.
Unit:
39 tests, 188 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
60 tests, 187 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Continues ECS-420

Adyen: Remove temporary amount modification for non-fractional currencies

---

lib/active_merchant/billing/gateways/adyen.rb
test/remote/gateways/remote_adyen_test.rb

[ECS-367](https://spreedly.atlassian.net/browse/ECS-367)

Adyen: Replace empty state string with N/A

---

lib/active_merchant/billing/gateways/migs.rb
test/remote/gateways/remote_migs_test.rb
test/unit/gateways/migs_test.rb

Added the `tx_source` gateway specific field to the MiGS gateway along
with remote and unit tests.
CE-34
Unit:
9 tests, 21 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
Remote:
14 tests, 44 assertions, 0 failures, 1 errors, 0 pendings, 0 omissions,
92.8571% passed
Undefined method `request_uri` error in `test_server_purchase_url`;
error unrelated to change

MiGS: Add tx_source gateway specific field

---

CHANGELOG
lib/active_merchant/billing/gateways/card_connect.rb
test/remote/gateways/remote_card_connect_test.rb

Remove underscores from level 3 gateway specific fields. This functionality existed but wasn't working correctly -- this PR fixes it. 
ECS-397
Unit:
22 tests, 92 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
Remote:
23 tests, 55 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed

CardConnect: Fix level 3 field parse

---

CHANGELOG
lib/active_merchant/billing/gateways/trust_commerce.rb
test/remote/gateways/remote_trust_commerce_test.rb
test/unit/gateways/trust_commerce_test.rb

I was not able to test this remotely. I'm not sure if this functionality is enabled via settings or if it cannot be tested in the sandbox.
Trust Commerce allows voids on purchases, refunds and captures, and
preauths. Preauth uses the 'reversal' function, while purchase, refund,
and capture use the Trust Commerce 'void' function'.
Expand void support for additional transaction types by tracking the
original action associated with the authorization transaction
id. The action take at Trust Commerce (reversal or void) is based on the
original action.
ECS-356
Unit:
12 tests, 41 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
16 tests, 59 assertions, 3 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
81.25% passed
Three unrelated, …

Trust Commerce: Support void after purchase

---

CHANGELOG
lib/active_merchant/billing/gateways/blue_snap.rb
test/unit/gateways/blue_snap_test.rb

Including an amount on capture can cause an issue if attempting to
capture full amount authorized and there are slight differences in
amount requested and amount actually authorized due to currency
exchange. BlueSnap will capture full amount authorized if no amount is
included in the capture request. Adds a flag for including the amount
only in the case of partial capture.
Continues ECS-454
Relates to ECS-430
Unit:
27 tests, 110 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
35 tests, 109 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

BlueSnap: Default to not send amount on capture

---

lib/active_merchant/billing/gateways/opp.rb
test/unit/gateways/opp_test.rb

This adds support for tokenizing cards in the Open Payments Platform Gateway.
Documentation for tokenization can be found here: https://docs.oppwa.com/tutorials/server-to-server/tokenisation
Added functionality:
- ability to pass a token to `purchase` to pay with a previously stored card
- ability to `store` a credit card

OPP: Adds support for store

---

CHANGELOG
lib/active_merchant/billing/gateways/cecabank.rb
test/remote/gateways/remote_cecabank_test.rb

Updated the encryption method for the CECAbank gateway from SHA1 to
SHA2. This change also included updating the URLs for the gateway and
revising the remote tests.
CE-23
Unit:
7 tests, 36 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
Remote:
5 tests, 17 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed

CECAbank: Update encryption to SHA2

---

lib/active_merchant/billing/gateways/worldpay.rb
test/unit/gateways/worldpay_test.rb

For 3DS version 2.x, the value of the 3DS DS transaction ID is retrieved from `three_d_secure [xid]` but the value is in `three_d_secure[:ds_transaction_id]`
Retrieve the 3DS DS transaction ID from `three_d_secure[:ds_transaction_id]`

WorldPay - use ds_transaction_id for 3DS 2.x

---

CHANGELOG
README.md
lib/active_merchant/billing/gateways/credorax.rb
test/fixtures.yml
test/remote/gateways/remote_credorax_test.rb
test/unit/gateways/credorax_test.rb

Credorax: add 3DS2 MPI auth data support
Unit:
22 tests, 102 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
25 tests, 45 assertions, 10 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
60% passed
NOTE: Failing tests also failing in current master as of time of this run (and these same 10 were passing only a couple hours ago). The Credorax test infrastructure with respect to the test Visa credentials seems very unstable (and possibly depenedent on the time of day the transactions are attempted), see:
https://github.com/activemerchant/active_merchant/pull/3040#issuecomment-437146298
Today, it seemed like they passed before 17:00 London time, and started failing with "Transaction has been declined." at or around 17:00 London time. …

Credorax: add 3DS2 MPI auth data support

---

CHANGELOG
lib/active_merchant/country.rb

Although these codes are not officially in the ISO standard, they are
used by the European Commission, and we're seeing some buyers use them.
The numeric code, which is almost never used by the provider, is one of
the reserved codes that will never be assigned to an actual country. If
Kosovo is added to the ISO standard, we can correct it at that time.

Add Kosovo to the list of countries

---

lib/active_merchant/billing/gateways/realex.rb
test/fixtures.yml
test/remote/gateways/remote_realex_test.rb
test/unit/gateways/realex_test.rb

A few sample request we got from Realex contacts
```
<mpi>
<cavv>AAACBllleHchZTBWIGV4AAAAAAA=</cavv>
<xid>crqAeMwkEL9r4POdxpByWJ1/wYg=</xid>
<eci>5</eci>
<message_version>1</message_version>
</mpi>
```
And
```
<mpi>
<eci>5</eci>
<ds_trans_id>c272b04f-6e7b-43a2-bb78-90f4fb94aa25</ds_trans_id>
<authentication_value>ODQzNjgwNjU0ZjM3N2JmYTg0NTM=</authentication_value>
<message_version>2.1.0</message_version>
</mpi>
```
New card comes from: https://developer.globalpay.com/#!/resources/test-card-numbers

[Realex] Add 3DS support through external MPI

---

lib/active_merchant/billing/gateways/paypal.rb
test/remote/gateways/remote_paypal_test.rb
test/unit/gateways/paypal_test.rb

Paypal currently does not accept 3DS values in AM. This PR passes the 3DS values, 1.x to Paypal.
Example usage from the Paypal [documentation](https://developer.paypal.com/docs/classic/paypal-payments-pro/integration-guide/3d-secure/) for 1.0
```
<Version>59.0</Version>
.
.
.
<ThreeDSecureRequest>
<MpiVendor3ds>Y</MpiVendor3ds>
<AuthStatus3ds>Y</AuthStatus3ds>
<Cavv>jMKEKlqlJGiJARAbxMDZ5+fnFeg=</Cavv>
<Eci3ds>02</Eci3ds>
<Xid>TTVmdlFxbERYVXo5R1hrVUY5bjY=</Xid>
</ThreeDSecureRequest>
```
Next up this [PR](https://github.com/activemerchant/active_merchant/pull/3285) will be merged once Paypal is ready to accept 2.0 parameters

Add 3DS values to paypal

---

CHANGELOG
lib/active_merchant/billing/gateways/card_connect.rb

Retrieve domain from gateway specific fields rather than at the
top gateway level
ECS-448
Unit:
22 tests, 92 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
Remote:
23 tests, 55 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed

CardConnect: fix domain GSF

---

CHANGELOG
lib/active_merchant/billing/gateways/braintree_blue.rb
test/remote/gateways/remote_braintree_blue_test.rb
test/unit/gateways/braintree_blue_test.rb

Implement stored credentials framework for Braintree
Unit:
73 tests, 174 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
Remote:
79 tests, 435 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed

ECS-217_braintree_stored_credentials

---

CHANGELOG
lib/active_merchant/billing/gateways/realex.rb
test/remote/gateways/remote_realex_test.rb
test/unit/gateways/realex_test.rb

Implemented support for `credit` (also known as `general_credit` in
Spreedly parlance) for the Realex gateway, including remote and unit
tests.
CE-52 / CE-58
Unit:
27 tests, 844 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
Remote:
26 tests, 135 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed

Realex: Implement credit

---

CHANGELOG
lib/active_merchant/billing/gateways/paymill.rb
test/unit/gateways/paymill_test.rb

Paymill now requires a currency and amount to be specified for tokenization. These are used
for an authorization. We now set this authorization amount to $1 USD -- the minimum allowed -- in our ```store``` requests. 
The ```currency``` and ```money``` options  are translated to ```presentation.amount3D``` and ```presentation.currency3D``` in the request made to Paymill.

Paymill: Add currency and amount to store requests

---

lib/active_merchant/billing/gateways/orbital.rb
test/remote/gateways/remote_orbital_test.rb
test/unit/gateways/orbital_test.rb

Adds support for 3ds to Orbital. All remote tests are passing using the test cards provided by Orbital.

[Orbital] Add support for 3DS

---

CHANGELOG
lib/active_merchant/billing/gateways/realex.rb
test/unit/gateways/realex_test.rb

Fix an error that occurs when the ```rebate_secret``` or ```refund_secret``` option is set to ```nil```. In that case, the Realex gateway initializer attempts to calculate the refund hash or credit hash, passing ```nil``` to ```Digest::SHA1.hexdigest```, causing a type error. The fix is to only compute each hash if its secret has actually been provided.

Realex: Fix an error that occurs when the rebate_secret or refund_secret is nil

---

CHANGELOG
lib/active_merchant/billing/gateways/beanstream.rb
lib/active_merchant/billing/gateways/beanstream/beanstream_core.rb

Per issue #3006 -- Beanstream requires `trnCardOwner` when storing a tokenized credit card.

Pass card owner when storing tokenized cards

---

lib/active_merchant/billing/gateways/monei.rb
test/remote/gateways/remote_monei_test.rb
test/unit/gateways/monei_test.rb

This PR adds 3d secure support for [MONEI gateway](https://monei.net/)
Full MONEI XML API documentation can be found in [XML_Transactions_3_4_4.pdf](https://github.com/activemerchant/active_merchant/files/3461045/XML_Transactions_3_4_4.pdf)
Remote test result:
```
rake test TEST=test/remote/gateways/remote_monei_test.rb
/Users/dmitriy/.rvm/rubies/ruby-2.5.5/bin/ruby -w -I"lib:test" -I"/Users/dmitriy/.rvm/gems/ruby-2.5.5/gems/rake-12.3.3/lib" "/Users/dmitriy/.rvm/gems/ruby-2.5.5/gems/rake-12.3.3/lib/rake/rake_test_loader.rb" "test/remote/gateways/remote_monei_test.rb" 
Loaded suite /Users/dmitriy/.rvm/gems/ruby-2.5.5/gems/rake-12.3.3/lib/rake/rake_test_loader
Started
Finished in 18.328891 seconds.
----------------------------------------------------------------------------- …
```

add MONEI 3d secure support

---

CHANGELOG
lib/active_merchant/billing/gateways/adyen.rb
test/remote/gateways/remote_adyen_test.rb

To create app based auth and purchases requests two things need to happen:
1) Send channel as "app"
2) Don't send notificationURL

Add app based 3DS auth and purchase to Adyen

---

CHANGELOG
lib/active_merchant/billing/credit_card.rb
lib/active_merchant/billing/credit_card_methods.rb
lib/active_merchant/billing/gateways/adyen.rb
lib/active_merchant/billing/gateways/blue_snap.rb
lib/active_merchant/billing/gateways/d_local.rb
lib/active_merchant/billing/gateways/global_collect.rb
lib/active_merchant/billing/gateways/mercado_pago.rb
lib/active_merchant/billing/gateways/payu_latam.rb
lib/active_merchant/billing/gateways/worldpay.rb
test/remote/gateways/remote_d_local_test.rb
test/remote/gateways/remote_payu_latam_test.rb
test/unit/credit_card_methods_test.rb

This adds support for the Naranja card type along with the custom
card number validation logic they use. Naranja is added as a card
type to the following gateways: Bluesnap, dLocal, PayU Latam, Ingenico
ePayments, Mercado Pago, Worldpay, Adyen
There is a single BIN number for Naranja (589562) -- it is co-branded
with Visa, Mastercard, and Amex and will be identified as the co-brand
in those cases.
Added remote gateway test for dLocal and PayU Latam -- remaining
gateways either didn't have a Naranja test card available or needed
additional configuration for Naranja cards (card type or region enabled)
Removed two tests from PayU Latam because capture and void methods are
now supported in the sandbox.
Remote dLocal tests
Remote
22 tests, 61 assertions, 0 failures, 0 errors, 0 pendings, 0 …

Adds Naranja card type

---

CHANGELOG
lib/active_merchant/billing/gateways/cyber_source.rb
test/remote/gateways/remote_cyber_source_test.rb
test/schema/cyber_source/CyberSourceTransaction_1.155.xsd
test/schema/cyber_source/CyberSourceTransaction_1.156.xsd
test/unit/gateways/cyber_source_test.rb

Added support for the issuer additionalData CyberSource-specific field. The CyberSource XML schema has also been updated. Per the gateway's instructions, we are now using version 1.156 in the test environment, and version 1.155 in production.

CyberSource: Add support for issuer additionalData gateway-specific field

---

CHANGELOG
activemerchant.gemspec
lib/active_merchant/billing/gateways/stripe.rb
lib/active_merchant/billing/gateways/stripe_payment_intents.rb
test/remote/gateways/remote_stripe_payment_intents_test.rb
test/unit/gateways/stripe_payment_intents_test.rb

In preparation for Stripe 3DS2 support, this PR adds support for Stripe Payment Intents.
Stripe Payment Intents is added as a gateway, with functionality to create new PaymentIntents 
and Stripe PaymentMethods. PaymentIntents can also be confirmed, captured, cancelled, and 
updated. This gateway is implemented as a subclass of the Stripe gateway. To take advantage of 
the latest features, the API for this gateway is bumped up to the latest version, `2019-05-16`.
Remote:
23 tests, 99 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
100% passed
===
_Confirming that original Stripe tests also passing:_
_Remote:_
_67 tests, 313 assertions, 0 failures, 0 errors, 0 …

Stripe Payment Intents - Add new gateway

---

CHANGELOG
lib/active_merchant/billing/gateways/checkout_v2.rb
test/unit/gateways/checkout_v2_test.rb

Adds a method to verify a payment after its gone through 3DS
authentication.
Loaded suite test/unit/gateways/checkout_v2_test
..........................
26 tests, 116 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Loaded suite test/remote/gateways/remote_checkout_v2_test
29 tests, 70 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Checkout_v2: Support for native 3DS2.0

---

CHANGELOG
lib/active_merchant/billing/gateways/eway_rapid.rb
test/remote/gateways/remote_eway_rapid_test.rb
test/unit/gateways/eway_rapid_test.rb

When setting the customer and shipping address fields for the ```purchase```, ```authorize```, ```store```, and ```update``` operations:
- When no address has been provided, default to the name associated with the payment method.
- Fixed a bug in which the email was not set if no address was provided.
- Fixed a bug in which the shipping address phone number was not set.
In addition, some existing failing/erroring tests were updated to pass correctly, and test coverage for the customer and shipping address data logic has been added.

eWAY Rapid: Resolve issues in setting customer and shipping address fields

---

CHANGELOG
lib/active_merchant/billing/gateways/payu_latam.rb
test/remote/gateways/remote_payu_latam_test.rb
test/unit/gateways/payu_latam_test.rb

Like with all other PayU Latam buyer options, the ```merchant_buyer_id``` field can be passed at the top level of the ```options``` hash, or under the ```buyer``` key.

PayU Latam: Add support for merchantBuyerId

---

CHANGELOG
lib/active_merchant/billing/gateways/trust_commerce.rb
test/remote/gateways/remote_trust_commerce_test.rb
test/unit/gateways/trust_commerce_test.rb

Also fix some tests that previously failed.
Unit:
4236 tests, 70441 assertions, 0 failures, 0 errors, 0 pendings, 2 omissions, 0 notifications
100% passed
Remote:
100% passed

Support custom fields for TrustCommerce

---

lib/active_merchant/billing/gateways/decidir.rb
test/remote/gateways/remote_decidir_test.rb

EVS-181
Adds Naranha card to Decidir gateway
Updated two tests to correspond to changed Decidir responses
Unit:
22 tests, 112 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
Remote:
17 tests, 60 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed

Decidir: Add Naranja Card

---

CHANGELOG
lib/active_merchant/billing/gateways/stripe_payment_intents.rb
test/remote/gateways/remote_stripe_payment_intents_test.rb

Rather than requiring a user to send in a hash with transfer data, this PR changes
to use individual `transfer_destination` and `transfer_amount` fields instead.
Remote:
24 tests, 103 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
100% passed

Stripe Payment Intents - Update transfer_data option

---

CHANGELOG
lib/active_merchant/billing/gateways/stripe_payment_intents.rb
test/remote/gateways/remote_stripe_payment_intents_test.rb

Saves billing details (address, name, email, phone) to payment methods.
Remote:
25 tests, 107 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
100% passed

Stripe Payment Intents: Add billing_details to payments

---

CHANGELOG
lib/active_merchant/billing/gateways/barclaycard_smartpay.rb
test/remote/gateways/remote_barclaycard_smartpay_test.rb

Like Adyen (#3298), we need to be able to create app based auth
and purchase requests, setting device_channel appropriately and
only sending notificationURL for browser based requests.
Remote:
36 tests, 87 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
97.2222% passed
Unit:
28 tests, 143 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unrelated pre-existing remote test failures:
- test_successful_third_party_payout (invalid credentials)

Barclaycard Smartpay: Add app based 3ds auth and purchase

---

CHANGELOG
lib/active_merchant/billing/gateways/checkout_v2.rb
lib/active_merchant/billing/gateways/stripe_payment_intents.rb
test/remote/gateways/remote_checkout_v2_test.rb
test/remote/gateways/remote_stripe_payment_intents_test.rb

This PR enables marking a transaction as MOTO on the Stripe Payment
Intents and Checkout V2 gateways. Note: For Stripe, accounts must
be configured to allow setting the [MOTO flag](https://stripe.com/guides/strong-customer-authentication#phone-sales). This PR also adds the list of 
supported countries for Stripe Payment Intents.
**Stripe Payment Intents**
Remote:
28 tests, 115 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
100% passed
**Checkout V2**
Remote:
30 tests, 72 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
26 tests, 116 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% …

Stripe Payment Intents, Checkout V2: MOTO flag

---

lib/active_merchant/billing/gateways/braintree_blue.rb
test/remote/gateways/remote_braintree_blue_test.rb
test/unit/gateways/braintree_blue_test.rb

Continued from #3312 
Unit:
74 tests, 175 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
80 tests, 435 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Braintree Blue: Adding 3DS2 passthru support

---

CHANGELOG
lib/active_merchant/billing/gateways/global_collect.rb

Adds the Cabal card to the Global Collect gateway (also known as the
Ingenico gateway).
The Ingenico gateway docs do not include a test card number for Cabal,
and sending card numbers that follow the Luhn algorithm and fall within
the Cabal card range results in error messages of "Rejected".
Therefore, no additional remote or unit tests were added to the Global
Collect gateway to test the implementation of the Cabal card type.
CE-94 / CE-97
Unit:
20 tests, 88 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
Remote:
17 tests, 40 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed

Global Collect: Add Cabal card

---

CHANGELOG
lib/active_merchant/billing/gateways/worldpay.rb
test/remote/gateways/remote_worldpay_test.rb

This PR adds the necessary fields to mark transactions as MOTO 
by setting `dynamicInteractionType` to `MOTO` when the 
payment is marked as a manual entry ([requires configuration on 
the account level to be able to use](http://support.worldpay.com/support/kb/gg/corporate-gateway-guide-beta/content/directintegration/paymentrequests.htm#Flexible)).
Remote:
51 tests, 217 assertions, 5 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
90.1961% passed
Unit:
66 tests, 392 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Worldpay: Exemption flagging (MOTO)

---

lib/active_merchant/billing/gateways/epay.rb
test/remote/gateways/remote_epay_test.rb
test/unit/gateways/epay_test.rb

Adds 3DS support to the epay payment method.
---- Unit Test ----
Loaded suite test/unit/gateways/epay_test.rb
16 tests, 55 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
---- Remote Test ----
Loaded suite test/remote/gateways/remote_epay_test.rb
9 tests, 15 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Bambora Online ePay 3DS support

---

lib/active_merchant/billing/gateways/checkout_v2.rb
test/remote/gateways/remote_checkout_v2_test.rb
test/unit/gateways/checkout_v2_test.rb

```
...........................
Finished in 0.012471 seconds.
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
27 tests, 120 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
```
```
...............................
Finished in 30.509284 seconds.
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
31 tests, 74 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 …
```

[Checkout.com] Using options[:metadata][:manual_entry] for Moto transactions

---

CHANGELOG
lib/active_merchant/billing/gateways/adyen.rb
test/remote/gateways/remote_adyen_test.rb
test/unit/gateways/adyen_test.rb

There are a few different ways to [request exemptions via Adyen](https://docs.adyen.com/payments-essentials/psd2-sca-compliance-and-implementation-guide?query=additionalData.executeThreeD#managingpsd2scacompliance).
Users can let Adyen handle compliance by default, they can
configure specific rules using dynamic 3dsecure, or they can set
exemption flags via the API. This PR updates the Adyen gateway to
allow users to set specific exemptions using the sca_exemption
field, used in conjunction with the execute_threed field. Users
can also now set execute_threed to false if they want to bypass
3DS on a transaction.
Remote:
64 tests, 207 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
39 tests, 188 assertions, 0 failures, 0 errors, 0 pendings, 0 …

Adyen: Set 3DS exemptions via API

---

CHANGELOG
lib/active_merchant/billing/gateways/stripe_payment_intents.rb
test/remote/gateways/remote_stripe_payment_intents_test.rb

You do not need to pass the transfer destination in a capture request,
and in fact the request will fail if you try to post that data.
However, before this PR, we were requiring that a destination account
be present before setting the associated fee/transfer amount. This PR
updates the logic to set only the application fee or transfer amount
on capture requests when present.
Remote:
29 tests, 124 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
100% passed

Stripe Payment Intents: Successfully set application fee on capture

---

CHANGELOG
test/remote/gateways/remote_mercado_pago_test.rb
test/unit/gateways/mercado_pago_test.rb

Adds remote and unit tests for the Naranja card type
The `test_partial_capture` and
`test_successful_purchase_with_processing_mode_gateway` remote tests are
currently failing and were failing prior to these changes.
Remote:
30 tests, 91 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions,
93.3333% passed
Unit:
28 tests, 147 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed

MercadoPago: Add tests for Naranja card

---

lib/active_merchant/billing/gateways/worldpay.rb

Adds 3DS support to worldpay gateway. Two remote tests failing that are
unlreated.
.................................................
51 tests, 221 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
96.0784% passed
Started
...................................................................
67 tests, 397 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Worldpay: Add 3DS2 Support

---

CHANGELOG
lib/active_merchant/billing/gateways/credorax.rb
test/remote/gateways/remote_credorax_test.rb
test/unit/gateways/credorax_test.rb

Adds 3DS 2.0 fields to credorax and a new field that is required for
passing 3DS authenticated fields.
Loaded suite test/remote/gateways/remote_credorax_test
..........................
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
26 tests, 73 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- …

Credorax: Add 3DS 2.0

---

CHANGELOG
lib/active_merchant/billing/gateways/stripe_payment_intents.rb

[CE-123](https://spreedly.atlassian.net/browse/CE-123)
Unit tests:
100% passed
Remote tests:
29 tests, 118 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
96.5517% passed 
Invalid request error generating failure on `test_create_payment_intent_that_saves_payment_method`: "A valid `customer` must be provided when `save_payment_method=true`".

Stripe Payment Intents: add supported countries

---

CHANGELOG
lib/active_merchant/billing/gateways/mundipagg.rb
test/remote/gateways/remote_mundipagg_test.rb
test/unit/gateways/mundipagg_test.rb

For ```purchase```, ```authorize```, and ```store```, extract any error messages from the gateway response and append them to the "message" response feld. Mundipagg can return errors at either the top level of the response object, or under the ```last_transaction``` ```gateway_response``` key.

Mundipagg: Append errors to message response field

---

CHANGELOG
lib/active_merchant/billing/gateways/redsys.rb
test/remote/gateways/remote_redsys_sha256_test.rb
test/unit/gateways/redsys_sha256_test.rb

Sets sca_exemption when available for 3ds transactions. Also sets
moto flag when requested.
Remote:
22 tests, 68 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
36 tests, 111 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Redsys: Add exemptions

---

CHANGELOG
lib/active_merchant/billing/gateways/credorax.rb
test/remote/gateways/remote_credorax_test.rb
test/unit/gateways/credorax_test.rb

Credorax now requires `3ds_transtype` is required. This passes a default
value if none is passed. Also passes optional field `3ds_version`.
Loaded suite test/unit/gateways/credorax_test
Started
.......................
Finished in 0.020239 seconds.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
23 tests, 125 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Credorax: Add A Mandatory 3DS field

---

lib/active_merchant/billing/gateways/beanstream.rb
lib/active_merchant/billing/gateways/beanstream/beanstream_core.rb
test/remote/gateways/remote_beanstream_test.rb

Change the void action for authorization transactions to capture a 0 amount, per Beanstream's recommendation.
ECS-514 #close
Unit:
23 tests, 108 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
43 tests, 195 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
95.3488% passed
NOTE: Failing tests also failing in current master as of time of this
run.

Beanstream: update void authorization

---

CHANGELOG
lib/active_merchant/billing/gateways/worldpay.rb
test/unit/gateways/worldpay_test.rb

The `&` symbol was causing issues when parsing responses from worldpay.
This updates the parsing method to Nokogiri so these special characters
no longer cause an issue.
2 remotes tests failing for unrelated reasons.
...................................................................
67 tests, 397 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
....................................................
54 tests, 235 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
96.2963% passed

Worldpay: Switch to Nokogiri

---

CHANGELOG
lib/active_merchant/billing/gateways/credorax.rb
test/remote/gateways/remote_credorax_test.rb
test/unit/gateways/credorax_test.rb

Credorax uses the field `a2` to mark payment source type. Possible 
values for this field are:
2 - Online Order (default value) 
3 - Telephone Order 
4 - Mail Order 
5 - Virtual Terminal
This PR sets the value to 3 when the manual entry flag is set. 
Unit:
24 tests, 127 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
27 tests, 77 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Credorax: Add MOTO support

---

CHANGELOG
lib/active_merchant/billing/gateways/credorax.rb
test/remote/gateways/remote_credorax_test.rb
test/unit/gateways/credorax_test.rb

Adds gateway specific fields to the Credorax gateway to enable the user
to select a different processor, including adding a unit test and a
(failing) remote test.
Gateway specific fields added:
- R1: processor name
- R2: processor merchant ID
CE-35
Unit:
23 tests, 106 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
Remote:
26 tests, 37 assertions, 21 failures, 0 errors, 0 pendings, 0 omissions,
19.2308% passed
The Credorax gateway integration was recently updated, and now many of
the remote tests that were previously passing are failing. It is
currently unknown why these tests are all failing. We have reached
out to Credorax to inquire about this new behavior.

Credorax: Enable selecting a processor

---

CHANGELOG
lib/active_merchant/billing/gateways/worldpay.rb
test/unit/gateways/worldpay_test.rb

This reverts 0735e8977affbd929e1605e5ded9e7d3567096a9 due XML parse
exceptions that we observed with production traffic.
Unit Tests:
67 tests, 397 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote Tests:
All failed because " Failed with 503 Service Unavailable" at the time of
this change

Revert "Worldpay: Switch to Nokogiri"

---

CHANGELOG
lib/active_merchant/billing/gateways/adyen.rb
test/remote/gateways/remote_adyen_test.rb
test/unit/gateways/adyen_test.rb

Added the Cabal card to the Adyen gateway, including adding unit and
remote tests.
Currently, Adyen does not support recurring transactions for Cabal
cards, so additional logic was added to the `store` method to return an
error message when attempting to store a Cabal card. Since the `store`
method for Adyen uses the `authorise` action, even though Cabal cards
cannot be successfully stored, the response from the gateway is
successful and does not return any sort of error message.
CE-99
Unit:
40 tests, 193 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
Remote:
68 tests, 214 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed

Adyen: Add Cabal card

---

CHANGELOG
lib/active_merchant/billing/gateways/decidir.rb
test/remote/gateways/remote_decidir_test.rb
test/unit/gateways/decidir_test.rb

Added remote tests for the new card types Cabal and Naranja now that
the Decidir test gateway has been updated to accept these card types.
In addition, added new logic to determine the correct
`payment_method_id` based on the card type.
With the update of the test gateway, some of the error messages changed,
so those were also updated in the remote tests.
CE-94 / CE-110
Unit:
22 tests, 112 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
Remote:
19 tests, 66 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed

Decidir: Add remote tests for Cabal and Naranja

---

lib/active_merchant/billing/gateways/payflow.rb
test/remote/gateways/remote_payflow_test.rb
test/unit/gateways/payflow_test.rb

Due to missing information, we've been getting 3DS errors from payflow_uk:
`Field format error: 12000-Transaction is not compliant due to missing or invalid 3D-secure authentication values`
This PR adds the missing fields following [this documentation](https://developer.paypal.com/docs/classic/payflow/3d-secure-mpi/#how-to-send-3-d-secure-authentication-data)

[3DS] Update status to accept the correct field in payflow integration

---

CHANGELOG
lib/active_merchant/billing/gateways/redsys.rb
test/remote/gateways/remote_redsys_sha256_test.rb
test/unit/gateways/redsys_sha256_test.rb

Ensure that the authorization field is set when performing 3DS transactions.
Remote:
100% passed
Unit:
36 tests, 112 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Redsys: Set authorization for 3DS transactions

---

CHANGELOG
lib/active_merchant/billing/gateways/adyen.rb
test/remote/gateways/remote_adyen_test.rb
test/unit/gateways/adyen_test.rb

Unit: 
48 tests, 231 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 
66 tests, 213 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
96.9697% passed. Both failures involve the `liabilityShift` 3DS field.
CE-133

Adyen: Add capture_delay_hours GSF

---

test/remote/gateways/remote_worldpay_test.rb

MOTO is now enabled on the test account used in Worldpay remote
testing. Updates test to actually check that purchase is successful
when flagged as MOTO.
Remote:
54 tests, 232 assertions, 5 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
90.7407% passed
(5 preexisting, unrelated errors)
Unit:
67 tests, 397 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Worldpay: Update test with MOTO enabled account

---

CHANGELOG
test/remote/gateways/remote_blue_snap_test.rb

Added remote tests for the new Cabal and Naranja card types that were
previously enabled.
CE-94 / CE-111
Unit:
30 tests, 142 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
Remote:
40 tests, 121 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions,
97.5% passed
`test_successful_purchase_with_3ds2_auth` is now failing with the error
message "Transaction failed  because of payment processing failure.:
400540 - Authorisation failed for request 2652197". It's not clear what
is causing this error, but it doesn't seem related to these changes.

BlueSnap: Add remote tests for Cabal and Naranja

---

CHANGELOG
test/remote/gateways/remote_worldpay_test.rb

Adds remote tests for both of the newly implemented card types:
- Cabal
- Naranja
The test card numbers for the new card types were taken directly from
WorldPay's
[documentation](https://beta.developer.worldpay.com/docs/wpg/latinamericaintegration/test).
CE-94 / CE-109
Unit:
67 tests, 397 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
Remote:
56 tests, 235 assertions, 5 failures, 0 errors, 0 pendings, 0 omissions,
91.0714% passed
Failing remote tests:
- test_3ds_version_1_parameters_pass_thru
- test_3ds_version_2_parameters_pass_thru
- test_successful_credit_using_token
- test_successful_mastercard_credit_on_cft_gateway
- test_successful_visa_credit_on_cft_gateway
The first two failing tests are associated with pass-through …

WorldPay: Add Cabal and Naranja remote tests

---

CHANGELOG
lib/active_merchant/billing/gateways/blue_pay.rb
test/remote/gateways/remote_blue_pay_test.rb
test/unit/gateways/blue_pay_test.rb

ACH refunds and credits [require DOC_TYPE to be set to PPD or CCD](https://www.bluepay.com/sites/default/files/documentation/BluePay_bp20post/Bluepay20post.txt)
to be processed successfully. This PR adds the ability to pass in
a specific DOC_TYPE in the request.
Remote:
17 tests, 84 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
27 tests, 130 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

BluePay: Allow setting DOC_TYPE in refund, credit

---

lib/active_merchant/billing/gateways/moneris.rb
test/remote/gateways/remote_moneris_test.rb
test/unit/gateways/moneris_test.rb

https://usa.visa.com/dam/VCOM/global/support-legal/documents/stored-credential-transaction-framework-vbs-10-may-17.pdf
https://developer.moneris.com/Documentation/NA/E-Commerce%20Solutions/API/Purchase
This change allows for the standardization of utilizing the stored credentials framework
1. VISA's stored credential transaction framework does not support 'recurring' nor 'installment' transactions
for cardholder-initiated, thus passing the ':cardholder' option will default ':payment_indicator' to 'C' for
initial transactions and to 'Z' for subsequent transactions.
2. The ':issuer_id', ':payment_indicator', and ':payment_information' options can still be passed directly and
will override any values set by the ':stored_credential' options.
Unit:
50 tests, 266 assertions, 0 failures, 0 …

Moneris: Add support for stored credentials

---

CHANGELOG
lib/active_merchant/billing/gateways/stripe.rb
test/unit/gateways/stripe_test.rb

we have noticed that there is a higher amount of payment anomalies since aug 2018. After digging we learned that this is due to Stripe's change in how they handle authorization. 
Essentially, historically, Stripe had a requirement in their backend to require a Transaction Certificate (TC) for emv authorizations prior to being able to capture the funds. In Aug 2018, Stripe removed this requirement and so their system automatically captured **all** emv authorizations. this was a business logic change on their backend.
To ensure that we are still withholding the same correct insert full-emv behaviours to prior to the change, we need to:
1. set capture to false https://stripe.com/docs/api/charges/create#create_charge-capture (same as current)
2. update the charge with the card param (same as …

Stripe: Restore non-auto capture behaviour for card present transactions

---

CHANGELOG
lib/active_merchant/billing/gateways/redsys.rb

Based on the Redsys docs, it seems that when you attempt 3DS but
3DS is not available, you will receive a direct response to your
request. Currently, we look under specific namespaces related to
the 3DS action step when performing 3DS, which would cause an error
if the service returned a direct response. This PR updates the
parse method to first look for the path //RETORNOXML/OPERACION
and if present (and successful), tries to parse the response.
Otherwise, we proceed to the 3DS specific parsing, or error
message if there was an issue.
Unfortunately, there's no way to test this in the Redsys sandbox,
but existing functionality appears in tact with this change.
Remote:
100% passed
Unit:
36 tests, 112 …

Redsys: Check for non-3DS response before attempting 3DS parse

---

lib/active_merchant/billing/gateways/ixopay.rb
test/fixtures.yml
test/remote/gateways/remote_ixopay_test.rb
test/unit/gateways/ixopay_test.rb

This pull request implements the Ixopay purchase action. It also includes skeleton code for additional work.
What's working:
* ```ruby -I test test/remote/gateways/remote_ixopay_test.rb -n test_successful_purchase```
* ```ruby -I test test/remote/gateways/remote_ixopay_test.rb -n test_failed_purchase```
* ```ruby -I test test/unit/gateways/ixopay_test.rb -n test_successful_purchase```
* ```ruby -I test test/unit/gateways/ixopay_test.rb -n test_failed_purchase```
The diff displayed here is relative to the initial code provided by running ```script/generate gateway ixopay```.
I'm planning a live review session for this code, but am opening the PR now for visibility.
Baseline: https://github.com/activemerchant/active_merchant/compare/ixopay_integration#diff-51a89ecca18e8620ad6cb8e059787833

CE-136: Ixopay purchase

---

lib/active_merchant/billing/gateways/ixopay.rb
test/remote/gateways/remote_ixopay_test.rb
test/unit/gateways/ixopay_test.rb

Implements the `refund` transaction type for the new Ixopay gateway.
CE-140
Unit:
14 tests, 16 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
Remote:
16 tests, 23 assertions, 0 failures, 0 errors, 0 pendings, 11 omissions,
100% passed

Ixopay: Implement refund

---

CHANGELOG
lib/active_merchant/billing/gateways/quickbooks.rb
test/fixtures.yml
test/remote/gateways/remote_quickbooks_test.rb
test/unit/gateways/quickbooks_test.rb

Quickbooks is deprecating OAuth 1.0 support, and requiring OAuth
2.0 no later than December 17, 2019. This PR adds support for
OAuth 2.0, requiring the `access_token`, `refresh_token`, `client_id`
and `client_secret` when creating a gateway. When refresh_token is
present, OAuth 2.0 authentication will be attempted. If not
included, OAuth 1.0 will be attempted and should still work until
the deprecation date.
In the Quickbooks implementation, the access_token expires every
60 minutes and you must use the refresh_token to generate a new
one. There's no way to proactively check if the token is still
valid; you'll just see that the request fails with an
`AuthenticationFailed` error. This PR adds logic to each action to
check for this error, and attempt to refresh the token and reissue
the …

Quickbooks: Add OAuth 2.0 support, support void

---

lib/active_merchant/billing/gateways/ixopay.rb
test/remote/gateways/remote_ixopay_test.rb
test/unit/gateways/ixopay_test.rb

Implements the void transaction type for the new Ixopay gateway,
including unit and remote tests.
CE-135 / CE-139
Unit:
15 tests, 52 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
Remote:
16 tests, 44 assertions, 0 failures, 0 errors, 0 pendings, 5 omissions,
100% passed

Ixopay: Implement void action

---

test/remote/gateways/remote_opp_test.rb
test/unit/gateways/opp_test.rb

This change is required for remote tests to pass
ECS-825
Unit:
14 tests, 73 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
15 tests, 48 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

OPP (Acapture): Update test cards' expirations

---

test/remote/gateways/remote_ixopay_test.rb
test/unit/gateways/ixopay_test.rb

Implement the `verify` action for the new Ixopay gateway, including
remote and unit tests.
CE-135 / CE-141
Unit:
15 tests, 59 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
Remote:
16 tests, 48 assertions, 0 failures, 0 errors, 0 pendings, 3 omissions,
100% passed

Ixopay: Implement verify action

---

CHANGELOG
lib/active_merchant/billing/gateways/quickbooks.rb
test/remote/gateways/remote_quickbooks_test.rb
test/unit/gateways/quickbooks_test.rb

While access_tokens expire every hour, there are potential
complications in refreshing them in certain workflows. Adds a flag,
`allow_refresh` to optionally refresh the access_token after making
a request. Also marks as a failure if authentication failed.
Remote:
16 tests, 40 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
21 tests, 114 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Quickbooks: Make refresh optional

---

lib/active_merchant/billing/gateways/ixopay.rb
test/remote/gateways/remote_ixopay_test.rb
test/unit/gateways/ixopay_test.rb

For refunds, the currency in the ```options``` hash was not passed to the ```refund``` method. This resulted in the default currency being used. I discovered the problem while testing with the new gateway in core. I specified USD for the currency for the purchase, but the credit (refund) defaulted to EUR, which caused a mismatch error at the gateway.
When I posted in Slack, I was under the impression that core was not passing the currency from the transaction for refunds. I was mistaken: the problem was just that we weren't propagating it to the ```add_refund``` helper in Active Merchant.
In Slack, we also spoke briefly about whether the latter part of the ```options[:currency] || currency(money)``` idiom was needed. I took a look and decided to leave that in for now, since the …

Ixopay: Add support for currency option to refund method

---

lib/active_merchant/billing/gateways/ixopay.rb

The Ixopay adapter was previously passing in a default ```callback_url``` of ```http://www.example.com``` in the case that the option was not provided. This change removes the default. The value of not having a (useless) default is that if the URL is not provided when required for the particular connector being used with Ixopay, Ixopay will be able to return an error as such to the user.

Ixopay: Remove default callback URL

---

.rubocop_todo.yml
CHANGELOG
lib/active_merchant/billing/credit_card_methods.rb
lib/active_merchant/billing/gateways/iridium.rb
lib/active_merchant/billing/gateways/moneris.rb
lib/active_merchant/billing/gateways/moneris_us.rb
lib/active_merchant/billing/gateways/orbital.rb
lib/active_merchant/billing/gateways/redsys.rb
test/unit/gateways/braintree_blue_test.rb
test/unit/gateways/skip_jack_test.rb

Fixes the multiline operation indentation for RuboCop.
Unit:
4356 tests, 71056 assertions, 0 failures, 0 errors, 0 pendings, 2 omissions,
100% passed
RuboCop:

RuboCop: Fix Layout/MultilineOperationIndentation

---

CHANGELOG
lib/active_merchant/billing/gateways/worldpay.rb
test/unit/gateways/worldpay_test.rb

In testing with Worldpay, there was some unexpected behavior when
the 3DS version was 2. The existing regex match didn't capture the
value of `2` as being equivalent to a 3DS2 version, and so the
cardholder name was getting set to '3D'. This update uses
`start_with?` to capture any version value that starts with `2`,
including `2`. Unit tests have also been updated to test various
permutations of 3DS2 version values.
Remote:
56 tests, 240 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
96.4286% passed
(pre-existing failures)
Unit:
69 tests, 411 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Worldpay: Update cardholder name logic based on 3DS version

---

CHANGELOG
lib/active_merchant/billing/gateways/quickbooks.rb
test/unit/gateways/quickbooks_test.rb

When an access_token has insufficient scope, a merchant will
receive the code `AuthorizationFailed`, rather than
`AuthenticationFailed`. This update checks for this error code
and marks such transactions as failures.
Unit:
22 tests, 118 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
17 tests, 42 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Quickbooks: Mark AuthorizationFailed responses as failures

---

CHANGELOG
lib/active_merchant/billing/gateways/credorax.rb
test/remote/gateways/remote_credorax_test.rb
test/unit/gateways/credorax_test.rb

Added support for the referral CFT transaction type on the Credorax
gateway (transaction type [34]).
To simplify this new transaction type, it is selected by passing a new
`referral_cft` gateway specific field while requesting a `refund`
transaction. Although the referral CFT transaction defaults to a credit
request when it has not been enabled on the Credorax gateway
integration, the referral CFT requires passing a `g2` value, i.e.,
"Previous Response ID". Therefore, because this transaction type
requires a reference authorization from a previous transaction, its
implmentation was more similar to a refund than a credit.
Because Spreedly's current Credorax gateway integration does not have
the ability to make referral CFT transactions, the remote and unit tests
for this new transaction …

Credorax: Add referral CTF transactions

---

CHANGELOG
lib/active_merchant/billing/gateways/d_local.rb
test/remote/gateways/remote_d_local_test.rb

DLocal has updated its Auth/Capture flow, now accepting captures at a
new endpoint. It has also changed to use an authorization_id parameter
for referencing Authorize transactions (needed in capture and void
requests).
Remote:
26 tests, 69 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
100% passed
ECS-565

DLocal: Updates for version 2.1

---

CHANGELOG
lib/active_merchant/billing/gateways/cyber_source.rb

Fixes an XML parsing error in `capture` requests on CyberSource.
In [a previous commit](https://github.com/activemerchant/active_merchant/commit/35b5dd95db0252c7b98d8411fd3adb50fc266eb8),
the `add_mdd_fields` method was added to `capture` transaction requests.
However, these fields are required to be passed in a specific location
within the XML request sent to the CyberSource gateway.
This commit moves the `add_mdd_fields` method within `capture` to the
correct location for XML parsing by the CyberSource gateway.
CE-234
Unit:
64 tests, 310 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
Remote:
65 tests, 278 assertions, 5 failures, 0 errors, 0 pendings, 0 omissions,
92.3077% passed
The 5 remote failures are previously existing and …

CyberSource: Fix XML error on capture

---

CHANGELOG
lib/active_merchant/billing/gateways/adyen.rb
test/unit/gateways/adyen_test.rb

Added the `splits` gateway specific field to the Adyen gateway.
For more details, see the Adyen documentation:
[Adyen API Reference](https://docs.adyen.com/api-explorer/#/PaymentSetupAndVerificationService/v50/payments__reqParam_splits)
[Adyen MarketPlace information about splits](https://docs.adyen.com/marketpay/processing-payments#providing-split-information)
CE-220
Unit:
51 tests, 243 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
Remote:
73 tests, 234 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions,
97.2603% passed
The two failing remote tests are
- `test_successful_purchase_with_auth_data_via_threeds1_standalone`
- `test_successful_purchase_with_auth_data_via_threeds2_standalone`
These have been failing for a while and …

Adyen: Add gateway specific field for splits

---

test/remote/gateways/remote_borgun_test.rb

Takes failures from 9 down to 1, failing test follows expected behavior
described in the comment.
Remote:
20 tests, 45 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
95% passed

Borgun: Update card for remote tests

---

lib/active_merchant/billing/gateways/adyen.rb
test/remote/gateways/remote_adyen_test.rb

The store action currently uses the /authorise endpoint when executing
the store call. While Adyen does return the recurringDetailReference in
the authorize response, there are some drawbacks to using this endpoint
if you are looking for a pure tokenize call to store payment details at
Adyen with no additional side effects.
1. The /authorise endpoint will run a full authorization at the issuing
bank meaning the authorize request itself could fail preventing a full
tokenize at Adyen despite there being nothing inherently wrong with the
card itself.
2. It's possible for a response from the authorize call to respond with
a 3DS flow which would be suboptimal if you're not interested in doing
that at the particular time of storing the card.
This PR is meant to be a starting point for iteration …

Adyen: Allow the use of the storeToken endpoint for store

---

CHANGELOG
lib/active_merchant/billing/gateways/barclaycard_smartpay.rb
test/remote/gateways/remote_barclaycard_smartpay_test.rb
test/unit/gateways/barclaycard_smartpay_test.rb

As a whitelabel of Adyen, Barclay also allows you to request
exemptions directly via the api. Updates the gateway to permit
`sca_exemption` option that will be populated for 3DS2 txns where
`execute_threed` option is passed.
Unit
34 tests, 167 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote
38 tests, 98 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
(unrelated preexisting failure: test_successful_third_party_payout)

Barclaycard Smartpay: Allow direct exemption requests

---

CHANGELOG
lib/active_merchant/billing/gateways/cyber_source.rb
test/unit/gateways/cyber_source_test.rb

We've had some cases where email ends up being sent as empty string and it causes the following error `missingField: c:billTo/c:email`. The current logic only checks for its existence, not for its value.
We should use `null@cybersource.com` for both `nil` and `""`.

Use null@cybersource.com when option[:email] is an empty string

---

CHANGELOG
lib/active_merchant/billing/gateways/adyen.rb
test/unit/gateways/adyen_test.rb

CE-233
Unit: 55 tests, 259 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 75 tests, 248 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
97.3333% passed 
Remote failures: 
test_successful_purchase_with_auth_data_via_threeds2_standalone
test_successful_purchase_with_auth_data_via_threeds1_standalone
Both fail on `assert_equal 'true', auth.params['additionalData']['liabilityShift']` with `<"true"> expected but was <nil>`, which I think is a familiar behavior.

Adyen: add recurring_contract_type GSF

---

CHANGELOG
lib/active_merchant/billing/gateways/credorax.rb
test/remote/gateways/remote_credorax_test.rb
test/unit/gateways/credorax_test.rb

Credorax 3DS requests are erroring with the message "At least 
one of input parameters is malformed. Parameter 3ds_version is
invalid.". We've been informed that you should not pass
`3ds_version` as part of the original transaction request, and
that the correct version will be returned in your response. You
only need to send it when a 92 needs to be triggered (three ds
completion) or when you're sending an i8 param in your original
request. This PR removes 3ds_version from the original request
where i8 is not passed.
Some updates to tests were also required. It appears that this
behavior is somewhat new, as the 3DS2 tests now fail without this
change. Additionally, the test card doesn't proceed to direct 
success as seemed to have been the case before based on the 
existing test; instead …

Credorax: Don't pass 3ds_version in initial 3ds request

---

CHANGELOG
lib/active_merchant/billing/credit_card.rb
lib/active_merchant/billing/credit_card_methods.rb
lib/active_merchant/billing/gateways/adyen.rb
lib/active_merchant/billing/gateways/redsys.rb
test/remote/gateways/remote_adyen_test.rb
test/remote/gateways/remote_redsys_sha256_test.rb
test/unit/credit_card_methods_test.rb
test/unit/gateways/adyen_test.rb
test/unit/gateways/redsys_sha256_test.rb
test/unit/gateways/redsys_test.rb

Added the UnionPay card type with support on Adyen and Redsys gateways.
Prior to adding UnionPay, cards that start with 62 were all classified
as Discover. Because UnionPay cards are able to run on Discover rails,
this was kept the same.
Unit and remote tests were added for UnionPay card numbers on Adyen.
UnionPay test card numbers aren't available for Redsys, so the new card
type hasn't yet been tested on this gateway. The changes made to the
Redsys remote test are simple cleanup to add a missing instance
variable.
CE-279 / CE-262
4382 tests, 71190 assertions, 0 failures, 0 errors, 0 pendings,
100% passed
Adyen unit tests:
56 tests, 263 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
Redsys SHA1 unit …

Add UnionPay card type

---

CHANGELOG
lib/active_merchant/billing/gateways/braintree_blue.rb
test/remote/gateways/remote_braintree_blue_test.rb

add_credit_card_to_customer method was assigning billing_address to
credit_card before credit_card existed. This issue was exposed through a
customer bug, and tests never actually tested the if options[:billing_address]
scenario.
Unit:
75 tests, 176 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
80 tests, 435 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
ECS-910

Braintree: Fix add_credit_card_to_customer in Store

---

CHANGELOG
lib/active_merchant/billing/gateways/ebanx.rb
test/remote/gateways/remote_ebanx_test.rb
test/unit/gateways/ebanx_test.rb

ECS-872/ECS-929
https://developers.ebanx.com/api-reference/ebanx-payment-api/payment-reference/reference-capture-operation/
Per Ebanx documentation: “You can make only one partial capture per authorized
payment and this feature is only available in Brazil. If you want to enable
this feature, please contact our Integration Team.”
1. Ebanx will capture full amount authorized if no amount is included in
the capture request. Adds a flag for including the amount only in the
case of partial capture.
2. Update tests for new error messages and handling of partial capture
Unit:
17 tests, 59 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
22 tests, 63 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Ebanx: Update capture method

---

lib/active_merchant/billing/gateways/adyen.rb
test/remote/gateways/remote_adyen_test.rb
test/unit/gateways/adyen_test.rb

Update so that Response responds correctly to success? when an unstore (disable) is performed successfully.
Unit tests:
56 tests, 264 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote tests:
81 tests, 271 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
97.5309% passed
_(2 failures were pre-existing:  test_successful_purchase_with_auth_data_via_threeds1_standalone, test_successful_purchase_with_auth_data_via_threeds2_standalone)_

Adyen: Set response success for unstore

---

CHANGELOG
lib/active_merchant/billing/gateways/cyber_source.rb
test/remote/gateways/remote_cyber_source_test.rb
test/unit/gateways/cyber_source_test.rb

Adds:
invoiceHeader.merchantDescriptor, available for auth, capture, and credit
installment.totalCount, available for auth
othertax.localTaxAmount
othertax.nationalTaxAmount, available for capture
I'm not super happy with what's happening to `add_payment_method_or_subscription` but don't have great ideas for an obvious refactor. 
CE-263

Cybersource: add GSFs

---

CHANGELOG

The fix was previously committed: cb4e18b356fe934746555e86dfae75a939f187d2

Fix changelog for fixing adyen response success for unstore

---

CHANGELOG
lib/active_merchant/billing/gateways/adyen.rb
test/unit/gateways/adyen_test.rb

Unit: 
57 tests, 267 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
81 tests, 271 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
97.5309% passed
Failures on 3DS (1 and 2) purchase_with_auth_data attempts.

Adyen: add recurring_contract_type to auth

---

CHANGELOG
lib/active_merchant/billing/gateways/stripe_payment_intents.rb
test/remote/gateways/remote_stripe_payment_intents_test.rb

localized_amount method for formatting non-fractional currencies was
used on authorize, but not capture, leading to capture requests for
larger amounts than authorized.
Unit:
100% passed
Remote:
30 tests, 123 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
ECS-939

Stripe Payment Intents: Use localized_amount on capture

---

CHANGELOG
lib/active_merchant/billing/gateways/merchant_warrior.rb
test/remote/gateways/remote_merchant_warrior_test.rb
test/unit/gateways/merchant_warrior_test.rb

This addes the `void` operation to the Merchant Warrior gateway along
with unit and remote tests.
Adding support for this operation required switching to a new provider,
which required new test card numbers to be used.
CE-294
Unit:
12 tests, 73 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
Remote:
13 tests, 66 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed

Merchant Warrior: Add void operation

---

CHANGELOG
lib/active_merchant/billing/gateways/decidir.rb
test/remote/gateways/remote_decidir_test.rb
test/unit/gateways/decidir_test.rb

Fixed a bug in which existing supported card types were not assigned the
correct payment method ID.
CE-315
Unit:
28 tests, 124 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
Remote:
21 tests, 70 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions,
95.2381% passed
The remote failure is a `504 Gateway Timeout` error. This doesn't seem
like an issue, although it is consistently happening for the same remote
test: `test_successful_purchase_with_amex`.
4385 tests, 71204 assertions, 0 failures, 0 errors, 0 pendings,
100% passed

Decidir: Update payment method IDs

---

lib/active_merchant/billing/gateways/adyen.rb
test/unit/gateways/adyen_test.rb

Added the `deliveryAddress` hash to the Adyen gateway using the existing
Active Merchant standard `shipping_address` hash.
Expanded an exising unit test to include tests for `deliveryAddress` in
a request; no additional remote tests were added since the delivery
address is not a required field and is not included in responses.
CE-295
Unit:
56 tests, 270 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
Remote:
81 tests, 271 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions,
97.5309% passed
4391 tests, 71246 assertions, 0 failures, 0 errors, 0 pendings,
100% passed
RuboCop:

Adyen: Add delivery address

---

CHANGELOG
lib/active_merchant/billing/gateways/authorize_net.rb
test/unit/gateways/authorize_net_test.rb

Some transactions are getting marked as failures due to improper
parsing when there are quotes in direct_response field. PR removes
extra quotes from `direct_response` field so that separate delimited
fields can be correctly parsed.
Unit:
97 tests, 575 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
69 tests, 238 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Auth.net: Ensure proper parsing when quotes in direct_response

---

CHANGELOG
lib/active_merchant/billing/gateways/decidir.rb
test/unit/gateways/braintree_blue_test.rb
test/unit/gateways/decidir_test.rb

Adds the correct `payment_method_id` value for the four debit cards that
Decidir supports. These are selected by passing the new `debit` GSF.
CE-308
Unit:
32 tests, 136 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
Remote:
21 tests, 70 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions,
95.2381% passed
The `test_successful_purchase_with_amex` remote test is failing with a
gateway timeout error.

Decidir: Add debit card payment method IDs

---

CHANGELOG
lib/active_merchant/billing/gateways/cyber_source.rb
test/remote/gateways/remote_cyber_source_test.rb
test/unit/gateways/cyber_source_test.rb

Added the existing `issuer_additional_data` and `merchantDefinedData`
gateway specific fields in the CyberSource gateway to `credit` and
`void` transactions.
CE-293
Unit:
74 tests, 340 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
Remote:
74 tests, 377 assertions, 5 failures, 0 errors, 0 pendings, 0 omissions,
93.2432% passed
Unrelated and existing failing remote tests:
- `test_successful_3ds_validate_authorize_request`
- `test_successful_3ds_validate_purchase_request`
- `test_successful_pinless_debit_card_puchase`
- `test_successful_validate_pinless_debit_card`
- `test_successful_tax_calculation`

CyberSource: Add issuer data+MDD to credit & void

---

CHANGELOG
lib/active_merchant/billing/gateways/card_stream.rb
test/remote/gateways/remote_card_stream_test.rb
test/unit/gateways/card_stream_test.rb

Zero-decimal currencies were being handled in an unexpected way on
Cardstream compared to other gateways. For instance, whereas we
expect a merchant to pass in an amount like 100 to be charged 1
JPY, this gateway processes this as though it's a charge of 100 JPY. 
This PR uses localized_amount to divide the value by 100 before 
passing along to the gateway. The gateway does not support any 
three-decimal currencies, so this PR does not try to test those 
scenarios.
This gateway also had quite a few failing tests due to cc year,
updated error messages and some duplicate transaction handling.
These are also updated in this PR. The tests are still somewhat
temperamental in that you'll sometimes get a timeout, but that
does not appear to be related to these updates as it's a different
test or …

Cardstream: Localize zero-decimal currencies

---

CHANGELOG
lib/active_merchant/billing/gateways/ebanx.rb
test/remote/gateways/remote_ebanx_test.rb

Added the `device_id` gateway specific field to purchase requests
on the EBANX gateway. In addition, added this new field to the
remote gateway tests to ensure that it is working correctly.
Similiar to [a previous commit](https://github.com/activemerchant/active_merchant/commit/7ec0f94c5794592a16bfaaa7280fbf1b853e8afd),
also updated the sandbox gateway response for one of the remote tests to
`Accepted`.
[ECS-966](https://spreedly.atlassian.net/browse/ECS-966)
Unit:
17 tests, 59 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
Remote:
22 tests, 63 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
4411 tests, 71319 assertions, 0 failures, 0 errors, 0 pendings, 2
100% passed

EBANX: Add additional data in post

---

CHANGELOG
lib/active_merchant/billing/gateways/credorax.rb
test/unit/gateways/credorax_test.rb

Sending Credorax an empty phone number parameter is causing transactions
to fail. To fix this, additional `if` statements have been added to the
address to ensure that only those `billing_address` parameters that
exist are sent to the gateway.
[CE-307](https://spreedly.atlassian.net/browse/CE-307)
Unit:
62 tests, 298 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
Remote:
39 tests, 144 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
4410 tests, 71318 assertions, 0 failures, 0 errors, 0 pendings, 2
100% passed

Credorax: Omit phone when nil

---

CHANGELOG
lib/active_merchant/billing/gateways/trans_first_transaction_express.rb
test/unit/gateways/trans_first_transaction_express_test.rb

The TransFirst Transaction Express gateway cannot handle hyphens
included in the zip code. This change strips any hyphens from the zip
code before sending it to the gateway.
[CE-328](https://spreedly.atlassian.net/browse/CE-328)
Unit:
22 tests, 106 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
Remote:
33 tests, 107 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions,
Seemingly unrelated failing test: `test_successful_verify`
4409 tests, 71312 assertions, 0 failures, 0 errors, 0 pendings, 2
100% passed

TransFirst TrExp: Remove hyphens from zip

---

.rubocop_todo.yml
CHANGELOG
lib/active_merchant/billing/gateways/migs/migs_codes.rb

Fixes the Rubocop todo item that enforces spacing within arrays created
using percent literals.
4408 tests, 71309 assertions, 0 failures, 0 errors, 0 pendings,
100% passed

Rubocop: Layout/SpaceInsideArrayPercentLiteral fix

---

.rubocop_todo.yml
CHANGELOG
lib/active_merchant/billing/avs_result.rb
lib/active_merchant/billing/gateways/blue_pay.rb
lib/active_merchant/billing/gateways/efsnet.rb
lib/active_merchant/billing/gateways/eway_managed.rb
lib/active_merchant/billing/gateways/metrics_global.rb
lib/active_merchant/billing/gateways/omise.rb
lib/active_merchant/billing/gateways/orbital.rb
lib/active_merchant/billing/gateways/pay_gate_xml.rb
lib/active_merchant/billing/gateways/payment_express.rb
lib/active_merchant/billing/gateways/plugnpay.rb
lib/active_merchant/billing/gateways/quickpay/quickpay_common.rb
lib/active_merchant/billing/gateways/secure_net.rb
lib/active_merchant/billing/gateways/secure_pay.rb
lib/active_merchant/billing/gateways/skip_jack.rb
lib/active_merchant/billing/gateways/stripe_payment_intents.rb
lib/active_merchant/billing/gateways/swipe_checkout.rb
lib/active_merchant/billing/gateways/usa_epay_advanced.rb
lib/active_merchant/billing/gateways/wirecard.rb
test/unit/gateways/omise_test.rb

Fixes the RuboCop todo item that enforces no extra spaces inside the
delimeters of `%i`, `%w`, and `%x` literals.
4408 tests, 71309 assertions, 0 failures, 0 errors, 0 pendings,
100% passed

RuboCop: Layout/SpaceInsidePercentLiteralDelimiter

---

CHANGELOG
lib/active_merchant/billing/gateways/mundipagg.rb
test/unit/gateways/mundipagg_test.rb

When the Mundipagg gateway response includes an `acquirer_return_code`,
it will now be returned as the `error_code` in the main response.
The `acquirer_message` was already being returned as the `message` in
the main response, so this change will provide more information for
troubleshooting to supplement the existing format.
Some changes were made to existing unit tests in order to make this
update. Two of the unit tests designed to test failure messages were
expecting `processing_error` as the `error_code`, which doesn't seem
correct. Therefore, these tests were updated to expect the
`acquirer_return_code` as the `error_code`.
[CE-264](https://spreedly.atlassian.net/browse/CE-264)
Unit:
27 tests, 119 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed …

Mundipagg: Return acquirer code as the error code

---

lib/active_merchant/billing/gateways/braintree_blue.rb
test/unit/gateways/braintree_blue_test.rb

When processing 3DS based requests there is a need to create a transaction
using a payment method nonce that is generated on the client. To facilitate that
need and keep existing behaviors with payment method nonces, a check for a
string based payment method nonce was added right before finalizing sale
parameters. If the payment method nonce is a string, the customer hash will be
removed since there should already be a customer in Braintree's system.
For further information regarding the need to use a client payment method nonce,
please check here: https://developers.braintreepayments.com/guides/3d-secure/server-side/ruby
Unit:
77 tests, 178 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
80 tests, 435 assertions, 0 failures, 0 errors, 0 …

Remove customer hash when using a payment_method_nonce

---

CHANGELOG
lib/active_merchant/billing/gateways/credorax.rb
test/remote/gateways/remote_credorax_test.rb
test/unit/gateways/credorax_test.rb

ECS-978
Per Credorax's latest [API docs](https://epower.credorax.com/wp-content/uploads/2019/11/Credorax-Source-Payment-API-Specifications-v1.3-.pdf),
their zero-decimal and three-decimal currencies list have changed:
- Add BIF, DJF, GNF, KMF, RWF, VUV, XAF, XOF, & XPF to the `currencies_without_fractions`
list
- Add IQD & LYD and remove RSD from the `currencies_with_three_decimal_places`
list
Some remote tests may fail due to Credorax's remote server timing out, thus
not related to these updates. The specific tests failing or error'ing may
change with each run.
Unit:
63 tests, 301 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
40 tests, 147 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Credorax: Update non-standard currencies list

---

.rubocop_todo.yml
CHANGELOG
lib/active_merchant/billing/gateways/optimal_payment.rb

Fixes the RuboCop todo that enforces that layout of the closing brace in
a multiline array literal.
[RuboCop](https://www.rubocop.org/en/stable/cops_layout/#layoutmultilinearraybracelayout)
4414 tests, 71334 assertions, 0 failures, 0 errors, 0 pendings, 2
100% passed

RuboCop: Fix Layout/MultilineArrayBraceLayout

---

CHANGELOG
lib/active_merchant/billing/gateways/redsys.rb

Redsys has notified us that the connection URL, https://sis.sermepa.es/,
is obsolete and will be cut in the coming weeks, and that we should
switch over to https://sis.redsys.es/ (replacing sermepa with redsys).
This PR updates the live_url to reflect this.
Unit:
36 tests, 112 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
100% passed

Redsys: Update production URL

---

CHANGELOG
lib/active_merchant/billing/gateways/clearhaus.rb
test/remote/gateways/remote_clearhaus_test.rb
test/unit/gateways/clearhaus_test.rb

ECS-977
Per Clearhaus' latest [API docs](https://docs.gateway.clearhaus.com/currencies.txt),
their zero-decimal currencies list have changed:
- Add CLP & UGX and remove BYR from the `currencies_without_fractions` list
Unit:
23 tests, 113 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
24 tests, 73 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Clearhaus: Update currencies without fractions list

---

CHANGELOG
lib/active_merchant/billing/gateways/merchant_warrior.rb
test/remote/gateways/remote_merchant_warrior_test.rb
test/unit/gateways/merchant_warrior_test.rb

The Merchant Warrior gateway does not support the `recurringFlag` field which is used to indicate if a transaction will be marked as recurring.
- https://dox.merchantwarrior.com/#processcard3162
- https://dox.merchantwarrior.com/#processauth3163
- CE-348
- Added support for the `recurringFlag` field via a `recurring_flag` option on the `process` and `authorize` functions
- Added missing unit test for Merchant Warrior `authorize` function
Unit:
```
17 tests, 92 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
```
Remote:
```
15 tests, 81 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
```

Merchant Warrior: Add recurringFlag to purchase & authorize

---

test/remote/gateways/remote_data_cash_test.rb

There were a few existing errors when trying to run DataCash remote
tests. Updates these tests to passing.
Remote:
29 tests, 90 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
14 tests, 34 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

DataCash: Fix remote tests

---

lib/active_merchant/billing/gateways/paymentez.rb
test/remote/gateways/remote_paymentez_test.rb
test/unit/gateways/paymentez_test.rb

- Per the Paymentez docs, the refund action response has a different shape than other responses from this gateway: https://paymentez.github.io/api-doc/#payment-methods-cards-refund
```json
{"status": "success", "detail": "Completed"}
```
- ActiveMerchant parses the success field of these messages correctly, but not the messages.
- Success field: https://github.com/activemerchant/active_merchant/blob/cee8dff883dfcfd0e64e10d189a443eee0aac82f/lib/active_merchant/billing/gateways/paymentez.rb#L232-L234
- Message field: https://github.com/activemerchant/active_merchant/blob/cee8dff883dfcfd0e64e10d189a443eee0aac82f/lib/active_merchant/billing/gateways/paymentez.rb#L243-L249
- Changed the Paymentez unit test void/refund payload shape to match the specs.
- Added checks on Paymentez unit and …

Paymentez: Correct refund and void message parsing

---

lib/active_merchant/billing/gateways/mercado_pago.rb
test/remote/gateways/remote_mercado_pago_test.rb
test/unit/gateways/mercado_pago_test.rb

- For Colombian users to supply IVA tax information to Mercado Pago, support is required for the `taxes` and `net_amount` fields on purchase requests. 
- https://www.mercadopago.com.co/developers/en/guides/localization/iva-colombia/
- CE-365
- Added support for `taxes` and `net_amount` fields on the Mercado Pago gateway. These optional fields allow Colombian users to add IVA tax information to transactions. 
- The `taxes` field has support for a single tax object or an array of tax objects to better support upstream XML representation of this field.
Unit:
```
4433 tests, 71395 assertions, 0 failures, 0 errors, 0 pendings, 2 omissions, 0 notifications
100% passed
```
Remote:
```
31 tests, 93 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
93.5484% passed
``` …

Mercado Pago: Add taxes and net_amount gateway specific fields

---

CHANGELOG
lib/active_merchant/billing/gateways/authorize_net.rb
test/unit/gateways/authorize_net_test.rb

There was a request that we remove all countries except United States,
Canada, and Australia from Authorize.net gateway guide
- https://docs.spreedly.com/payment-gateways/authorize-net/
This is due to PSD2/SCA in Europe. Authorize.net will not add any new customers for the countries being removed because they won't support SCA.
This [change will only affect documentation](https://github.com/activemerchant/active_merchant/wiki/Contributing#setting-the-gateways-metadata).
CE-368
```
rake TEST=test/unit/gateways/authorize_net_test.rb
97 tests, 575 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
```
```
4435 tests, 71401 assertions, 0 failures, 0 errors, 0 pendings, 2 omissions, 0 notifications
100% passed
```
I ran this twice. The first …

Authorize.Net: Remove supported countries except for AU CA US

---

CHANGELOG
lib/active_merchant/billing/gateways/credorax.rb
test/unit/gateways/credorax_test.rb

This is the start of an effort to create an escape hatch to allow folks to add
additional request data when creating 3DS 2 based transactions. Credorax is the
first gateway to leverage the change. I had added more gateways, but complexity
grew quickly when doing so.
usage summary:
When creating a 3DS 2 based authorization or purchase, if the option `{ three_ds_2: { optional: { ... } }`
is provided, all fields inside of the optional hash will be applied to the post
body root.
example
```rb
options = {
three_ds_2: {
optional: {
a: 1,
b: 2
}
}
}
credorax.purchase(amount, payment_method, options)
...
post data will look like:
{
...existing_post_data,
a: 1,
b: 2
}
```
In addition to the change, the signing of the credorax request body no longer fails with frozen strings. Checkout unit tests on …

Allow optional fields in 3DS 2 based transactions

---

README.md

There was a request that we remove all countries except United States,
Canada, and Australia from Authorize.net
This is due to PSD2/SCA in Europe. Authorize.net will not add any new customers for the countries being removed because they won't support SCA. More [details can be found on their site](https://www.authorize.net/en-gb/).
This PR only affects the README, and keeps Authorize.net's list of supported countries consistent with the changes made in #3511 
[CE-382](https://spreedly.atlassian.net/browse/CE-382)

Authorize.net: Trim supported countries to AU, CA, US in README

---

lib/active_merchant/billing/gateways/bpoint.rb
test/remote/gateways/remote_bpoint_test.rb
test/unit/gateways/bpoint_test.rb

The `void` method for the BPoint gateway was previously implemented
incorrectly. Throughout Active Merchant, gateway `void` requests are
passed only an authorization number for the original transaction and an
options hash. However, for BPoint, the `void` method was also passed an
explicit `amount`. Due to the implementations on top of Active Merchant,
this was causing issues for Spreedly customers.
The BPoint `void` method has been rewritten to take in only
`authorization` and an `options` hash. Because the BPoint gateway
requires the amount to be sent on void transactions, this value should
be sent within the `options` hash with the key `amount`.
CE-338
Unit:
19 tests, 63 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
Remote:
18 tests, 41 …

BPoint: Remove amount from void requests

---

CHANGELOG
lib/active_merchant/billing/gateways/worldpay.rb

When building an XML request, the `.tag!` method is only required if the
XML tag is a non-standard string, e.g., if it contains a hyphen or a
colon. Therefore, this method is often not needed and can be replaced
with a far more concise version.
This commit removes all unnecessary `.tag!` method calls for the
Worldpay gateway to improve the readability of the code.
Unit:
69 tests, 411 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
Remote:
56 tests, 240 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions,
96.4286% passed
4426 tests, 71371 assertions, 0 failures, 0 errors, 0 pendings, 2
100% passed

Worldpay: Remove unnecessary .tag! methods

---

CHANGELOG
lib/active_merchant/billing/gateways/stripe_payment_intents.rb
test/remote/gateways/remote_stripe_payment_intents_test.rb
test/unit/gateways/stripe_payment_intents_test.rb

Indian Stripe Payment Intents users must specify their transaction as
`cross_border_classification: "export"` in order to sell to customers
outside of India.
[CE-358](https://spreedly.atlassian.net/browse/CE-358)
Adds the ability to specify a Stripe Payment Intent `cross_border_classification`. This must be set to "export" to sell to customers outside of India.
If this parameter is blank or set to "domestic", then it will be
treated as a domestic transaction.
**Note:** this parameter seems like it might only be allowed for Indian Stripe users. When I send the `cross_border_classification` parameter through, I get back the error:
```
Received unknown parameter: cross_border_classification
```
For now, I've commented out the remote test that sends this parameter.
I'm in touch with Stripe …

Stripe Payment Intents: Allow cross_border_classification parameter

---

CHANGELOG
lib/active_merchant/billing/gateways/ebanx.rb
test/unit/gateways/ebanx_test.rb

Per EBANX, the `integration_key` can include digits and letters. This
change ensures the full value is properly scrubbed from the transcript.
Unit:
17 tests, 59 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
22 tests, 63 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

EBANX: Fix `scrub`

---

CHANGELOG
lib/active_merchant/billing/gateways/worldpay.rb
test/remote/gateways/remote_worldpay_test.rb
test/unit/gateways/worldpay_test.rb

* These fields will be needed for Worldpay 3DS2 for frictionless flow. This the requires adding the `<riskData>` field, which contains three child elements: `<authenticationRiskData>`, `<shopperAccountRiskData>`, and `<transactionRiskData>`.
* By providing additional information in the <riskData> element, this lowers the chance that the shopper will be challenged.
* [Relevant Worldpay docs](https://beta.developer.worldpay.com/docs/wpg/directintegration/3ds2#initial-xml-payment-request)
* CE-371
- Add support for `riskData` element (and child elements) for the Worldpay gateway.
```
4441 tests, 71464 assertions, 0 failures, 0 errors, 0 pendings, 2 omissions, 0 notifications
100% passed
```
Gateway-specific Unit Test:
```
rake TEST=test/unit/gateways/worldpay_test.rb
70 …
```

Worldpay: Add riskData support

---

CHANGELOG
lib/active_merchant/billing/gateways/stripe_payment_intents.rb
test/remote/gateways/remote_stripe_payment_intents_test.rb
test/unit/gateways/stripe_payment_intents_test.rb

This parameter wasn't able to be tested through our test account,
and the merchant who was going to test it in production is
no longer with our customer.
Also, I was unable to find documentation of this parameter
beyond a Word doc that the customer sent us.
CE-196
```
rake TEST=test/unit/gateways/stripe_payment_intents_test.rb
100% passed
```
```
rake TEST=test/remote/gateways/remote_stripe_payment_intents_test.rb
30 tests, 123 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
```
Failing test also fails on `master`:
* test_create_payment_intent_that_saves_payment_method

Revert Stripe Payment Intents GSF "cross_border_classification"

---

CHANGELOG
lib/active_merchant/billing/gateways/paypal/paypal_common_api.rb
test/remote/gateways/remote_paypal_test.rb
test/unit/gateways/paypal/paypal_common_api_test.rb

ECS-986
Possible `nil` or blank values in the `subtotal`, `shipping`, `handling`,
or `tax` fields will cause the `localized_amount` method to break causing
`NoMethodError`.
This change requires for the affected fields to have a value before being
evaluated.
Unit:
19 tests, 38 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
29 tests, 81 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Paypal: Fix OrderTotal elements in `add_payment_details`

---

CHANGELOG
lib/active_merchant/billing/gateways/decidir.rb
test/remote/gateways/remote_decidir_test.rb
test/unit/gateways/decidir_test.rb

Add support for additional gateway-specific fields for Decidir:
Also, fixed some remote Decidir tests that weren't quite doing what they seemed to be doing.
* `fraud_detection` can be set to help control if a transaction is sent for fraud review. 
* `establishment_name` is a merchant soft descriptor.
* `site_id` helps link the transaction to a specific trade account, as a business may have multiple trade accounts with Decidir.
CE-340
CE-357
CE-380
```
4444 tests, 71479 assertions, 0 failures, 0 errors, 0 pendings, 2 omissions, 0 notifications
100% passed
```
```
rake TEST=test/unit/gateways/decidir_test.rb
32 tests, 139 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
```
```
rake TEST=test/remote/gateways/remote_decidir_test.rb
21 …
```

Decidir: Add support for establishment_name, site_id, and fraud_detection

---

CHANGELOG
lib/active_merchant/billing/gateways/stripe.rb
lib/active_merchant/billing/gateways/stripe_payment_intents.rb
test/remote/gateways/remote_stripe_payment_intents_test.rb
test/remote/gateways/remote_stripe_test.rb
test/unit/gateways/stripe_payment_intents_test.rb
test/unit/gateways/stripe_test.rb

- https://stripe.com/docs/connect/required-updates/statement-descriptor-updates
- CE-419
Adds support for the `statement_descriptor_suffix` field on both the Stripe and the Stripe Payment Intents gateways.
Stripe Remote Tests
```
68 tests, 315 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
```
Stripe Payment Intents Remote Tests
```
30 tests, 130 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
```
Unit Tests
```
4446 tests, 71482 assertions, 0 failures, 0 errors, 0 pendings, 2 omissions, 0 notifications
100% passed
```

Stripe: Add support for `statement_descriptor_suffix` field

---

CHANGELOG
lib/active_merchant/billing/gateways/merchant_warrior.rb
test/remote/gateways/remote_merchant_warrior_test.rb
test/unit/gateways/merchant_warrior_test.rb

The `void` method for the Merchant Warrior gateway was previously
implemented incorrectly. Throughout Active Merchant, gateway `void`
requests are passed only an authorization number for the original
transaction and an options hash. However, for Merchant Warrior, the void
method was also passed an explicit amount. Due to the implementations on
top of Active Merchant, this was causing issues for Spreedly customers.
The Merchant Warrior `void` method has been rewritten to take in only
authorization and an options hash. Because the Merchant Warrior gateway
requires the amount to be sent on void transactions, this value should
be sent within the `options` hash with the key `amount`.
In addition, the required verification hash for `void` transactions
should consist of the original transaction …

Merchant Warrior: Send void amount in options

---

CHANGELOG
lib/active_merchant/billing/gateways/authorize_net.rb
test/remote/gateways/remote_authorize_net_test.rb
test/unit/gateways/authorize_net_test.rb

https://developer.authorize.net/api/reference/features/echeck.html
A Spreedly customer reported notifications from Authorize.Net that a
savings account transaction was processed as a checking account transaction.
Authorize.Net requires `accountType` to be passed for `eCheck` transactions
in order for proper reporting and to avoid these type of notifications.
Though these `eCheck` transactions have been successful without the `accountType`
field being passed, the customer would like the notifications to stop.
Unit:
98 tests, 584 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
70 tests, 242 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
4447 tests, 71494 assertions, 0 failures, 0 errors, 0 …

Authorize.Net: Pass `account_type` to `check` payment types

---

CHANGELOG
lib/active_merchant/billing/gateways/stripe.rb
lib/active_merchant/billing/gateways/stripe_payment_intents.rb
test/remote/gateways/remote_stripe_payment_intents_test.rb
test/remote/gateways/remote_stripe_test.rb
test/unit/gateways/stripe_payment_intents_test.rb
test/unit/gateways/stripe_test.rb

Stripe has changed the fields that are supported/required for Connect transactions.
- Adds support for the following fields on the Stripe gateway for Connect transactions:
- `transfer_data[amount, destination]`
- `on_behalf_of`
- `transfer_group`
- `application_fee_amount`
- Adds support for the following fields on the Stripe Payment Intents gateway:
- `application_fee_amount` - this was already supported via `application_fee`, this change adds support for its proper name while retaining support for its original one
This was done by moving the `add_connected_account` function from the Stripe Payment Intents gateway to the Stripe gateway which it inherits from. One change had to be made to the implementation: since the Stripe Payment Intents gateway called the `application_fee_amount` …

Stripe: Add connected account support

---

CHANGELOG
lib/active_merchant/billing/gateways/bambora_apac.rb
test/remote/gateways/remote_bambora_apac_test.rb
test/unit/gateways/bambora_apac_test.rb

The `void` method for the Bambora Apac gateway was previously
implemented incorrectly. Throughout Active Merchant, gateway `void`
requests are passed only an authorization number for the original
transaction and an options hash. However, for Bambora Apac, the void
method was also passed an explicit amount. This break in the established
pattern was causing issues for implementations on top of Active
Merchant.
The Bambora Apac `void` method has been rewritten to take in only
authorization and an options hash. Because the Bambora Apac gateway
requires the amount to be sent on void transactions, this value should
be sent within the `options` hash with the key `amount`.
CE-389
Unit:
7 tests, 48 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0
notifications
100% passed
Remote:
15 …

Bambora Apac: Send void amount in options

---

CHANGELOG
lib/active_merchant/billing/gateways/credorax.rb
test/unit/gateways/credorax_test.rb

ECS-938
https://epower.credorax.com/wp-content/uploads/2019/11/Credorax-Source-Payment-API-Specifications-v1.3-.pdf
The `3ds_transtype` parameter is incorrectly being set by the `transaction_type`
parameter which is meant for setting the `a9` parameter used for stored
credentials transactions and thus causing failed transactions with "At
least one of input parameters is malformed. Parameter 3ds_transtype is
invalid." error.
This change allows the `3ds_transtype` parameter to be explicitly set, otherwise
it defaults to "01"
Unit:
66 tests, 307 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
40 tests, 147 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
4446 tests, 71485 assertions, 0 …

Credorax: Fix `3ds_transtype` setting in post

---

CHANGELOG
lib/active_merchant/billing/gateways/redsys.rb
test/unit/gateways/redsys_sha256_test.rb

In some Redsys 3DS requests, the API will return `SIS0042`, which
signifies an error calculating the signature. After some testing,
this appears to be caused by special characters in various fields
of the request (in particular the `DS_MERCHANT_TITULAR` field).
Non-3DS requests escape the entire xml_request_from response, but
after testing the same approach for 3DS, that doesn't quite work
(you'll still end up with an encoding error after the first round of
3ds-related api requests). This PR updates to escape the cardholder
name when the transaction calls for 3DS to prevent such errors. It
also does the same thing for the description field as that seemed
like the most likely other place where a special character could
end up. I feel like there's probably a better way to do this, so if
you …

Redsys: Properly escape special characters in 3DS requests

---

CHANGELOG
test/remote/gateways/remote_stripe_payment_intents_test.rb
test/unit/gateways/stripe_payment_intents_test.rb

Add tests for "Idempotency-Key" header for Stripe Payment Intents.
This header is tested for Stripe, but had not yet been directly
tested for Stripe Payment Intents.
See documentation at:
https://stripe.com/docs/api/idempotent_requests
CE-394 > CE-431
Local
```
ruby -Ilib:test test/unit/gateways/stripe_payment_intents_test.rb
9 tests, 55 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
```
All local:
```
4455 tests, 71541 assertions, 0 failures, 0 errors, 0 pendings, 2 omissions, 0 notifications
100% passed
```
Remote
```
ruby -Ilib:test test/remote/gateways/remote_stripe_payment_intents_test.rb
32 tests, 139 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
96.875% passed
```
1 failed test that fails on …

Stripe Payment Intents: Add tests for idempotency_key header

---

CHANGELOG
test/remote/gateways/remote_paypal_test.rb
test/unit/gateways/paypal/paypal_common_api_test.rb

Exposed after commit [3540](https://github.com/activemerchant/active_merchant/pull/3540)
Unit:
19 tests, 38 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
29 tests, 81 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
4455 tests, 71541 assertions, 0 failures, 0 errors, 0 pendings, 2 omissions, 0 notifications
100% passed
RuboCop:

Paypal: Fix RuboCop Style/HashSyntax violations

---

CHANGELOG
lib/active_merchant/billing/gateways/safe_charge.rb

- The SafeCharge gateway was missing four countries in its `supported_countries` list.
Adds four supported countries to the SafeCharge gateway:
- Gibraltar (GI)
- Hong Kong (HK)
- Mexico (MX)
- Singapore (SG)
```
4455 tests, 71541 assertions, 0 failures, 0 errors, 0 pendings, 2 omissions, 0 notifications
100% passed
```

SafeCharge: Adds four supported countries

---

CHANGELOG
lib/active_merchant/billing/gateways/fat_zebra.rb
test/remote/gateways/remote_fat_zebra_test.rb
test/unit/gateways/fat_zebra_test.rb

ECS-890
Per Fat Zebra support, `is_billing` set to true is required for
successful tokenization of cards without CVV.
-Fixed a remote test and removed a `puts` statement
Unit:
20 tests, 105 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
25 tests, 89 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
4457 tests, 71551 assertions, 0 failures, 0 errors, 0 pendings, 2 omissions, 0 notifications
100% passed

Fat Zebra: Add `is_billing` in post for `store` call

---

CHANGELOG
lib/active_merchant/billing/gateways/ixopay.rb
test/remote/gateways/remote_ixopay_test.rb
test/unit/gateways/ixopay_test.rb

Implemented support for stored credentials on the Ixopay gateway.
Ixopay is slightly unusual in that it does not return a true
`network_transaction_id` and therefore this value cannot be sent on
subsequent transactions.
See [Ixopay's documentation on recurring transactions](https://gateway.ixopay.com/documentation/gateway#transaction-types)
as well as [an example recurring debit transaction](https://gateway.ixopay.com/documentation/direct-pci-enabled-api?xml#transactionwithcard-request-debit).
CE-161
Unit:
28 tests, 138 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
Remote:
23 tests, 95 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
4458 tests, 71557 assertions, 0 failures, 0 errors, 0 …

Ixopay: Support stored credentials

---

CHANGELOG
lib/active_merchant/billing/gateways/checkout_v2.rb
test/remote/gateways/remote_checkout_v2_test.rb

The response from Checkout direct 3DS requests often includes
the message "Unable to parse error message" because while the
transaction is pending, the existing fields we try to parse a
message from are not present. This PR updates the message_from
field to also check in the status field for a possible message
before using the default.
Remote:
32 tests, 77 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
27 tests, 120 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

CheckoutV2: Use status as message for 3DS txns in progress

---

CHANGELOG
lib/active_merchant/billing/gateways/stripe_payment_intents.rb
test/remote/gateways/remote_stripe_payment_intents_test.rb

Stripe Payment Intents supports the use of an idempotency key, but
that key can only be used against a single endpoint. Because the
Stripe PI flow can touch multiple different endpoints, we need to
ensure that it is slightly different across the different types
of requests to prevent errors. For instance, if the payment method
provided is a credit card, the adapter hits the payment method endpoint
to create that object before hitting the payment intent endpoint to
create the intent. This PR adds a method to add a suffix aligning to
request endpoints other than /payment_intents (e.g. a post to /payment_methods
would be <provided-key-pm> or a post to /payment_intents/intent-id/capture
would be <provided-key-capture>) to ensure that keys are unique but stable
across a request type. Also adds …

Stripe Payment Intents: Updates for idempotency key support

---

CHANGELOG
test/remote/gateways/remote_adyen_test.rb

In support of failover routing transaction cleanup, add tests for
voiding an authorization using the same idempotency key.
ERO-96
Unit:
58 tests, 275 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
84 tests, 305 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Adyen: Add tests for voiding with idempotency keys

---

CHANGELOG
lib/active_merchant/billing/gateways/fat_zebra.rb
test/remote/gateways/remote_fat_zebra_test.rb
test/unit/gateways/fat_zebra_test.rb

Related to https://github.com/activemerchant/active_merchant/pull/3551
Use the existing `recurring` flag to set the `is_billing` requirement
from the gateway. `recurring` set to true will allow `store` calls to succeed
without a CVV.
Unit:
20 tests, 105 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
25 tests, 89 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
4464 tests, 71595 assertions, 0 failures, 0 errors, 0 pendings, 2 omissions, 0 notifications
100% passed

Fat Zebra: Fix `store` call

---

CHANGELOG
lib/active_merchant/billing/gateways/adyen.rb
test/remote/gateways/remote_adyen_test.rb
test/unit/gateways/adyen_test.rb

ECS-1016
https://docs.adyen.com/checkout/tokenization
`shopperInteraction` possible values:
* `Ecommerce`: Transactions where shoppers enter their card details.
* `ContAuth`: Transactions using previously stored card details, which
include the card number and card expiry date.
`recurringProcessingModel` possible values:
* `Subscription`: A series of transactions with fixed or variable amounts,
following a fixed time interval.
* `CardOnFile`: Transactions where a shopper stores card details, and
transactions where the shopper purchases from your website or app at a
later time using the previously stored card details
* `UnscheduledCardOnFile`: Contracts that occur on a non-fixed schedule
using stored card details.
Initial merchant initiated recurring stored credential transactions was …

Adyen: Fix stored credentials

---

CHANGELOG
lib/active_merchant/billing/credit_card_methods.rb
test/unit/credit_card_methods_test.rb

Updated the BIN ranges for the Alelo and Maestro cards to accurately
reflect ranges for those cards.
CE-363
CE-364
CE-438
4479 tests, 71674 assertions, 0 failures, 0 errors, 0 pendings, 2 omissions, 0 notifications
100% passed

Update BIN ranges for Alelo and Maestro cards

---

CHANGELOG
lib/active_merchant/billing/gateways/stripe_payment_intents.rb
test/unit/gateways/stripe_payment_intents_test.rb

ECS-858
When a user creates a new Stripe account and fail to verify their phone
number before attempting transactions, they will get a `You cannot confirm
this PaymentIntent because it's missing a payment method. You can either
update the PaymentIntent with a payment method and then confirm it again,
or confirm it again directly with a payment method.` error message when
attempting to run any transactions with raw credit card numbers.
This change will return early when a `payment_methods` call fails and
provide a more useful error message, instead of continuing on to the
`payment_intents` call.
Unit:
10 tests, 61 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
36 tests, 174 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 …

Stripe Payment Intents: Early return failed `payment_methods` response

---

CHANGELOG
lib/active_merchant/billing/gateways/borgun.rb
test/remote/gateways/remote_borgun_test.rb
test/unit/gateways/borgun_test.rb

Support passing airline data fields pursuant to https://docs.borgun.com/paymentgateways/bgateway/#sending-passenger-itinerary. 
Some fields are required; we don't validate those, but the adapter will pass generated error messages back to the user. Of particular note, the English documentation above says that Version is required, but requests that include Version as part of PassengerItineraryData are rejected. The documentation for the corresponding Icelandic implementation of the API does not appear to include Version (https://docs.borgun.is/formats/mci10/ section A1). 
CE-385
Remote: 21 tests, 48 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit: 9 tests, 41 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Borgun: support airline data

---

CHANGELOG
lib/active_merchant/billing/gateways/global_collect.rb
test/remote/gateways/remote_global_collect_test.rb
test/unit/gateways/global_collect_test.rb

Add support for optional "requiresApproval"
gateway-specific field for Ingenico/GlobalCollect gateway.
If `requires_approval` is sent in as the boolean `true`, then a purchase
will **not** request capture.
If `requires_approval` is not sent, or is sent in as `false`,
then a purchase **will** request capture.
Please see [Ingenico/GlobalCollect's documentation](https://epayments-api.developer-ingenico.com/s2sapi/v1/en_US/ruby/payments/create.html?paymentPlatform=GLOBALCOLLECT#payments-create-payload)
**Note:** you have to click on `Group: cardPaymentMethodSpecificInput`
in order to get to info about the `requiresApproval` field.
```
requiresApproval
Description
•	true = the payment requires approval before the funds will be captured using the Approve payment or Capture payment API
•	false = …
```

Ingenico/GlobalCollect: Add support for 'requires_approval' field

---

CHANGELOG
test/remote/gateways/remote_cenpos_test.rb

Make updates to fix remote tests failures for CenPOS:
* update test cards/expiration based on docs
* adjust address and zip values to trigger AVS rules
* updates to error message text
* need to use a specific amount to trigger declines
It also comments out one test which is failing due to the amount
being set in the method itself (the value 100 is always resulting
in a declined transaction for test cards, but is always used in
verify calls).
Remote:
22 tests, 56 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
23 tests, 98 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

CenPOS: Fix remote tests failures

---

CHANGELOG
test/remote/gateways/remote_realex_test.rb

Currently, remote realex tests are failing when using the
:realex_with_account fixtures. They all pass with no other
updates when using just the :realex fixtures. Update the
gateway to use the :realex set of fixtures.
To test, ensure remote tests are passing for you.
Remote:
27 tests, 138 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
31 tests, 981 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Realex: Update remote tests (gateway fixtures)

---

CHANGELOG
lib/active_merchant/billing/gateways/firstdata_e4_v27.rb
test/remote/gateways/remote_firstdata_e4_v27_test.rb
test/unit/gateways/firstdata_e4_v27_test.rb

Some transactions on this gateway that used stored credentials
appeared successful to start, but were ultimately rejected because
the initation value was missing. That seems to match up with remote
test behavior seen before updating this branch, as current stored
credentials remote tests appear to pass, despite not tagging the value
as expected. This PR updates add_stored_credentials to pass along
the appropriate value ('M' or 'C') into an XML field called `Initiation`,
per [docs](https://support.payeezy.com/hc/en-us/articles/206601408-First-Data-Payeezy-Gateway-Web-Service-API-Reference-Guide#3.13). 
Unit:
31 tests, 147 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
26 tests, 111 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 …

First Data E4 v27: Correctly tag stored credentials intiation

---

CHANGELOG
lib/active_merchant/billing/gateways/orbital.rb
test/remote/gateways/remote_orbital_test.rb
test/unit/gateways/orbital_test.rb

ECS-1076
https://secure.paymentech.com/developercenter/files/file?fid=J4p8Vagjmx4%3D
Subsequent cardholder initiated stored credential transactions are failing
due to the `get_msg_type` method looking for the `customer` parameter.
This change corrects the method to look for the `cardholder` parameter
instead in order to return the correct `MITMsgType` required by the gateway.
Unit:
91 tests, 527 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
34 tests, 188 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
4459 tests, 71574 assertions, 0 failures, 0 errors, 0 pendings, 2 omissions, 0 notifications
100% passed

Orbital: Fix stored credentials

---

lib/active_merchant/billing/gateways/cyber_source.rb
test/remote/gateways/remote_cyber_source_test.rb
test/unit/gateways/cyber_source_test.rb

ECS-1080
Voiding `purchase` transactions were failing due to `<ccAuthReversalService run=\"true\">`
being sent in the request instead of the required `<voidService run=\"true\">`.
This change corrects this issue.
Unit:
76 tests, 340 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
75 tests, 385 assertions, 5 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
93.3333% passed
4460 tests, 71572 assertions, 0 failures, 0 errors, 0 pendings, 2 omissions, 0 notifications
100% passed
The 5 remote failures seem to be previously existing and unrelated:
- test_successful_3ds_validate_authorize_request
- test_successful_3ds_validate_purchase_request
- test_successful_pinless_debit_card_puchase
- test_successful_tax_calculation
- …

CyberSource: Fix `void` for `purchase` transactions

---

lib/active_merchant/billing/gateways/checkout_v2.rb
lib/active_merchant/billing/network_tokenization_credit_card.rb
test/remote/gateways/remote_checkout_v2_test.rb
test/unit/gateways/checkout_v2_test.rb
test/unit/network_tokenization_credit_card_test.rb

Make Purchase call on Checkout V2 gateway using a network token. Add
`use_network_token` to the response to indicate NT was used for the
transaction

Checkout V2: Purchase using Network Token

---

lib/active_merchant/billing/gateways/opp.rb
test/fixtures.yml

This fix the tests for opp by updating fixtures credentials.
Credentials required for opp gateway was updated in https://github.com/activemerchant/active_merchant/commit/8c0e5d3b745abc11cde06766907934b3824266ed, but not fixtures
```
$ rake test TEST=test/unit/gateways/opp_test.rb 
..............
Finished in 0.056895137 seconds.
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
14 tests, 73 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- …
```

fix opp tests

---

CHANGELOG
lib/active_merchant/billing/gateways/optimal_payment.rb
test/remote/gateways/remote_optimal_payment_test.rb

Add support for store on Optimal Payment, which calls verify with
the cc and any options passed. You can use the authorization value
returned from the successful transaction to issue a purchase or auth,
which will utilize that same payment method.
Remote:
18 tests, 85 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
19 tests, 75 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Optimal Payment: Add store method

---

CHANGELOG
lib/active_merchant/billing/gateways/iridium.rb
test/unit/gateways/iridium_test.rb

ECS-1119
Iridium (PayVector) requires the transaction amount to be sent in "minor
currency". This change ensures that zero-decimal currencies are properly
sent (i.e. 14200 JPY is sent as 142)
A new remote test was not written because Iridium (PayVector) does not
return the amount in the response.
Unit:
13 tests, 56 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
21 tests, 84 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
4462 tests, 71592 assertions, 0 failures, 0 errors, 0 pendings, 2 omissions, 0 notifications
100% passed

Iridium: Localize zero-decimal currencies

---

CHANGELOG
lib/active_merchant/billing/gateways/iveri.rb
test/remote/gateways/remote_iveri_test.rb
test/unit/gateways/iveri_test.rb

ECS-1124
iVeri now requires an amount other than `0` for the `authorize` action.
Unit:
15 tests, 62 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
19 tests, 46 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
4461 tests, 71591 assertions, 0 failures, 0 errors, 0 pendings, 2 omissions, 0 notifications
100% passed

iVeri: Fix `verify` action

---

CHANGELOG
lib/active_merchant/billing/gateways/ixopay.rb
test/unit/gateways/ixopay_test.rb

ECS-1133
Ixopay requires three-decimal currencies (i.e. KWD) amount to be sent with
three decimal values. For example, amount = 1000 KWD is currently sent as
10.00 KWD, when it should be 1.000 KWD. This change corrects this.
A new remote test was not written because Ixopay does not return the amount
in the response.
Unit:
29 tests, 144 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
23 tests, 95 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
4463 tests, 71612 assertions, 0 failures, 0 errors, 0 pendings, 2 omissions, 0 notifications
100% passed

Ixopay: Properly support three-decimal currencies

---

CHANGELOG
README.md
lib/active_merchant/billing/gateways/payment_express.rb

PaymentExpress has rebranded as Windcave. Update homepage_url, display_name, and readme listing to match the new name.
Remote:
15 tests, 70 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
34 tests, 249 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

PaymentExpress: Update name and url to reflect rebrand

---

CHANGELOG
activemerchant.gemspec
lib/active_merchant/billing/gateways/decidir.rb
lib/active_merchant/billing/gateways/kushki.rb
test/remote/gateways/remote_kushki_test.rb
test/remote/gateways/remote_optimal_payment_test.rb
test/unit/gateways/decidir_test.rb

Decidir, in some odd cases, is returning a json response that was not
being caught by the `error_code_from` method
CE-378
Unit: 33 tests, 143 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 21 tests, 75 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Decidir: Handle unique error response

---

CHANGELOG
lib/active_merchant/billing/gateways/checkout_v2.rb
test/unit/gateways/checkout_v2_test.rb

When we're unable to parse an error message from the returned body
of a checkout response, we send the generic message `Unable to read
error message`. This causes confusion, and in a lot of cases there
is more information we could be providing to help inform users of the
problem. Specifically, when there's a 4xx error, we attempt to parse
the response body, but can ultimately get a ParserError which will end
up setting the AM message to a generic error message. We've seen with
401 errors, the body is simply an empty string, so this default happens
everytime and customers have to dig to figure out exactly what happened.
This PR updates the logic to instead set an error type and code when
rescuing the ParserError (if available). That leads us to present a more
informative error in such …

CheckoutV2: Send appropriate error messages for 4xx errors

---

CHANGELOG
lib/active_merchant/billing/gateways/elavon.rb
test/unit/gateways/elavon_test.rb

CE-505
Unit:
33 tests, 157 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
TBD: Remote tests were unreliable at time of comitting. Please try running when reviewing.

Elavon: add ssl_dynamic_dba field

---

CHANGELOG
lib/active_merchant/billing/gateways/iats_payments.rb
test/remote/gateways/remote_iats_payments_test.rb
test/unit/gateways/checkout_v2_test.rb
test/unit/gateways/iats_payments_test.rb

Upgrade the iATs gateway to version 3 following the examples found
https://www.iatspayments.com/netgate/ProcessLinkv3.asmx and
https://www.iatspayments.com/netgate/CustomerLinkv3.asmx
Additionally, add support for phone, email, and country fields
CE-291
Unit: 17 tests, 172 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 14 tests, 55 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

iATs Payments: Upgrade to v3 and add GSFs

---

CHANGELOG
lib/active_merchant/billing/gateways/elavon.rb

CE-505
Unit:
33 tests, 157 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
27 tests, 120 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
96.2963% passed

Elavon: Cleanup inadvertent field removal (avs_address) in #3600

---

CHANGELOG
lib/active_merchant/billing/gateways/iats_payments.rb
test/remote/gateways/remote_iats_payments_test.rb
test/unit/gateways/iats_payments_test.rb

Changing previous update to include the fields, `phone`, `country`, and
`email` in `add_address` for `purchase` and `store` methods
CE-291
Unit: 17 tests, 172 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 12 tests, 46 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

iATS Payments: Updating gateway to accept additional fields

---

CHANGELOG
lib/active_merchant/billing/gateways/braintree_blue.rb
test/unit/gateways/braintree_blue_test.rb

Before this change, if the `force_full_refund_if_unsettled` option was
set to true, and the refund failed for any reason other than the one
that triggered the `#void` call, the `#refund` method would return
nothing at all. Which is bad. Very bad.

Fix broken refund response when force_full_refund_if_unsettled is true

---

CHANGELOG
lib/active_merchant/billing/gateways/iats_payments.rb
test/remote/gateways/remote_iats_payments_test.rb
test/unit/gateways/iats_payments_test.rb

iats_payments gateway has had support for store, but not using stored
payment methods. Adds ability to purchase with a CustomerCode.
Unit:
18 tests, 178 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
13 tests, 56 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
ECS-1177

iATS Payments: Add support for Customer Code payment method

---

CHANGELOG
lib/active_merchant/billing/gateways/cyber_source.rb
test/unit/gateways/cyber_source_test.rb

1. Send a specific card brand commerceIndicator for 3DS to comply with following doc
2. Pass application_id as partnerSolutionID

Cybersource additions

---

CHANGELOG
lib/active_merchant/billing/gateways/adyen.rb
test/unit/gateways/adyen_test.rb

When 3DS2 fails, Adyen will return an error under refusalReason.
Previously, we were checking for this value with the `authorise`
and the `authorise3d` endpoints, but not for `authorise3ds2`.
Updates message_from to properly check for the refusal reason when
present for 3DS2 txns.
Unit:
66 tests, 315 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
89 tests, 343 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Adyen: Correctly parse error messages for 3DS2 auths

---

lib/active_merchant/billing/gateways/cyber_source.rb

Having `partnerSolutionID` in the top level namespace generates a 500 parsing error on the Cybersource side. Remote tests seem to pass now. Not sure why I didn't catch that earlier.
This error was introduced in this commit https://github.com/activemerchant/active_merchant/pull/3620/commits/8c5136ab5f2bbd3f143461150e20bb0c95f6163c.  Since AM doesn't use cassettes it's pretty hard to show the test but I can confirm I got it to run properly locally. Cybersource also confirmed that it should be at the end of the xml...

Set partnerSolutionID after the business rules 

---

CHANGELOG
lib/active_merchant/billing/gateways/realex.rb
test/unit/gateways/realex_test.rb

When customer try to complete the checkout with Realex, the following error appears after they enter the payment details.
example error
```
The line number 21 which contains ' [custipaddress] 2a02:c7d:da18:ac00:6d10:4f13:1795:4890 [/custipaddress] ' does not conform to the schema.
```
closes https://github.com/activemerchant/active_merchant/issues/3569
Ignore IPs that don't match the ipv4 standard

 Ignore IPv6 unsupported addresses

---

CHANGELOG
lib/active_merchant/billing/gateways/braintree_blue.rb
lib/active_merchant/billing/gateways/cyber_source.rb
lib/active_merchant/billing/gateways/elavon.rb
lib/active_merchant/billing/gateways/realex.rb
lib/active_merchant/billing/gateways/worldpay.rb
test/remote/gateways/remote_elavon_test.rb
test/unit/gateways/elavon_test.rb
test/unit/gateways/worldpay_test.rb

Previously, the `verify` action for the Elavon gateway was implemented
as a $1 authorization followed by a void action.
This change implements a true verify action using the `ccverify` action.
This update means that customers will no longer see potentially
confusing holds on their accounts.
CE-553
Unit:
32 tests, 153 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
Remote:
27 tests, 119 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
4471 tests, 71666 assertions, 0 failures, 0 errors, 0 pendings, 2
100% passed

Elavon: Implement true verify action

---

CHANGELOG
lib/active_merchant/billing/gateways/litle.rb
test/remote/gateways/remote_litle_test.rb
test/unit/gateways/litle_test.rb

Litle (Vantiv Ecommerce) allows (and may require) expiration date information to be sent when a `litleToken` is used as the payment method.
Tests currently in extreme disarray.

Litle: pass expiration data for basis payment method

---

lib/active_merchant/billing/gateways/realex.rb

A linting error was recently introduced:
```
lib/active_merchant/billing/gateways/realex.rb:377:9: C: Style/DoubleNegation: Avoid the use of double negation (!!). (https://github.com/rubocop-hq/ruby-style-guide#no-bang-bang)
!!ip_address[/\A\d+\.\d+\.\d+\.\d+\z/]
```
Fixes a Style/DoubleNegation linting error was introduced in the Realex gateway by changing the statement to `!statement.nil?` from `!!statement`.
```
4493 tests, 71886 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
```

Fix Style/DoubleNegation linting error

---

CHANGELOG
lib/active_merchant/billing/gateways/stripe_payment_intents.rb
test/remote/gateways/remote_stripe_payment_intents_test.rb
test/unit/gateways/stripe_payment_intents_test.rb

The Stripe PI refund method first makes an API call to check for
the associated charge id of the payment intent to be refunded. If
this payment intent does not have an associated charge, or if there
is some sort of error (whether service availability, etc), subsequent
steps in the refund process will raise errors due to the way we try
to parse out the charge id. This PR updates refund to check for any
errors resulting from the initial get request. If there are any, we
stop the process and simply return a failed response with that error.
Next we try to parse out the charge id from the response. If it's nil,
we again simply send back a failed response with appropriate message
and halt processing. Otherwise, we use that charge_id to call the stripe
refund method as before.
This PR also …

Stripe Payment Intents: Handle errors in refund process

---

CHANGELOG
lib/active_merchant/billing/gateways/hps.rb
test/unit/gateways/hps_test.rb

For check payment methods, the HPS adapter attempts to upcase the
account_type and account_holder_type fields when adding them to
the request. If either of these is missing, a NoMethodError is raised.
This PR makes an update to safely call upcase in these instances
to prevent such errors.
Remote (same failures on master):
50 tests, 125 assertions, 5 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
90% passed
Unit:
54 tests, 267 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

HPS: Prevent NoMethodError when account_type or account_holder_type nil

---

CHANGELOG
lib/active_merchant/billing/gateways/stripe.rb
lib/active_merchant/billing/gateways/stripe_payment_intents.rb
test/remote/gateways/remote_stripe_payment_intents_test.rb

Currently Stripe Payment Intents will return a successful response
if a user tries to initiate a purchase or auth and the api responds
with a status of `required_action` (i.e. if additional steps are
required to authenticate with 3ds and proceed with the transaction).
In other adapters that implement 3DS, we use an `execute_threed` flag
to either signify that we should hit a 3DS specific endpoint, or
classify a response as success/failure depending on whether or not
3DS was requested. For Stripe, there's no separate 3DS endpoint; rather,
if a transaction requires 3DS the response will just signify that in the
status field and by having redirect urls. This PR updates to use the
presence of an `execute_threed` option to either classify the response
as a failure should that field not be …

Stripe Payment Intents: Utilize execute_threed flag to determine success

---

CHANGELOG
lib/active_merchant/billing/gateways/elavon.rb
test/remote/gateways/remote_elavon_test.rb
test/unit/gateways/elavon_test.rb

Adds support for Level 2 and Level 3 fields for the Elavon gateway.
CE-543
Unit:
33 tests, 192 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
Remote:
28 tests, 123 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
4499 tests, 71947 assertions, 0 failures, 0 errors, 0 pendings, 0
100% passed

Elavon: Add Level 3 fields

---

CHANGELOG
lib/active_merchant/billing/gateways/mercado_pago.rb
test/remote/gateways/remote_mercado_pago_test.rb

CE-562, CE-593
Unit:
38 tests, 174 assertions, 0 failures, 0 errors,
100% passed
Remote:
32 tests, 82 assertions, 8 failures, 1 errors,
71.875% passed
All Unit Tests:
4501 tests, 71919 assertions, 0 failures, 0 errors,
100% passed

Mercado Pago: Add payment_method_option_id field

---

CHANGELOG
lib/active_merchant/billing/gateways/stripe.rb
test/remote/gateways/remote_stripe_test.rb

Currently, the Stripe adapter can be used to attempt an authorize
with a check object. However, this causes an application error,
because if you pass a check directly in an authorize, we don't try
to tokenize it in any way before processing, so it errors out with
a NoMethodError (we're trying to process it as though it's a credit
card, and in this case, there's no `month` method on the check,
causing an error). Additionally, ACH simply does not seem to be
supported by Stripe for revenue transfers where funds aren't captured - 
after storing a check as you'd have to do for a purchase, you'll
end up with an error related to capture being false if you attempt
the auth. This PR updates the logic in authorize to check if the
payment method is a check before processing the auth, and if so, we …

Stripe: Provide error when attempting an authorize with ACH

---

CHANGELOG
lib/active_merchant/billing/gateways/element.rb
test/remote/gateways/remote_element_test.rb
test/unit/gateways/element_test.rb

CE-376, CE-584
Remote:
20 tests, 57 assertions, 1 failures, 0 errors,
95% passed
Unit:
20 tests, 53 assertions, 0 failures, 0 errors,
100% passed
Remote test failure seems to be pending an update with an updated
value containing an actual CardPresentCode value. This
modification to remote unit tests may need to be removed.

Element: Add card_present_code field

---

lib/active_merchant/billing/gateways/cyber_source.rb
test/unit/gateways/cyber_source_test.rb

For mastercard cards, we need to always be passing a collectionIndicator for the request to succeed.
I decided to use `2` as the default collectionIndicator, as it was already the one used for tokenized card and
it seems to match our usecase from all the pther choices:
- 0: UCAF collection is not supported at your web
site.
- 1: UCAF collection is supported at your web
site, and the UCAF was populated.
- 2: UCAF collection is supported at your web
site and the UCAF was populated. This value
indicates a successful Mastercard Identity
Check transaction.
- 5: UCAF collection is supported at your web
site, and the UCAF was populated based on the
risk assessment that the issuer performed. This
value is supported only for Masterpass
transactions.
- 6: UCAF collection is supported at your web …

[Cybersource] Set a default collectionIndicator

---

CHANGELOG
lib/active_merchant/billing/gateways/orbital.rb
test/remote/gateways/remote_orbital_test.rb
test/unit/gateways/orbital_test.rb

Adds support for Level 3 fields to the Orbital gateway, including
support for sending an array of line item details.
CE-560
Unit:
93 tests, 553 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
Remote:
35 tests, 190 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
4505 tests, 72007 assertions, 0 failures, 0 errors, 0 pendings, 0
100% passed

Orbital: Add support for Level 3 fields

---

lib/active_merchant/billing/gateways/braintree_blue.rb
test/unit/gateways/metrics_global_test.rb

Since this commit in Rails https://github.com/rails/rails/commit/d9539281bd6c314786b9f05ff6cba1d89509b174,
`extract_options` is no longer required automatically, since this class uses it, lets require it. 
We're also requiring the `singleton_class` when `class_eval` is used.
This fixes the tests on Rails master.

Explicitly require "extract_options" from Braintree Blue

---

lib/active_merchant/billing/gateways/forte.rb
test/remote/gateways/remote_forte_test.rb

The sec_code field for echeck transactions was recently added to the
Forte gateway in 1c4b10818a780d0c80e4554e0843741193c6584a. After
customer issues and digging into Forte value definitions, it has become
clear that 'PPD' should be the default value when none is specified.
Forte currently assigns PPD to a transaction where no sec_code is specified,
so we should follow that pattern here.
Forte will soon be requiring a sec_code is sent on any echeck
transaction, which is why a default is being set.
Remote:
22 tests, 63 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
20 tests, 67 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
CE-532

Forte: Change default sec_code value to PPD

---

CHANGELOG
lib/active_merchant/billing/gateways/element.rb
test/remote/gateways/remote_element_test.rb
test/unit/gateways/element_test.rb

Give the option to send through a specific terminal id via transactions to the Element(Vantiv) gateway and corrected a few Rubocop errors manually
CE-506
Unit: 
19 tests, 51 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
Remote
21 tests, 55 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Element(Vantiv) : Add terminal id field to transactions

---

CHANGELOG
lib/active_merchant/billing/gateways/payu_latam.rb
test/remote/gateways/remote_payu_latam_test.rb
test/unit/gateways/payu_latam_test.rb

In PayU Latam requests, passing in certain billing_address fields
as empty strings (specifically `country`) will result in an error.
This PR updates the logic to not pass a billing_address country field
that's blank.
Remote:
34 tests, 83 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
97.0588% passed
unrelated failure, also on master: `test_well_formed_refund_fails_as_expected`
Unit:
32 tests, 122 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Payu Latam: Prevent blank country in billing_address

---

CHANGELOG
lib/active_merchant/billing/gateways/d_local.rb
test/remote/gateways/remote_d_local_test.rb
test/unit/gateways/d_local_test.rb

DLocal was previously only passing state and country in the billing
address due to checking for incorrect address fields. DLocal also
separates number and street fields, so adds address parser for address1.
Unit:
20 tests, 81 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
27 tests, 71 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
ECS-1267

DLocal: Fix address field names

---

CHANGELOG
lib/active_merchant/billing/gateways/cyber_source.rb
test/unit/gateways/cyber_source_test.rb

We've been experiencing an error with 3DS 2.0 where Cybersource still
requires an xid even though this field isn't present for 3DS 2.0 transactions.
This is the exact error `<c:missingField>c:xid</c:missingField>`
After discussing with Cybersource and Cardinal it was decided that we
will send the cavv as the xid for 3DS 2.0 until they sort out their api.

[Cybersource] Send cavv as xid when xid is missing

---

CHANGELOG
lib/active_merchant/billing/gateways/d_local.rb
test/unit/gateways/d_local_test.rb

Recent address parsing addition in 6419a3474fb87a0d02d75d8312de61e823e8beec
did not account for nil address1. Adds handling to not attempt parsing
when there is no address1.
Unit:
22 tests, 90 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
28 tests, 73 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
ECS-1267

DLocal: Handle nil address1

---

CHANGELOG
lib/active_merchant/billing/gateways/braintree_blue.rb
test/remote/gateways/remote_braintree_blue_test.rb
test/unit/gateways/braintree_blue_test.rb

Added the [industry-specific fields for travel and lodging](https://developers.braintreepayments.com/guides/amex-direct-industry-specific/ruby#travel/cruise-industry-parameters)
to the Braintree gateway.
In addition, the (rather large) `create_transaction_parameters` method
was refactored to pull out many new methods as the main method was
getting sufficiently unweildy to cause RuboCop to complain about it.
While doing this refactoring, I discovered that [the recurring parameter
is now deprecated](https://developers.braintreepayments.com/reference/request/transaction/sale/ruby#recurring),
so I removed its use while still allowing the existing parameter to be
passed into Active Merchant in order to keep this from being a breaking
change.
CE-470
Unit:
80 tests, 183 assertions, 0 failures, 0 …

Braintree: Add travel and lodging fields

---

CHANGELOG
lib/active_merchant/billing/gateways/stripe.rb

Stripe API keys can be up to 255 characters now, and these longer
keys ended up with line breaks when encoded in the headers, causing
the error: `ArgumentError: header field value cannot include CR/LF`.
Use strict_encode64 to prevent these characters from being added.
Stripe:
Remote:
71 tests, 324 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
98.5915% passed
(test_successful_store_with_existing_account failure - looks to be related to test data - `Account ... already has the maximum 200 external accounts attached.` - and also fails on master)
Unit:
138 tests, 738 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Stripe PI
Remote:
39 tests, 183 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications …

Stripe: strict_encode64 api key

---

CHANGELOG
lib/active_merchant/billing/gateways/stripe_payment_intents.rb
test/remote/gateways/remote_stripe_payment_intents_test.rb
test/unit/gateways/stripe_payment_intents_test.rb

Added the `verify` action to the Stripe Payment Intents gateway using
the [SetupIntents endpoint](https://stripe.com/docs/api/setup_intents/create).
CE-554
Unit:
13 tests, 77 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
Remote:
41 tests, 188 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
ÿ7 tests, 72072 assertions, 0 failures, 0 errors, 0 pendings, 0
100% passed

Stripe PI: Implement verify action

---

CHANGELOG
lib/active_merchant/billing/credit_card.rb
lib/active_merchant/billing/credit_card_methods.rb
lib/active_merchant/billing/gateways/kushki.rb
lib/active_merchant/billing/gateways/paymentez.rb
test/remote/gateways/remote_kushki_test.rb
test/remote/gateways/remote_paymentez_test.rb
test/unit/credit_card_methods_test.rb

No Alia test card numbers seem to be available, so no tests were written.
Paymentez and Kushki both had some changed resposes; I updated these.
Paymentez does specifically call out that they now support partial
capture for some transactions:
https://paymentez.github.io/api-doc/#payment-methods-cards-capture
Unit tests:
4521 tests, 72082 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Kushki remote:
13 tests, 42 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Paymentez remote:
26 tests, 66 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
CE-640

Add Alia cardtype

---

CHANGELOG
test/unit/gateways/element_test.rb

A couple of unit tests for the Element gateway were previously
implemented as remote tests, which I discovered last night when the
Element gateway was down and the unit test file failed.
To ensure that the unit test file is not dependent on the gateway being
up, these two tests using remote calls to the gateway have been replaced
with actual unit tests that stub out the communication with the gateway.
Unit:
19 tests, 72 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
Remote:
21 tests, 55 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
4520 tests, 72098 assertions, 0 failures, 0 errors, 0 pendings, 0
100% passed

Element: Fix unit tests

---

.rubocop_todo.yml
CHANGELOG
Rakefile
activemerchant.gemspec
test/test_helper.rb

Fixed the RuboCop to-do for [Style/SpecialGlobalVars](https://docs.rubocop.org/rubocop/cops_style.html#stylespecialglobalvars).
4517 tests, 72070 assertions, 0 failures, 0 errors, 0 pendings, 0
100% passed

RuboCop: Fix Style/SpecialGlobalVars

---

.rubocop_todo.yml
CHANGELOG
lib/active_merchant/billing/gateways/banwire.rb
lib/active_merchant/billing/gateways/cams.rb
lib/active_merchant/billing/gateways/credorax.rb
lib/active_merchant/billing/gateways/digitzs.rb
lib/active_merchant/billing/gateways/ebanx.rb
lib/active_merchant/billing/gateways/merchant_one.rb
lib/active_merchant/billing/gateways/micropayment.rb
lib/active_merchant/billing/gateways/pagarme.rb
lib/active_merchant/billing/gateways/quickpay/quickpay_v10.rb
lib/active_merchant/billing/gateways/stripe.rb
lib/active_merchant/billing/gateways/usa_epay_advanced.rb
lib/active_merchant/billing/gateways/worldpay.rb
test/unit/gateways/eway_managed_test.rb

Fixed the RuboCop to-do for [Style/StringLiteralsInInterpolation](https://docs.rubocop.org/rubocop/cops_style.html#stylestringliteralsininterpolation).
4517 tests, 72070 assertions, 0 failures, 0 errors, 0 pendings, 0
100% passed

RuboCop: Fix Style/StringLiteralsInInterpolation

---

CHANGELOG
lib/active_merchant/billing/gateways/stripe.rb
lib/active_merchant/billing/gateways/stripe_payment_intents.rb

Support added for 5 additional countries: [Czech Republic, Romania, Bulgaria, Cyprus, and Malta](https://stripe.com/blog/stripe-launches-in-five-more-european-countries)
Stripe PI
Remote:
41 tests, 188 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
13 tests, 77 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
remote:
Stripe
Remote:
71 tests, 325 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
138 tests, 738 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Stripe, Stripe PI: Update supported country list

---

CHANGELOG
lib/active_merchant/billing/gateways/cyber_source.rb

Adds UAE to supported countries list
Remote:
80 tests, 403 assertions, 5 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
93.75% passed (5 known unrelated failures)
Unit:
86 tests, 402 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Cybersource: Update supported countries list

---

.rubocop_todo.yml
CHANGELOG
activemerchant.gemspec

Fixes the RuboCop to-do for [Gemspec/OrderedDependencies](https://docs.rubocop.org/rubocop/cops_gemspec.html#gemspecordereddependencies).
This cop ensures that the dependencies listed in the Gemspec are listed
in alphabetical order.
4522 tests, 72123 assertions, 0 failures, 0 errors, 0 pendings, 0
100% passed

RuboCop: Fix Gemspec/OrderedDependencies

---

lib/active_merchant/billing/gateways/worldpay.rb
test/unit/gateways/worldpay_test.rb

Exclude empty `inst_id` as per recommendation from Worldpay:
> \<order orderCode="c12999949615176.2" installationId=""\>
> If there is not installation ID, you should not be including this data. You can instead just submit:
> \<order orderCode="c12999949615176.2"\>
> The response with NMTOKEN must be a name token usually means a value is missing. Anything with "" and nothing is in the middle of the quotes typically will produce this error.

Worldpay: exclude empty inst_id

---

CHANGELOG
lib/active_merchant/billing/gateways/mercado_pago.rb
test/remote/gateways/remote_mercado_pago_test.rb
test/unit/gateways/mercado_pago_test.rb

Add notification_url GSF, also update Mercado-Pago test card values
Unit:
Finished in 0.033803 seconds.
37 tests, 171 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote 
 Finished in 67.755391 seconds.
31 tests, 85 assertions, 5 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
83.871% passed
0.46 tests/s, 1.25 assertions/s
All Unit tests:
  Finished in 11.617083 seconds.
4517 tests, 72070 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
388.82 tests/s, 6203.79 assertions/s
Tests unrelated to this work are still failing, so that should be addressed in another ticket

Mercado-Pago: Notification url GSF

---

CHANGELOG
lib/active_merchant/billing/base.rb
test/test_helper.rb

This is a remnant of when all offsites gateway were extracted to
`OffsitPayments`. The namespace `Billing::Integrations` doesn't
exist anymore.
References https://github.com/activemerchant/active_merchant/issues/3503#issuecomment-647739812
```
irb(main):001:0> require 'activemerchant'
=> true
irb(main):002:0> ActiveMerchant
=> ActiveMerchant
irb(main):003:0> ActiveMerchant::Billing
=> ActiveMerchant::Billing
irb(main):004:0> ActiveMerchant::Billing::Integrations
Traceback (most recent call last):
4: from /opt/rubies/2.6.5/bin/irb:23:in `<main>'
3: from /opt/rubies/2.6.5/bin/irb:23:in `load'
2: from /opt/rubies/2.6.5/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
1: from (irb):4
NameError (uninitialized constant ActiveMerchant::Billing::Integrations)
```

Remove reference to `Billing::Integrations`

---

CHANGELOG
lib/active_merchant/billing/gateways/credorax.rb
test/unit/gateways/credorax_test.rb

Credorax 3DS requires the field 3ds_homephonecountry for 3DS requests
where the phone number is present. However, if the phone number is not
present, you'll get an error if you still send this field. We originally
allowed users to pass optional fields by adding an `optional` key to the
three_ds_2 options hash (#3515). This PR updates the method to check for
this specific key and only set it if phone is present. I don't love this,
but unsure if there's a better way to do this given that we support the
field as an arbitrary one passed in this optional hash - other ideas
welcome!
Remote:
40 tests, 147 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
68 tests, 321 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Credorax: Only send 3ds_homephonecountry when phone number is present

---

CHANGELOG
lib/active_merchant/billing/gateways/cyber_source.rb
test/unit/gateways/cyber_source_test.rb

Added four new fields to allow for directly overriding the standard
stored credential fields for the Cybersource gateway. These four new
fields are all held within the `stored_credential_overrides` hash:
```
@options[:stored_credential_overrides] = {
subsequent_auth: 'true',
subsequent_auth_first: 'false',
subsequent_auth_stored_credential: 'true',
subsequent_auth_transaction_id: '54321'
}
```
CE-698
Unit:
87 tests, 410 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
Remote:
81 tests, 407 assertions, 5 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
93.8272% passed
4523 tests, 72134 assertions, 0 failures, 0 errors, 0 pendings, 0
100% passed
Unrelated, previously failing remote tests:
- …

Cybersource: Add fields to override stored creds

---

CHANGELOG
lib/active_merchant/billing/gateways/firstdata_e4_v27.rb
test/unit/gateways/firstdata_e4_v27_test.rb

The recently added strip_line_breaks method added the requirement that all values in the shipping hash be strings. It is often the case though that nil values are supplied, especially for fields like address2. 
This fix changes the function to allow for nil values.
No test changes were made since the function is already under test with test_requests_scrub_newline_and_return_characters_from_verification_string_components
4533 tests, 72185 assertions, 0 failures, 0 errors, 0 pendings,
100% passed

FirstdataE4V27Gateway: Fix strip_line_breaks method

---

CHANGELOG
lib/active_merchant/billing/gateways/cyber_source.rb

Can't really use a boolean if `false` is a valid value, I guess 😅

Cybersource: Allow false for subsequent auth override

---

CHANGELOG
lib/active_merchant/billing/gateways/credorax.rb
test/unit/gateways/credorax_test.rb

Credorax does not accept the value 30 (deep color) as an input for browser depth. 
Instead we should default to 32 when this value is returned.
Unit:
69 tests, 327 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
40 tests, 147 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Credorax: Default 3ds_browsercolordepth to 32 when passed as 30

---

CHANGELOG
lib/active_merchant/billing/gateways/cyber_source.rb
test/unit/gateways/cyber_source_test.rb

Update logic to send `cavv` as `xid` for 3DS2 according to `Cybersource` recommendations.
Pierre (@pi3r) was talking with Cybersource about an error that we had related to the `xid` field and we got this response from them:
```
1.x
if xid is present, send it
do not send the cavv in the xid XML element
2.x
if xid is present, send it
else if cavv is present, send cavv in the xid XML element for all card brands except :master
```
So this change intends to make the code behave in the recommended way.
Is there anything that I'm missing? Any improvement suggestion?

Update logic to send cavv as xid for 3DS2

---

lib/active_merchant/billing/gateways/cyber_source.rb
test/unit/gateways/cyber_source_test.rb

We use the `authorization` as a reference when voiding/refunding a transaction. `authorization` isn't set when the transaction is in review which prevents later void/refund.

[Cybersource] Set authorization on the response when in Fraud Review

---

lib/active_merchant/billing/gateways/realex.rb
test/unit/gateways/realex_test.rb

Major/minor versions (ex: 1.0.2) in the `message_version` tag is not accepted for 3D Secure v1 for the Realex gateway. For a valid 3D Secure v1 request `message_version` must be either 1 or blank.

Realex: Change 3DSecure v1 message_version to a valid format

---

CHANGELOG
lib/active_merchant/billing/gateways/global_collect.rb
test/remote/gateways/remote_global_collect_test.rb
test/unit/gateways/global_collect_test.rb

Add the option of sending the number of installments for payments and related tests. Remote tests are failing to result in 502 errors on this gateway (on branch master as well as this one).
Unit:
24 tests, 105 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
22 tests, 33 assertions, 13 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
40.9091% passed
Local:
4537 tests, 72200 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Ingenico/Global Collect: Add Installments

---

lib/active_merchant/billing/gateways/global_collect.rb

Remove trailing spaces, which will allow [others branches to pass CI](https://travis-ci.org/github/activemerchant/active_merchant/jobs/714608258#L290) =)

Fix rubocop offense (trailing spaces)

---

activemerchant.gemspec

While debugging recent PRs we (@bbraschi  and I) noticed that it was not possible to do step-by-step debugging and stack navigation, so this PR adds it.
Just added `pry-byebug` as a development dependency.
Just running the tests with a breakpoint set `require 'pry'; binding.pry` and then use the commands `step` and `continue`.
Any other way of doing this? Any suggestions?

Add pry-byebug development dependency

---

CHANGELOG
lib/active_merchant/billing/gateways/cyber_source.rb
test/unit/gateways/cyber_source_test.rb

A merchant can attempt to authorize a non-3DS-authenticated transaction but the liability shift may not occur under the same conditions as it would for a fully 3DS-authenticated transaction.
This is the case, for example, in the `Failed Frictionless Authentication` test with the `4000000000001018` credit card, [here](https://developer.cybersource.com/library/documentation/dev_guides/Payer_Authentication_SO_API/html/index.html#t=Topics%2FTest_Cases_for_3D_Secure_2_x.htm).
If a merchant does not want to attempt to authorize a non-3DS-authenticated transaction, then the call to authorize the transaction through `active_merchant` should not be made and there won't be a problem.
On the other hand, a merchant may want to authorize a non-3DS-authenticated transaction and a corresponding call to …

Cybersource: do not send 3DS fields if 'cavv` is missing and `commerceIndicator` is inferred

---

CHANGELOG
lib/active_merchant/billing/gateways/cyber_source.rb
test/unit/gateways/cyber_source_test.rb

Cybersource confirmed than the same commerce indicators can be used for 
- `maestro` and `master` 
- `discover` and `diners_club`
This PR updates `ActiveMerchant::Billing::CyberSourceGateway::ECI_BRAND_MAPPING` accordingly

Cybersource: add `maestro` and `diners_club` to ECI_BRAND_MAPPING

---

CHANGELOG
lib/active_merchant/billing/gateways/cyber_source.rb
test/remote/gateways/remote_cyber_source_test.rb
test/unit/gateways/cyber_source_test.rb

The Cybersource XML request must follow the defined [xsd schema format](https://ics2wstest.ic3.com/commerce/1.x/transactionProcessor/CyberSourceTransaction_1.167.xsd) 
or else it will result in an XML parse error. Currently, if someone
tries to use stored credential fields in addition to the partner
solution id, they will receive an XML parse error from the gateway. The 
schema requires `subsequentAuth` to come before the solution id and 
for the other stored credential fields to come after solution id. This PR 
updates the request building methods to ensure that these fields are 
added in the right order, also adding remote tests for this behavior.
Remote:
89 tests, 457 assertions, 5 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
94.382% passed
(pre-existing failures)
Unit: …

Cybersource: Ensure Partner Solution Id placement conforms to schema

---

CHANGELOG

Payment facilitators must pass this value for auth/purchase transactions
CE-839
Unit:
69 tests, 325 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
91 tests, 351 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Adyen: Pass `subMerchantId` as `additionalData`

---

CHANGELOG
lib/active_merchant/billing/gateways/litle.rb
test/unit/gateways/litle_test.rb

ACH transactions in which the `checkNum` was `nil` were previously
sending an empty `checkNum` node, which caused failures against the
Litle gateway.
This adds a check so that the `checkNum` node is created only when there
is a value for this field.
ECS-1350
Unit:
46 tests, 201 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
Remote:
43 tests, 188 assertions, 13 failures, 0 errors, 0 pendings, 0
69.7674% passed
Many remote tests are currently failing [due to previously noted
changes to the gateway's responses](https://github.com/activemerchant/active_merchant/issues/3618).
100% passed

Litle: Omit checkNum when nil

---

CHANGELOG
lib/active_merchant/billing/gateways/cyber_source.rb
test/remote/gateways/remote_cyber_source_test.rb

XML parse error observed if this field comes after partnerSolutionId. Switch order and add tests. Also check merchant_descriptor in case that could cause issues.
Unit:
96 tests, 467 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
93 tests, 481 assertions, 5 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
94.6237% passed

Cybersource: Ensure issueradditionaldata comes before partnerSolutionId

---

.rubocop_todo.yml
CHANGELOG
test/unit/gateways/forte_test.rb

Fixes the RuboCop to-do for [Style/Attr](https://docs.rubocop.org/rubocop/0.85/cops_style.html#styleattr).
100% passed

RuboCop: Fix Style/Attr

---

CHANGELOG
lib/active_merchant/billing/gateways/payflow.rb
test/remote/gateways/remote_payflow_test.rb
test/unit/gateways/payflow_test.rb

For rev share flagging purposes, Payflow requires the corresponding
code to be included as ExtData field BUTTONSOURCE, similar to Paypal.
[Example structure as follows](https://stackoverflow.com/a/19414626), confirmed by paypal/payflow support:
```
<Sale>
<PayData>
(Invoice)
(Tender)
</PayData>
(ExtData)*
</Sale>
```
This PR updates sale and auth requests to set this field appropriately
when application_id is provided
Unit:
49 tests, 243 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
38 tests, 156 assertions, 12 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
68.4211% passed
(unrelated failures preexist on master)

Payflow: Use application_id to set buttonsource

---

CHANGELOG
lib/active_merchant/billing/gateways/hps.rb
test/remote/gateways/remote_hps_test.rb

Currently, if you try to issue a refund using a capture as your
reference transaction, you will get an error. This is because the
authorization value here only refers to the capture, with no
connection to the auth. In other adapters, we solve for this by
building up an authorization value that includes references to the
current transaction as well as reference transactions (and potentially
other data). This allows us to parse this field to return the
correct reference transaction for supplemental actions. This PR
updates HPS to build an authorization value including the authorize
transaction id for captures. It also adds in logic to pluck off
the appropriate value when issuing a refund on a capture txn.
Unit:
54 tests, 267 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 …

HPS: Enable refunds using capture txn

---

CHANGELOG
lib/active_merchant/billing/gateways/quickbooks.rb
test/remote/gateways/remote_quickbooks_test.rb

This fixes a bug caused by submitting an empty string for the state
field (which is submitted as 'region' to Quickbooks). While `nil` values
for this field are fine because the field is then simply omitted from
the request sent to Quickbooks, sending an empty string results in the
error message `card.address.region is invalid`.
ECS-1355
Unit:
22 tests, 118 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
Remote:
18 tests, 44 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
100% passed

Quickbooks: Omit empty strings in address

---

CHANGELOG
lib/active_merchant/billing/gateways/orbital.rb
test/remote/gateways/remote_orbital_test.rb
test/unit/gateways/orbital_test.rb

Add level 3 fields to capture transactions. Revert a previous 'fix'
where PC3DtlLineTot was incorrectly assumed to be the correct tag
(should be `PC3Dtllinetot`).
CE-930
Unit: 95 tests, 561 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 37 tests, 192 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
94.5946% passed

Orbital: Allow level 3 fields to be passed on capture

---

CHANGELOG
lib/active_merchant/billing/gateways/credorax.rb
test/remote/gateways/remote_credorax_test.rb
test/unit/gateways/credorax_test.rb

Credorax now requires the following parameters when issuing CFT payouts:
* j5 - Fund recipient's first name
* j13 - Fund recipient's surname
Updates the ~credit and~ referral_cft action to set these two fields,
and checks for their presence in the tests. _(Updated: credorax confirmed that 
they're not required for general credit [6], only actions [34], [35], [37], and [38] - 
of these, currently AM only supports [[34]](https://github.com/activemerchant/active_merchant/blob/master/lib/active_merchant/billing/gateways/credorax.rb#L409))_
Remote:
41 tests, 152 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
69 tests, 331 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Credorax: Send j5 and j13 params for CFT txns

---

CHANGELOG
lib/active_merchant/billing/gateways/blue_snap.rb
test/unit/gateways/blue_snap_test.rb

A recent commit added support for receiving meta-data on BlueSnap but did not protect against a `nil` key being submitted for that field. Line 218 with `{ transaction_meta_data: nil }` would raise a NoMethodError.
This change protects against `{ transaction_meta_data: nil }` for BlueSnap.
4556 tests, 72358 assertions, 0 failures, 0 errors, 0 pendings,

BlueSnap: Protect against nil metadata

---

CHANGELOG

https://github.com/activemerchant/active_merchant/pull/3752
The changelog entry for this was placed in the wrong section.
Fix the changelog entry.
4556 tests, 72358 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications

Fix changelog from previous commit

---

lib/active_merchant/billing/gateways/cyber_source.rb
test/unit/gateways/cyber_source_test.rb

When `ActionController::Parameters` is passed to Cybersource, the default address fields are used
instead of the passed parameters. See following comment for more information.
References: https://github.com/activemerchant/active_merchant/pull/3747#issuecomment-686720226

[CyberSource] Ensure the default address doesn't override `ActionController::Parameters`

---

CHANGELOG
lib/active_merchant/billing/gateways/adyen.rb
test/remote/gateways/remote_adyen_test.rb
test/unit/gateways/adyen_test.rb

In df60a2c5512bf43917a8d5d825d6b7c021dbdd1d when execute_threeds is
false it is assigned to the additionalData as a whole instead of
additively, so previously added additionalData fields were destroyed.
This change adds the field safely.
Remote:
92 tests, 353 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
70 tests, 330 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Adyen: Safely add execute_threeds: false

---

CHANGELOG
lib/active_merchant/billing/gateways/iats_payments.rb
test/remote/gateways/remote_iats_payments_test.rb
test/unit/gateways/iats_payments_test.rb

Give ability to pass customer details outside of the scope of the
billing address
CE-795
Unit: 18 tests, 178 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 14 tests, 61 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

iATS Payments: Pass email address outside of the billing address scope

---

CHANGELOG
lib/active_merchant/billing/gateways/orbital.rb
test/unit/gateways/orbital_test.rb

When attempting certain apple pay transactions, the following error
occurs:
```
Error. The Orbital Gateway has received a badly formatted message.
Field [Verified-By-Visa XID] exceeded max length of [40]
```
This is technically because in practice, the creditcard.transaction_id
on these network tokens is (sometimes? always?) longer than 40 characters,
and we aren't trimming it down in any way. However, after looking at the
docs, it does not appear that XID is actually a required field for
transactions made with network tokens - instead, the main field of note
is `DigitalTokenCryptogram`. From docs:
```
An additional cryptogram field (digitalTokenCrytogram) has been added
which is compatible with all card brand specific cryptograms. This field
must also be submitted as Base 64 encoded. The …
```

Orbital: Don't pass xid for txns using network tokens

---

CHANGELOG
lib/active_merchant/billing/gateways/worldpay.rb
test/unit/gateways/worldpay_test.rb

Add the ability to send through an Idempotency-Key as a header on Worldpay transactions as an option. This is a beta feature for WorldPay, so no remote test was written as we do not have access to use it.
Unit tests:
75 tests, 491 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote tests:
Finished in 78.308251 seconds.
57 tests, 239 assertions, 5 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
91.2281% passed
The tests (which are also failing on master):
test_3ds_version_1_parameters_pass_thru
test_3ds_version_2_parameters_pass_thru
test_successful_credit_using_token
test_successful_mastercard_credit_on_cft_gateway
test_successful_visa_credit_on_cft_gateway

Worldpay: Add Support for Idempotency Key

---

CHANGELOG
lib/active_merchant/billing/gateways/orbital.rb

`if :line_tot` is not resolving to true in some cases because the value
is actually a string. Expanding the check to evaluate against a string
and symlink should resolve this issue.
CE-762
Unit: 95 tests, 560 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 37 tests, 192 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
94.5946% passed

Orbital: Fix line_tot conditional check

---

.rubocop_todo.yml
CHANGELOG
lib/active_merchant/billing/compatibility.rb

Fixes the RuboCop to-do for [Naming/MemoizedInstanceVariableName](https://docs.rubocop.org/rubocop/0.85/cops_naming.html#namingmemoizedinstancevariablename).
4543 tests, 72248 assertions, 0 failures, 0 errors, 0 pendings, 0
100% passed

RuboCop: Fix Naming/MemoizedInstanceVariableName

---

.rubocop_todo.yml
CHANGELOG
test/remote/gateways/remote_barclays_epdq_extra_plus_test.rb
test/remote/gateways/remote_netpay_test.rb
test/remote/gateways/remote_payu_in_test.rb

Fixes the RuboCop to-do for [Style/BlockComments](https://docs.rubocop.org/rubocop/0.85/cops_style.html#styleblockcomments).
100% passed

RuboCop: Fix Style/BlockComments

---

.rubocop_todo.yml
CHANGELOG
test/test_helper.rb

Fixes the RuboCop to-do for [Naming/ConstantName](https://docs.rubocop.org/rubocop/0.85/cops_naming.html#namingconstantname).
In this case, RuboCop was incorrectly thinking that `AssertionClass`
should be a constant, likely because of the capitalization used for this
variable. To fix this issue, this variable has been renamed as an
instance variable.
4543 tests, 72248 assertions, 0 failures, 0 errors, 0 pendings, 0
100% passed

RuboCop: Fix Naming/ConstantName

---

CHANGELOG
lib/active_merchant/billing/gateways/orbital.rb
test/remote/gateways/remote_orbital_test.rb
test/unit/gateways/orbital_test.rb

After fixing an issue with problematic values being sent for network
tokenized PMs (#3757), errors relating to the request not adhering to the
DTD would sometimes appear. This happens in the existing code when
soft descriptors are passed along with a network tokenized card.
In the schema, the soft descriptor fields need to come before the
network token fields. This PR updates the order of these elements
and adds additional test conditions.
Unit:
96 tests, 563 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
37 tests, 192 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
94.5946% passed
(same as master)

Orbital: Fix schema errors

---

CHANGELOG
lib/active_merchant/billing/gateways/cyber_source.rb

When all `mdd_field` options are `nil`, the merchantDefinedData gets
added as an empty XML tag which causes the gateway to return a parse
error.

CyberSource: Only include non-nil `mdd_` fields

---

.rubocop_todo.yml
CHANGELOG
lib/active_merchant/billing/gateways/merchant_partners.rb
lib/active_merchant/billing/gateways/mercury.rb
lib/active_merchant/billing/gateways/orbital.rb
test/remote/gateways/remote_paypal_test.rb
test/unit/gateways/merchant_ware_test.rb
test/unit/gateways/merchant_ware_version_four_test.rb
test/unit/gateways/orbital_test.rb
test/unit/gateways/paypal/paypal_common_api_test.rb

Fixes the RuboCop to-do for [Naming/VariableNumber](https://docs.rubocop.org/rubocop/0.85/cops_naming.html#namingvariablenumber).
PayPal remote tests:
29 tests, 81 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
100% passed

RuboCop: Fix Naming/VariableNumber

---

CHANGELOG
lib/active_merchant/billing/gateways/adyen.rb
test/remote/gateways/remote_adyen_test.rb
test/unit/gateways/adyen_test.rb

Pass in subMerchant fields for reconciliation
Also update `apple_pay` and `google_pay` test cards
CE-985
Unit: 70 tests, 336 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 92 tests, 353 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Adyen: Add subMerchant fields

---

lib/active_merchant/billing/gateways/paypal_express.rb
test/unit/gateways/paypal_express_test.rb

Similar to commit e99842b5c124e034e0a05c9c9151d50c25e798ff
For reference transactions, PayPal Express does not require payment_type, invoice_id, description or ip. We shouldn't
require them either. They can be optionally passed in, but are not required. This change removes the requirement from reference based authorizations.
PayPal remote tests:
29 tests, 81 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
PayPal Express remote tests:
3 tests, 8 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
4563 tests, 72384 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
EVS-661

PayPal Express: reduce param requirements

---

CHANGELOG
lib/active_merchant/billing/gateways/payu_latam.rb
test/remote/gateways/remote_payu_latam_test.rb
test/unit/gateways/payu_latam_test.rb

Added support for partial refunds indicated by passing
`partial_refund: true`
in the options hash.
Previously, all refunds were treated as full refunds, regardless of the
amount sent to the gateway.
ECS-1401
Unit:
34 tests, 137 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed
Remote:
35 tests, 79 assertions, 3 failures, 0 errors, 0 pendings, 0 omissions,
91.4286% passed
4563 tests, 72389 assertions, 0 failures, 0 errors, 0 pendings, 0
100% passed

PayU Latam: Support partial refunds

---

.rubocop_todo.yml
CHANGELOG
lib/active_merchant/billing/gateways/opp.rb
test/unit/gateways/payu_latam_test.rb

Fixes the RuboCop to-do for [Performance/RedundantMatch](https://docs.rubocop.org/rubocop-performance/cops_performance.html#performanceredundantmatch).
4561 tests, 72379 assertions, 0 failures, 0 errors, 0 pendings, 0
100% passed

RuboCop: Fix Performance/RedundantMatch

---

CHANGELOG
lib/active_merchant/billing/gateways/nmi.rb
test/remote/gateways/remote_nmi_test.rb
test/unit/gateways/nmi_test.rb

Add standardized 3DS fields to the NMI gateway per the documented convention that active_merchant has adopted. Active Merchant documentation related to 3DS can be found on the [Standardized 3DS Fields wiki](https://github.com/activemerchant/active_merchant/wiki/Standardized-3DS-Fields).
CE-869
Unit:
46 tests, 352 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
42 tests, 156 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

NMI: Add standardized 3DS fields.

---

CHANGELOG
lib/active_merchant/billing/gateways/mundipagg.rb
test/remote/gateways/remote_mundipagg_test.rb
test/unit/gateways/mundipagg_test.rb

Add ability to send through SubMerchant object which enables the sending of information from sub-accredited.
CE-1027
Unit:
29 tests, 128 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
39 tests, 95 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Mundipagg: Add support for SubMerchant fields

---

CHANGELOG
lib/active_merchant/billing/gateways/stripe_payment_intents.rb
test/remote/gateways/remote_stripe_payment_intents_test.rb
test/unit/gateways/stripe_payment_intents_test.rb

Enable override of Stripe's SCA engine and directly request 3DS using
the request_three_d_secure option. When 3DS is not supported for the
card being charged, liability is still shifted, as indicated by the
'attempt_acknowledged' response in
`payment_method_details.three_d_secure.result`.
Details of field use: https://stripe.com/docs/api/payment_intents/create#create_payment_intent-payment_method_options-card-request_three_d_secure
3DS Result values: https://stripe.com/docs/api/charges/object#charge_object-payment_method_details-card-three_d_secure-result
Unit:
14 tests, 84 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
42 tests, 192 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
ECS-1455

Stripe Payment Intents: Add request_three_d_secure option

---

CHANGELOG
lib/active_merchant/billing/gateways/decidir.rb
test/remote/gateways/remote_decidir_test.rb
test/unit/gateways/decidir_test.rb

Allow for csmdds array to be passed to fraud detection
CE-1048
Unit: 34 tests, 165 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 22 tests, 77 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications

Decidir: Add csmdds gsf for fraud detection

---

.rubocop_todo.yml
CHANGELOG
lib/active_merchant/billing/compatibility.rb
lib/active_merchant/billing/gateways/card_connect.rb
lib/active_merchant/billing/gateways/firstdata_e4.rb
lib/active_merchant/billing/gateways/merchant_ware.rb
lib/active_merchant/billing/gateways/merchant_ware_version_four.rb
lib/active_merchant/billing/gateways/orbital.rb
lib/active_merchant/billing/gateways/quickbooks.rb
lib/active_merchant/billing/gateways/quickpay/quickpay_v10.rb
lib/active_merchant/billing/gateways/realex.rb
test/unit/gateways/nab_transact_test.rb

Fixes the RuboCop to-do for [Performance/StringReplacement](https://docs.rubocop.org/rubocop-performance/cops_performance.html#performancestringreplacement).
4565 tests, 72404 assertions, 0 failures, 0 errors, 0 pendings, 0
100% passed

RuboCop: Fix Performance/StringReplacement

---

CHANGELOG
lib/active_merchant/billing/gateways/blue_snap.rb
test/remote/gateways/remote_blue_snap_test.rb
test/unit/gateways/blue_snap_test.rb

Shipping info will be passed from the shipping_address params instead of
at the transaction level
CE-913
Unit: 38 tests, 223 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 47 tests, 162 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Blue Snap: Pass shipping info from the shipping_address params

---

CHANGELOG
lib/active_merchant/billing/gateways/checkout_v2.rb
test/remote/gateways/remote_checkout_v2_test.rb
test/unit/gateways/checkout_v2_test.rb

Give the option to pass attempt_n3d which will attempt non-3d secure if
the card issure is not enrolled
CE-1080
Unit: 29 tests, 129 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 33 tests, 83 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Checkout V2: Support ability to pass attempt_n3d 3ds field

---

lib/active_merchant/billing/gateways/elavon.rb
test/remote/gateways/remote_elavon_test.rb
test/unit/gateways/elavon_test.rb

Elavon has deprecated the old `process.do` endpoint; to be able to display passed L3 fields in Elavon's UI, the new `processxml.do` endpoint must be used. 
`process.do` passed and received data as a string of parameters; `processxml.do` passes a querystring-formatted block of XML in the request body.

Elavon: Upgrade to `processxml.do`

---

CHANGELOG
lib/active_merchant/billing/gateways/checkout_v2.rb
test/remote/gateways/remote_checkout_v2_test.rb
test/unit/gateways/checkout_v2_test.rb

This updates the support for the attempt_n3d field when it is passed
outside of the three_d_secure context
CE-1080
Unit: 29 tests, 129 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 33 tests, 83 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Checkout V2: Support for attempt_n3d 3DS field

---

Gemfile

A new major version of the Braintree gem was released on October 19th (v3.0). Sadly we have this bit of code that ensures that the Braintree gem's version is in an exact range that 3.0 now exceeds.
https://github.com/activemerchant/active_merchant/blob/90be621c434909f3afd5d482870eca53edf7187a/lib/active_merchant/billing/gateways/braintree_blue.rb#L10
Since we install the latest Braintree version on CI this causes the following error:
```
Error: test_address_country_handling(BraintreeBlueTest): RuntimeError: Need braintree gem >= 2.78.0. Run `gem install braintree --version '~>2.78'` to get the correct version.
```
https://travis-ci.org/github/activemerchant/active_merchant/jobs/739300791
I have no idea if this check is still relevant but at this time I do not want to figure it out, I just …

Remove Braintree specific version dependency

---

CHANGELOG
lib/active_merchant/billing/gateways/checkout_v2.rb

In some cases `three_d_secure` may not be set while `execute_threed` is
leading to `attempt_n3d` not being passed when `[:'3ds'][:enabled]` is
CE-1080
Unit: 29 tests, 129 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:33 tests, 83 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Checkout V2: Pass attempt_n3d along with 3ds enabled

---

CHANGELOG
lib/active_merchant/billing/gateways/global_collect.rb
test/remote/gateways/remote_global_collect_test.rb
test/unit/gateways/global_collect_test.rb

Uses standardized three_d_secure data fields to include 3DS2
authenticated data on the Global Collect gateway
Also adds acs_transaction_id to standardized list (change to
contributing wiki pending approval here). This is another common auth
field that has not been required yet, but is fitting for the
standardized fields.
ECS-1435
Unit:
24 tests, 105 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
23 tests, 57 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
95.6522% passed
One unrelated failure, also failing on master

GlobalCollect: Add support for Third-party 3DS2 data

---

CHANGELOG
lib/active_merchant/billing/gateways/authorize_net.rb
test/remote/gateways/remote_authorize_net_test.rb

Though authorize.net [appears to specify in docs](https://developer.authorize.net/api/reference/index.html#payment-transactions) that `isFirstSubsequentAuth` should be passed in `processingOptions`, doing so results in failure. 
Unit:
101 tests, 601 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
73 tests, 269 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
CE-1026

Authorize.net: Don't pass isFirstSubsequentAuth

---

CHANGELOG
lib/active_merchant/billing/gateways/litle.rb
test/remote/gateways/remote_litle_test.rb
test/unit/gateways/litle_test.rb

Add support for general credit transactions
CE-1072
Unit: 48 tests, 208 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 45 tests, 193 assertions, 13 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
71.1111% passed
Failing remote tests area also failing on main

Litle: Add support for general credit transactions

---

lib/active_merchant/billing/gateways/redsys.rb
test/unit/gateways/redsys_sha256_test.rb

Support 3DS2 Fields, adding an embedded JSON document in node DS_MERCHANT_MPIEXTERNAL
ECS-1427
Unit:
41 tests, 145 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
23 tests, 72 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Redsys: Add 3DS2 Integration Support

---

CHANGELOG
lib/active_merchant/billing/gateways/cyber_source.rb
test/unit/gateways/cyber_source_test.rb

Some merchants reached out as the firstname/lastname don't match in Cybersource.
This change will use the firstname/lastname from the billing/shipping address instead of
the payment method. We have reached to Cybersource to ensure this is a safe change.
Email I got with Scott Griffiths at Cybersource:
```
Since this code is not owned by Cybersource, but rather an active_merchant opensource repository, we are not sure why the payment method first/last name is persisted to the shipTo and billTo elements.  
Yes, you can safely send the actual shipTo and billTo first and last names to Cybersource.
```

[Cybersource] Use firstname/lastname from the address instead of the payment method

---

CHANGELOG
lib/active_merchant/billing/gateways/credorax.rb
test/remote/gateways/remote_credorax_test.rb
test/unit/gateways/credorax_test.rb

Allow use of normalized three_d_secure hash with v1 auth data as
with v2. Also use `start_with?` to check the version so that the
request doesn't error on that parameter when passing a specific
minor version.
Remote
42 tests, 155 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
70 tests, 333 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Credorax: Allow 3DS1 normalized pass-through, ease version matching

---

CHANGELOG
lib/active_merchant/billing/gateways/authorize_net_cim.rb
lib/active_merchant/billing/gateways/decidir.rb
test/remote/gateways/remote_decidir_test.rb

Adds bill_to, purchase_totals, customer_in_site, retail_transaction_data, ship_to, tax_voucher_required.
Updated an error message as Decidir had changed their messages for declined auth/verify to be more specific.
Unit test
34 tests, 165 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote tests
22 tests, 77 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
local:
4586 tests, 72562 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Decidir: Add addtitional fraud detection fields

---

CHANGELOG
lib/active_merchant/billing/gateways/worldpay.rb
test/remote/gateways/remote_worldpay_test.rb
test/unit/gateways/worldpay_test.rb

ECS-1536
Worldpay currently does not have support for requesting different sizes for 3DS2 challenge content.
Adds support for Worldpay's additional3DSData.challengeWindowSize field which lets merchants request different sizes for 3DS2 challenge content.
4590 tests, 72595 assertions, 0 failures, 0 errors, 0 pendings,
100% passed
693 files inspected, no offenses detected
Before:
57 tests, 239 assertions, 5 failures, 0 errors, 0 pendings,
91.2281% passed
After:
58 tests, 242 assertions, 5 failures, 0 errors, 0 pendings,
91.3793% passed

Worldpay: Add support for challengeWindowSize

---

CHANGELOG
lib/active_merchant/billing/gateways/adyen.rb
test/unit/gateways/adyen_test.rb

Per Adyen's documentation it should be "ID" as opposed to "Id"
Unit Tests:
70 tests, 336 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote Tests:
92 tests, 353 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Local Tests:
4589 tests, 72591 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Correct capitalization for SubmerchantID field on Adyen

---

CHANGELOG
lib/active_merchant/billing/response.rb

What: Add `network_transaction_id` as an attribute to Response
Why: Elavon (and possibly other gateways) require two different fields for a stored credential network_transaction_id (see #3816). Rather than dividing management duties between the host library and AM, provide a unified interface so that concatenation and division can occur within a single codebase.

Response: add network_transaction_id attribute

---

CHANGELOG
lib/active_merchant/billing/gateways/decidir.rb
lib/active_merchant/billing/gateways/litle.rb

Decidir documentation shows that the field name is `device_unique_identifier` rather than `device_unique_id` as used in their error messaging.
Also includes a Rubocop correction for the litle gateway
Unit Tests:
34 tests, 165 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote Tests:
22 tests, 78 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Local Tests:
4597 tests, 72631 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Decidir: correct field name for fraud prevention

---

CHANGELOG
lib/active_merchant/billing/credit_card.rb
lib/active_merchant/billing/credit_card_methods.rb
lib/active_merchant/billing/gateways/paymentez.rb
test/remote/gateways/remote_paymentez_test.rb
test/unit/credit_card_methods_test.rb

No Serfinanza card numbers are available, so no tests were written
Paymentez looks to have had a changed response so that was updated
Litle had a rubocop offense that was resolved
CE-992
Unit:
4598 tests, 72632 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
26 tests, 66 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Add Serfinanza cardtype

---

CHANGELOG
lib/active_merchant/billing/credit_card.rb
lib/active_merchant/billing/credit_card_methods.rb
lib/active_merchant/billing/gateways/paymentez.rb
test/unit/credit_card_methods_test.rb

No Olimpica test card numbers are available, so no tests were written
CE-992
Unit:
4598 tests, 72632 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
26 tests, 66 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Paymentez: Revise Serfinanza to be Olimpica card type

---

CHANGELOG
lib/active_merchant/billing/gateways/credorax.rb
test/remote/gateways/remote_credorax_test.rb
test/unit/gateways/credorax_test.rb

The Credorax 3DS Adviser module depends on the use of the `3ds_initiate` parameter and can be controlled more specifically with the use of the `f23` parameter. If the `3ds_initiate` parameter isn’t received in the original request, it will be sent with a value of ’01’ by default. The `f23` parameter is optional and has no default if it is not sent in the original request.
Unit:
69 tests, 331 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
42 tests, 155 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
CE-1082

Credorax: Add support for 3DS Adviser

---

CHANGELOG
lib/active_merchant/billing/gateways/decidir.rb
test/remote/gateways/remote_decidir_test.rb
test/unit/gateways/decidir_test.rb

From talks between the customer and the gateway, the field needed to be sent in as`device_unique_id`
and then add fraud_detection > device_unique_identifier in the card_data object to work.
Local test:
4600 tests, 72884 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
34 tests, 165 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
22 tests, 78 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Update fraud detection field: device_unique_id on Decidir gateway

---

CHANGELOG
lib/active_merchant/billing/gateways/braintree_blue.rb
test/unit/gateways/braintree_blue_test.rb

[CE-1132](https://spreedly.atlassian.net/browse/CE-1132)
Unit: 81 tests, 184 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 82 tests, 439 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Note: Have not included a remote test for the account_type field because currently Braintree does not support account_type parameter on sandbox environments

Braintree_Blue: Add support for account_type field

---

CHANGELOG
lib/active_merchant/billing/gateways/redsys.rb
test/remote/gateways/remote_redsys_test.rb
test/unit/gateways/redsys_test.rb

CE-1184
Remote tests failing on master:
test_successful_authorise_using_vault_id
test_successful_purchase_using_vault_id
Remote:
21 tests, 60 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
90.4762% passed
Unit
33 tests, 104 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Redsys: Add support for stored_credential

---

CHANGELOG
lib/active_merchant/billing/gateways/stripe_payment_intents.rb
test/remote/gateways/remote_stripe_payment_intents_test.rb
test/unit/gateways/stripe_payment_intents_test.rb

CE-1220
Unit:
17 tests, 109 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
48 tests, 208 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Note: Some tests failed for different gateway with rake test:local

Stripe Payment Intents: Add error_on_requires_action Support

---

CHANGELOG
lib/active_merchant/billing/gateways/paypal.rb
lib/active_merchant/billing/gateways/redsys.rb
test/remote/gateways/remote_paypal_test.rb
test/remote/gateways/remote_redsys_sha256_test.rb
test/remote/gateways/remote_redsys_test.rb
test/unit/gateways/paypal_test.rb
test/unit/gateways/redsys_sha256_test.rb

Added support for using three_ds_server_trans_id as threeDSServerTransID if provided
Added support to set Eci when 3ds version 2
ECS-1599
Unit:
33 tests, 104 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
Remote
21 tests, 60 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
90.4762% passed
The following tests failed on master:
test_successful_authorise_using_vault_id
test_successful_purchase_using_vault_id

Redsys: Update Mpi Fields

---

CHANGELOG
lib/active_merchant/billing/gateways/paypal.rb
test/remote/gateways/remote_paypal_test.rb
test/unit/gateways/paypal_test.rb

Update the AuthStatus3ds field to prefer pulling from the standardized
auth_response_status field.
https://developer.paypal.com/docs/paypal-payments-pro/integration-guide/3d-secure/#5-complete-direct-payment-integration-using-3-d-secure-fields
Unit:
68 tests, 279 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
30 tests, 83 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Paypal: Update AuthStatus3ds MPI field

---

CHANGELOG
lib/active_merchant/billing/gateways/orbital.rb
lib/active_merchant/billing/gateways/paypal.rb
test/remote/gateways/remote_orbital_test.rb
test/schema/orbital/Request_PTI83.xsd
test/unit/gateways/orbital_test.rb

WIP - Orbital: Add 3DS2 support
Current status: methods have been built to add `MCProgramProtocol`, `MCDirectoryTransID` and `UCAFInd`. Remote tests are returning the error, "Request does not adhere to the DTD. Please correct and send again." Which indicates a XML schema validation issue. Using `xmllint`, we have locally validated that what we are sending in the request matches their latest published XML request schema architecture. We have a ticket open with Orbital's Support team for this issue.
CE-1242

Orbital: Update 3DS support for Mastercard 

---

.rubocop.yml
CHANGELOG
lib/active_merchant/billing/gateways/payeezy.rb
test/remote/gateways/remote_payeezy_test.rb
test/unit/gateways/payeezy_test.rb

Unit: 35 tests, 168 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 35 tests, 137 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed 
On the addition to rubocop.yml: 
Previously, rubocop generated the following error: `Naming/PredicateName: Rename is_scheduled to scheduled?. (https://github.com/rubocop-hq/ruby-style-guide#bool-methods-qmark)`. Since the term we send to the gateway is literally `is_scheduled`, I've added a permanent exception for this cop on this gateway.

Payeezy: support standardized stored credentials

---

lib/active_merchant/billing/gateways/pin.rb
test/remote/gateways/remote_pin_test.rb
test/unit/gateways/pin_test.rb

The Pin Payments API does support 3DS passthrough and therefore the Pin Payments active_merchant gateway is being expanded to allow for this capability in active_merchant.
The Pin Payments API Documentation describing the 3DS fields is [here](https://pinpayments.com/developers/api-reference/charges#post-charges)
Test Cards for the Pin Payments platform are [here](https://pinpayments.com/developers/api-reference/test-cards)
```
Chris.Kruger@hostname active_merchant % rake test:remote TEST=test/remote/gateways/remote_pin_test.rb
The dependency jruby-openssl (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for java. To add those platforms to the bundle, run `bundle lock --add-platform java`. …
```

passthrough 3DS for Pin Payments

---

CHANGELOG
lib/active_merchant/billing/gateways/cyber_source.rb
test/remote/gateways/remote_cyber_source_test.rb
test/unit/gateways/cyber_source_test.rb

CyberSource requires certain billing address fields be sent in with requests. The existing `setup_address_hash` method has been updated so that if it receives a value of `nil` for any of the `billing_address` subfields, it will send `nil` to the gateway. If a `billing_address` subfield is received without an override value or with an empty string value, it will be replaced with the default_address value found in the `setup_address_hash` method.
[CE-1281](https://spreedly.atlassian.net/browse/CE-1281)
Local tests:
4606 tests, 72931 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
102 tests, 499 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
95 tests, 491 assertions, 5 failures, 0 errors, 0 pendings, …

CyberSource: Update `billing_address` override

---

CHANGELOG
lib/active_merchant/billing/gateways/paymentez.rb
test/remote/gateways/remote_paymentez_test.rb
test/unit/gateways/paymentez_test.rb

3DS MPI fields are not currently supported for Paymentez gateway (ECS-1608)
Source: https://paymentez.github.io/api-doc/#payment-methods-cards-debit-with-token-base-case
Adds 3DS MPI field support to Paymentez gateway.
Remote tests are permissive and do not allow for failure cases due to invalid parameters, so only successful remote tests were added.
Unit Tests:
---
4608 tests, 72918 assertions, 0 failures, 0 errors, 0 pendings,
100% passed
Rubocop:
---
693 files inspected, no offenses detected
Remote Tests:
---
30 tests, 70 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions,
100% passed

Paymentez: Add 3DS MPI field support

---

CHANGELOG
lib/active_merchant/billing/gateways/blue_snap.rb
test/remote/gateways/remote_blue_snap_test.rb
test/unit/gateways/blue_snap_test.rb

Add support for the `fraud-session-id` field within the `transaction-fraud-info` object. Update the previously used `ip` field to be `shopper_ip_address` within the `transaction_fraud-info` object. Additional details can be found via [BlueSnap's Documentation](https://developers.bluesnap.com/v8976-XML/docs/transaction-fraud-info). Sample request and response content can be found in [BlueSnap's Auth Capture documentation](https://developers.bluesnap.com/v8976-XML/docs/auth-capture)
Local:
4611 tests, 72957 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
39 tests, 229 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
48 tests, 164 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 …

BlueSnap: Add support `fraud-session-id` field

---

CHANGELOG
lib/active_merchant/billing/gateways/blue_snap.rb
test/remote/gateways/remote_blue_snap_test.rb
test/unit/gateways/blue_snap_test.rb

The `shopper-ip-address` field will now accept `ip` as a top level field within the received `options` hash rather than it needing to be nested within `transaction-fraud-info`
Local
4615 tests, 72965 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote
48 tests, 164 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit
39 tests, 229 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

BlueSnap: Update handling of `transaction-fraud-info` fields

---

lib/active_merchant/billing/gateways/firstdata_e4_v27.rb
test/unit/gateways/firstdata_e4_v27_test.rb

Firsdata/Payeezy contacted Shopify to let us know that they need
the ECI for applepay/discover to be set to 5 and not 4.
See: https://support.payeezy.com/hc/en-us/articles/203730589-Ecommerce-Flag-Values
We also need to pass a WalletProviderID of 4 when the card source
is apple pay.
See: https://support.payeezy.com/hc/en-us/articles/206601408-First-Data-Payeezy-Gateway-Web-Service-API-Reference-Guide#3.9

[Firstdatae427] Fixes some apple pay transaction issues

---

CHANGELOG
lib/active_merchant/billing/gateways/global_collect.rb
test/remote/gateways/remote_global_collect_test.rb
test/unit/gateways/global_collect_test.rb

The gateway has various character limits for a few of the `billingAddress` and `shippingAddress` fields. These character limits are now being enforced and include `street`, `state`, and `additionalInfo`.
CE-1016
Unit:
27 tests, 133 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
24 tests, 59 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
95.8333% passed
One unrelated failure, also failing on main branch

GlobalCollect: Truncate address fields

---

CHANGELOG
lib/active_merchant/billing/gateways/litle.rb
test/remote/gateways/remote_litle_test.rb
test/unit/gateways/litle_test.rb

The gateway has a character limit of 35 for `address` fields. This is now being enforced on `address1`, `address2` and `city` fields.
CE-1017
Local:
4625 tests, 73027 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
50 tests, 218 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
46 tests, 196 assertions, 13 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
71.7391% passed
Tests failing are also failing on main branch

Vantiv/Litle: Truncate address fields

---

CHANGELOG
lib/active_merchant/billing/gateways/worldpay.rb
test/remote/gateways/remote_worldpay_test.rb
test/unit/gateways/worldpay_test.rb

Unit:
77 tests, 500 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote (before changes):
58 tests, 242 assertions, 5 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
91.3793% passed
Remote (after changes):
59 tests, 246 assertions, 5 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
91.5254% passed
CE-1301

Worldpay: allow purchase without capture

---

CHANGELOG
lib/active_merchant/billing/gateways/redsys.rb

Adds a new response code (195 - Requires SCA authentication), fixes a typo
Remote:
25 tests, 76 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
42 tests, 161 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Redsys: Add code 0195, fix typo

---

CHANGELOG
lib/active_merchant/billing/gateways/orbital.rb
test/remote/gateways/remote_orbital_test.rb

Gateway Name: Orbital (Chase Paymentech)
Short Summary: Updating ECP details to look at the payment source for account information instead of options, fixed tests to reflect that
Unit:
Started
.......................................................................................................
Finished in 0.343716 seconds.
----------------------------------------------------------------------------------------------------------
103 tests, 617 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
----------------------------------------------------------------------------------------------------------
299.67 tests/s, 1795.09 assertions/s
Remote:
Started …

Updating add_ecp_details

---

.github/workflows/ruby-ci.yml

This is a followup to the same PR in [activemerchant/payment_icons](https://github.com/activemerchant/payment_icons/pull/400), so we Github Actions behavior similar in other `activemerchant` repos.

Run GitHub Actions CI on PRs

---

CHANGELOG
lib/active_merchant/billing/gateways/elavon.rb
test/remote/gateways/remote_elavon_test.rb
test/unit/gateways/elavon_test.rb

Unicode characters greater than 1 byte appear to result in an increase
in length+1 for each character for each byte greater than 1.
`force_encoding('iso-8859-1')` on the individual piece of data and then
re-encoding the request data to `utf-8` seems to resolve the issue.
CE-1231
Unit: 41 tests, 226 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 35 tests, 165 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Elavon: Fix issue with encoding data sent in the request

---

.github/workflows/ruby-ci.yml

Rails master is now on 7.0.0 alpha, and it doesn't work with ruby under 2.7.

Fix the tests for Gemfile.rails_master

---

CHANGELOG
lib/active_merchant/billing/gateways/stripe_payment_intents.rb
test/remote/gateways/remote_stripe_payment_intents_test.rb
test/unit/gateways/stripe_payment_intents_test.rb

Ensure `setup_future_sage` and `off_session` work when using SetupIntents and
PaymentIntents APIs
ECS-1512
Local:
4630 tests, 73058 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
52 tests, 244 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
20 tests, 132 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Ensure `setup_future_usage` and `off_session` work 

---

CHANGELOG
lib/active_merchant/billing/gateways/elavon.rb
test/remote/gateways/remote_elavon_test.rb

The `&` char converts to the longer html encoding AFTER truncated,
resulting in the request being rejected for strings that are too long.
Easiest solution is to just remove the `&` from any value added to the
xml.
CE-1231
Unit: 42 tests, 229 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 35 tests, 165 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Elavon: Remove ampersand char from fields

---

CHANGELOG
test/remote/gateways/remote_orbital_test.rb

Includes use of a new MID for 3DS remote tests
56 tests, 270 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
107 tests, 637 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Updating remote_orbital_test to use three_ds_gateway

---

CHANGELOG
lib/active_merchant/billing/gateways/mercado_pago.rb
test/remote/gateways/remote_mercado_pago_test.rb

No valid test card number is known for Creditel, so no tests were added.
Unit:
38 tests, 175 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
32 tests, 94 assertions, 3 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
90.625% passed
Failing tests (also seen in #3741 ):
- test_successful_purchase_with_taxes_and_net_amount
- test_successful_purchase_with_processing_mode_gateway
- test_partial_capture
CE-1295

Mercado Pago: support Creditel card type

---

CHANGELOG
lib/active_merchant/billing/gateways/payeezy.rb
test/remote/gateways/remote_payeezy_test.rb
test/unit/gateways/payeezy_test.rb

When a `bank_resp_code` is returned and is not equal to '100', it is mapped to `error_code`. If a transaction errors for a different reason and a `bank_resp_code` is not returned, the `error_code` will reflect its previous behavior, pulling the `code` from `messages` within the `Error` field in the response.
CE-1303
Remote:
36 tests, 141 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
36 tests, 172 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Payeezy: Update error mapping

---

CHANGELOG
lib/active_merchant/billing/gateways/hps.rb
test/remote/gateways/remote_hps_test.rb
test/unit/gateways/hps_test.rb

Heartland Payment System treats recurring purchases as a separate transaction type.
The initiator field (here referred to as 'CardOnFile') and the network_transaction_id are both nested under Transaction -> CreditSale -> Block1 -> CardonFileData
The reason_type (signified by the 'OneTime' indicator at HPS)is nested under Transaction -> RecurringBilling -> Block1 -> RecurringData
This structure required supporting the recurring transaction type so that stored credentials can be supported for this gateway.
Local:
4630 tests, 73050 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
55 tests, 152 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
57 tests, 283 assertions, 0 failures, 0 errors, 0 pendings, 0 …

Add Support for Stored Credentials on HPS gateway

---

CHANGELOG
lib/active_merchant/billing/gateways/orbital.rb
test/remote/gateways/remote_orbital_test.rb
test/unit/gateways/orbital_test.rb

110 tests, 649 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
59 tests, 281 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Orbital: Ensure payment_detail sends for ECP

---

CHANGELOG
lib/active_merchant/billing/gateways/payeezy.rb
test/remote/gateways/remote_payeezy_test.rb

CE-1303
Update `error_code_from` method to send `nil` if `bank_resp_code` is present and equal to '100', map the value of `bank_resp_code` to `error_code` if it is not equal to '100'
Unit:
36 tests, 172 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
36 tests, 141 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Payeezy: Update `error_code_from` method

---

CHANGELOG
lib/active_merchant/billing/gateways/worldpay.rb
test/remote/gateways/remote_worldpay_test.rb
test/unit/gateways/worldpay_test.rb

CE-1341
Unit:
78 tests, 504 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
60 tests, 249 assertions, 5 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
- 5 failing tests also fail on master branch

Worldpay: Add support for `statementNarrative` field

---

CHANGELOG
lib/active_merchant/billing/gateways/mercado_pago.rb
test/remote/gateways/remote_mercado_pago_test.rb
test/unit/gateways/mercado_pago_test.rb

Users can pass `true` as the `capture` value to execute a force capture
on an authorize transaction, which changes the initial default value for
this option from `false`. Mercado Pago defaults the `capture` value to
`true` unless it is explicitly set to `false`.
CE-1332
Unit: 39 tests, 181 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 33 tests, 96 assertions, 3 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications

Mercado Pago: Give ability to pass capture option in authorize txn

---

CHANGELOG
lib/active_merchant/billing/gateways/orbital.rb
test/remote/gateways/remote_orbital_test.rb

110 tests, 649 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
61 tests, 295 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Orbital: Send ECP details with refund

---

CHANGELOG
lib/active_merchant/billing/gateways/worldpay.rb
test/remote/gateways/remote_worldpay_test.rb
test/unit/gateways/worldpay_test.rb

ECS-14244
ActiveMerchant sends default values to WorldPay for the billing address when no value is given. This can be problematic when the gateway needs to do address verification.
This commit removes the defaults for billing address state, address1, and city. The WorldPay docs specify that if either field of address1 and city is given, the other must also be, so defaulting was added for these fields when only one or the other is given.
Worldpay Remote Tests Before:
60 tests, 249 assertions, 5 failures, 0 errors, 0 pendings,
Worldpay Remote Tests After:
61 tests, 250 assertions, 5 failures, 0 errors, 0 pendings,
Unit Tests:
4652 tests, 73157 assertions, 0 failures, 0 errors, 0 pendings,
693 files …

WorldPay: remove some defaults in billing address

---

CHANGELOG
lib/active_merchant/billing/gateways/worldpay.rb
test/unit/gateways/worldpay_test.rb

ECS-1706
PR #3902 removed some defaults per the Worldpay documentation. While the sandbox allowed these fields to be blank, the production gateway wants them filled in.
This commit reverts the address1 and city changes to always default to a non-null value.
Worldpay remote tests (same pass rate as master):
61 tests, 250 assertions, 5 failures, 0 errors, 0 pendings, 0 omissions,
91.8033% passed
Unit tests:
4652 tests, 73159 assertions, 0 failures, 0 errors, 0 pendings,
100% passed

Worldpay: reintroduce address1 and city defaults

---

CHANGELOG
lib/active_merchant/billing/gateways/stripe_payment_intents.rb
test/remote/gateways/remote_netbanx_test.rb
test/remote/gateways/remote_stripe_payment_intents_test.rb
test/unit/gateways/stripe_payment_intents_test.rb

Currently we are passing the validate field to Stripe PI’s /customers endpoint rather than the /payment_methods endpoint. This field is essentially ignored by the /customers endpoint, and all payment methods are being validated, even if the request was sent with ”validate”: false. This commit includes updates to instead pass "validate": false during the attachment step (POST /v1/payment_methods/:id/attach), rather than when the customer is being created. This will guarantee that Stripe does not validate cards when users do not want to do so.
ECS-1681
Unit:
23 tests, 141 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
54 tests, 250 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Local:
4655 tests, 73169 …

Stripe PI: Send Validate on Payment Method Attach

---

CHANGELOG
lib/active_merchant/billing/gateways/adyen.rb
test/remote/gateways/remote_adyen_test.rb

Add test to confirm successful refund possible using `pspReference` from an `authorize` transaction instead of a `capture` transaction. Update test cards that had expired.
CE-803
Local:
4650 tests, 73149 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
71 tests, 372 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
94 tests, 361 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Adyen: Update handling of authorization returned from gateway

---

CHANGELOG
lib/active_merchant/billing/gateways/orbital.rb
test/remote/gateways/remote_orbital_test.rb
test/unit/gateways/orbital_test.rb

114 tests, 668 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
65 tests, 306 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Orbital: Send AVSname for all eCheck transactions

---

CHANGELOG
lib/active_merchant/billing/gateways/litle.rb
test/remote/gateways/remote_litle_test.rb
test/unit/gateways/litle_test.rb

Went to expand the use of customer_id field for use on capture and refund per request. Discovered that AM was not sending the field to the gateway correctly. The field `customer` should have been `customer_id` to work properly. Added tests for the field and confirmed that it is now being sent correctly.
Failing tests match the tests failing on master:
test_authorize_and_capture_with_stored_credential_recurring(RemoteLitleTest)
test_avs_and_cvv_result(RemoteLitleTest)
test_capture_unsuccessful(RemoteLitleTest)
test_echeck_store_and_purchase(RemoteLitleTest)
test_purchase_with_token_and_date_successful(RemoteLitleTest)
test_refund_unsuccessful(RemoteLitleTest)
test_store_and_purchase_with_token_successful(RemoteLitleTest)
test_store_successful(RemoteLitleTest) …

Correct customer_id field on Litle/Vantiv Gateway

---

CHANGELOG
lib/active_merchant/billing/gateways/forte.rb
test/remote/gateways/remote_forte_test.rb
test/unit/gateways/forte_test.rb

Loaded suite test/unit/gateways/forte_test
22 tests, 85 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Loaded suite test/remote/gateways/remote_forte_test
23 tests, 73 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Forte: Send xdata fields

---

CHANGELOG
lib/active_merchant/billing/gateways/orbital.rb
test/remote/gateways/remote_orbital_test.rb
test/unit/gateways/orbital_test.rb

113 tests, 664 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
64 tests, 302 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
4662 tests, 73206 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Orbital: Remove unnecessary requirements checks

---

CHANGELOG
test/remote/gateways/remote_stripe_payment_intents_test.rb

Ensure the responses expected from /setup_intents/ endpoint match the
expected shape.
Local:
4652 tests, 73160 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
53 tests, 251 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
20 tests, 132 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Stripe PI: Enhance testing of SetupIntents API

---

CHANGELOG
lib/active_merchant/billing/gateways/safe_charge.rb

The NT transaction fails if one of the 3DS params is not passed in the request. The change sets a default value correctly if the param is not passed in the request.
Unit:
24 tests, 130 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
28 tests, 71 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
92.8571% passed
The two tests that failed (test_successful_3ds_purchase and test_successful_regular_purchase_through_3ds_flow_with_invalid_pa_res) were failing before as well.
Local:
4677 tests, 73271 assertions, 4 failures, 3 errors, 0 pendings, 0 omissions, 0 notifications
99.8503% passed
None of the failures/errors are related to Safecharge gateway

SafeCharge: Fix nil error for NT flow

---

CHANGELOG
lib/active_merchant/billing/gateways/orbital.rb
test/remote/gateways/remote_orbital_test.rb
test/unit/gateways/orbital_test.rb
test/unit/gateways/worldpay_test.rb

General credit transactions utilize the same endpoint as `refund`, but do not require a `tx_ref_num` and should be passed a payment method
CE-1312
Local: 4677 tests, 73272 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit: 114 tests, 670 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 65 tests, 304 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Orbital: Add support for general credit

---

CHANGELOG
lib/active_merchant/billing/gateways/redsys.rb
test/remote/gateways/remote_redsys_sha256_test.rb
test/unit/gateways/redsys_sha256_test.rb

The use of `sca_exemption` requires passing
`DS_MERCHANT_DIRECTPAYMENT=true` for those terminals where 3DS2 is
enabled.
This commit introduces a new option
`sca_exemption_direct_payment_enabled` that can be used to pass this
value, when needed
ECS-1747
Local:
45 tests, 183 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
30 tests, 103 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
4681 tests, 73300 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Note:
`test/remote/gateways/remote_redsys_test.rb`:
- failing same as current HEAD, 3633283fa2606321f87f94bdecacc2307b91ed16

Banco Sabadell: Ensure sca_exemption field is used

---

CHANGELOG
lib/active_merchant/billing/gateways/redsys.rb
test/unit/gateways/redsys_sha256_test.rb

Enables AM API clients to override decision to escape in case different
criteria than default is needed
Local:
4682 tests, 73306 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
45 tests, 183 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
31 tests, 111 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Redsys: Refactor XML character escape logic

---

CHANGELOG
lib/active_merchant/billing/gateways/hps.rb
test/remote/gateways/remote_hps_test.rb
test/unit/gateways/hps_test.rb

CE-1428
Local: 4682 tests, 73306 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit: 60 tests, 293 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 57 tests, 154 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
96.4912% passed
**Notice:** Tests relying on the `hps_echeck` credentials are currently failing with an `Authorization` error. As a result, reviewers should expect 2 failing remote tests. A message will be sent to the gateway in an effort to resolve this, but for the meantime we will move forward with the changes in this PR.

HPS: Strip zip codes of non-alphanumeric characters

---

CHANGELOG
lib/active_merchant/billing/gateways/worldpay.rb
test/remote/gateways/remote_worldpay_test.rb
test/unit/gateways/worldpay_test.rb

Most of the changes include test coverage for the updated configuration
for the Worldpay merchant, where responses now reflect a synchronous
workflow. The primary change is in the response message and in some
cases the structure of the response that is returned.
In the case of a `capture` transaction, the previous criteria for
success would expect to find an XML tag `<ok>`. For the changes in the
response, we can now more consistently look for the value in the
`<lastEvent>` tag. See difference in the response methods on line 1252 and 1269.
Refer to the new `synchronous_response` methods and compare them to
their counterparts to see the difference in what we expect from the
current implementation versus the new changes.
Refund remote test: Worldpay does not appear to `settle` a `capture` …

Worldpay synchronous response changes

---

CHANGELOG
lib/active_merchant/billing/gateways/payway_dot_com.rb
test/remote/gateways/remote_payway_dot_com_test.rb
test/unit/gateways/payway_dot_com_test.rb

The scrub method didn't scrub responses properly as the response has some extra spaces. Additionally, failed transactions include the account number in message field.Even though it is the invalid account number it must be scrubbed as we don't know what part of it is invalid, maybe just 1 didgit. This commit includes changes to fix described issues. Remote tests and unit tests were expanded also.
ECS-1713
Unit:
15 tests, 62 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
16 tests, 43 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

PaywayDotCom: Improve Scrubbing

---

CHANGELOG
lib/active_merchant/billing/gateways/adyen.rb
test/remote/gateways/remote_adyen_test.rb
test/unit/gateways/adyen_test.rb

Add the Network Transaction Reference for MIT requests - see https://docs.adyen.com/api-explorer/#/Payout/v30/post/payout__reqParam_additionalData-AdditionalDataCommon-networkTxReference
The new tests assume the test merchant has toggled on Network
Transaction Reference in the Additional Data Settings of the API URLs
section of the Adyen account dashboard. Otherwise the value is not
returned in initial responses.
Also add this value as a param on the Response itself.
Remote (2 failures on master):
96 tests, 361 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
97.9167% passed
Unit:
73 tests, 384 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Adyen: Pass Network Tx Reference for MIT

---

CHANGELOG
lib/active_merchant/billing/gateways/qvalent.rb
test/fixtures.yml
test/remote/gateways/remote_qvalent_test.rb
test/unit/gateways/qvalent_test.rb

To all transactions in the normal payment flow
Update fixtures file to explain how to set up the appropriate credentials for testing
Update `card.storedCredentialUsage` field and 3DS `order.xid` and others
Update deprecated `INITIAL_STORAGE` to `UNSCHEDULED_MIT` in unit test and nest order object into 3DS options
[CE-1337](https://spreedly.atlassian.net/browse/CE-1337)
Unit:
27 tests, 128 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
100% passed

Qvalent: add `customer_reference_number`

---

CHANGELOG
lib/active_merchant/billing/gateways/adyen.rb
lib/active_merchant/billing/gateways/orbital.rb

116 tests, 683 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
100% passed
4691 tests, 73342 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Orbital: Add 'ND' ECPActionCode to $0 Prenote Check

---

CHANGELOG
lib/active_merchant/billing/gateways/checkout_v2.rb
test/remote/gateways/remote_checkout_v2_test.rb
test/unit/gateways/checkout_v2_test.rb

CE-1444
Local:
4692 tests, 73353 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
30 tests, 140 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
34 tests, 88 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Checkout: Add support for stored_credential

---

CHANGELOG
lib/active_merchant/billing/gateways/credorax.rb
test/remote/gateways/remote_credorax_test.rb
test/unit/gateways/credorax_test.rb

Unit:
69 tests, 333 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
43 tests, 158 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
CE-1446

Credorax: Add support for 3ds_reqchallengeind

---

CHANGELOG
lib/active_merchant/billing/gateways/adyen.rb
test/remote/gateways/remote_adyen_test.rb
test/unit/gateways/adyen_test.rb

Support the cancelOrRefund endpoint when `cancel_or_refund` boolean
option is passed. Void transaction defaults to 'cancel' if the value is
false or non-existent.
Test were failing because of a change in the expected error message from
Adyen
CE-1408
Unit: 74 tests, 387 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 97 tests, 373 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Adyen: cancelOrRefund endpoint when passed as option

---

CHANGELOG
lib/active_merchant/billing/gateways/orbital.rb
test/remote/gateways/remote_orbital_test.rb

* Ensuring line_items are passed on capture
* Fixed a DTD issue with Level3 tax format
Loaded suite /Users/jessiagee/.asdf/installs/ruby/2.5.7/lib/ruby/gems/2.5.0/gems/rake-13.0.3/lib/rake/rake_test_loader
4696 tests, 73364 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
696 files inspected, no offenses detected
116 tests, 683 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
68 tests, 316 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Orbital: Pass line_items on capture

---

CHANGELOG
lib/active_merchant/billing/gateways/braintree_blue.rb
test/remote/gateways/remote_braintree_blue_test.rb
test/unit/gateways/braintree_blue_test.rb

If a merchant sends the field `allow_card_verification` as `true`, the `verify` method will utilize Braintree's credit-card-verification endpoint. If `allow_card_verification` is sent as `false` or not sent at all, it will execute the `verify` with the existing authorize/void transaction flow as it has in the past. To note: `allow_card_verification` is not a gateway supported field so it is not passed on to Braintree during the `verify` process. The purpose of the field is to direct which flow the `verify` method should use.
CE-555
Local:
4697 tests, 73368 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
82 tests, 188 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
83 tests, 442 assertions, 0 …

Braintree: Add support for $0 auth verification

---

CHANGELOG
lib/active_merchant/billing/gateways/braintree_blue.rb
test/remote/gateways/remote_braintree_blue_test.rb
test/unit/gateways/braintree_blue_test.rb

Local:
4703 tests, 73388 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
82 tests, 189 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
83 tests, 444 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Braintree: Return `cvv_code` and `avs_code` in response

---

lib/active_merchant/billing/gateways/braintree_blue.rb
test/remote/gateways/remote_braintree_blue_test.rb
test/unit/gateways/braintree_blue_test.rb

The `risk_data` information, [seen here in Braintree's documentation](https://developers.braintreepayments.com/reference/request/transaction/sale/ruby#risk_data), can be sent for fraud analysis
CE-1488
Local:
4705 tests, 73392 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
83 tests, 190 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
84 tests, 446 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Braintree: Add support for `risk_data` fields

---

lib/active_merchant/billing/gateways/credorax.rb
test/unit/gateways/credorax_test.rb

CE-1308
According to Credorax, the collection of `3ds_shipaddr` fields must all have a value or else none of them should be sent in the request.
Unit
Loaded suite test/unit/gateways/credorax_test
70 tests, 344 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote
Loaded suite test/remote/gateways/remote_credorax_test
43 tests, 158 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Credorax: do not send 3ds shipping address fields if any are blank

---

CHANGELOG
lib/active_merchant/billing/check.rb
test/unit/check_test.rb

Add support for Canadian bank accounts, specifically validate routing
numbers. Validation is performed against the first 3 digits of the
routing number and a list financial institution numbers.
CE-1468
Unit: 10 tests, 22 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:

Support Canadian Bank Accounts

---

CHANGELOG
lib/active_merchant/billing/gateways/cyber_source.rb
test/unit/gateways/cyber_source_test.rb

This update does not change how mdd_field is passed in with a transaction, only how it is adjusted for proper xml formatting according to [CyberSource gateway documentation](https://support.cybersource.com/s/article/What-is-an-XML-example-of-merchant-defined-data-fields-mddField-in-an-SOAP-call). Based on this, it should not break existing customer's use of the field.
CE-258
Local:4710 tests, 73418 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit: 102 tests, 499 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 95 tests, 490 assertions, 6 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
93.6842% passed
Failing remote tests are also failing on master branch: …

CyberSource: Update XML tag for merchantDefinedData

---

lib/active_merchant/billing/gateways/d_local.rb
test/remote/gateways/remote_d_local_test.rb

CE-1511
This PR adds `elo`, `alia`, and `carnet` to the list of cardtypes supported by the dLocal gateway.
It also adds fixes for the remote dLocal tests, most of which were failing. A new `payer.document` was required to get most of the tests passing again.
The test `test_failed_purchase_with_cabal` was removed because dLocal's sandbox does not validate cards and simply returns a success unless a failure is stimulated in the `description` field of the request (see https://docs.dlocal.com/guides/getting-started/sandbox-testing#testing-payments). 
I am seeing two failing remote tests, `test_successful_refund` and `test_partial_refund`, both of which fail with an `insufficient funds` error. This is because the sandbox merchant account has a (fake) funds balance that is currently in the …

dLocal: Add supported cardtypes

---

CHANGELOG
lib/active_merchant/billing/gateways/elavon.rb
test/remote/gateways/remote_elavon_test.rb
test/unit/gateways/elavon_test.rb

CE-1525
Remote tests currently failing on my machine due to unresolved credentialing issues. Any reviewer should run `test/remote/gateways/remote_elavon_test.rb` and verify that all remote tests are passing.
rubocop:
local:
4711 tests, 73421 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Elavon: Send `ssl_vendor_id` field

---

CHANGELOG
test/remote/gateways/remote_credorax_test.rb
test/unit/gateways/credorax_test.rb

`d2` is known as an echo parameter, which will be returned in the transaction response if the respective parameter is sent in the request
CE-1078
Local:
4716 tests, 73439 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
76 tests, 365 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
44 tests, 161 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Credorax: Add support for `d2` field

---

CHANGELOG
lib/active_merchant/billing/gateways/worldpay.rb
test/remote/gateways/remote_worldpay_test.rb
test/unit/gateways/worldpay_test.rb

Note: Currently, the cancelOrRefund method behaves in a way opposite to what Worldpay docs claim.  See https://developer.worldpay.com/docs/wpg/manage/modificationrequests#xml-reference: `<cancelOrRefund> ... Must include the <amount> information`, but actually doing this causes an error.
CE-1208
Remote:
------
67 tests, 289 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
97.0149% passed
Failures: test_3ds_version_2_parameters_pass_thru, test_3ds_version_1_parameters_pass_thru
Unit:
----
85 tests, 530 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Worldpay: support cancelOrRefund via options

---

CHANGELOG
lib/active_merchant/billing/gateways/payeezy.rb
test/remote/gateways/remote_payeezy_test.rb
test/unit/gateways/payeezy_test.rb

Adds the ability to credit a customer without a prior transaction id connected to the refund.
remote:
38 tests, 151 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
unit:
38 tests, 180 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
local:
4711 tests, 73422 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Enable General Credit on Payeezy gateway

---

CHANGELOG
lib/active_merchant/billing/credit_card_methods.rb
test/unit/credit_card_methods_test.rb

Adding several bins for MC and 1 for Maestro.
Change check on ln:207 from `range.cover?(bin)` to
`range.include?(bin)`.
The reason for this is, upon adding arrays of individual bins (following
existing convention in this file), `cover?` only applies to a range of
values. `include?` allows us to add single value arrays in existing bin
range sets and achieve same outcomes.
`include?` and `cover?` are both inclusive, so:
`(1..2).cover?(1)` returns `true`
`(1..2).include?(1)` returns `true`
CE-1593
Unit: 44 tests, 503 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: No Remote Tests

Bin Range Update

---

Gemfile
lib/active_merchant/billing/gateways/adyen.rb
test/remote/gateways/remote_adyen_test.rb
test/unit/gateways/adyen_test.rb

Apply default card holder name for credit cards as well, not just `NetworkTokenizationCreditCard`. Covers cards that are passed in without a name.
---
remote:
98 tests, 375 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
unit:
75 tests, 391 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
local:
4720 tests, 73455 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
RuboCop:

Adyen: Set default card holder name

---

CHANGELOG
lib/active_merchant/billing/gateways/qvalent.rb
test/unit/gateways/qvalent_test.rb

CE-1176
Local:
4720 tests, 73460 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
Loaded suite test/remote/gateways/remote_qvalent_test
100% passed
Rubocop:

Qvalent: remove `pem_password` from required creds

---

CHANGELOG
lib/active_merchant/billing/gateways/authorize_net.rb
test/remote/gateways/remote_authorize_net_test.rb
test/unit/gateways/authorize_net_test.rb

Add support for reccuring payment types. Extract networkTransId into response. Set originalNetworkTransId for all MIT transactions. Set isFirstRecurringPayment if it is a first recurring transaction.
ECS-1817
Unit:
107 tests, 637 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
73 tests, 269 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Authorize.Net: Stored Credential Support Improvements

---

lib/active_merchant/billing/gateways/cyber_source.rb
test/remote/gateways/remote_cyber_source_test.rb
test/schema/cyber_source/CyberSourceTransaction_1.181.xsd
test/unit/gateways/cyber_source_test.rb

This PR adds the following five fields to the CyberSource gateway adapter:
- billTo.merchantTaxID
- salesSlipNumber
- installment.planType
- installment.firstInstallmentDate
- airlineData.agentCode
This PR also includes a new XML Schema Definition (XSD) for the CyberSource Gateway. This serves as a reference for the expected format/nesting of the new fields.
CE-1541
Remote:
98 tests, 502 assertions, 6 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
93.8776% passed
**The following remote tests are currently failing on master as well as this branch:**
test_successful_validate_pinless_debit_card
test_successful_pinless_debit_card_purchase
test_successful_tax_calculation
test_successful_authorization_and_failed_capture
test_successful_3ds_validate_authorize_request …

CyberSource: Support multiple new fields

---

lib/active_merchant/billing/gateways/authorize_net_cim.rb
test/remote/gateways/remote_authorize_net_cim_test.rb
test/unit/gateways/authorize_net_cim_test.rb

Currently the 'unmaskExpirationDate' option only exists when getting a
customer payment profile. If you get a customer profile, which in turn
includes connected customer payment profiles, this option is not
available.
That would mean in cases where you may be trying to get a default card,
or just a list of cards, you need to make 2..n calls in order to get the
expiration date.
Additionally, the Auth.net CIM api allows for getting the issuer info:
- The Issuer Identification Number (IIN)
- Also sometimes known as the Bank Identification Number (BIN)
- Not all issuers are banks
This adds the issuer info option as well to both the customer profile call
and the customer payment profile call.

Add 'unmaskExpirationDate' and 'includeIssuerInfo' to customer profile call

---

lib/active_merchant/billing/gateways/cashnet.rb
test/remote/gateways/remote_authorize_net_cim_test.rb
test/remote/gateways/remote_cashnet_test.rb

**Note for running CASHNet remote tests:**
If you run the remote tests as is, you will see a failure on `test_successful_purchase_and_refund` and `test_successful_refund_with_options`. This is because CASHNet's test api requires one business day to pass between the purchase transactions and the attempted refund. One way around this is to send a test purchase transaction, copy the transaction number in the `tx` field of the response, _wait one day_, and then replace the `purchase.authorization` variable with your saved transaction number in the test's refund call.
I have saved up a few of these transactions numbers so you can message me whenever you intend to run the remote tests.
CE-798
Local:
4719 tests, 73458 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications …

CASHNet: Update Gateway Adapter

---

CHANGELOG
lib/active_merchant/billing/gateways/elavon.rb
test/unit/gateways/elavon_test.rb

This PR makes it so that ssl_vendor_id can be passed via the options provided to the gateway on initialization (`@options`) as opposed to just on a per-transaction basis (`options`).
CE-1660
Remote:
35 tests, 165 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Local:
4732 tests, 73513 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Rubocop:

Elavon: pass ssl_vendor_id

---

CHANGELOG
Gemfile
lib/active_merchant/billing/gateways/braintree_blue.rb
test/unit/gateways/braintree_blue_test.rb

We want to be able to support Braintree's 3.0.1 gem with active merchant, as this give us access to some new parameters we need. 
This required two changes:
1. Update lib/active_merchant/billing/gateways/braintree_blue.rb to support braintree versions of 3.0.x
2. `android_pay_card` has been renamed to `google_pay_card`, so `ActiveMerchant::Billing::BraintreeBlueGateway#add_payment_method` has been modified to be aware of that.
I have ran the Braintree remote test suite, and nothing is breaking with this change. This shouldn't introduce any breaking changes.
```
4731 tests, 73512 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
```

Support braintree 3.0.1

---

CHANGELOG
lib/active_merchant/billing/gateways/braintree_blue.rb

Lift restriction on the Braintree gem version to allow for versions
older than 3.* to work with AM. A part of this is to dynamically
determine the key name for pay card (`google_pay_card` for versions > 3
and `android_pay_card` for older versions).
CE-1579
Unit: 83 tests, 190 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 84 tests, 444 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
97.619% passed

Remove Braintree Version Restriction

---

lib/active_merchant/billing/gateways/paypal_express.rb
test/unit/gateways/paypal_express_test.rb

When processing a transaction on PayPal buyer account based on a previous transaction, including the optional merchant session id field will allow PayPal to have additional mean to detect possible fraud.  This pull request include this optional field when available to PayPal express `DoReferenceTransaction` request.
This functionality available in [paypal_common_api.rb](https://github.com/activemerchant/active_merchant/blob/master/lib/active_merchant/billing/gateways/paypal/paypal_common_api.rb#L419)  but not in `paypal_express.rb` 
PayPal documentation: https://developer.paypal.com/docs/nvp-soap-api/do-reference-transaction-soap/

Enable PayPal express gateway to send merchant session id with DoReferenceTransaction

---

CHANGELOG
lib/active_merchant/billing/gateways/payment_express.rb
test/remote/gateways/remote_payment_express_test.rb
test/unit/gateways/payment_express_test.rb

Verify call was not passing the currency code to the Payment Express aka Windcave gateway. It appears it was not passing an amount originally, which is needed in order to verify with a currency code.
Local:
4733 tests, 73517 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
37 tests, 263 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
17 tests, 79 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Add amount to verify calls for Payment Express/Windcave

---

CHANGELOG
lib/active_merchant/billing/gateways/checkout_v2.rb
test/remote/gateways/remote_checkout_v2_test.rb
test/unit/gateways/checkout_v2_test.rb

Added `metadata` fields to request payment, capture, void, and refund per [Checkout's documentation](https://api-reference.checkout.com/#operation/requestAPaymentOrPayout)
Local
4735 tests, 73541 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit
34 tests, 169 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote
38 tests, 99 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

CE-1043 checkout metadata

---

CHANGELOG
lib/active_merchant/billing/gateways/adyen.rb
test/remote/gateways/remote_adyen_test.rb
test/unit/gateways/adyen_test.rb

Add support to pass `networkTxReference`, from initial auth
transactions, to subsequent MIT requests. We also extract the
`networkTxReference` from the gateway response and add it to the
`network_transaction_id` field in the Response object.
CE-1603
Unit: 76 tests, 397 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 99 tests, 378 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Adyen: Support networkTxReference field

---

CHANGELOG
lib/active_merchant/billing/gateways/pay_trace.rb
test/fixtures.yml
test/remote/gateways/remote_pay_trace_test.rb
test/unit/gateways/pay_trace_test.rb

- Support the following standard AM methods: authorize, capture, purchase, void, refund, store and verify
- Authorize and purchase methods support receiving PAN or vaulted customer ID
- Support additional general methods: redact, settle
- [PayTrace API documentation](https://developers.paytrace.com/support/home)
CE-1601
Local:
4748 tests, 73563 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
16 tests, 49 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
21 tests, 56 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

PayTrace: new gateway build

---

CHANGELOG
lib/active_merchant/billing/gateways/nmi.rb
test/remote/gateways/remote_nmi_test.rb
test/unit/gateways/nmi_test.rb

NMI is now using `cardholder_auth` to determine the `eci` value at the gateway level.
Local:
4757 tests, 73618 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
46 tests, 352 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
42 tests, 156 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Update NMI 3DS2 field for eci

---

CHANGELOG
lib/active_merchant/billing/gateways/payu_latam.rb
test/remote/gateways/remote_payu_latam_test.rb
test/unit/gateways/payu_latam_test.rb

Corrects the mapping of phone numbers from `shipping_address` object, so that if a payment method has a phone number saved to it that will be mapped first (`billing_address[:phone]`), otherwise if the transaction contains `shipping_address[:phone_number]` that will be mapped, otherwise we will map an empty string.
CE-1665
2 unrelated failing tests (also failing on master):
`test_successful_purchase_colombia` (timeout response from colombia sandbox)
`test_well_formed_refund_fails_as_expected` (failing for at least a while, e.g.: https://github.com/activemerchant/active_merchant/pull/3657)
Rubocop:
702 files inspected, no offenses detected
Unit:
4760 tests, 73628 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
35 tests, 83 assertions, 2 …

PayULatam: adjust phone number mapping

---

CHANGELOG
lib/active_merchant/billing/gateways/adyen.rb
test/remote/gateways/remote_adyen_test.rb

Pass networkTxReference in additionalData hash for all relevant
transactions. This value should be passed with stored credential fields
used in MIT.
CE-1603
Unit: 76 tests, 397 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 100 tests, 385 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Adyen: Pass networkTxReference in additionalData hash

---

CHANGELOG
lib/active_merchant/billing/gateways/pay_trace.rb
test/remote/gateways/remote_pay_trace_test.rb
test/unit/gateways/pay_trace_test.rb

PayTrace supports the addition of level_3_data to any approved and unsettled sale transaction. In order to add level_3_data to an approved transaction, the transaction will have to have been completed and returned a transaction_id. Due to this workflow, the method to add level_3_data has been built into the end of the purchase method. As of now, only Visa and MasterCard are supported for level_3_data so an additional test has been included in the remote file to make sure that if a card other than visa or MasterCard is processed, the purchase will go through and the attempt to add level_3_data will be ignored.
CE-1737
Local:
4774 tests, 73670 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
17 tests, 50 assertions, 0 failures, 0 errors, 0 …

PayTrace: Support level_3_data fields

---

CHANGELOG
lib/active_merchant/billing/gateways/blue_pay.rb
test/remote/gateways/remote_blue_pay_test.rb
test/unit/gateways/blue_pay_test.rb

This PR adds support for Stored Credentials to the BluePay Gateway Adapter.
According to their [docs](https://support.cardpointe.com/compliance/visa-stored-credential-transaction-framework-mandate#new-authorization-request-parameters), BluePay expects two fields, `cof` and `cofscheduled`, on all authorization requests using Stored Credentials. This PR maps incoming `stored_credential` parameters to these fields.
CE-1669
Rubocop:
Unit:
4779 tests, 73706 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
Loaded suite test/remote/gateways/remote_blue_pay_test
18 tests, 89 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

BluePay: Add Stored Credentials

---

CHANGELOG
lib/active_merchant/billing/gateways/orbital.rb
test/remote/gateways/remote_orbital_test.rb
test/unit/gateways/orbital_test.rb

122 tests, 716 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
69 tests, 320 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
4778 tests, 73709 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Orbital: Adding MC SCARecurringPayment field

---

lib/active_merchant/billing/gateways/braintree_blue.rb
test/remote/gateways/remote_braintree_blue_test.rb
test/unit/gateways/braintree_blue_test.rb

Allow sending the transaction_source as recurring_first or moto. Also
exposes the `recurring` param on responses.
https://developer.paypal.com/braintree/docs/reference/request/transaction/sale#transaction_source
Remote:
86 tests, 455 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
85 tests, 192 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Braintree: Support recurring_first and moto reasons

---

CHANGELOG
lib/active_merchant/billing/gateways/pay_trace.rb
test/remote/gateways/remote_pay_trace_test.rb
test/unit/gateways/pay_trace_test.rb

Add option to pass `include_capture_amount` field to trigger the sending of specified amount. Without this option set to true, the capture method will act on whatever dollar amount the original authorization included.
Local:
4784 tests, 73748 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
19 tests, 74 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
25 tests, 64 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

PayTrace: Adjust capture method

---

CHANGELOG
test/remote/gateways/remote_barclays_epdq_extra_plus_test.rb

`add_eci` is already a method used in this gateway. 
- wrote a test for checking a custom eci option works
- there are remote tests failing, but they are failing on master as well:
-  `test_unsuccessful_refund`
- `test_successful_refund`
- `test_invalid_login`

Ce 1646 barclays e pdq extra plus add gsf

---

CHANGELOG
lib/active_merchant/billing/gateways/cyber_source.rb
test/fixtures.yml
test/remote/gateways/remote_cyber_source_test.rb
test/unit/gateways/cyber_source_test.rb

Add support for incremental auth (adjust) transactions. In scenarios
where a merchant authorizes payment but needs to make an adjustment to
that auth before capture, they make an adjust request. Currently, a
merchant would have to execute a void and a new auth before capture.
CE-1438
Unit: 102 tests, 499 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 96 tests, 496 assertions, 7 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
92.7083% passed
Our MID credentials do not support this feature, so the test fails.

CyberSource: Adjust Auth

---

CHANGELOG
lib/active_merchant/billing/gateways/payflow.rb
lib/active_merchant/billing/gateways/payflow/payflow_common_api.rb
test/remote/gateways/remote_payflow_test.rb
test/unit/gateways/payflow_test.rb

CE-1704
Local: 4792 tests, 73784 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit: 49 tests, 244 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 38 tests, 169 assertions, 8 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
78.9474% passed

Payflow: Add support for MERCHDESCR field.

---

CHANGELOG
lib/active_merchant/billing/gateways/orbital.rb
test/remote/gateways/remote_orbital_test.rb
test/unit/gateways/orbital_test.rb

It is not sufficient to look at ProcStatus 0=Success for setting refunds as successful. Additional response parameter that needs to be checked is ApprovalStatus that can have the following values:  0=Declined 1=Approved 2=Message/System Error. If it was not approved RespCode will indicate the reason.
ECS-1881
Unit:
125 tests, 726 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
70 tests, 323 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Orbital: Correct Success Logic for Refund

---

CHANGELOG
lib/active_merchant/billing/gateways/pay_trace.rb
test/remote/gateways/remote_pay_trace_test.rb
test/unit/gateways/pay_trace_test.rb

Remove support for `include_capture_amount` field, it is not needed for partial captures to succeed
CE-1777
Local:
4795 tests, 73802 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
100% passed
Remote:
27 tests, 69 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

PayTrace: Support $0 authorize in verify method

---

CHANGELOG
lib/active_merchant/billing/check.rb
test/unit/check_test.rb

* American routing numbers are always 9 digits and
must pass the Luhn test
* Canadian routing numbers are 8 digits and must exist
in a pre-approved list
Loaded suite test/unit/check_test
12 tests, 26 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
4799 tests, 73813 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Updating bank routing number validation check

---

CHANGELOG
lib/active_merchant/billing/gateways/kushki.rb
test/remote/gateways/remote_kushki_test.rb
test/unit/gateways/kushki_test.rb

Added 'contactDetails' object to the charge request when options under 'contact_details' are present.
CE-647
Unit:
15 tests, 98 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 
13 tests, 42 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Kushki: Add 'contactDetails' fields

---

CHANGELOG
lib/active_merchant/billing/gateways/adyen.rb
lib/active_merchant/billing/three_d_secure_eci_mapper.rb
test/remote/gateways/remote_adyen_test.rb
test/unit/gateways/adyen_test.rb

EVS-830
Needs to be less than 80 characters for Google Pay transactions
Unit:
Finished in 9.874792 seconds.
----------------------------------------------------------------------------------------------------------------------------------------
4798 tests, 73809 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
----------------------------------------------------------------------------------------------------------------------------------------
485.88 tests/s, 7474.49 assertions/s
Inspecting 705 files
Remote:
Finished in 115.285449 seconds.
----------------------------------------------------------------------------------------------------------------------------------------
103 tests, 399 …

Adyen: Truncating order_id and remote test

---

CHANGELOG
lib/active_merchant/billing/gateways/worldpay.rb
test/remote/gateways/remote_worldpay_test.rb
test/unit/gateways/worldpay_test.rb

Worldpay is moving to a new synchronous response workflow and in some
scenarios will lead to different success cases, particularly for the
`purchase` transaction, where a `MultiResponse`, asynchronous
transaction workflow is invoked.
For some MID configurations, a transaction can be executed with a
`skip_capture` option, which allows for the `authorize` to be
executed and subsequently will be implicitly captured, rendering a
`CAPTURED` value for the `lastEvent` tag.
This change is for broadening the scope of our success criteria within
the context of an `authorize` transaction to allow for `AUTHORISED` or
`CAPTURED`.
CE-1786
Unit: 89 tests, 542 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 71 tests, 304 assertions, 2 failures, 0 errors, 0 …

Worldpay: Synchronous Response with purchase transaction

---

lib/active_merchant/billing/credit_card_methods.rb
test/unit/credit_card_methods_test.rb

Added new JCB BIN ranges to card detector.
Test Summary
Local: 4828 tests, 73852 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit: 46 tests, 534 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: None

Updated BIN ranges on JCB card types

---

CHANGELOG
lib/active_merchant/billing/gateways/cyber_source.rb
test/unit/gateways/cyber_source_test.rb

Previously if a string such as 'false' is sent in for ignore_avs or
ignore_cvv, those fields would be sent with the value 'true'. Now we
convert these field values to strings and check them against 'true' to
prevent false positives.
Unit:
107 tests, 528 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote (7 unrelated failures that match master):
101 tests, 512 assertions, 7 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
93.0693% passed

CyberSource: Allow string content for Ignore AVS/CVV flags

---

CHANGELOG
lib/active_merchant/billing/gateways/decidir.rb
test/remote/gateways/remote_decidir_test.rb
test/unit/gateways/decidir_test.rb

ECS-1582
Ensures error message parsing and string building is handled correctly
regardless of type. Also updates remote Decidir tests with correct
error message.
Test Summary
Local: 4830 tests, 73862 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
Unit: 36 tests, 175 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
Remote: 23 tests, 81 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications

Decidir: generalize handling of unique error messages

---

CHANGELOG
lib/active_merchant/billing/gateways/authorize_net.rb
test/unit/gateways/authorize_net_test.rb

The element `cardholderAuthentication` was removed from the request for the `authorize_net` gateway for non-3DS transactions.
ECS-1456
Test Summary
Unit:
Loaded suite test/unit/gateways/authorize_net_test
108 tests, 640 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
Loaded suite test/remote/gateways/remote_authorize_net_test
73 tests, 269 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Remove cardholderAuthentication for non-3DS transactions

---

CHANGELOG
lib/active_merchant/billing/gateways/blue_snap.rb
test/unit/gateways/blue_snap_test.rb

BlueSnap can throw 429 errors (rate limiting) at times, which are not
currently handled by the AM adapter. We do however, handle 401s and
403s. This PR adds 429s to the types of errors specifically handled.
When they occur, we will send back the response body without trying to
parse any xml.
Info on 429 error from bluesnap docs: https://developers.bluesnap.com/v8976-JSON/docs/error-handling-overview#section-http-503-and-429-errors
Unit:
40 tests, 233 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: PENDING

BlueSnap: Handle 429 errors

---

CHANGELOG
test/unit/gateways/orbital_test.rb

Update test file to account for uninitialized @credit_card variable warnings
Local:
4832 tests, 73883 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Orbital Unit:
127 tests, 741 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Orbital Remote:
70 tests, 323 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Orbital: Update unit test files

---

CHANGELOG
lib/active_merchant/billing/gateways/orbital.rb
test/unit/gateways/orbital_test.rb

Sometimes, the response we receive from Orbital will have some content
that can't be parsed (specifically, we've seen unexpected null chars -
\u0000). Instead of blowing up when this happens, this change subs the
null chars in the body with a placeholder string. As this is the only
character we've seen cause issues at this point, only null is stripped
in this PR.
Remote:
70 tests, 323 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
128 tests, 747 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Orbital: Strip null characters from responses

---

CHANGELOG
lib/active_merchant/billing/gateways/merchant_warrior.rb
test/remote/gateways/remote_merchant_warrior_test.rb
test/unit/gateways/merchant_warrior_test.rb

Handle the case when Merchant Warrior response contains invalid XML.
ECS-1373
Test Summary
Local: 4834 tests, 73895 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
Unit: 26 tests, 138 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
Remote:

Merchant Warrior: handle unexpected XML response

---

CHANGELOG
lib/active_merchant/billing/gateways/braintree_blue.rb
test/remote/gateways/remote_braintree_blue_test.rb
test/unit/gateways/braintree_blue_test.rb

Responses from failed verify transactions using the verification endpoint
instead of the MultiResponse authorize + void have a different response
structure than successes and other transaction responses. Adds guards to
fix NoMethodError when contents are not present.
Remote:
87 tests, 458 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
85 tests, 192 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
ECS-1933

Braintree: Fix NoMethodError for failed card verification

---

lib/active_merchant/billing/gateways/pay_arc.rb

* Ensure that currency field isn't added twice if currency is already
passed in options param
* Call .compact on filtered_options to remove all nil values and ensure
duplicates are not sent erroneously
Loaded suite test/unit/gateways/pay_arc_test
14 tests, 42 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Loaded suite test/remote/gateways/remote_pay_arc_test
Failure: test_successful_credit(RemotePayArcTest) due to MID set up on PayArc's side
19 tests, 48 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
94.7368% passed
4835 tests, 73897 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Inspecting 707 files
707 files inspected, no offenses …

PayArc currency and parameters updates

---

lib/active_merchant/billing/gateways/pay_arc.rb
test/remote/gateways/remote_pay_arc_test.rb

* Fixed an issue with CC months not working for '01', '02', etc.
* Added `tax_rate` to the charges allowed list
* Removed the `duplicate` default void reason
Loaded suite test/remote/gateways/remote_pay_arc_test
`test_successful_credit` fails due to MID configuration on PayArc's side
22 tests, 54 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
95.4545% passed
Loaded suite test/unit/gateways/pay_arc_test
14 tests, 42 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
4835 tests, 73897 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Inspecting 707 files

PayArc: Formatting CC month, adding tax_rate, removing default void reason

---

CHANGELOG
lib/active_merchant/billing/gateways/kushki.rb
test/remote/gateways/remote_kushki_test.rb

CE-1800
Unit: 16 tests, 103 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 14 tests, 45 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Local: 4829 tests, 73857 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Kushki: Add support for fullResponse, fix boolean bug

---

lib/active_merchant/billing/gateways/mundipagg.rb
test/remote/gateways/remote_mundipagg_test.rb
test/unit/gateways/mundipagg_test.rb

This allows a user to pass in authorization_secret_key for a transaction
and use that for Basic Auth instead of the api_key that is passed in
when the gateway is instantiated
CE-1829
remote tests:Finished in 24.491592 seconds.
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
39 tests, 97 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
1.59 tests/s, 3.96 assertions/s
unit tests: Finished in 0.227902 seconds. …

Mundipagg: Added support to overwrite api_key

---

CHANGELOG
lib/active_merchant/billing/gateways/pay_arc.rb
test/remote/gateways/remote_pay_arc_test.rb

* Use `options[:billing_address]` to look at the payment method
data
* Added email and phone_number to `credit` and `token`
4836 tests, 73901 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Loaded suite test/remote/gateways/remote_pay_arc_test
`test_successful_credit` fails due to MID configuration on PayArc's side
`test_successful_adds_phone_number_for_purchase` fails due to an issue with the PayArc API, I've reached out to PayArc and waiting on a response
23 tests, 57 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
91.3043% passed
Loaded suite test/unit/gateways/pay_arc_test
14 tests, 42 assertions, 0 failures, 0 errors, 0 pendings, 0 …

PayArc: Updating `add_address`

---

CHANGELOG
lib/active_merchant/billing/gateways/payeezy.rb
test/remote/gateways/remote_payeezy_test.rb

Implement `add_soft_descriptors` option in the `credit` method.
Remote: 38 tests, 151 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit: 38 tests, 180 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Local: 4844 tests, 73935 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Payeezy: Add support for `add_soft_descriptors`

---

CHANGELOG
lib/active_merchant/billing/gateways/worldpay.rb
test/remote/gateways/remote_worldpay_test.rb

Some merchants that execute `authorize` transactions with Worldpay are configured to
automatically capture those transactions via the payment processor
(dependent on region) and therefore can expect to receive 'CAPTURED' in
the list of success criteria when checking the `last_event` value.
Expanding the `authorize_request` to expect `AUTHORISED` or `CAPTURED`
handles this case for those merchants
CE-1786
Unit: 88 tests, 538 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 71 tests, 304 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
97.1831% passed

Worldpay: Support 'CAPTURED' response for `authorize` transactions

---

CHANGELOG
lib/active_merchant/billing/gateways/global_collect.rb
test/remote/gateways/remote_global_collect_test.rb
test/unit/gateways/global_collect_test.rb

This change adds a new header capable of passing an idempotence key to the `global_collect` gateway. Note that the only non-passing remote test fails with a `502` bad gateway error response, but this is noted as being an intermittent response from the gateway's side.
Test Summary
Local: 4844 tests, 73931 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Unit: 28 tests, 136 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote: 25 tests, 86 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 96% passed

Ingenico (Global Collect): New idempotence key header

---

CHANGELOG
lib/active_merchant/billing/gateways/pay_trace.rb
test/unit/gateways/pay_trace_test.rb

Several of the fields within the `line_items` field were not being formatted properly due to them being nested. Previously, the `amount` method was being called on *_amount fields, which was giving an error related to them needing to be integers. The fields that have boolean values were being transformed into strings and throwing errors at the gateway level. These changes remedy both of those issues.
Local:
4846 tests, 73941 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
100% passed
Remote:
27 tests, 69 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Rubocop:

PayTrace: Adjust handling of `line_items` subfields

---

CHANGELOG
lib/active_merchant/billing/credit_card_formatting.rb
lib/active_merchant/billing/gateways/worldpay.rb
test/remote/gateways/remote_worldpay_test.rb
test/unit/credit_card_formatting_test.rb
test/unit/gateways/worldpay_test.rb

This pull request fixes the issue when expiration 2 digits year is converted to 4 digits by adding 00to the beginning. For example, '22' becomes '0022'. Now if year is 2 digits '20' is added to the beginning. For example, '22' becomes '2022'.
ECS-1973
4847 tests, 73948 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
534.01 tests/s, 8147.08 assertions/s
Inspecting 707 files
Unit:
89 tests, 541 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote (2 failed same as on master):
72 tests, 307 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
97.2222% passed

Worldpay: Correct Expiration Year Format

---

CHANGELOG
lib/active_merchant/billing/gateways/payflow.rb
test/unit/gateways/payflow_test.rb

See https://developer.paypal.com/docs/payflow/3d-secure-mpi/
- Rubocop:
```
```    
- Local tests:
```
4848 tests, 73971 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
```
- Remote tests:
```
bundle exec rake test:remote TEST=test/remote/gateways/remote_payflow_test.rb
```
| branch |  results |
| -- | -- |
| payflow_3ds2_update |  `38 tests, 163 assertions, 10 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 73.6842% passed` |
| master | `38 tests, 163 assertions, 10 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 73.6842% passed` <br> the same |
In the most recent Payflow PR, [here](https://github.com/activemerchant/active_merchant/pull/4066#issue-698834138), only 8 tests failed.

Payflow: add THREEDSVERSION and DSTRANSACTIONID when present

---

CHANGELOG
lib/active_merchant/billing/gateways/orbital.rb
test/remote/gateways/remote_orbital_test.rb
test/unit/gateways/orbital_test.rb

Enable the scrub method to filter all appearances of bank account numbers.
4852 tests, 73989 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
461.72 tests/s, 7040.89 assertions/s
Inspecting 707 files
Unit:
129 tests, 750 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
71 tests, 327 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Orbital: Ensure full e-check scrubbing

---

CHANGELOG
lib/active_merchant/billing/gateways/paysafe.rb
test/fixtures.yml
test/remote/gateways/remote_paysafe_test.rb
test/unit/gateways/paysafe_test.rb

- Support the following AM methods: authorize, capture, purchase, verify, void, refund, store
- Add support for payment tokens in all transaction types
- Support additional methods: credit and redact
- [Paysafe card API documentation](https://developer.paysafe.com/en/cards/api/)
- [Paysafe vault API documentation](https://developer.paysafe.com/en/vault/api/)
CE-1555
Rubocop:
710 files inspected, no offenses detected
Local:
4864 tests, 74030 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
13 tests, 44 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
21 tests, 51 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Paysafe: Add gateway integration

---

CHANGELOG
lib/active_merchant/billing/gateways/elavon.rb
test/remote/gateways/remote_elavon_test.rb
test/unit/gateways/elavon_test.rb

For recurring transactions, an initial call must be made to the gateway using merchant_initiated_unscheduled, as well as ssl_get_token (to request the token) and ssl_add_token (to store that token with the payment method). Once stored the ssl_token will be sent with subsequent purchases that are marked as "recurring".
Local:
4853 tests, 73995 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
46 tests, 243 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
38 tests, 171 assertions, 4 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
89.4737% passed
The four failing remote tests are also failing on the master branch and I am working with Elavon to get them resolved.

Enables Recurring Transactions on Elavon

---

CHANGELOG
lib/active_merchant/billing/gateways/orbital.rb
test/remote/gateways/remote_orbital_test.rb
test/unit/gateways/orbital_test.rb

ECS-2012
When a 3DS version is given to Orbital with the minor version numbers (i.e. "2.2.0"), Orbital returns an error:
> Error. The Orbital Gateway has received a badly formatted message. Field [MasterCard Program Protocol] exceeded max length of [1]
This commit converts the version number to a string and truncates it to only include the major version number (i.e. "2").
After changing just the tests, the remote tests were able to recreate the error. There were four failures:
```
Failure: test_successful_master_authorization_with_3ds(RemoteOrbitalGatewayTest)
Failure: test_successful_master_purchase_with_3ds(RemoteOrbitalGatewayTest)
Failure: test_successful_purchase_with_sca_recurring_master_card(RemoteOrbitalGatewayTest)
Failure: test_transcript_scrubbing(RemoteOrbitalGatewayTest)
``` …

Orbital: Truncate three_d_secure[:version]

---

CHANGELOG
lib/active_merchant/billing/gateways/nmi.rb
test/remote/gateways/remote_nmi_test.rb
test/unit/gateways/nmi_test.rb

The `cardholder_auth` field of the NMI integration is a non-standard 3DS field. It was originally implemented in ActiveMerchant by adding a new field to the `three_d_secure` hash, but it turns out that it can be derived via the `authentication_response_status` standard field in there already.
This commit changes the NMI gateway to use the populate the `cardholder_auth` field using the 3DS standard field `authentication_response_status`.
test/remote/gateways/remote_nmi_test:
42 tests, 156 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
rake test:local:
4867 tests, 74048 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
710 files inspected, no offenses detected

NMI: Change cardholder_auth 3DS field population

---

CHANGELOG
lib/active_merchant/billing/gateways/adyen.rb

Upgrade the Payment API Version to v64 and the Recurring
API Version to v49.
103 tests, 399 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
77 tests, 402 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Adyen: Upgrade API Version

---

CHANGELOG
lib/active_merchant/billing/gateways/payeezy.rb
test/remote/gateways/remote_payeezy_test.rb
test/unit/gateways/payeezy_test.rb

Adds the merchant_ref field to general credit transactions and the soft_descriptor hash to refunds.
Unit
40 tests, 188 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
41 tests, 170 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Updates fields for Payeezy gateway

---

CHANGELOG
lib/active_merchant/billing/gateways/elavon.rb
test/remote/gateways/remote_elavon_test.rb
test/unit/gateways/elavon_test.rb

To give the user full control of when the token is added.
Unit:
47 tests, 243 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
38 tests, 172 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications

Adds ssl_token field for Elavon gateway
