- CHANGELOG
- lib/active_merchant/billing/credit_card_methods.rb
- test/unit/credit_card_methods_test.rb
China UnionPay cards beginning with 62 are able to run on Discover rails in the US and Canada. Because of this, these cards were previously lumped together with Discover. There is no change to how these transactions will be processed, but we would like to break them out in order to identify UnionPay cards correctly. 
Discover's [BIN list](https://www.discoverglobalnetwork.com/content/dam/discover/en_us/dgn/pdfs/IPP-VAR-Enabler-Compliance.pdf) was used in order to understand specific BIN ranges belonging to UnionPay.
____
**Unit tests:**
4897 tests, 74184 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Pull UnionPay's 62* BIN ranges out of Discover's

- CHANGELOG
- lib/active_merchant/billing/gateways/monei.rb
- test/remote/gateways/remote_monei_test.rb
Billing detils fields are not required as per Gateway documentation https://docs.monei.com/api/#operation/payments_create, but empty fields cause validation errors. This commit forces to fill billing details fields only if they are provided. Additionaly, some fields were added to billing details as per documentation.
ECS-1694
Unit:
17 tests, 61 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
100% passed
> Monei: Update Creation of Billing Details

- CHANGELOG
- lib/active_merchant/billing/gateways/paysafe.rb
- test/remote/gateways/remote_paysafe_test.rb
- Include remote tests for visa and MasterCard each for 3DS1 and 3DS2. Mastercard requires a specific field be sent, which is why it has its own test separate from the visa test.
CE-1572
Local:
4891 tests, 74161 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Rubocop:
713 files inspected, no offenses detected
Unit:
12 tests, 41 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
26 tests, 63 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Paysafe: Add support for 3DS

- CHANGELOG
- lib/active_merchant/billing/gateways/adyen.rb
- test/remote/gateways/remote_adyen_test.rb
- test/unit/gateways/adyen_test.rb
Adding ACH/Bank Accounts to Adyen.
Remote tests:
114 tests, 433 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit tests:
83 tests, 434 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Adyen: Add ACH Support

- CHANGELOG
- lib/active_merchant/billing/gateways/paysafe.rb
- test/remote/gateways/remote_paysafe_test.rb
- test/unit/gateways/paysafe_test.rb
Adjust logic for profile data so the phone field is being successfully passed in the request whether it is included in the billing address hash within the options hash or if it an independent field included in the options hash
Rubocop:
713 files inspected, no offenses detected
Local:
4906 tests, 74228 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
29 tests, 70 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
13 tests, 45 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Paysafe: Adjust profile data

- CHANGELOG
- lib/active_merchant/billing/gateways/stripe_payment_intents.rb
- test/remote/gateways/remote_stripe_payment_intents_test.rb
- test/unit/gateways/stripe_payment_intents_test.rb
This work adds support for the GSF `claim_without_transaction_id`. Gateway validation for this field occurs through a different service, before the transaction request is sent to the gateway.
Test Summary
Local: 4897 tests, 74189 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit: 26 tests, 152 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 58 tests, 285 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> StripePaymentIntentsGateway: Add GSF `claim_without_transaction_id`

- CHANGELOG
- lib/active_merchant/billing/credit_card_methods.rb
- test/unit/credit_card_methods_test.rb
[CE-1885](https://spreedly.atlassian.net/browse/CE-1885)
Unit Tests:
4919 tests, 74278 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> RouteX: Support cardtype

- lib/active_merchant/billing/gateways/moka.rb
- test/remote/gateways/remote_moka_test.rb
Moka's API only accepts two-digit strings in the ExpMonth field.
Loaded suite test/remote/gateways/remote_moka_test
22 tests, 61 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
Unit tests:
4918 tests, 74276 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
Rubocop:
> Moka: make sure month is always two digits

- CHANGELOG
- lib/active_merchant/billing/gateways/d_local.rb
- test/remote/gateways/remote_d_local_test.rb
- test/unit/gateways/d_local_test.rb
Added the fields device_id and ip to the payer object. dlocal's device_id is event_uuid and dlocal's ip is onboarding_ip_address. The additional_data field is a blob, anything can be sent in under that.
unit: 23 tests, 93 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
remote: 28 tests, 73 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> dlocal: Add device_id and ip to payer object and add additional_data

- CHANGELOG
- lib/active_merchant/billing/gateways/orbital.rb
- test/remote/gateways/remote_orbital_test.rb
Including a gsub pattern for scrubbing the cryptogram from the
transcript.
CE-1940
Unit: 129 tests, 750 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 72 tests, 328 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Orbital: Scrub Payment Cryptogram

- CHANGELOG
- lib/active_merchant/billing/gateways/paysafe.rb
- test/remote/gateways/remote_paysafe_test.rb
- test/unit/gateways/paysafe_test.rb
- Add/edit unit tests to verify field formatting in request data
- Add remote tests to confirm successful transactions for airline merchants
- Add test for store and purchase using new token
Local:
4911 tests, 74270 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
15 tests, 72 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
31 tests, 94 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Paysafe: Add support for airline fields

- CHANGELOG
- lib/active_merchant/billing/gateways/stripe.rb
- lib/active_merchant/billing/gateways/stripe_payment_intents.rb
- test/remote/gateways/remote_stripe_payment_intents_test.rb
- test/remote/gateways/remote_stripe_test.rb
- test/unit/gateways/stripe_payment_intents_test.rb
- test/unit/gateways/stripe_test.rb
Add option to pass `"radar_options[session]"="{{RADAR_SESSION_ID}}"` when creating a charge and when creating a Payment Intent
ECS-2059
Stripe
Unit
140 tests, 745 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote
73 tests, 337 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
98.6301% passed
Note: failed test fails on master also
Stripe Payment Intents
Unit
30 tests, 168 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote
62 tests, 299 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
4922 tests, 74288 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
716 files inspected, no …
> Stripe and Stripe PI: Add Radar Session Option

- CHANGELOG
- lib/active_merchant/billing/credit_card_methods.rb
- test/unit/credit_card_methods_test.rb
Revises [Pull UnionPay's 62* BIN ranges out of Discover's #4103](https://github.com/activemerchant/active_merchant/pull/4103)
I ran into issues while testing payment processing using [Stripe's test UnionPay card](https://stripe.com/docs/testing) (6200000000000005) as it wasn't previously included in ActiveMerchant's UnionPay's BIN range. This PR simply adds it to the existing BIN range.
I also added some additional tests for Vr and Carnet to ensure that their 627* range cards are getting classified correctly (Elo also has 627* cards but there was already an existing test). 
------------
**Unit tests**:
4926 tests, 74323 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Add UnionPay test card to BIN range

- CHANGELOG
- lib/active_merchant/billing/gateways/global_collect.rb
- test/remote/gateways/remote_global_collect_test.rb
- test/unit/gateways/global_collect_test.rb
Global Collect has a pre-production url endpoint that we need to make
available.
This endpoint can be enabled by setting `url_override` to
`preproduction` when initializing the gateway.
CE-1964
Unit: 53 tests, 227 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 25 tests, 61 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
96% passed
> Global Collect: Support URL override

- CHANGELOG
- lib/active_merchant/billing/gateways/pay_conex.rb
- test/remote/gateways/remote_pay_conex_test.rb
- test/unit/gateways/pay_conex_test.rb
Before changes applied: 
Remote:
24 tests, 38 assertions, 16 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
33.3333% passed
After changes applied:
Remote:
25 tests, 41 assertions, 16 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
36% passed
Unit: 
20 tests, 90 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Local:
4927 tests, 74327 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> PayConex: scrub bank account info from transcripts

- CHANGELOG
- lib/active_merchant/billing/gateways/moka.rb
Moka returns an error when `OrderTrxCode` is given on subsequent calls;
`capture`, `void`, and `refund`. Removing the method call from those
transactions should resolve the issue.
CE-1990
Unit: 16 tests, 73 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 22 tests, 61 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Moka: Remove additional transaction data from subsequent calls

- CHANGELOG
- lib/active_merchant/billing/gateways/moka.rb
- test/remote/gateways/remote_moka_test.rb
4926 tests, 74324 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Loaded suite test/unit/gateways/moka_test
16 tests, 73 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Loaded suite test/remote/gateways/remote_moka_test
23 tests, 63 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Moka: Ensure CvcNumber can be an empty string

- lib/active_merchant/billing/credit_card_methods.rb
- test/unit/credit_card_methods_test.rb
Amends #4122 
Errors occurred during payment process testing using Stripe's test UnionPay card (6200000000000005) as it wasn't previously included in ActiveMerchant's CUP range.
In #4122, I mistakenly added the wrong number of 0's for the test BIN 😔 and therefore the test card was still not getting classified correctly. I've updated this and added an additional test.
________
4928 tests, 74331 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Fixup PR #4122 Add UnionPay test card to BIN range

- CHANGELOG
- lib/active_merchant/billing/credit_card_methods.rb
- test/unit/credit_card_methods_test.rb
4928 tests, 74332 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Maestro: allow card lengths for non-validated cards

- lib/active_merchant/billing/credit_card_methods.rb
Nondeterministic `require` loading was occasionally
causing this file to raise a `NameError` when
loaded by itself. Sometimes it would succeed,
when a different file that `require 'set'`ed  would
load first.
> `uninitialized constant ActiveMerchant::Billing::CreditCardMethods::Set (NameError)`
Local tests:
100% passed
Rubocop:
> Make "set" `require`d by credit_card_methods.rb

- lib/active_merchant/billing/gateways/moka.rb
- test/remote/gateways/remote_moka_test.rb
Moka's default currency is 'TL'. We discovered that if you create an
authorization for a different currency (say 'USD'), you still must pass
that currency on the capture, otherwise Moka will default to 'TL' and
the response will be a `CurrencyDoesntMatch` error.
CE-1999
Rubocop:
Local:
100% passed
Remote:
Loaded suite test/remote/gateways/remote_moka_test
24 tests, 67 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Moka: Pass Currency on Capture transactions

- CHANGELOG
- lib/active_merchant/billing/gateways/paysafe.rb
- The gateway expects the amount and percent fields to be integers when they reach the gateway. This was not originally discovered when writing unit and remote tests, but popped up as an error when writing integration tests.
Local:
100% passed
Rubocop:
Unit:
15 tests, 2 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
100% passed
> Paysafe: Update field mapping for split_pay

- CHANGELOG
- lib/active_merchant/billing/gateways/safe_charge.rb
- test/remote/gateways/remote_safe_charge_test.rb
Safe Charge accepts at least one currency (Chilean Peso) that does not
include fractional units. If a request includes a decimal point in the
amount, the gateway will return an error. This PR leverages the `localized_amount`
method to truncate the amount to whole units.
CE-1909
Rubocop:
Local:
100% passed
Remote:
29 tests, 77 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
96.5517% passed
You should expect this remote test to fail for reasons not related to this PR:
`test_successful_regular_purchase_through_3ds_flow_with_invalid_pa_res`
> SafeCharge: Account for non-fractional currencies

- CHANGELOG
- lib/active_merchant/billing/gateways/card_stream.rb
- test/unit/gateways/card_stream_test.rb
This PR makes it possible to specify a `country_code` in the request (not to be confused with `customerCountryCode`).
Previously it was simply defaulting to 'GB' every time.
CE-1960
Rubocop:
Local:
4929 tests, 74340 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
31 tests, 200 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
93.5484% passed
You should expect to see both of the following tests fail with the message "ERROR CODE (RC_IP_BLOCKED_PRIMARY)":
`test_successful_amex_purchase_and_refund_with_force_refund`
`test_successful_amex_authorization_and_capture`
This is the result of cnfigurations for AMEX cards on our test account, which I am unable to change.
> CardStream: Support passing country_code in request

- CHANGELOG
- lib/active_merchant/billing/gateways/adyen.rb
- test/remote/gateways/remote_adyen_test.rb
- test/unit/gateways/adyen_test.rb
Adds a bit of logic to the way the Adyen gateway passes phone numbers so that if a payment method has a phone number saved to it that will be mapped first (`billing_address[:phone]`), otherwise if the transaction has (`billing_address[phone_number]`) that will be mapped. If neither are available we will map an empty string. Similar to [#4005](https://github.com/activemerchant/active_merchant/pull/4005).
CE-1908
Test Summary:
There were 17 test errors due to not having monei api_key
Local:
4930 tests, 74297 assertions, 0 failures, 17 errors, 0 pendings, 0 omissions, 0 notifications
99.6552% passed
Unit:
88 tests, 450 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
119 tests, 441 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 …
> Adyen: Adjust phone number mapping

- CHANGELOG
- lib/active_merchant/billing/gateways/mit.rb
When Active Merchant is used in rails application that uses module ActiveSupport to_json method will be overwritten and `<` and `>` will be encoded. This commit includes the change that to_json from ActiveSupport is not used when converting parameters to json string.
Unit:
9 tests, 33 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
8 tests, 22 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> MIT: Change how parameters are converted to JSON

- CHANGELOG
- lib/active_merchant/billing/gateways/stripe.rb
- test/remote/gateways/remote_stripe_test.rb
- test/unit/gateways/stripe_test.rb
For the Stripe and Stripe Payment Intents gateways, when a check/e-check `store` transaction is performed the account_number should be scrubbed.
ECS-2001
Test Summary
Local:
4932 tests, 74350 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
141 tests, 747 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
74 tests, 338 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
98.6486% passed
The remote test failure returned this message "Account acct_17FRNfIPBJTitsen already has the maximum 200 external accounts attached." I am not sure how to fix this as I believe it is not related to a change I made but rather this account has been tested too much.
> Stripe: add account_number to scrubbing

- CHANGELOG
- lib/active_merchant/billing/gateways/paysafe.rb
- Resolve rubocop errors from unrelated merge
CE-2060
Rubocop:
Local/Unit:
4936 tests, 74363 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
100% passed
> Paysafe: Remove invalid code

- CHANGELOG
- lib/active_merchant/billing/gateways/nmi.rb
- test/remote/gateways/remote_nmi_test.rb
- test/unit/gateways/nmi_test.rb
Added `descriptors` gateway specific fields to the
NMI gateway along with unit and remote tests.
CE-1970
Unit:
4938 tests, 74380 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
43 tests, 161 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Rubocop:
> NMI: Add descriptors

- CHANGELOG
- lib/active_merchant/billing/gateways/stripe.rb
- lib/active_merchant/billing/gateways/stripe/stripe_payment_intents_response.rb
- lib/active_merchant/billing/gateways/stripe_payment_intents.rb
- test/remote/gateways/remote_stripe_payment_intents_test.rb
- test/unit/gateways/stripe_payment_intents_test.rb
ECS-2093
In order to add suppport for Stripe alternative payment methods (APMs), the StripePI gateway must support a `setup_purchase` method. This method takes an `amount`, `currency`, and array of `payment_method_types` then submits a post to the `payment_intents` endpoint. It should return a transaction in the `requires_payment_method` status as the user completes the transaction flow for whichever payment method they selected.
Since Stripe APM's are offsite purchases that could be completed at any point, transactions that flow through the `setup_purchase` will have a response of type `StripePaymentIntentsResponse`. This is done to ensure that systems can identify this type of transaction as different from other StripePI transactions, similar to how Paypal Express works.
Test Summary …
> Stripe Payment Intents: Add setup_purchase

- CHANGELOG
- lib/active_merchant/billing/gateways/safe_charge.rb
- test/remote/gateways/remote_safe_charge_test.rb
- test/unit/gateways/safe_charge_test.rb
Added sg_NotUseCVV gateway specific field to the
safe charge gateway along with unit and remote tests.
CE-2084
Remote:
30 tests, 81 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
Rubocop:
719 files inspected, no offenses detected
Unit:
4956 tests, 74516 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Safe Charge: Add sg_NotUseCVV field

- CHANGELOG
- lib/active_merchant/billing/gateways/payu_latam.rb
- test/remote/gateways/remote_payu_latam_test.rb
- test/unit/gateways/payu_latam_test.rb
This PR:
* Maps maestro card type to 'MASTERCARD' in accordance with gateway API.
* Maps a specific maestro BIN (590712) to 'CODENSA' in accordance with the gateway API.
* Updates the expiration dates on some of the test cards to achieve more consistent responses from the gateway sandbox, as advised by the gateway's technical support team.
* Modifies a remote test for `refund` that has been red for quite a while. The test was [originally written to accommodate issues with the gateway's sandbox](https://github.com/activemerchant/active_merchant/pull/2334), but those issues have been resolved and we are able to successfully test `refund` again.
CE-2074 & CE-2080
Rubocop:
720 files inspected, no offenses detected
Local:
4958 tests, 74520 assertions, 0 failures, 0 errors, 0 pendings, 0 …
> PayU Latam: send correct card types for maestro and condensa

- CHANGELOG
- lib/active_merchant/billing/gateways/stripe.rb
- lib/active_merchant/billing/gateways/stripe/stripe_payment_intents_response.rb
- lib/active_merchant/billing/gateways/stripe_payment_intents.rb
- test/remote/gateways/remote_stripe_payment_intents_test.rb
In PR #4178 support for a `setup_purchase` transaction was added to the Stripe PI gateway. As part of this, a new `Response class` was added so systems can differentiate that this is an offsite transaction. Creating a new `Response` class is not the best way to implement this and therefore refactoring to remove it.
Test Summary
Local:
4977 tests, 74599 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
31 tests, 171 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
65 tests, 305 assertions, 3 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
95.3846% passed
**There are 3 tests failing on master**
> Stripe Payment Intents: refactor response

- lib/active_merchant/billing/gateways/safe_charge.rb
- test/unit/gateways/safe_charge_test.rb
String parameter support is added for sg_NotUseCVV field
CE-2084
Rubocop:
723 files inspected, no offenses detected
Unit:
4977 tests, 74599 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
30 tests, 81 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
> Safe Charge: Support string for Add sg_NotUseCVV field

- CHANGELOG
- lib/active_merchant/billing/gateways/wompi.rb
- test/remote/gateways/remote_wompi_test.rb
- test/unit/gateways/wompi_test.rb
Remote: 9 tests, 21 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit: 9 tests, 38 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Rubocop: 723 files inspected, no offenses detected
CE-1979
> Wompi: cast error messages to JSON

- CHANGELOG
- lib/active_merchant/billing/gateways/nmi.rb
- test/unit/gateways/nmi_test.rb
ECS-1833
For client initiated transactions on the NMI gateway, we should not be sending the `:initial_transaction_id`. Please see [NMI Docs](https://secure.networkmerchants.com/gw/merchants/resources/integration/integration_portal.php#credential_on_file_information) for more information.
Test Summary
Local:
4979 tests, 74605 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
48 tests, 375 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
43 tests, 161 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> NMI: omit initial_transaction_id for CIT

- CHANGELOG
- lib/active_merchant/billing/gateways/stripe.rb
- lib/active_merchant/billing/gateways/stripe_payment_intents.rb
- test/remote/gateways/remote_stripe_payment_intents_test.rb
- test/unit/gateways/stripe_payment_intents_test.rb
`fulfillment_date` is a root field while `event_type` belongs in the `metadata` object.
Any reviewer should run the remote tests for both the Stripe PI and regular Stripe gateways, as this PR makes changes to both files.
CE-2101
Local:
4980 tests, 74615 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Rubocop:
722 files inspected, no offenses detected
Remote:
Loaded suite test/remote/gateways/remote_stripe_payment_intents_test
66 tests, 311 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Loaded suite test/remote/gateways/remote_stripe_test
74 tests, 338 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Stripe Payment Intents: Add support for fulfillment_date and event_type

- CHANGELOG
- lib/active_merchant/billing/gateways/paysafe.rb
- test/remote/gateways/remote_paysafe_test.rb
- test/unit/gateways/paysafe_test.rb
Change credit card brand to be `master` instead of `mastercard` to adhere to existing pattern and reflect value received when interacting with Spreedly's core API.
This change ensures that the `ds_transaction_id` is included for Mastercard 3DS2 transactions.
CE-2133
Local
4994 tests, 74763 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
RuboCop
Unit
15 tests, 72 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote
100% passed
> Paysafe: Adjust logic for sending 3DS field

- lib/active_merchant/billing/gateways/d_local.rb
- test/remote/gateways/remote_d_local_test.rb
- test/unit/gateways/d_local_test.rb
Previously this adapter was doing an auth followed by a void. DLocal
supports performing `verify` by passing an amount of 0 on
authorizations. The gateway returns a status code of 700 to signify
success when performing this action.
CE-2064
Rubocop:
723 files inspected, no offenses detected
Local:
4978 tests, 74601 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
Loaded suite test/remote/gateways/remote_d_local_test
28 tests, 75 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> DLocal: Implement $0 Verify

- CHANGELOG
- lib/active_merchant/billing/gateways/ebanx.rb
- test/remote/gateways/remote_ebanx_test.rb
- test/unit/gateways/ebanx_test.rb
The headers that are generated for the `commit` method are now generated via a helper method. This method will look for a gateway specific field `processing_type`; if the field is present with a value of `local`, an additional header will be added to the gateway request: `x-ebanx-api-processing-type`.
CE-2113
Rubocop:
Local:
4995 tests, 74785 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
Loaded suite test/remote/gateways/remote_ebanx_test
25 tests, 69 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> EBANX: Added `processing_type` Gateway Specific Field

- CHANGELOG
- lib/active_merchant/billing/gateways/paysafe.rb
Paysafe gateway requires an API key be sent in with the headers for each request. The API key is a concatenated version of the account's username and password. This PR takes the concatenation responsibility off of the user and does it automatically.
Rubocop:
Local:
4996 tests, 74789 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
15 tests, 72 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
100% passed
> Paysafe: Concatenate credentials for headers

- CHANGELOG
- lib/active_merchant/billing/gateways/stripe_payment_intents.rb
- test/remote/gateways/remote_stripe_payment_intents_test.rb
ECS-2122
Adding a call to `add_metadata` when making a `setup_purchase` to ensure that any metadata sent to AM is sent to Stripe. Also added a quick fix to one of the remote tests that were failing.
Test Summary
Local:
996 tests, 74789 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
32 tests, 175 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
66 tests, 311 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Stripe PI: add_metadata to setup_purchase

- CHANGELOG
- test/remote/gateways/remote_orbital_test.rb
Added google pay purchase and auth capture remote tests on orbital
gateway for end to end testing.
[CE-1819](https://spreedly.atlassian.net/browse/CE-1819)
Unit:
4999 tests, 74808 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Rubocop:
Remote:
76 tests, 345 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Orbital: Add googlepay payment tests

- CHANGELOG
- lib/active_merchant/billing/gateways/mundipagg.rb
- test/unit/gateways/mundipagg_test.rb
Updated `success_from` method of mundipagg gateway to get success result
from transaction response.
CE-1974
Rubocop:
Unit:
4999 tests, 74808 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
41 tests, 101 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Mundipagg: Update success method

- CHANGELOG
- lib/active_merchant/billing/gateways/worldpay.rb
- test/remote/gateways/remote_worldpay_test.rb
This PR contains two commits for ease of reviewing.
The first commit decomposes some complex methods in the Worldpay adapter in order to make the code easier to maintain and to allow us to reuse some of the logic.
The second commit adds support for the Visa Direct Fast Funds Credit feature, using a switch called `fast_fund_credit`. Current documentation for this feature can be found [here](https://developer.worldpay.com/docs/wpg/manage/fastaccess/#disbursement). This feature will be available for visa credit cards as well as tokenized visa credit cards.
Unit:
5001 tests, 74815 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Rubocop:
Remote:
90 tests, 375 …
> Worldpay: Add support for Visa Direct Fast Funds Credit

- CHANGELOG
- lib/active_merchant/billing/gateways/paysafe.rb
- test/remote/gateways/remote_paysafe_test.rb
- test/unit/gateways/paysafe_test.rb
[Paysafe stored credential API docs](https://developer.paysafe.com/en/cards/api/#/introduction/complex-json-objects/storedcredential)
CE-1569
Local:
5001 tests, 74815 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
16 tests, 77 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
31 tests, 94 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Rubocop:
> Paysafe: Add support for stored credentials

- CHANGELOG
- lib/active_merchant/billing/gateways/worldpay.rb
- test/remote/gateways/remote_worldpay_test.rb
- test/unit/gateways/worldpay_test.rb
Unit:
5004 tests, 74828 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
RuboCop:
Remote:
91 tests, 379 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
97.8022% passed
Failing remote tests unrelated to this change:
test_3ds_version_1_parameters_pass_thru
test_3ds_version_2_parameters_pass_thru
> Worldpay: Set default eCommerce indicator for EMVCO network tokens

- CHANGELOG
- lib/active_merchant/billing/check.rb
- test/unit/check_test.rb
Canadian routing numbers are typically handled either in print/MICR format or
electronic format (see https://en.wikipedia.org/wiki/Routing_number_(Canada)#Format).
Update check validation to handle checks with a valid Canadian institution number, presented in the standard electronic format.
Unit tests:
5002 tests, 74820 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Rubocop:
> Update Canadian institution number handling

- CHANGELOG
- lib/active_merchant/billing/gateways/mercado_pago.rb
- test/remote/gateways/remote_mercado_pago_test.rb
- test/unit/gateways/mercado_pago_test.rb
Updated `verify` method to allow custom amount in options to support card
validation rules.
CE-2136
Remote:
36 tests, 102 assertions, 3 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
Unit:
5004 tests, 74828 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Rubocop:
> Mercado Pago: Update verify for custom amount

- CHANGELOG
- test/test_helper.rb
This reverts commit 653116444dd926d6d5172563c11ed9a000301103.
Unit:
5009 tests, 74848 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Rubocop:
> Revert "Remove YAML warning on load_fixtures_method"

- CHANGELOG
- lib/active_merchant/billing/gateways/usa_epay_transaction.rb
- test/remote/gateways/remote_usa_epay_transaction_test.rb
* Added a store test for authorize with a third party token
* Updated authorize param to use 'payment' instead of 'credit card'
5010 tests, 74852 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Loaded suite test/unit/gateways/usa_epay_transaction_test
51 tests, 307 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Loaded suite test/remote/gateways/remote_usa_epay_transaction_test
34 tests, 127 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> USAePay: Add store test, update authorize param

- lib/active_merchant/billing/gateways/priority.rb
- test/remote/gateways/remote_priority_test.rb
* The existing add_bank method did not actually set the bank information
appropriately so removed it until further information if necessary
5009 tests, 74848 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
12 tests, 127 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
20 tests, 56 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Priority: Remove bank account tender type

- CHANGELOG
- lib/active_merchant/billing/gateways/wompi.rb
- test/unit/gateways/wompi_test.rb
CE-2013
Local Tests:
5010 tests, 74852 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit Tests:
12 tests, 51 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote Tests:
14 tests, 36 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Wompi: update authorization in capture

- CHANGELOG
- lib/active_merchant/billing/gateways/ipg.rb
- test/remote/gateways/remote_ipg_test.rb
Updated authorization for IPG so that `hosted_data_id` is sent for store
and `OrderId` for other
CE-2231
Unit:
5010 tests, 74852 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Rubocop:
Remote:
14 tests, 41 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> IPG: Update authorization for store

- CHANGELOG
- lib/active_merchant/billing/gateways/paymentez.rb
Updated card mappings for the paymentez implementation
CE-2167
Remote:
31 tests, 66 assertions, 6 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
80.6452% passed
Unit:
5010 tests, 74852 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Rubocop:
> Paymentez: Update card mappings

- lib/active_merchant/billing/gateways/orbital.rb
Fix for brand name correction for `master` in orbital gateway.
CE-2232
Unit:
5010 tests, 74849 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Rubocop:
Remote:
76 tests, 345 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Orbital: Quick fix for brand correction

- lib/active_merchant/billing/gateways/priority.rb
- test/remote/gateways/remote_priority_test.rb
- test/unit/gateways/priority_test.rb
* Refund was currently using blind credit instead of refund
* Removed unused params updates
5009 tests, 74781 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
11 tests, 59 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
20 tests, 56 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Priority: Cleaning up refund method

- CHANGELOG
- lib/active_merchant/billing/gateways/priority.rb
- test/remote/gateways/remote_priority_test.rb
- test/unit/gateways/priority_test.rb
* Return more useful error and success messages from parsing
* Tests are now looking at response.message, response.error_code instead of response['message'], response['errorCode'] etc.
5009 tests, 74782 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
11 tests, 60 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
20 tests, 55 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Priority: update parsing for error messages

- CHANGELOG
- lib/active_merchant/billing/gateways/ipg.rb
- test/remote/gateways/remote_ipg_test.rb
- test/unit/gateways/ipg_test.rb
Added `tpv_error_code` and `tpv_error_msg` response fields when store
transaction fails for IPG implementation.
Unit:
5011 tests, 74854 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Rubocop:
Remote:
16 tests, 48 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> IPG: Add store error response

- CHANGELOG
- lib/active_merchant/billing/gateways/ipg.rb
- test/unit/gateways/ipg_test.rb
Send default `currency` for verify method and allow two digit string in
`ExpMonth` in IPG request.
CE-2249
CE-2250
Unit:
5010 tests, 74849 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Rubocop:
Remote:
16 tests, 48 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> IPG: verify method bug fixes for core

- CHANGELOG
- lib/active_merchant/billing/gateways/stripe.rb
- test/remote/gateways/remote_stripe_payment_intents_test.rb
- test/remote/gateways/remote_stripe_test.rb
- test/unit/gateways/payeezy_test.rb
- test/unit/gateways/stripe_payment_intents_test.rb
- test/unit/gateways/stripe_test.rb
Adds the option to pass `skip_radar_rules`, which allows a radar-enabled account to create Charges or Intents without applying any radar screening to the transaction.
Also fixes a rubocop error and two date-specific test failures.
Reviewer should run remote tests for both the Stripe and Stripe Payment Intents gateway adapters.
CE-2234
5018 tests, 74825 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
Loaded suite test/remote/gateways/remote_stripe_test
75 tests, 342 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Loaded suite test/remote/gateways/remote_stripe_payment_intents_test
68 tests, 318 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 …
> Stripe: Add support for `skip_radar_rules`

- CHANGELOG
- lib/active_merchant/billing/gateways/cyber_source.rb
- test/remote/gateways/remote_cyber_source_test.rb
- test/unit/gateways/cyber_source_test.rb
Added `userPO`, `taxable`, `nationalTaxIndicator`, `taxAmount`, and
`nationalTax` in the cyber source implementation.
CE-2240
Remote:
101 tests, 520 assertions, 6 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
94.0594% passed
Unit:
5020 tests, 74836 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Rubocop:
> CyberSource: Add tax fields

- CHANGELOG
- lib/active_merchant/billing/gateways/kushki.rb
- test/remote/gateways/remote_kushki_test.rb
- test/unit/gateways/kushki_test.rb
CE-2246
Remote:
14 tests, 45 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
16 tests, 104 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Local:
5020 tests, 74837 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Kushki: Add support for `metadata`

- CHANGELOG
- lib/active_merchant/billing/gateways/orbital.rb
- test/remote/gateways/remote_orbital_test.rb
- test/unit/gateways/orbital_test.rb
Added `sca_merchant_initiated` field in orbital implementation to
support master card eci 7 to exempt from SCA when flag is set.
CE-2236
Remote:
77 tests, 349 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
5022 tests, 74849 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Rubocop:
> Orbital: Add SCA Merchant Initiated field

- lib/active_merchant/billing/gateways/global_collect.rb
- test/remote/gateways/remote_global_collect_test.rb
The production url for Ingenico (Global Collect) is
https://world.api-ingenico.com. Currently, Ingenico redirects to the
new url but it has been advised that we update the `live_url`.
[Ingenico endpoints](https://epayments-api.developer-ingenico.com/s2sapi/v1/en_US/java/endpoints.html?paymentPlatform=ALL)
CE-2116
Unit: 31 tests, 154 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 29 tests, 72 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
96.5517% passed
> GlobalCollect: Update Production Endpoint

- CHANGELOG
- lib/active_merchant/billing/gateways/decidir_plus.rb
- test/fixtures.yml
- test/remote/gateways/remote_decidir_plus_test.rb
- test/unit/gateways/decidir_plus_test.rb
This is a PR to add the gateway adapter for Decidir Plus
Things to note in this PR:
* No auth/capture or void/cancel transactions
* Payment Method's must be `stored` and the returned third party token
will be used in combination with other card data in subsequent
`purchase` and `refund` transactions
* The reference token is comprised of the `stored` payment method's `id`
(returned from Decidir+) and the `bin` of the payment method,
separated by a pipe (`|`)
* Authorization is handled by an `apikey` passed into the headers.
Either the `public_key` for the tokenization endpoint or `private_key`
for the rest
* Some fields that are stubbed in with defaults ARE REQUIRED in order
for the transaction to be successful (i.e., `purchase` will fail
without `sub_payments` array)
CE-2145
Unit: 6 …
> Decidir Plus: Add Gateway Adapter

- CHANGELOG
- lib/active_merchant/billing/gateways/decidir_plus.rb
- test/remote/gateways/remote_decidir_plus_test.rb
- test/unit/gateways/decidir_plus_test.rb
**What changed?**
* Refactored purchase method to pass arguments to other methods that are
responsible for appending the `post` hash with data for a `purchase`
transaction
* `token` and `bin` are parsed from a `payment` of String type instead
of a `payment_id` in the `options` hash
CE-2145
Unit: 6 tests, 20 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 8 tests, 27 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Decidir Plus: Update payment reference

- CHANGELOG
- lib/active_merchant/billing/gateways/paysafe.rb
- test/remote/gateways/remote_paysafe_test.rb
-`redact` method changed to `unstore`
CE-2285
Remote:
31 tests, 94 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
16 tests, 77 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Local:
5034 tests, 74935 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Rubocop:
> Paysafe: Update redact method

- CHANGELOG
- lib/active_merchant/billing/gateways/elavon.rb
- test/remote/gateways/remote_elavon_test.rb
CE-2242
Line 301 in add_auth_purchase_params was causing an extra ssl_token field with a nil value to be added to the request. The changes remove the extra ssl_token, which has eliminated the invalid card errors. I’ve added some logic in the commit method and the authorization_from method to handle the third_party_token coming from the store call.
Unit Tests:
47 tests, 243 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote Tests:
37 tests, 172 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
97.2973% passed
test_successful_special_character_encoding_truncation(RemoteElavonTest) is failing currently on master and on my branch. (the remote test results have been a bit inconsistent for me yesterday and today)
Local:
5035 …
> Elavon: `third_party_token` bug fix

- lib/active_merchant/billing/network_tokenization_credit_card.rb
- test/unit/network_tokenization_credit_card_test.rb
Some payment gateways require attributes that cannot currently
be instantiated with network_tokenization_credit_card.
For example - some gateways require `deviceManufacturerIdentifer` and
`paymentDataType` to be passed in for apple pay which can now be stored
in the metadata.
--------------
How `metadata` can be used - I did a quick 📖 and while `eci`, `payment_cryptogram`, `transaction_id` are common across wallets (hence we have these attributes in the model), there are some [apple-pay specific fields](https://developer.apple.com/library/archive/documentation/PassKit/Reference/PaymentTokenJSON/PaymentTokenJSON.html) such as `deviceManufacturerIdentifer` and `paymentDataType` and [google-pay specific fields](https://developers.google.com/pay/api/android/guides/resources/payment-data-crypto …
> Add metadata to network_tokenization_credit_card

- CHANGELOG
- lib/active_merchant/billing/gateways/decidir_plus.rb
- test/remote/gateways/remote_decidir_plus_test.rb
- test/unit/gateways/decidir_plus_test.rb
Add `sub_payment` fields to `purchase` transactions. This field needs to
be set in the post body, regardless of whether or not it is populated
with data.
Fix country code for this gateway.
CE-2145
Unit: 7 tests, 25 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 9 tests, 30 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Decidir Plus: Sub Payment Fields

- CHANGELOG
- lib/active_merchant/billing/gateways/payway_dot_com.rb
* updated Production and test endpoint URLs (old ones are deprecated as of Jan 31st 2022
and just return aywayCode only for gateway_specific_response_field message field
* Adds commit from https://github.com/DanAtPayway/active_merchant/pull/1/commits/b96319f41284faba982138d277688e3056141803
Loaded suite test/remote/gateways/remote_payway_dot_com_test
16 tests, 43 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Loaded suite test/unit/gateways/payway_dot_com_test
16 tests, 64 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
5038 tests, 74959 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> PayWay: Update endpoints and response code

- CHANGELOG
- lib/active_merchant/billing/gateways/global_collect.rb
- test/remote/gateways/remote_global_collect_test.rb
Also fixes an issue in the remote tests that caused intermittent
failures.
CE-2319
unit
5035 tests, 74943 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
rubocop
remote
Loaded suite test/remote/gateways/remote_global_collect_test
31 tests, 78 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
96.7742% passed
The following test is failing on master for unrelated reasons (it looks as though installments was never implemented correctly): 
`test_successful_purchase_with_installments`
> GlobalCollect: Add support for Naranja and Cabal card types

- CHANGELOG
- lib/active_merchant/billing/gateways/payflow.rb
- test/remote/gateways/remote_payflow_test.rb
- test/unit/gateways/payflow_test.rb
Added support for `stored_credential` to allow recurring payments of
cardholder and merchant in payflow pro implementation.
CE-2244
Closes #4277
Remote:
39 tests, 169 assertions, 10 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
74.359% passed
Unit:
5036 tests, 74956 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Rubocop:
> PayFlow Pro: Add Stored Credentials

- CHANGELOG
- lib/active_merchant/billing/gateways/decidir_plus.rb
- test/remote/gateways/remote_decidir_plus_test.rb
- test/unit/gateways/decidir_plus_test.rb
Add support for fraud detection with Decidir Plus.
This PR includes a method to add `fraud_detection` fields to the post
body of a `purchase` transaction. The `csmdds` subfield of
`fraud_detection` is expected to be given as an array of hashes with a
`code` and `description` value.
CE-2337
Unit: 8 tests, 30 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 10 tests, 33 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Decidir Plus: Fraud Detection Fields

- CHANGELOG
- lib/active_merchant/billing/gateways/credorax.rb
- test/remote/gateways/remote_credorax_test.rb
- test/unit/gateways/credorax_test.rb
**UPDATE: I have amended this PR to demonstrate that names get added to the requests when present. I made two comments on the PR showing where this update took place, in order to assist with reviewing.**
Credit should now be using `O=35` instead of `O=6`
CE-2235
Rubocop:
Unit:
5036 tests, 74946 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
45 tests, 164 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Credorax: Update OpCode for Credit transactions

- CHANGELOG
- lib/active_merchant/billing/gateways/credorax.rb
- test/remote/gateways/remote_credorax_test.rb
- test/unit/gateways/credorax_test.rb
This reverts commit 13eccbd9f24a761abaecc9ecf7d36e1c1a420a62.
This is being done because Credorax has indicated that they need to switch back to the general credit service signified by `OpCode: 6`.
Unit:
5050 tests, 75010 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Rubocop:
Remote:
Loaded suite test/remote/gateways/remote_credorax_test
45 tests, 164 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Revert "Credorax: Update OpCode for Credit transactions"

- CHANGELOG
- lib/active_merchant/billing/gateways/blue_snap.rb
- test/remote/gateways/remote_blue_snap_test.rb
- test/unit/gateways/blue_snap_test.rb
Bluesnap: Add support for optional Idempotency Key field on purchase, authorize, capture, refund, and void. Idempotency Key is passed as a header.
Unit tests:
41 tests, 237 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote tests:
49 tests, 166 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> CE-2343 Bluesnap Idempotency

- CHANGELOG
- lib/active_merchant/billing/gateways/decidir_plus.rb
- test/fixtures.yml
- test/remote/gateways/remote_decidir_plus_test.rb
- test/unit/gateways/decidir_plus_test.rb
Added `authorize`, `capture`, `void`, `verify` methods for decidir plus
along with its test cases.
CE-2159
Remote:
15 tests, 51 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
5059 tests, 75068 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Rubocop:
> Decidir Plus: Add supported methods

- CHANGELOG
- lib/active_merchant/billing/gateways/paymentez.rb
- test/remote/gateways/remote_paymentez_test.rb
Fixed `authorize` to call `purchase` so that capture can be made on core for paymentez implementation.
CE-1920
Remote:
33 tests, 83 assertions, 4 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
87.8788% passed
Unit:
5057 tests, 75059 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Rubocop:
> Paymentez: Fix authorize for core

- CHANGELOG
- lib/active_merchant/billing/gateways/orbital.rb
- test/remote/gateways/remote_orbital_test.rb
- test/unit/gateways/orbital_test.rb
This PR contains six commits. The first five commits are a step-by-step refactoring and reorganizing of the Orbital gateway adapter. This was done in order to make it possible to audit the gateway adapter's support of network tokenization.
The sixth commit adds the `supports_network_tokenization?` method to the gateway adapter.
The results of the audit are that the Orbital gateway adapter currently supports network tokenization as evidenced by the inclusion of the following fields in a transaction with a network token:
`AuthenticationECIInd`
`DPANInd` (set to the value 'Y')
`DigitalTokenCryptogram`
As per the Orbital docs, inclusion of `DigitalTokenCryptogram` obviates the requirement for brand-specific crytogram references in the request (such as `cavv`, `aav`, or `aevv`).
CE-2332 …
> Orbital: refactor gateway adapter and indicate support for network tokenization

- CHANGELOG
- lib/active_merchant/billing/gateways/ipg.rb
- test/unit/gateways/ipg_test.rb
Removed `uruguay` from supported countries along with its currency code
and test case changes in ipg implementation.
CE-2374
Unit:
5057 tests, 75059 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Rubocop:
Remote:
17 tests, 53 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> IPG: Remove Uruguay from supported countries

- CHANGELOG
- lib/active_merchant/billing/gateways/decidir_plus.rb
- test/remote/gateways/remote_decidir_plus_test.rb
- test/unit/gateways/decidir_plus_test.rb
Added `unstore` method along with its required changes in purchase to
receive valid token in decidir plus implementation.
CE-2144
Remote:
16 tests, 56 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
5064 tests, 75089 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Rubocop:
> DecidirPlus: Add `unstore` method

- CHANGELOG
- lib/active_merchant/billing/gateways/decidir.rb
- lib/active_merchant/billing/gateways/decidir_plus.rb
- test/remote/gateways/remote_decidir_plus_test.rb
- test/remote/gateways/remote_decidir_test.rb
The gateway expects the `sub_payments` sub-fields `installments` and `amount` to be integers instead of strings
CE-2361
Local:
5063 tests, 75084 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Rubocop:
Decidir Tests
Unit:
38 tests, 184 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
24 tests, 84 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Decidir Plus Tests
Unit:
11 tests, 44 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
15 tests, 51 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Decidir & Decidir Plus: Revise handling of sub_payment sub-fields

- lib/active_merchant/billing/gateways/decidir_plus.rb
- test/remote/gateways/remote_decidir_plus_test.rb
- test/unit/gateways/decidir_plus_test.rb
Improve the quality of the `message` we return in the response from the
gateway. These changes will account for a `status` of `rejected` and
check for an error message returned in the `status_details` from
Decidir Plus and will also account for `fraud_detection` responses
CE-2387
Unit: 13 tests, 53 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 16 tests, 56 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Decidir Plus: Improve response messaging

- CHANGELOG
- lib/active_merchant/billing/gateways/payu_latam.rb
- test/remote/gateways/remote_payu_latam_test.rb
CE-586
This PR has some refactoring of the `message_from` method. It also updates several tests that were failing due to changes in the gateway's response. PayU Latam now supports `capture` so tests that were added by a previous contributor were uncommented out.
Local:
5057 tests, 75059 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
38 tests, 101 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
37 tests, 146 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> PayU Latam: Refactor/fix failing remote tests

- lib/active_merchant/billing/gateways/safe_charge.rb
- test/remote/gateways/remote_safe_charge_test.rb
- test/unit/gateways/safe_charge_test.rb
Also updates tests to reflect new `verify` flow.
CE-190
Rubocop:
Unit:
5068 tests, 75098 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
Loaded suite test/remote/gateways/remote_safe_charge_test
30 tests, 83 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> SafeCharge: Change Verify to send 0 amount

- CHANGELOG
- lib/active_merchant/billing/gateways/d_local.rb
- test/remote/gateways/remote_d_local_test.rb
- test/unit/gateways/d_local_test.rb
CE-2421
Rubocop:
Unit:
5069 tests, 75101 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
Loaded suite test/remote/gateways/remote_d_local_test
29 tests, 76 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
96.5517% passed
The following test is failing for reasons unrelated to this change:
`test_successful_purchase_naranja`
As far as I can tell, this test began failing with [this commit](https://github.com/activemerchant/active_merchant/commit/cdfce9fe3a9962f93a0f2a2c7c83ac59042a3656). This test fails with the message "Merchant has no authorization to use this API". My hunch is that resolving this would require contacting dLocal to make adjustments to our Sandbox account.
> DLocal: Add support for `force_type` field

- CHANGELOG
- lib/active_merchant/billing/gateways/decidir_plus.rb
- test/remote/gateways/remote_decidir_plus_test.rb
- test/unit/gateways/decidir_plus_test.rb
Add support to override the payment method name value with one given in
the options hash.
CE-2149
Unit: 1 tests, 5 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 17 tests, 60 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Decidir Plus: `name_override` option on `store`

- test/remote/gateways/remote_stripe_payment_intents_test.rb
- test/unit/gateways/stripe_payment_intents_test.rb
Tested shipping address field to be passed in to the stripe pi gateway.
CE-2425
Remote:
73 tests, 327 assertions, 4 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
94.5205% passed
Unit:
5070 tests, 75113 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Rubocop:
> Stripe PI: test shipping address

- CHANGELOG
- lib/active_merchant/billing/gateways/decidir_plus.rb
- test/remote/gateways/remote_decidir_plus_test.rb
Determine `payment_method_id` based on `card_brand` passed in the
options hash for auth and purchase transactions
CE-2424
Unit: 13 tests, 53 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote0: 17 tests, 58 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> DecidirPlus: Handle `payment_method_id` by `card_brand`

- CHANGELOG
- lib/active_merchant/billing/gateways/decidir_plus.rb
- test/remote/gateways/remote_decidir_plus_test.rb
- test/unit/gateways/decidir_plus_test.rb
Add support for `debit` and `payment_method_id` gateway fields. Decidir+
requires that transactions after `store` need to contain a
`payment_method_id` that corresponds to the `payment_method` tokenized
on the initial `store` call. `payment_method_id`'s are also different
for debit and credit cards, so the `debit` option allows for users to
pass that value manually.
CE-2424
Unit: 13 tests, 55 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 22 tests, 74 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> DecidirPlus: `debit` and `payment_method_id` fields

- lib/active_merchant/billing/gateway.rb
- lib/active_merchant/billing/gateways/stripe.rb
We have a requirement to display a better message to merchants for Stripe's `amount_too_small` error. This will raise our `amount_invalid` error message suggesting an amount error instead of the default error informing the buyer to try again in a few minutes.
`rake test:units TEST=test/unit/gateways/stripe_test.rb`
```
....................................................................................
Finished in 0.048985 seconds.
------------------------------------------------------------------------------------------------------------------------------------------------
142 tests, 750 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
--------------------------------------------------------------------------------------------------------------------- …
```
> Addition of invalid_amount for amount_too_small Stripe error handler

- CHANGELOG
- lib/active_merchant/billing/gateways/decidir_plus.rb
- test/remote/gateways/remote_decidir_plus_test.rb
- test/unit/gateways/decidir_plus_test.rb
Updated `error_code_from` method to contain reason id in the error code
response.
CE-2490
Unit:
5113 tests, 75341 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Rubocop:
736 files inspected, no offenses detected
Remote:
23 tests, 77 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> DecidirPlus: Update `error_code` method

- CHANGELOG
- lib/active_merchant/billing/gateways/stripe_payment_intents.rb
- test/remote/gateways/remote_stripe_payment_intents_test.rb
Merchants that want to trigger 3DS flows manually
use the `request_three_d_secure` field when creating an intent
to do that. This was already added to `create_intent`, this
commit adds it to the `create_setup_intent` as well.
Stripe docs: https://stripe.com/docs/api/setup_intents/object#setup_intent_object-payment_method_options-card-request_three_d_secure
ECS-2391
Test Summary
Local:
5123 tests, 75395 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
39 tests, 207 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
75 tests, 353 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Stripe PI: add request_three_d_secure to setup_intent

- CHANGELOG
- lib/active_merchant/billing/gateways/visanet_peru.rb
- test/unit/gateways/visanet_peru_test.rb
Unit: 16 tests, 96 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 18 tests, 27 assertions, 16 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
11.1111% passed
CE-1846
> Visanet Peru: use timestamp for purchase number

- CHANGELOG
- lib/active_merchant/billing/gateways/rapyd.rb
- test/remote/gateways/remote_rapyd_test.rb
- test/unit/gateways/rapyd_test.rb
Add support to pass `metadata` on `purchase`, `authorize`, and `refund`
transactions and `ewallet_id` on `purchase` and `authorize`
transactions.
`metadata` can contain any collection of data so long as it is a json
object.
CE-2396
Unit: 16 tests, 47 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 21 tests, 57 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Rapyd: Add `metadata` and `ewallet_id` options

- CHANGELOG
- lib/active_merchant/billing/gateways/priority.rb
- test/remote/gateways/remote_priority_test.rb
- test/unit/gateways/priority_test.rb
CE-2491
This PR makes significant adjustments to the Priority gateway integration.
I will describe some of the changes below, but I also want to note two areas that warrant additional investigation:
1. the`verify` action and its dependency `create_jwt`. These methods are using the gateway's BIN lookup service, which is not a standard approach to verifying a card.
2. the `get_payment_status` and `close_batch` actions. It's not clear why these actions were implemented, as they are currently being used exclusively to manipulate transactions within the test cases. A merchant going through Spreedly would have no way to take advantage of these actions.
I will open some new tickets to investigate these two areas.
The changes made in this PR include:
* The  `pos_data` object has been extracted to …
> Priority: Refactor gateway integration, add additional fields to request

- CHANGELOG
- lib/active_merchant/billing/gateways/rapyd.rb
- test/remote/gateways/remote_rapyd_test.rb
- test/unit/gateways/rapyd_test.rb
Field name change to `pm_type` to be more specific
CE-2396
Unit: 16 tests, 47 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 21 tests, 57 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Rapyd: Update `type` option to `pm_type`

- lib/active_merchant/billing/gateways/priority.rb
- test/unit/gateways/priority_test.rb
Turns out, when you use `replay_id` to recall a previous transaction that has already settled or has already been voided, the response.status is `Settled` or `Voided`, respectively. These statuses were not included in the `success_from` method and we were not testing for these scenarios, so the result would be to incorrectly mark the transaction as `failed`.
Rubocop:
Unit:
5160 tests, 75567 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
27 tests, 81 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Priority: add `settled` and `voided` to list of successful response statuses

- CHANGELOG
- lib/active_merchant/billing/gateways/blue_pay.rb
- lib/active_merchant/billing/gateways/checkout_v2.rb
- lib/active_merchant/billing/gateways/paysafe.rb
- test/remote/gateways/remote_blue_pay_test.rb
- test/remote/gateways/remote_paysafe_test.rb
- test/unit/gateways/blue_pay_test.rb
- test/unit/gateways/checkout_v2_test.rb
- test/unit/gateways/paysafe_test.rb
CE-2541
There is a bug in the `case` statements where we are attempting to
resolve it conditionally with an `||`, but `case` takes a single value
or list of values
Tests for BluePay were failing, due to a different `response.message`
The `test_invalid_credentials` test for PaySafe was not failing with the expected response
Unit:
BluePay: 30 tests, 142 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Paysafe: 16 tests, 77 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
40 tests, 236 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
CheckoutV2: 43 tests, 110 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
BluePay: 19 tests, 90 …
> Multiple Gateways: Resolve `when/case` bug

- CHANGELOG
- lib/active_merchant/billing/gateways/airwallex.rb
- test/remote/gateways/remote_airwallex_test.rb
- test/unit/gateways/airwallex_test.rb
Add support for Spreedly's 3DS Global Solution. One notable distinction
is that Airwallex only supports three digit 3DS versions. Versions
returned from the MPI are formatted to meet that requirement.
Ex: 2.0 => 2.0.0
CE-2301
Unit:
31 tests, 130 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
25 tests, 56 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Airwallex: Add 3DS Global Support

- CHANGELOG
- lib/active_merchant/billing/credit_card_methods.rb
- test/unit/credit_card_methods_test.rb
Add bin ranges so that the French card brand Cartes Bancaires can be identified.
Confirmed that all Cartes Bancaires cards are fixed at 16 characters in length.
_______
**Test Summary:**
Unit:
5156 tests, 75540 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
291.85 tests/s, 4275.79 assertions/s
Local
5160 tests, 75568 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Add Cartes Bancaires bin ranges

- CHANGELOG
- lib/active_merchant/billing/gateways/airwallex.rb
- test/remote/gateways/remote_airwallex_test.rb
- test/unit/gateways/airwallex_test.rb
Airwallex requires specific NTID values in order to test the full Stored
Credential flow from CIT auth to MIT purchase. These values are now
automatically populated based on card `brand`. This PR also removes the
`original_transaction_id` GSF.
CE-2593
Unit:
33 tests, 176 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
100% passed
> Airwallex: Update Stored Credential testing

- CHANGELOG
- lib/active_merchant/billing/gateways/simetrik.rb
- test/remote/gateways/remote_simetrik_test.rb
- test/unit/gateways/simetrik_test.rb
CE-2407
This PR does some refactoring and updates some value types that were being passed incorrectly. The scrub method has also been updated.
Remote tests:
12 tests, 24 assertions, 0 failures, 8 errors, 0 pendings, 0 omissions, 0 notifications
33.3333% passed
Unit tests:
12 tests, 82 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Simetrik: Fix integer and float types

- lib/active_merchant/billing/gateways/monei.rb
- test/unit/gateways/monei_test.rb
Monei's sandbox does not care if this field gets passed or not, but its omission will cause failures in production.
This field can be found[ here in Monei's docs ](https://docs.monei.com/api/#operation/payments_create
)if you expand the `paymentMethod` object and the child `card` object.
CE-2562
Rubocop:
Unit:
5174 tests, 75676 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
100% passed
> Monei: add cardholderName field

- CHANGELOG
- lib/active_merchant/billing/gateways/blue_snap.rb
- test/remote/gateways/remote_blue_snap_test.rb
- test/unit/gateways/blue_snap_test.rb
Depending on which endpoint is being used, the gateway's response on a refund will include the transaction id in either the `transaction-id` or the `refund-transaction-id` field of the parsed response.
This change updates the `authorize_from` method to account for the presence of `refund-transaction-id` on select refund transactions.
Currently, there is one remote test that is failing on master: `test_successful_purchase_with_level3_data`. When I inspect the response for this test, I do not see any of [the response fields that BlueSnap's documentation lists for level3data](https://developers.bluesnap.com/v8976-JSON/docs/level3data). Instead I see ` "transaction-processed-with-l3d-supported-acquirer"=>"false"`. My best guess here is that this indicates a setting that needs to be changed on …
> BlueSnap: parse refund-transaction-id correctly

- CHANGELOG
- lib/active_merchant/billing/gateways/worldpay.rb
- test/unit/gateways/worldpay_test.rb
The data is embedded in XML attributes and was therefore not included in the parsed response.
There is no remote test to describe this behavior because Worldpay's Sandbox does not return `IssuerResponseCode`. An example of the XML response we should expect has been included in the unit tests.
CE-2546
Rubocop:
Unit:
5175 tests, 75682 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
94 tests, 392 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Worldpay: extract issuer response code

- CHANGELOG
- lib/active_merchant/billing/gateways/litle.rb
- test/unit/gateways/litle_test.rb
The LitleGateway parse method reads elements and their text values, but does not read any of the elements attributes. Here we read one very specific attribute (probably not worth generalizing just yet). Here we're interested in a Litle saleResponse that may or may not have the attribute `duplicate='true'`. All Litle saleResponses will include duplicate: true/false.
Note on testing: Remote test for this feature is missing. It looks like the `testvantivcnp` api does not return the duplicate attribute the same way the production api does. Additionally, something seems to have changed in the `testvantivcnp` api such that existing remote tests fail. PR coming soon with fixes for existing tests.
CE-2506
Local:
5175 tests, 75684 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 …
> Vantiv: Read saleResponse duplicate attribute

- lib/active_merchant/billing/gateways/rapyd.rb
- test/remote/gateways/remote_rapyd_test.rb
- test/unit/gateways/rapyd_test.rb
Add support for 3DS v2 fields for Rapyd
Rapyd supports the standard transaction fields for 3DS: `3d_version`,
`cavv`, `eci`, `xid`, `ds_trans_id`
Fields can be passed, regardless of the version being used.
Documentation for simulating a 3DS transaction can be found in the Rapyd
documentation for
[Simulating 3DS Authentication](https://docs.rapyd.net/build-with-rapyd/reference/testing-for-payments-api#simulating-3ds-authentication-api-method)
CE-2596-rapyd_3ds
Unit: 16 tests, 47 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 23 tests, 65 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Rapyd: 3DS Support

- CHANGELOG
- lib/active_merchant/billing/gateways/d_local.rb
- test/unit/gateways/d_local_test.rb
The `X-Idempotency-Key` header was not being sent in requests.
CE-2655
Rubocop:
Unit:
5185 tests, 75757 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
31 tests, 80 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
96.7742% passed
The following test is failing for reasons unrelated to this change:
`test_successful_purchase_naranja`
As far as I can tell, this test began failing with [this commit](https://github.com/activemerchant/active_merchant/commit/cdfce9fe3a9962f93a0f2a2c7c83ac59042a3656). This test fails with the message "Merchant has no authorization to use this API". My hunch is that resolving this would require contacting dLocal to make adjustments to our Sandbox …
> DLocal: fix Idempotency Header bug

- CHANGELOG
- lib/active_merchant/billing/gateways/rapyd.rb
- test/remote/gateways/remote_rapyd_test.rb
- test/unit/gateways/rapyd_test.rb
Add support for:
* `complete_payment_url`
* `error_payment_url`
* `description`
* `statement_descriptor`
These fields are subfields of the `payment` object
CE-2606
Unit: 18 tests, 76 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 23 tests, 65 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Rapyd: Additional Fields

- CHANGELOG
- lib/active_merchant/billing/gateways/braintree_blue.rb
- test/remote/gateways/remote_braintree_blue_test.rb
For ECS-2435
Test Summary
Local: 5176 tests, 75655 assertions, 0 failures, 18 errors, 0 pendings, 0 omissions, 0 notifications
99.6522% passed
Unit: 90 tests, 200 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 96 tests, 524 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Braintree Blue: Return client token in AM response

- CHANGELOG
- lib/active_merchant/billing/gateways/rapyd.rb
- test/unit/gateways/rapyd_test.rb
Add support for $0 auth (verify). In order to successfully pass a $0
verify, the value much be an int.
CE-2618
Unit: 16 tests, 65 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 23 tests, 65 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Rapyd: Zero Dollar Auth

- CHANGELOG
- lib/active_merchant/billing/gateways/rapyd.rb
- test/remote/gateways/remote_rapyd_test.rb
Scrub the `account_number` and `routing_number` from the transcript
CE-2622
Unit: 17 tests, 69 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 24 tests, 69 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Rapyd: Scrub ACH

- CHANGELOG
- lib/active_merchant/billing/gateways/visanet_peru.rb
CE-2624
This updates the existing time stamp logic and filters it to be an even more specific slice of time, and appends two randomly generated numbers  to the end of the string. The existing unit test (def test_nonconsecutive_purchase_numbers
on line 42) seemed sufficient and is passing. 16  of 18 remote tests are failing and have been for at least 6 months.
Unit:
16 tests, 96 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
18 tests, 27 assertions, 16 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
11.1111% passed
Local:
5184 tests, 75754 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> VisaNet Peru: purchase_number bug fix

- CHANGELOG
- lib/active_merchant/billing/gateways/plexo.rb
- test/remote/gateways/remote_plexo_test.rb
- test/unit/gateways/plexo_test.rb
Changed field name from `meta_data` to `metadata` as per the standards
of the gateway field.
CE-2567
Unit:
5208 tests, 75877 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Rubocop:
742 files inspected, no offenses detected
Remote:
16 tests, 47 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Plexo: Change field name to `metadata`

- CHANGELOG
- lib/active_merchant/billing/gateways/rapyd.rb
Add `ewallet` to `refund` and `metadata`, `ewallet`, and
`payment_fields` to `store` transactions.
CE-2606
Unit: 18 tests, 79 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 27 tests, 79 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Rapyd: Pass Fields to `refund` and `store`

- CHANGELOG
- lib/active_merchant/billing/gateways/airwallex.rb
Accidentally left comments in a previous commit. This PR removes them.
CE-2665
Unit:
33 tests, 176 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
100% passed
> Airwallex: Remove comments

- CHANGELOG
- lib/active_merchant/billing/gateways/airwallex.rb
- test/unit/gateways/airwallex_test.rb
The `referrer_data` field is used internally by Airwallex to monitor traffic
CE-2678
Unit:
34 tests, 179 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
100% passed
> Airwallex: Send `referrer_data` on `create_payment_intent` requests

- CHANGELOG
- lib/active_merchant/billing/gateways/adyen.rb
- lib/active_merchant/billing/gateways/stripe_payment_intents.rb
- test/remote/gateways/remote_adyen_test.rb
- test/remote/gateways/remote_stripe_payment_intents_test.rb
- test/unit/gateways/adyen_test.rb
This changes the error message returned when the 'attempt_3dsecure' flag is left off a gateway request in need of authentication at the gateway to be clearer to someone using Spreedly's API.
[ECS-2393](https://spreedly.atlassian.net/browse/ECS-2393)
rake test:local - 5213 tests, 75896 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Stripe PI Unit: 39 tests, 207 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Stripe PI Remote: 77 tests, 357 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Adyen Unit: 94 tests, 479 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Adyen Remote (same 3 failures appear on Master): 123 tests, 439 assertions, 3 …
> Updated error messaging for Adyen/StripePI

- CHANGELOG
- lib/active_merchant/billing/gateways/airwallex.rb
- test/unit/gateways/airwallex_test.rb
This commit changes `referrer_type` to `referrer_data`
CE-2678
Unit:
34 tests, 179 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
100% passed
> Airwallex: Fix `referrer_data` on Setup transactions

- CHANGELOG
- lib/active_merchant/billing/gateways/rapyd.rb
- test/remote/gateways/remote_rapyd_test.rb
- test/unit/gateways/rapyd_test.rb
Update the `add_address` method to populate from the `billing_address`
subhash of the `options` hash.
Also modify the `phone` to remove non-int characters
SER-137
Unit: 18 tests, 79 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 27 tests, 79 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Rapyd: Correctly add `billing_address`

- CHANGELOG
- lib/active_merchant/billing/gateways/shift4.rb
- test/fixtures.yml
- test/remote/gateways/remote_shift4_test.rb
- test/unit/gateways/shift4_test.rb
Refactored gateway as per the technical document, updated remote tests to remove redundancy, refactored gateway file to remove unwanted fields.
SER
Remote:
11 tests, 29 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Rubocop:
Unit:
5229 tests, 75978 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Shift4: Code Refactoring

- CHANGELOG
- lib/active_merchant/billing/gateways/paypal/paypal_express_response.rb
- test/unit/gateways/paypal_express_test.rb
This adds an accessor method to the Paypal Express Response object that allows easy retrieval of the transaction status.
[ECS-2405](https://spreedly.atlassian.net/browse/ECS-2405)
Remote Paypal Express:
3 tests, 8 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit Paypal Express:
66 tests, 196 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Local:
5216 tests, 75920 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Paypal Express: Add checkout status to response object

- CHANGELOG
- lib/active_merchant/billing/gateways/rapyd.rb
`complete_payment_url` and `error_payment_url` were incorrectly nested
in the `payment` hash.
[Rapyd Payment Object](https://docs.rapyd.net/build-with-rapyd/reference/payment-object)
SER-154
Unit: 18 tests, 80 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 27 tests, 79 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Rapyd: Un-nest the payment urls

- CHANGELOG
- lib/active_merchant/billing/gateways/paypal/paypal_express_response.rb
- test/unit/gateways/paypal_express_test.rb
Updates response method name.
Local:
5231 tests, 75997 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
66 tests, 196 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
3 tests, 8 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Paypal Express: Correct naming mistake for accessor

- CHANGELOG
- lib/active_merchant/billing/gateways/shift4.rb
Passing `100` integer value ends up literally being $100, since Shift4
takes the `amount` as a float.
SER-160
Unit: 18 tests, 80 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 27 tests, 79 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Shift4: $0 auth

- CHANGELOG
- lib/active_merchant/billing/gateways/shift4.rb
- test/remote/gateways/remote_shift4_test.rb
- test/unit/gateways/shift4_test.rb
Updated `success_from` method to look into response code along with errors in response to determine success.
SER-166
Unit:
5243 tests, 76069 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Rubocop:
Remote:
16 tests, 35 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Shift4: Update `success` definition

- lib/active_merchant/billing/gateways/airwallex.rb
- test/remote/gateways/remote_airwallex_test.rb
- test/unit/gateways/airwallex_test.rb
Airwallex has requested that we default to a uuid instead of a timestamp for these fields.
They have also requested that we remove the `_setup` suffix from the `merchant_order_id` field, as that field does not need to be unique per transaction and will be used by customers during reconciliation.
The `_setup` suffix remains for the `request_id` field, because that field must be unique for every request, so the suffix is useful for differentiating two separate but associated requests (e.g. a `create_payment_intent` followed by a subsequent `sale`).
SER-65
Unit:
5243 tests, 76069 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Rubocop:
Remote:
Loaded suite test/remote/gateways/remote_airwallex_test
26 tests, 61 …
> Airwallex: change timestamps to uuids and remove `_setup` suffix from merchant_order_id

- CHANGELOG
- lib/active_merchant/billing/credit_card.rb
- lib/active_merchant/billing/credit_card_methods.rb
- lib/active_merchant/billing/gateways/checkout_v2.rb
- test/remote/gateways/remote_checkout_v2_test.rb
- test/unit/credit_card_methods_test.rb
- test/unit/gateways/checkout_v2_test.rb
This PR takes the BINs from [this list](https://www.checkout.com/docs/payments/payment-methods/cards/mada#Mada_BINs) and adds any that do not already pass validation.
CheckoutV2 also requests the metadata field `udf1` be sent on Mada transactions, so this will be added on BINs where we can definitively determine the `mada` card type.
No remote tests are added using these BINs, because Checkout does not provide any test numbers in these BIN ranges, and Checkout's sandbox rejects any payments not using test numbers.
A support ticket has been opened at the gateway to request valid test data for Mada cards.
SER-35
Unit:
5246 tests, 76083 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Rubocop:
Remote:
Loaded …
> Add mada card type; add support in CheckoutV2

- CHANGELOG
- lib/active_merchant/billing/gateways/stripe.rb
- test/remote/gateways/remote_stripe_test.rb
- test/test_helper.rb
- test/unit/gateways/stripe_test.rb
Update the `add_charge_details` method to include an `add_shipping_address`
method, similar to the [Stripe Payment Intents integration](https://github.com/activemerchant/active_merchant/blob/master/lib/active_merchant/billing/gateways/stripe_payment_intents.rb#L36). The [Charges API](https://stripe.com/docs/api/charges/create#create_charge-shipping) accepts these fields as well.
CER-35
Remote
Finished in 138.947824 seconds.
75 tests, 342 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit
Finished in 0.098302 seconds.
143 tests, 759 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Local
Finished in 21.406045 seconds.-
5245 tests, 76084 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications …
> Stripe: Add shipping address

- CHANGELOG
- lib/active_merchant/billing/gateways/worldpay.rb
- test/remote/gateways/remote_worldpay_test.rb
- test/unit/gateways/worldpay_test.rb
CER-18
This PR updates the logic in the `required_status_message` and `message_from` methods. It should prevent the AM generated response message from showing up in auth or purchase (where it does not belong) and also adds `issuer_response_description` as an option for the response message.  I was not able to replicate the AM generated failure response message with remote tests, and the IssuerResponseCode (and it’s attribute description) are not returned in the sandbox.
These changes have exposed some flawed logic for 3 of the Remote 3DS Auth tests. I've left comments on them with further explanation for why I've commented some lines out.
A unit test has been included to show that in the absence of a useful response from the gateway, the issuer/bank response can be mapped to …
> Worldpay: update logic for AM generated response message

- CHANGELOG
- lib/active_merchant/billing/gateways/worldpay.rb
- test/remote/gateways/remote_worldpay_test.rb
- test/unit/gateways/worldpay_test.rb
This reverts commit 60f2fc9b8bff37a412a84f59335daaeee69294f7.
This is being done because these changes are triggering 3DS test failures.
CER-18
Unit
103 tests, 608 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote
99 tests, 408 assertions, 0 failures, 1 errors, 0 pendings, 0 omissions, 0 notifications
98.9899% passed
* This test has been erroring on master, unrelated to this change
Local
5263 tests, 76133 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Revert "Worldpay: update logic for AM generated response message"

- CHANGELOG
- lib/active_merchant/billing/gateways/braintree_blue.rb
- test/fixtures.yml
- test/remote/gateways/remote_braintree_blue_test.rb
- test/unit/gateways/braintree_blue_test.rb
Support for specifying the Venmo business profile, passed when specified
in creating the payment nonce client-side.
https://developer.paypal.com/braintree/docs/guides/venmo/server-side/ruby#specifying-the-business-profile
ECS-2518
Unit:
91 tests, 201 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
98 tests, 530 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> BraintreeBlue: Add venmo profile_id

- CHANGELOG
- lib/active_merchant/billing/gateways/braintree_blue.rb
- test/remote/gateways/remote_braintree_blue_test.rb
- test/unit/gateways/braintree_blue_test.rb
Braintree blue can support partial captures for certain
types of transactions. This commit adds logic to handle partial capture
logic if the `partial_capture` field is passed down.
Test Summary
Local:
5269 tests, 76156 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
92 tests, 204 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
98 tests, 530 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Braintree Blue: Partial capture

- CHANGELOG
- lib/active_merchant/billing/gateways/global_collect.rb
- test/remote/gateways/remote_global_collect_test.rb
- test/unit/gateways/global_collect_test.rb
CER-59
Adds `payment_product_id` as an option that can be passed as an override to the
existing `BRAND MAP`.
Unit:
43 tests, 219 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
40 tests, 104 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
97.5% passed
The failing test is also failing on master
Local:
5271 tests, 76163 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Ingenico: add support for `paymentProductId`

- CHANGELOG
- lib/active_merchant/billing/gateways/adyen.rb
- test/remote/gateways/remote_adyen_test.rb
- test/unit/gateways/adyen_test.rb
This makes it possible to pass the `networkTxReference` field with `store`
CER-91
Unit:
95 tests, 482 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
124 tests, 443 assertions, 3 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
97.5806% passed
One failing test is related to something that might be an outdated assumption (Adyen doesn’t allow recurring transactions with Cabal). The other two are 3DS2-related. All are failing on master.
Local:
5272 tests, 76166 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Adyen: add network_transaction_id to store call

- CHANGELOG
- lib/active_merchant/billing/gateways/worldpay.rb
- test/remote/gateways/remote_worldpay_test.rb
This change ensures that the machine cookie is extracted from the response correctly and returned in the initial 3DS setup request will be included in the headers on all the subsequent requests in the Worldpay challenge flow.
There are 3 calls total for a purchase using Worldpay's 3ds:
1. The preauth/setup request: sent to WP as an `authorize`, this one won't need a cookie as it's the first request. We'll receive a response that requests 3DS authentication, and contains a cookie. Then there is a redirect to the issuer's challenge form. 
2. The "3ds order": another redirect will happen after the user submits the form, and we get the authentication results from issuer. Then we'll send Worldpay the "3ds order" containing the authentication results in the `paResponse` field. This one must …
> Add machine cookie to subsequent calls during 3DS challenge

- lib/active_merchant/billing/gateways/airwallex.rb
- test/unit/gateways/airwallex_test.rb
`return_url` is no longer a required field on Airwallex authorizations. This PR changes it to an optional field.
CE-225
Unit:
33 tests, 181 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
100% passed
> Airwallex: update `return_url`

- CHANGELOG
- lib/active_merchant/billing/gateways/stripe_payment_intents.rb
- test/remote/gateways/remote_stripe_payment_intents_test.rb
ECS-2548
The Stripe PI gateway setup intent flow does
not include an optional options hash during
the retrieve_setup_intent method. This
prohibits someone using Stripe connect
from completing this flow.
Test Summary
Local:
5273 tests, 76175 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
39 tests, 207 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
78 tests, 371 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Stripe PI: add options for setup intent

- CHANGELOG
- lib/active_merchant/billing/gateways/checkout_v2.rb
- test/remote/gateways/remote_checkout_v2_test.rb
- test/unit/gateways/checkout_v2_test.rb
Updated checkoutv2 to take payment id from options parameters instead of getting it as a payment method.
SER-201
Remote:
72 tests, 186 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
5269 tests, 76156 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Rubocop:
> CheckoutV2: Update logic to send payment id via options

- CHANGELOG
- lib/active_merchant/billing/gateways/airwallex.rb
- test/remote/gateways/remote_airwallex_test.rb
- test/unit/gateways/airwallex_test.rb
Added `skip_3ds` field support for airwallex along with unit and remote test cases.
SEr-229
Unit:
5276 tests, 76200 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Rubocop:
Remote:
27 tests, 63 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Airwallex: Add `skip_3ds` field

- CHANGELOG
- lib/active_merchant/billing/gateways/shift4.rb
- test/remote/gateways/remote_shift4_test.rb
- test/unit/gateways/shift4_test.rb
Corrected parameter typo for stored credential to `initial_transaction` in the shift4 implementation along with testing.
SER-193
Unit:
5284 tests, 76224 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Rubocop:
Remote:
17 tests, 39 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Shift4: Stored credential parameter name change

- CHANGELOG
- lib/active_merchant/billing/gateways/rapyd.rb
- test/remote/gateways/remote_rapyd_test.rb
- test/unit/gateways/rapyd_test.rb
For `authorize` and `purchase` transactions we can optionally pass the
`customer` object which is similarly used in the transaction endpoint.
The value is prepended `cus_` and is required if the payment method is
omitted
`add_token` was incorrectly sending the whole `authorization` which is a
combination of a transaction or customer id and a payment token (based
on the `authorization_from` method
Remote test for `test_successful_store_and_purchase` includes a
commented out test purchase (commented out) because the payment method
must go through a 3DS authorization flow before it can be utilized in
payment transactions (sandbox only)
[Create Customer Object](https://docs.rapyd.net/build-with-rapyd/reference/customer-object#create-customer)
SER-228
Unit: 20 tests, 91 assertions, 0 failures, …
> Rapyd: Pass Customer ID and fix `add_token` method

- CHANGELOG
- lib/active_merchant/billing/gateways/worldpay.rb
- test/remote/gateways/remote_worldpay_test.rb
- test/unit/gateways/worldpay_test.rb
CER-18
Updating the `required_status_message` method to only generate the AM response if using one of the actions called out in the method. The transaction types are all multi-response and use a combination of actions.
Remote Tests:
100 tests, 392 assertions, 4 failures, 1 errors, 0 pendings, 0 omissions, 0 notifications
95% passed
*4 failing tests are 3DS tests that hinge on that message being auto-generated. The message being auto-generated means that the transaction itself failed. When prying into the responses, for these tests `@success = false`. The 1 error is also happening on master, may be related to recent Worldpay updates.
Unit Tests:
104 tests, 613 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Local:
5274 tests, 76180 assertions, 0 …
> Worldpay: Update  `required_status_message` and `message_from` methods

- CHANGELOG
- lib/active_merchant/billing/gateways/adyen.rb
- test/remote/gateways/remote_adyen_test.rb
This change allows ACH transactions to fail with an Adyen error message
instead of with a NoMethodError when no `:country` is present inside the
`:billing_address` hash
CER-151
LOCAL
5284 tests, 76224 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
UNIT
95 tests, 482 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
REMOTE
125 tests, 445 assertions, 3 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
97.6% passed
- There are two 3DS tests failing, and another related to Cabal card type. These failures are not connected to this change and are also failing on master
> Adyen: modify handling of countryCode for ACH

- CHANGELOG
- lib/active_merchant/billing/gateways/litle.rb
- test/remote/gateways/remote_litle_test.rb
- test/unit/gateways/litle_test.rb
CER-51
This PR adds the `fraudFilterOverride` flag, a boolean which when set to true will override all fraud filters for the submitted transaction.
Unit Tests:
56 tests, 240 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote Tests:
56 tests, 226 assertions, 13 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
76.7857% passed
* I ran the remote tests several times and 13 (sometimes 14) tests are failing and have been for over a year. I think this gateway is due for an overhaul but the failures aren’t related to the changes and are also failing on master.
Local Tests:
5288 tests, 76246 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Vantiv(Litle): Add support for `fraudFilterOverride`

- CHANGELOG
- lib/active_merchant/billing/gateways/payu_latam.rb
- test/remote/gateways/remote_payu_latam_test.rb
- test/unit/gateways/payu_latam_test.rb
This adds three optional fields to the `extra_parameters` block.
I have also modified the test expectations for three failing remote tests.
The behavior is the same, but the gateway error message seems to have slightly changed.
CER-150
LOCAL
5291 tests, 76262 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
UNIT
38 tests, 151 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
REMOTE
39 tests, 103 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> PayU Latam: Add `extra1`, `extra2`, `extra3` fields

- CHANGELOG
- lib/active_merchant/billing/gateways/paysafe.rb
- test/remote/gateways/remote_paysafe_test.rb
- test/unit/gateways/paysafe_test.rb
Beginning in September 2022, Paysafe will require mandatory changes to the handling of Account Funding Transactions via the Visa network
https://developer.paysafe.com/en/cards/api/#/fundingTransaction
CER-96
LOCAL
5288 tests, 76248 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
UNIT
17 tests, 82 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
REMOTE
33 tests, 101 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Paysafe: Add fundingTransaction object

- CHANGELOG
- lib/active_merchant/billing/gateways/merchant_e_solutions.rb
- test/remote/gateways/remote_merchant_e_solutions_test.rb
- test/unit/gateways/merchant_e_solutions_test.rb
Test `moto_ecommerce_ind` field for purchase transaction along with unit and remote tests.
SER-271
Remote:
20 tests, 84 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
5293 tests, 76270 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Rubocop:
> MerchantE: Test `moto_ecommerce_ind` field passing.

- lib/active_merchant/billing/gateways/alelo.rb
- test/fixtures.yml
- test/remote/gateways/remote_alelo_test.rb
- test/unit/gateways/alelo_test.rb
- test/unit/transcripts/alelo_purchase
- test/unit/transcripts/alelo_purchase_scrubbed
Adding purchase call and updating the response handling
so the code is able to retry the acces_token and key in
unauthorized errors.
Finished in 37.256649 seconds.
5295 tests, 76270 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Finished in 30.736933 seconds.
16 tests, 41 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Add purchase Alelo

- CHANGELOG
- lib/active_merchant/billing/gateways/rapyd.rb
Removed brazil, mexico, and US from rapyd supported countries.
SER-278
Unit:
5293 tests, 76279 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Rubocop:
Remote:
29 tests, 84 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Rapyd: Update Supported Countries

- CHANGELOG
- lib/active_merchant/billing/gateways/stripe_payment_intents.rb
- test/remote/gateways/remote_stripe_payment_intents_test.rb
This corrects an issue where email was being dropped from billing_details in the request.
The previous assumption was that email would be a field contained within the billing_address hash, but (in Spreedly's integration, at least), it's actually nested at the top-level of the options hash.
This change should not affect behavior of the add_billing_address method for any other integrations with Active Merchant that do supply an email attribute as part of the billing_address hash.
CER-41
LOCAL
5292 tests, 76267 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
UNIT
39 tests, 207 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
REMOTE
78 tests, 372 assertions, 0 failures, 0 …
> Stripe Payment Intents: fix bug with billing address email

- CHANGELOG
- lib/active_merchant/billing/gateways/shift4.rb
- test/remote/gateways/remote_shift4_test.rb
- test/unit/gateways/shift4_test.rb
Added customer object to purchase and store & removed transaction object from store opertaion for shift4 gateway implementation.
SER-277
SER-275
SER-279
Unit:
5294 tests, 76283 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Rubocop:
Remote:
19 tests, 45 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Shift4: Add customer object to transactions

- CHANGELOG
- lib/active_merchant/billing/credit_card.rb
- lib/active_merchant/billing/credit_card_methods.rb
- lib/active_merchant/billing/gateways/checkout_v2.rb
- test/unit/credit_card_methods_test.rb
BP Plus cards come in two formats, both 17 digits long, and _both containing two spaces:_
* 7050N NNNNNNNNN NNN
* 705N NNNNNNNN NNNNN
The first format (7050N) should pass a luhn check once the spaces are removed.
The second format (705N) contains a luhn check digit as the final digit. This PR adds an implementation of the luhn algorithm that accounts for this check digit (details on the algorithm can be found [here](https://en.wikipedia.org/wiki/Luhn_algorithm)).
The PR also includes a regex to identify the bp_plus card type, and modifications to the `valid_card_number_characters?` method to accommodate the spaces in the numbers.
SER-267
Unit Tests:
5295 tests, 76287 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Rubocop:
746 files inspected, no …
> Add bp_plus card type and custom validations

- CHANGELOG
- lib/active_merchant/billing/gateways/rapyd.rb
- test/remote/gateways/remote_rapyd_test.rb
- test/unit/gateways/rapyd_test.rb
Rapyd automatically settles ACH transactions at EOD and force-capturing.
SER-284
Unit: 20 tests, 93 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 29 tests, 84 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Rapyd: No force `capture` for ACH

- CHANGELOG
- lib/active_merchant/billing/gateways/wompi.rb
- test/remote/gateways/remote_wompi_test.rb
- test/unit/gateways/wompi_test.rb
Previous changes to this gateway redirected all refund requests to the
void endpoint. This meant that any partial refund attempts were processed
as full refunds, because the void method did not accept an amount.
Wompi has advised that it is now possible to send amount_in_cents to this
void_sync endpoint to allow for partial refunds.
CER-152
LOCAL
5276 tests, 76199 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
UNIT
12 tests, 58 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
REMOTE
13 tests, 34 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Wompi: allow partial refund amount on void_sync

- CHANGELOG
- lib/active_merchant/billing/gateways/shift4.rb
- test/remote/gateways/remote_shift4_test.rb
- test/unit/gateways/shift4_test.rb
Shift4 requires a timestamp be sent with the timezone offset (offset from GMT).
Correct format: `yyyy-mm-ddThh:mm:ss.nnn+hh:mm`
This PR corrects the offset for the timestamp to be either `-hh:mm` or `+hh:mm` depending on the offset relative to GMT (i.e., `-05:00` for 'EST').
SER-273
Unit: 19 tests, 112 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote: 21 tests, 51 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> Shift4: Timezone Offset

- .github/workflows/ruby-ci.yml
This commit adds Rubocop as a github action
to ensure all PRs have the linter run
> Rubocop GHA

- CHANGELOG
- lib/active_merchant/billing/gateways/orbital.rb
- test/unit/gateways/orbital_test.rb
The card sec val ind is only valid on BIN 1 merchant Visa and Discover transactions
This issue is not reflected in the sandbox, but was exposed in Developer
Center testing during certification. The intended application of this
field is also documented in the code comment.
ECS-2144
Unit:
141 tests, 803 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
119 tests, 497 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Orbital: Fix CardSecValInd

- CHANGELOG
- lib/active_merchant/billing/gateways/shift4.rb
- test/remote/gateways/remote_shift4_test.rb
Remove the `setup_access_token` method call from the constructor and make the method public so that users may retrieve the `access_token` one time and pass the value to other instances of the gateway class
Due to reasons at Shift4, calls to retrieve the `access_token` must be made once because the `auth_token` value has a one-time use. Any subsequent requests to exchange the `auth_token` for an `access_token` will lead to an invalid `access_token`
Because of the way we instantiate the gateway subclasses, in order to run this access token request on setup, we need to call `super` to initialize the `options` instance variable
SER-221
Unit: 21 tests, 121 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote: 21 tests, 51 assertions, 0 failures, 0 …
> Shift4: Retrieve `access_token` once

- CHANGELOG
- lib/active_merchant/billing/gateways/redsys.rb
- test/remote/gateways/remote_redsys_test.rb
Some Redsys customers receive a secret key with url safe characters. This has caused problems with the `encrypt` method, because Base64.strict_decode64 throws an error when it encounters one of these characters. Using urlsafe_decode64 instead should prevent this error from occurring in the future.
CER-75
Local
5307 tests, 76382 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Unit
33 tests, 104 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote
22 tests, 62 assertions, 5 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 77.2727% passed
(The 5 failures also occur on master)
> Redsys: update Base64 encryption handling for secret key

- CHANGELOG
- lib/active_merchant/billing/gateways/openpay.rb
- test/remote/gateways/remote_openpay_test.rb
- test/unit/gateways/openpay_test.rb
Updated endpoint from `.mx` to `.co` along with slight change in error message for the declined transactions as returned by the gateway. Added unit test to verify that the correct url is being hit for the gateway.
SER-304
Unit:
5334 tests, 76512 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Rubocop:
Remote:
24 tests, 80 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 95.8333% passed
> OpenPay: Update url endpoint

- CHANGELOG
- lib/active_merchant/billing/gateways/shift4.rb
- test/unit/gateways/shift4_test.rb
Update implementation to refuse `postalCode` when its value is nil or empty string. Also added a unit test to verify the implementation.
SER-305
Remote:
21 tests, 51 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Unit:
5333 tests, 76511 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Rubocop:
> Shift4: Not to send `postalCode` if value is nil

- CHANGELOG
- lib/active_merchant/billing/gateways/plexo.rb
- test/remote/gateways/remote_plexo_test.rb
- test/unit/gateways/plexo_test.rb
Updated field param name to `refund_type` and tested partial refund remote test.Also added tests for finger_print
SER-306
SER-307
Remote:
18 tests, 39 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Unit:
5334 tests, 76512 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Rubocop:
> Plexo: Update param key to `refund_type` and tests for `finger_print`

- CHANGELOG
- lib/active_merchant/billing/gateways/cyber_source.rb
- test/remote/gateways/remote_cyber_source_test.rb
- test/unit/gateways/cyber_source_test.rb
CER-198
`secCode` allows users to pass in  a three letter code that describes how a payment was authorized by the consumer or business receiving an ACH transaction. SEC stands for 'Standard Entry Class'. SEC codes are defined and maintained by NACHA, the governing body for the ACH network.
Unit Tests:
119 tests, 574 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote Tests:
116 tests, 594 assertions, 3 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 97.4138% passed
*Note - 3 failing tests have been several months, appears to be connected to lack of a LATAM account. Also failing on master
Local:
5334 tests, 76513 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> Cybersource: add support for `secCode` field

- lib/active_merchant/billing/gateways/d_local.rb
- test/remote/gateways/remote_d_local_test.rb
- test/unit/gateways/d_local_test.rb
Get payment status by payment id and find payments by order id.
Unit: 36 tests, 155 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote: 33 tests, 89 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 96.9697% passed
> dLocal: Add transaction query API(s) request

- CHANGELOG
- lib/active_merchant/billing/gateways/shift4.rb
- test/remote/gateways/remote_shift4_test.rb
Update AM to decline referral transactions (having responseCode of R) for shift4 along with test case.
Also updated response handling to parse error message from gateway for the 500 (internal server errors) along with remote test.
SER-323
SER-324
Remote:
23 tests, 55 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Unit:
5338 tests, 76541 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Rubocop:
> Shift4: Decline referral transactions

- CHANGELOG
- lib/active_merchant/billing/gateways/shift4.rb
- test/remote/gateways/remote_shift4_test.rb
- test/unit/gateways/shift4_test.rb
Fixed authorization to remove `|` when invoice is not present and remove card entry modes from store and verify along with test cases.
SER-332
SER-331
SER-329
Unit:
5342 tests, 76557 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Rubocop:
Remote:
24 tests, 58 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> Shift4: Fix authorization and entryMode param

- CHANGELOG
- lib/active_merchant/billing/gateways/d_local.rb
- lib/active_merchant/billing/gateways/mercado_pago.rb
- test/remote/gateways/remote_d_local_test.rb
- test/remote/gateways/remote_mercado_pago_test.rb
- test/unit/gateways/d_local_test.rb
- test/unit/gateways/mercado_pago_test.rb
Get transaction by authorization (id)
or by external_reference (order_id)
Also adjusts inquire method signature in dlocal to match mercado_pago's
ECS-2589
mercado_pago:
Unit:
43 tests, 201 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
remote requests not currently working, all 500s :(
d_local:
Unit:
36 tests, 155 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
33 tests, 89 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
> MercadoPago: Add transaction inquire request

- CHANGELOG
- lib/active_merchant/billing/gateways/worldpay.rb
- test/remote/gateways/remote_worldpay_test.rb
- test/unit/gateways/worldpay_test.rb
Can derive orderCode from authorization, or pass it directly as :order_id option.
ECS-2615
Unit:
106 tests, 625 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote:
102 tests, 392 assertions, 20 failures, 1 errors, 0 pendings, 0 omissions, 0 notifications 79.4118% passed
(failures match master branch, and may be due to credentials used)
> Worldpay: Add transaction inquire request

- CHANGELOG
- lib/active_merchant/billing/gateways/adyen.rb
- test/unit/gateways/adyen_test.rb
Added new error codes in mapping for `STANDARD_ERROR_CODE` so that for dispatch `known_error_list` can support passing of standard error codes instead of gateway error code numbers. Unit test for each failover errors are added as well.
SER-266
Unit:
5352 tests, 76613 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Rubocop:
Remote:
125 tests, 443 assertions, 4 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 96.8% passed
> Adyen: Map Standard Error Codes

- CHANGELOG
- lib/active_merchant/billing/gateways/cyber_source.rb
- test/remote/gateways/remote_cyber_source_test.rb
- test/schema/cyber_source/CyberSourceTransaction_1.201.xsd
- test/unit/gateways/cyber_source_test.rb
This PR adds support for `discount_management_indicator` and `purchase_tax_amount` in the `purchaseTotals` element, and `installment_total_amount` and `installment_annual_interest_rate` in the installment element.
It also updates to the most current version of the CyberSource API XSD file.
CER-194
Unit Tests:
120 tests, 577 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote Tests:
117 tests, 598 assertions, 3 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 97.4359% passed
*The three failing tests are also failing on master and relate to 3DS, require extra action to pass.
Local Tests:
5353 tests, 76623 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> CyberSource: add support for several fields

- CHANGELOG
- lib/active_merchant/billing/gateways/shift4.rb
- test/unit/gateways/shift4_test.rb
Updated refund request to remove `customer` object from the request along with test to verify the implementation.
SER-343
SER-344
Unit:
5352 tests, 76621 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Rubocop:
Remote:
24 tests, 58 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> Shift4: Update refund request

- CHANGELOG
- lib/active_merchant/billing/gateways/trans_first_transaction_express.rb
- test/unit/gateways/trans_first_transaction_express_test.rb
This change makes the gateway compatible with Nokogiri versions 1.2x and greater.
While the PR does not include an change to the Nokogiri version within Active Merchant, it should be tested locally against Nokogiri version 1.13.4 to ensure that downstream apps using Rails 6 can enforce this version of Nokogiri without causing problems for this gateway.
_NOTE: NO REMOTE TESTS HAVE BEEN RUN ON THIS BRANCH_ because attempts to connect to the gateway's sandbox are timing out. It is not clear if this is an account-specific issue or if the gateway sandbox no longer exists. Attempts to consult the gateway itself have revealed that TransactionExpress may be nearing its end-of-life.
ECS-2536
Unit:
5354 tests, 76627 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% …
> TransFirstTransactionExpress: Add prefix to transCode xml tag

- lib/active_merchant/billing/gateways/d_local.rb
- test/remote/gateways/remote_d_local_test.rb
- test/unit/gateways/d_local_test.rb
CER-212
Remote:
34 tests, 92 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 97.0588% passed
*Failing test is also failing on master
Unit:
37 tests, 158 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Local:
5355 tests, 76630 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
NOTE: I looked into test cards on the DLocal docs to try to fix the failing test, and all card payments are supposed to pass by default in sandbox mode. The only reason for failure should be if you pass in a code in the description. I'm not sure why this particular card type is causing a failure.
> D Local: Add support for `original_order_id` field

- CHANGELOG
- lib/active_merchant/billing/check.rb
- test/unit/check_test.rb
- test/unit/gateways/card_stream_test.rb
Canadian routing numbers are typically handled either in print/MICR format or electronic format (see https://en.wikipedia.org/wiki/Routing_number_(Canada)#Format).
Adds ability to send valid MICR formatted Canadian routing numbers, which may still be expected by some gateways.
Unit tests:
5308 tests, 76382 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Rubocop:
ECS-2144
> Accept both formats of Canadian routing numbers

- CHANGELOG
- lib/active_merchant/billing/gateways/checkout_v2.rb
- test/remote/gateways/remote_checkout_v2_test.rb
- test/unit/gateways/checkout_v2_test.rb
CER-219
For this field, the customer should provide a previous network transaction id from the CheckoutV2 gateway. It is the customer’s responsibility to store and manage the network transaction ids. When a value is present, this field should override the existing stored credential logic and add the stored credential values to the transaction request.
Local:
5363 tests, 76675 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Unit:
50 tests, 278 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote:
74 tests, 188 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 98.6486% passed
Note: Failing test is also failing on master and unrelated to this change.
> CheckoutV2: Add support for `merchant_initiated_transaction_id`

- CHANGELOG
- lib/active_merchant/billing/gateways/card_connect.rb
- test/remote/gateways/remote_card_connect_test.rb
- test/unit/gateways/card_connect_test.rb
Added stored credential implementation and fixed `ecomind` field to pass any valid value as per the documentation (`T`, `R`, `E`) along with remote and unit tests.
SER-376
Unit:
5363 tests, 76675 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Rubocop:
Remote:
25 tests, 57 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> CardConnect: Add Stored Credential

- lib/active_merchant/billing/gateways/stripe.rb
Previously using Bearer Authorization instead of Basic. Previously, the call did not seem to result in actual deletions, whereas after the switch there were multiple deletions.
> Stripe: Fix header for test account deletion call

- CHANGELOG
- lib/active_merchant/billing/gateways/ipg.rb
- test/remote/gateways/remote_ipg_test.rb
- test/unit/gateways/ipg_test.rb
ECS-2655
The IPG gateway requires a `store_id` to be
used as part of the authentication. This
value is correlates to a given merchant and
is currently saved on the gateway initalize.
By saving it only then, it prevents merchants
with submerchants from using this gateway.
This commit adds a new optional field that
will override the saved `store_id` with one
passed in for that merchant.
Test Summary
Remote:
18 tests, 54 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> IPG Gateway: override store id

- CHANGELOG
- lib/active_merchant/country.rb
- test/remote/gateways/remote_adyen_test.rb
- test/unit/gateways/adyen_test.rb
Kosovo's XK country code is considered invalid by Adyen, but the Adyen API will accept QZ as a valid value to represent Kosovo instead
CER-266
> Add alternate alpha2 country code for Kosovo

- CHANGELOG
- lib/active_merchant/billing/gateways/cyber_source.rb
- test/remote/gateways/remote_cyber_source_test.rb
- test/unit/gateways/cyber_source_test.rb
CER-243
This PR refactors the order of some methods to prevent XML parse errors. It also adds support for the following fields:
installment_gracePeriodDuration
taxManagementIndicator
purchaseTotals_invoiceAmount
purchaseTotals_originalAmount
invoiceHeader_referenceDataCode
invoiceHeader_invoiceNumber
ccCaptureService_gratuityAmount
ccAuthService_mobileRemotePaymentType
otherTax_vatTaxRate
Local:
5371 tests, 76705 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote:
118 tests, 600 assertions, 4 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 96.6102% passed
There is one additional remote test failure due to the fields not being added at the top level.
Unit:
123 tests, 588 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 …
> CyberSource: Refactor and add support for several fields

- lib/active_merchant/billing/gateways/reach.rb
- test/fixtures.yml
- test/remote/gateways/remote_reach_test.rb
- test/unit/gateways/card_stream_test.rb
- test/unit/gateways/reach_test.rb
Adding Reach gateway with authorize, purchase and capture calls, also small correction on the CardStream local test to complain with Rubocop warnings.
Finished in 6.627757 seconds.
7 tests, 14 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
5365 tests, 76686 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Reach: adding gateway

- CHANGELOG
- lib/active_merchant/billing/gateways/orbital.rb
- test/remote/gateways/remote_orbital_test.rb
- test/unit/gateways/orbital_test.rb
Orbital adapter is currently failing certification based on missing support for these changes. Adds:
- Support for commercial echeck (BankAccountType = 'X')
- Support for Discover 3DS (DigitalTokenCryptogram)
Unit:
144 tests, 817 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote:
122 tests, 509 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
ECS-2144
> Orbital: integration improvements

- CHANGELOG
- lib/active_merchant/billing/gateways/payeezy.rb
- test/remote/gateways/remote_payeezy_test.rb
- test/unit/gateways/payeezy_test.rb
Integrate apple pay in payeezy implementation along with tests.
[Payeezy DPAN implementation](https://developer.payeezy.com/payeezy-api/apis/post/transactions-7) which is akin to our `NetworkTokenizationCreditCard` object
SER-336
Rubocop:
Unit: 43 tests, 201 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote: 42 tests, 172 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> Payeezy: Add apple pay

- CHANGELOG
- lib/active_merchant/billing/gateways/payeezy.rb
- test/remote/gateways/remote_payeezy_test.rb
- test/unit/gateways/payeezy_test.rb
Scrub the `xid` and `cavv` values from the transcript. Additional scrub for `cvv`.
SER-336
Unit: 44 tests, 203 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote: 43 tests, 174 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> Payeezy Scrub Cryptogram

- lib/active_merchant/billing/gateways/reach.rb
- test/remote/gateways/remote_reach_test.rb
- test/unit/gateways/reach_test.rb
Summary:
In order to scrub fields in the transaction transript, this commit
adds fields to be filtered.
Remote Test:
Finished in 10.189499 seconds.
7 tests, 18 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit Test:
6 tests, 27 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Rubocop:
> Reach: add Scrubing

- CHANGELOG
- lib/active_merchant/billing/gateways/cyber_source.rb
- test/remote/gateways/remote_cyber_source_test.rb
- test/unit/gateways/cyber_source_test.rb
This PR updates a few methods so that fields can be sent independently without causing the method to return if certain fields aren’t present. It also updates the order in which some methods are added to the request re: the XSD file.
Unit Tests:
124 tests, 592 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote:
119 tests, 605 assertions, 5 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 95.7983% passed
*There are 3 tests that have been failing for months and a few others that are failing intermittently associated with bank accounts. I tried to look and see if maybe just the response message had changed but the failures are unpredictable and sometimes pass, while another bank account test fails.
Local:
5399 tests, 76829 assertions, 0 …
> CyberSource: Refactor to better adhere to XSD

- CHANGELOG
- lib/active_merchant/billing/gateways/cyber_source.rb
- test/remote/gateways/remote_cyber_source_test.rb
- test/unit/gateways/cyber_source_test.rb
This reverts commit 77d6e0b38c769d3026b058b168e5dd65954716d0.
Local Tests
5399 tests, 76828 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Unit Tests
123 tests, 588 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote Tests
118 tests, 602 assertions, 3 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 97.4576% passed
*same 3 are failing on master
> Revert "CyberSource: Refactor to better adhere to XSD"

- lib/active_merchant/billing/gateways/reach.rb
- test/remote/gateways/remote_reach_test.rb
This PR is based on [PR 4632](https://github.com/activemerchant/active_merchant/pull/4632)
This integration support the following payment operations:
Verify
Void
Refund
Finished in 40.346607 seconds.
5370 tests, 76698 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
133.10 tests/s, 1900.98 assertions/s
Finished in 11.168364 seconds.
12 tests, 27 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
1.07 tests/s, 2.42 assertions/s
> Reach: PSP Integration - Verify / Void / Refund

- lib/active_merchant/billing/credit_card_methods.rb
- test/unit/credit_card_methods_test.rb
DX-240
This adds a couple of Cabal 8 digit BIN ranges, and moves Cabal higher in the selection process since Discover has most of the BINs starting with 65
All local tests pass, did not run remote tests
5410 tests, 76915 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> updating cabal BIN range

- lib/active_merchant/billing/gateways/reach.rb
- test/remote/gateways/remote_reach_test.rb
- test/unit/gateways/reach_test.rb
Summary:
In order to be able to store credentials, this commit adds add_stored_credentials method, and get_network_payment_reference to be used in network_transaction_id
Remote Tests:
Finished in 36.906747 seconds.
16 tests, 42 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Unit Tests:
Finished in 2.793742 seconds.
15 tests, 51 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Rubocop:
> Reach: Add stored credential support

- CHANGELOG
- lib/active_merchant/billing/gateways/element.rb
- test/remote/gateways/remote_element_test.rb
- test/unit/gateways/element_test.rb
Enables the `add_address` method to successfully find `email` whether it is nested at the top level of the `options` hash or within the `billing_address` object
CER-330
LOCAL
5411 tests, 76919 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
REMOTE
29 tests, 82 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Element: fix bug with billing address email

- lib/active_merchant/billing/gateways/reach.rb
- test/unit/gateways/reach_test.rb
This change aims to fix an bug related with the way to handle not supported card brands.
Finished in 130.664153 seconds.
25 tests, 66 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Finished in 35.408869 seconds.
5415 tests, 76945 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
152.93 tests/s, 2173.04 assertions/s
Inspecting 756 files
> Reach: Fixing bug when using union pay card

- lib/active_merchant/billing/gateways/reach.rb
- test/remote/gateways/remote_reach_test.rb
- test/unit/gateways/reach_test.rb
Refactoring the parse method to parse JSON body
without symbols.
Finished in 117.823171 seconds.
25 tests, 66 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Finished in 37.864568 seconds.
5416 tests, 76949 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Reach: refactor to prevent symbols on response

- lib/active_merchant/billing/gateways/reach.rb
- test/remote/gateways/remote_reach_test.rb
- test/unit/gateways/reach_test.rb
This PR solves 5 issues:
1) Remove exception for no allowed store credentials combination and leave the field empty.
2) Remove exception for not supported card brand and sent instead a not supported string.
3) Fixes a Typo on stored credentials code and test related with 'unscheduled' transactions.
4) Uses the order_id (transaction token) to populate the ReferenceId field.
5) Fixes and add the corresponding tests for 1 to 3.
Finished in 136.495605 seconds.
27 tests, 70 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Finished in 33.332219 seconds.
5419 tests, 76964 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Reach: Fixing store credentials and Exception issues

- CHANGELOG
- lib/active_merchant/billing/gateways/ebanx.rb
- test/remote/gateways/remote_ebanx_test.rb
- test/unit/gateways/ebanx_test.rb
This field can be optionally passed in with the `creditcard` hash
LOCAL:
5421 tests, 76971 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
REMOTE:
26 tests, 70 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
96.1538% passed
- This test also fails on the master branch
CER-317
> EBANX: add soft_descriptor field

- CHANGELOG
- lib/active_merchant/billing/gateways/commerce_hub.rb
- test/remote/gateways/remote_commerce_hub_test.rb
- test/unit/gateways/commerce_hub_test.rb
Summary:
In order to perform transactions using Apple Pay and Google Pay this commit adds the fields required and optionals to made succesful requests.
Remote Tests:
Finished in 76.906747 seconds.
18 tests, 48 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Unit Tests:
Finished in 0.093742 seconds.
12 tests, 101 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Rubocop:
> Commerce_hub: Add Apple Pay and Google Pay

- CHANGELOG
- lib/active_merchant/billing/gateways/element.rb
- test/remote/gateways/remote_element_test.rb
Summary:
This PR updates element/vantiv gateway to support apple/google pay transactions
Remote Tests
Finished in 35.250506 seconds.
31 tests, 86 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> Element/Vantiv: Add google pay and apple pay support

- lib/active_merchant/billing/gateways/reach.rb
- test/remote/gateways/remote_reach_test.rb
- test/unit/gateways/reach_test.rb
Provides proper format handling on reach gateway to receive amount as cents on authorize/purchase and refund.
Finished in 105.613556 seconds.
28 tests, 70 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Finished in 30.429736 seconds.
5425 tests, 77010 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Reach: fix amount handling to work with cents properly

- CHANGELOG
- lib/active_merchant/billing/gateways/global_collect.rb
- test/remote/gateways/remote_global_collect_test.rb
- test/unit/gateways/global_collect_test.rb
Get payment status by payment id.
Unit:
44 tests, 224 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote:
41 tests, 90 assertions, 11 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 73.1707% passed
> GlobalCollect: Add transaction inquire request

- CHANGELOG
- lib/active_merchant/billing/gateways/braintree_blue.rb
- test/remote/gateways/remote_braintree_blue_test.rb
Adds the `additional_processor_response` to the transaction hash for unsuccessful transactions
CER-284
LOCAL
5414 tests, 76942 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
REMOTE
100 tests, 491 assertions, 4 failures, 4 errors, 0 pendings, 0 omissions, 0 notifications 92% passed
These failures/errors are present on the master branch as well
> Braintree: return additional processor response

- CHANGELOG
- lib/active_merchant/billing/gateways/payeezy.rb
- test/remote/gateways/remote_payeezy_test.rb
- test/unit/gateways/payeezy_test.rb
Allow for the `billing_address` name value to be used if the `name` value is blank for the payment method
Unit:
45 tests, 206 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote: 45 tests, 180 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> Payeezy name from `billing_address` on `purchase`

- CHANGELOG
- lib/active_merchant/billing/credit_card.rb
- lib/active_merchant/billing/credit_card_methods.rb
- lib/active_merchant/billing/gateways/plexo.rb
- test/remote/gateways/remote_plexo_test.rb
- test/unit/credit_card_methods_test.rb
This change adds 5 new credit card brands (passcard, edenred, anda, tarjeta-d, sodexo bins ) and allows plexo gateway to use it.
Remote Tests:
Finished in 45.329665 seconds.
28 tests, 50 assertions, 0 failures, 0 errors, 0 pendings, 3 omissions, 0 notifications 100% passed
Unit Tests:
Finished in 0.013674 seconds.d
20 tests, 115 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Rubocop
> Plexo: add 5 credit card brands

- CHANGELOG
- lib/active_merchant/billing/gateways/stripe_payment_intents.rb
- test/remote/gateways/remote_stripe_payment_intents_test.rb
This change makes it possible to access the result of the call to `/payment_methods` alongside the ultimate result of the call to `/setup_intents` in the response 
CER-357
REMOTE
80 tests, 378 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
UNIT
5439 tests, 77065 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> Stripe PI: use MultiResponse in create_setup_intent

- CHANGELOG
- lib/active_merchant/billing/gateways/credorax.rb
- test/remote/gateways/remote_credorax_test.rb
- test/unit/gateways/credorax_test.rb
Credorax is changing the requirements for MIT transactions in regards to NTIDs. Moving forward, all MIT transactions need to pass in the NTID if present. Additionally the NTID value is from the `Z50` flag and passed directly from the card scheme.
Credorax notification:
For any MIT transactions, this Trace ID must be stored from the original Card Holder initiated (CIT) transaction where the Card details were stored on file originally. When using Finaro gateway/acquiring this Trace ID is returned in the z50 parameter and must be sent in the g6 parameter for any subsequent MIT transactions, (if using an external token engine or your own token engine and the original CIT is not processed through Finaro, please liaise with your processor to obtain this Trace ID). Additionally, this original …
> Credorax: Update MIT logic

- CHANGELOG
- lib/active_merchant/billing/gateways/adyen.rb
- test/remote/gateways/remote_adyen_test.rb
- test/unit/gateways/adyen_test.rb
CER-333
This change will allow for recurring payments with Apple Pay on Adyen by eliminating mpi data hash from request after initial payment.
Unit:
104 tests, 528 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
131 tests, 440 assertions, 12 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
90.8397% passed
*Failing tests mostly related to 3DS/Store transactions, also failing on master. Newly added remote test passes.
Local:
5430 tests, 77037 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Adyen: Add support for `skip_mpi_data` flag

- CHANGELOG
- lib/active_merchant/billing/gateways/trust_commerce.rb
- test/remote/gateways/remote_trust_commerce_test.rb
Fix Store/Unstore features
Remote tests
-------------------------------------------------------------------------- 
22 tests, 80 assertions, 3 failures, 0 errors, 0 pendings, 
0 omissions, 0 notifications 
86.3636% passed
Failing tests not related with changes
unit tests
-------------------------------------------------------------------------- 
20 tests, 64 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> TrustCommerce: Update `authorization_from` to handle `store` response

- CHANGELOG
- lib/active_merchant/billing/gateways/trust_commerce.rb
- test/remote/gateways/remote_trust_commerce_test.rb
- test/unit/gateways/trust_commerce_test.rb
Enable verify feature on TrustCommerce Gateway
Remote tests
-------------------------------------------------------------------------- 
22 tests, 78 assertions, 3 failures, 0 errors, 0 pendings, 
0 omissions, 0 notifications 86.3636% passed
Failing tests not related with changes
unit tests
-------------------------------------------------------------------------- 
20 tests, 64 assertions, 0 failures, 0 errors, 0 pendings, 
0 omissions, 0 notifications 100% passed
> TrustCommerce Verify feature added

- CHANGELOG
- lib/active_merchant/billing/gateways/rapyd.rb
- test/remote/gateways/remote_rapyd_test.rb
- test/unit/gateways/rapyd_test.rb
Description
Rapyd Gateway send customer info on store transactions, with this commit it will be able to send customer on authorize and purchase transaction, when it use a US “PMT”s include the addresses object into the customer data in order to be able to perform US transactions properly.
GWI-489
Unit test
Finished in 0.123245 seconds.
22 tests, 103 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote test
Finished in 100.082672 seconds.
33 tests, 92 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
0.33 tests/s, 0.92 assertions/s
Rubocop
> Rapyd: Add customer object to transactions

- CHANGELOG
- lib/active_merchant/billing/gateways/checkout_v2.rb
- test/fixtures.yml
- test/remote/gateways/remote_checkout_v2_test.rb
- test/unit/gateways/checkout_v2_test.rb
Summary:
In order to use Third Party Vaulting (TPV), this commit adds store and unstore methods.
Remote test
-----------------------
Finished in 240.268913 seconds.
82 tests, 203 assertions, 2 failures, 0 errors,
97.561% passed
Unit test
-----------------------
Finished in 0.268913 seconds.
52 tests, 289 assertions, 0 failures, 0 errors,
100% passed
Rubocop
-----------------------
> CheckoutV2: Add store/unstore

- lib/active_merchant/billing/gateways/moneris.rb
- test/remote/gateways/remote_moneris_test.rb
Description
Truncate google pay and apple pay order id to 100 (max length of characters that google pay / apple pay accepts)
Unit test
Finished in 27.168945 seconds.
5439 tests, 77066 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote test
200.19 tests/s, 2836.55 assertions/s
Rubocop
> Moneris: Fix google pay (update apple pay)

- CHANGELOG
- lib/active_merchant/billing/gateways/litle.rb
This commit adds a prelive URL to the Vantiv/Litle gateway. It relies on the existing url_override logic to set the prelive_url
Test Summary
Remote:
56 tests, 226 assertions, 13 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 76.7857% passed
> Litle: Add prelive url

- lib/active_merchant/billing/gateways/commerce_hub.rb
- test/remote/gateways/remote_commerce_hub_test.rb
- test/unit/gateways/commerce_hub_test.rb
Add changes to address some observations/improvements
in the CommerceHub certification.
* SER-494 / SER-498: setting and using order_id as reference
* SER-495: use the correct end-point for verify
* SER-496 / SER-497: get avs and cvv verification codes
* SER-500: getting an error code from response
Finished in 108.050361 seconds.
23 tests, 63 assertions, 0 failures, 0 errors,
100% passed
Finished in 46.103032 seconds.
5458 tests, 77155 assertions, 0 failures, 0 errors,
100% passed
> Commercehub fixing bugs

- CHANGELOG
- lib/active_merchant/billing/gateways/commerce_hub.rb
- test/unit/gateways/commerce_hub_test.rb
* SER-495: Fix success detection to verify
* SER-507: set default `create_token` for purchase and authorize transactions
Finished in 290.029817 seconds.
23 tests, 64 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Finished in 46.103032 seconds.
5458 tests, 77155 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> CommerceHub: Fixing verify status and prevent tokenization

- CHANGELOG
- lib/active_merchant/billing/gateways/payeezy.rb
- test/unit/gateways/payeezy_test.rb
Payeezy requires sending original network transaction id to as cardbrand_original_transaction_id.
Unit:
47 tests, 217 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote:
46 tests, 184 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> Payeezy: Update Stored Credentials

- lib/active_merchant/connection.rb
- test/unit/connection_test.rb
The case for initiating a GET request raises a frivolous ArgumentError when the code already ignores any attempt to pass in a body to the request.
> Remove raise ArgumentError on get requests

- CHANGELOG
- lib/active_merchant/billing/gateways/checkout_v2.rb
- test/fixtures.yml
- test/remote/gateways/remote_checkout_v2_test.rb
- test/unit/gateways/checkout_v2_test.rb
Summary:
In order to use Third Party Vaulting (TPV), this commit adds store and unstore methods. For apple pay/google pay the actual credentials could work, but for credit cards, and bank account the credentials required are secret_api_key and public_api_key.
This commits also, refactor the initialize method removing the rescue ArgumentError, and modifing the commit method to use ssl_request.
Remote test
-----------------------
Finished in 164.163913 seconds.
88 tests, 216 assertions, 0 failures, 0 errors,
100% passed
Unit test
-----------------------
Finished in 0.046893 seconds.
53 tests, 297 assertions, 0 failures, 0 errors,
100% passed
Rubocop
-----------------------
756 …
> ChekoutV2:Add store/unstore

- lib/active_merchant/billing/gateways/payeezy.rb
- test/remote/gateways/remote_payeezy_test.rb
- test/unit/gateways/payeezy_test.rb
Payeezy has stated the inclusion of `xid` values for AP (Amex underlying) transactions could result in failures. Add guard to ignore adding this field if the underlying is `american_express`
Unit: 49 tests, 227 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote: 47 tests, 186 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> Payeezy: Ignore `xid` for AP Amex

- CHANGELOG
- lib/active_merchant/billing/gateways/braintree_blue.rb
- test/remote/gateways/remote_braintree_blue_test.rb
This PR is to update the transaction method to include the processor_authorization_code.
Local:
5462 tests, 77124 assertions, 0 failures, 19 errors, 0 pendings, 0 omissions, 0 notifications
99.6521% passed
Unit:
93 tests, 206 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
101 tests, 495 assertions, 4 failures, 4 errors, 0 pendings, 0 omissions, 0 notifications
92.0792% passed
> Braintree: Update transaction hash method

- lib/active_merchant/billing/gateways/commerce_hub.rb
- test/remote/gateways/remote_commerce_hub_test.rb
- test/unit/gateways/commerce_hub_test.rb
Updating the refund reference to only use referenceTransactionId
SER-523
Finished in 291.397602 seconds.
23 tests, 64 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
95.6522% passed
Finished in 37.637689 seconds.
5474 tests, 77230 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> CommerceHub: setting transactionReferenceId for refunds

- CHANGELOG
- lib/active_merchant/billing/gateways/paymentez.rb
- test/remote/gateways/remote_paymentez_test.rb
- test/unit/gateways/paymentez_test.rb
Get payment status by Paymentez transaction id
Unit:
30 tests, 127 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote:
34 tests, 73 assertions, 9 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 73.5294% passed
** These failures also existed on the main branch **
> Paymentez: Add inquire by transaction_id

- lib/active_merchant/billing/gateways/commerce_hub.rb
- test/remote/gateways/remote_commerce_hub_test.rb
- test/unit/gateways/commerce_hub_test.rb
Description
This commit add new fields for transactions with stored credentials options and remove the current referenceMerchantTransactionId in order to use referenceTransactionId
[SER-504](https://spreedly.atlassian.net/browse/SER-504) 
[SER-536](https://spreedly.atlassian.net/browse/SER-536)
Unit test
Finished in 0.01392 seconds.
22 tests, 147 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
1580.46 tests/s, 10560.34 assertions/s
Remote test
Finished in 296.371956 seconds.
24 tests, 63 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
0.08 tests/s, 0.21 assertions/s
Rubocop
760 files inspected, no offenses …
> CommerceHub: Update fields for transactions with sotred credentials

- CHANGELOG
- lib/active_merchant/billing/gateways/checkout_v2.rb
- test/remote/gateways/remote_checkout_v2_test.rb
- test/unit/gateways/checkout_v2_test.rb
This PR is to add the support for an optional idempotency key through the header during requests and should be available to all actions (purchase, authorize, and etc). I did note that the failing remote tests were sending back 401 unauthorized even when on the latest upstream master branch. Not sure what that is but here is also a [link to the docs](https://www.checkout.com/docs/payments/manage-payments/retry-a-payment) to save you a few clicks.
Test results can be found below:
Local:
5469 tests, 77162 assertions, 0 failures, 19 errors, 0 pendings, 0 omissions, 0 notifications 99.6526% passed
Unit:
54 tests, 300 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote:
89 tests, 213 assertions, 4 failures, 0 errors, 0 pendings, 0 omissions, 0 …
> Checkout_v2: Add idempotency key support

- CHANGELOG
- lib/active_merchant/billing/gateways/adyen.rb
- test/remote/gateways/remote_adyen_test.rb
- test/unit/gateways/adyen_test.rb
shopper_statement is already a supported gateway field however Adyen is claiming that it works fine for auth, but not for capture. This is to fix/add to the capture action requests so that shopperStatement is nested within addtionalData and set properly.
Local:
5477 tests, 77201 assertions, 0 failures, 19 errors, 0 pendings, 0 omissions, 0 notifications
99.6531% passed
Unit:
105 tests, 531 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
132 tests, 443 assertions, 12 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
> Adyen: add support for shopper_statement field for capture action

- CHANGELOG
- lib/active_merchant/billing/gateways/ebanx.rb
- test/remote/gateways/remote_ebanx_test.rb
ECS-2829
Ebanx requires that merchants pass in an email in
order to complete a transaction. Previously, ActiveMerchant was sending in a default email if one was not provided which causes Ebanx's fraud detection to mark these transactions as failed for fraud. This incorrect failure message has led to merchant frustration since they could not quickly know the root of the problem
Test Summary
Remote:
32 tests, 88 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 96.875% passed
> Ebanx: Remove default email

- CHANGELOG
- lib/active_merchant/billing/gateways/kushki.rb
- test/remote/gateways/remote_kushki_test.rb
- test/unit/gateways/kushki_test.rb
This PR will allow support for the months field and deferred fields. The [gateway documentation](https://api-docs.kushkipagos.com/docs/online-payments/card/operations/create-a-card-v-1-charge#request-body) has the deferred field as an object, however we believe it's more easy and intuitive to support them as individual GSFs.
Local:
5481 tests, 77221 assertions, 0 failures, 19 errors, 0 pendings, 0 omissions, 0 notifications
99.6533% passed
Unit:
17 tests, 109 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
16 tests, 51 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Kushki Gateway: Add support for the months and deferred fields

- CHANGELOG
- lib/active_merchant/billing/gateways/borgun.rb
- test/remote/gateways/remote_borgun_test.rb
- test/unit/gateways/borgun_test.rb
ECS-2861
A merchant using the Borgun gateway reported that when a user was completing the challenge, the gateway was displaying a value 100 times greater than what was requested. This casused the ccardholders to stop the 3DS flow and abandon the cart.
After reaching out to the Borgun gateway they explained that the ISK currency on Borgun is sometimes a 0 decimal currency and sometimes a 2 decimal currency. The explanation given via email is that we must provide the TrCurrencyExponent of 2 when utilizing the 3DS flow but not on the finish sale portion.
Remote:
22 tests, 47 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 90.9091% passed
Note: these 2 tests fail on master
> Borgun: Update TrCurrencyExponent

- CHANGELOG
- lib/active_merchant/billing/gateways/bogus.rb
- test/unit/gateways/bogus_test.rb
Add support for the `verify` functionality to the Bogus Gateway. 
While the [gateway template](https://github.com/activemerchant/active_merchant/blob/master/generators/gateway/templates/gateway.rb#L53) traditionally defines `verify` as an `authorize` + `void`, for the sake of the bogus gateway where responses are faked, this has been simplified to just an `authorize` since the `void` call is traditionally ignored.
> Bogus: Add verify functionality

- CHANGELOG
- lib/active_merchant/billing/gateways/checkout_v2.rb
- test/remote/gateways/remote_checkout_v2_test.rb
- test/unit/gateways/checkout_v2_test.rb
Add Shipping Address details based on the Checkout.com [API reference](https://api-reference.checkout.com/#operation/requestAPaymentOrPayout)
Finished in 21.159827 seconds.
------------------------------------------------------------------------------------------------------------------------------------------------------------
5492 tests, 77316 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Finished in 55.268942 seconds.
------------------------------------------------------------------------------------------------------------------------------------------------------------
89 tests, 211 assertions, 1 failures, 3 errors, 0 pendings, 0 omissions, 0 notifications
95.5056% passed
Test that failed is due to Sandbox account not supporting credit …
> Checkout: Add Shipping Address

- CHANGELOG
- lib/active_merchant/billing/gateways/adyen.rb
Adyen advised that `googlepay` is the correct value to send for `selectedBrand`
CER-550
LOCAL
5498 tests, 77340 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
GATEWAY - UNIT TESTS
105 tests, 531 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
GATEWAY - REMOTE TESTS
132 tests, 443 assertions, 12 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 90.9091% passed
> Adyen: update selectedBrand mapping for Google Pay

- CHANGELOG
- lib/active_merchant/billing/gateways/shift4.rb
- test/remote/gateways/remote_shift4_test.rb
- test/unit/gateways/shift4_test.rb
This change maps `options[:order_id]` to Shift4's `vendorReference` field
CER-563
LOCAL
5498 tests, 77341 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
GATEWAY UNIT TESTS
25 tests, 154 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
GATEWAY REMOTE TESTS
25 tests, 58 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 92% passed
(These failures also exist on the master branch)
> Shift4: add vendorReference field

- CHANGELOG
- lib/active_merchant/billing/gateways/litle.rb
- test/remote/gateways/remote_litle_test.rb
- test/unit/gateways/litle_test.rb
Add 001 and 010 to be considered successful responses for Litle.
Remote
57 tests, 251 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Unit
58 tests, 255 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> Litle update the successful_from method

- CHANGELOG
- lib/active_merchant/billing/gateways/shift4.rb
- lib/active_merchant/errors.rb
- test/remote/gateways/remote_shift4_test.rb
- test/unit/gateways/shift4_test.rb
ECS-2845
OAuth has become a standard authentication
mechanism for many gateways in recent years
however AM has not been updated to support error
handling when a merchant passes incorrect details
to the gateway.
In non OAuth flows we would return a failed response. This commit now raises a new exception type indicating that the request failed at the OAuth stage rather than the transaction stage of a request
Remote:
25 tests, 57 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 92% passed
> Improve error handling: OAuth

- activemerchant.gemspec
> Rexml is no longer a default gem in Ruby 3.

- activemerchant.gemspec
Reverts activemerchant/active_merchant#3852. This broke CI. Will need to investigate.
> Revert "Rexml is no longer a default gem in Ruby 3."

- activemerchant.gemspec
- test/unit/gateways/payflow_test.rb
Rexml is no longer included with Ruby 3+, we therefore need to add the dependency explicitely. This fixes the issue encountered in https://github.com/activemerchant/active_merchant/pull/3852.
See https://www.ruby-lang.org/en/news/2020/09/25/ruby-3-0-0-preview1-released/
> Add rexml as a gem dependency

- CHANGELOG
- lib/active_merchant/billing/gateways/cyber_source.rb
- lib/active_merchant/billing/gateways/cyber_source_rest.rb
- test/remote/gateways/remote_cyber_source_rest_test.rb
- test/unit/gateways/cyber_source_test.rb
ECS-2849
A previous commit from 2015 restricted the ability to pass business rules such as `ignoreAVSResult` and `ignoreCVResult` on API requests with NetworkTokenization cards. Merchants are now asking for this to be allowed on requests with payment methods such as NT/AP/GP and the remote tests seem to indicate we can add these fields for these types of payment methods.
Remote:
119 tests, 607 assertions, 3 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 97.479% passed
> Cybersource: Add business rules for NT

- CHANGELOG
- lib/active_merchant/billing/gateways/adyen.rb
- test/unit/gateways/adyen_test.rb
Adyen error messaging uses the generic refusalReasonRaw field as part of the response message. Adyen offers a more detailed Mastercard-specific field called merchantAdviceCode that should be present for failed Mastercard transactions.
Adyen error messaging now checks for the merchantAdviceCode first. If it is not present (i.e. this is not a Mastercard transaction or it is a Mastercard transaction and this field is missing for some reason) then the default refusalReasonRaw field is used (like previous functionality).
ECS-2767
Unit:
107 tests, 539 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote:
132 tests, 443 assertions, 12 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 90.9091% passed
*These 12 tests fail on master
> Adyen: Update Mastercard error messaging

- CHANGELOG
- lib/active_merchant/billing/gateways/authorize_net.rb
- test/remote/gateways/remote_authorize_net_test.rb
- test/unit/gateways/authorize_net_test.rb
Adds a bit of logic to the Authorize.net gateway so that phone number can be passed via `billing_address[phone_number]` in addition to `billing_address[phone]` This is similar to #4138
CER-590
LOCAL
5503 tests, 77374 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
UNIT
121 tests, 681 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
REMOTE
84 tests, 301 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> Authorize.net: update mapping for billing address phone number

- CHANGELOG
- lib/active_merchant/billing/gateways/commerce_hub.rb
- test/remote/gateways/remote_commerce_hub_test.rb
- test/unit/gateways/commerce_hub_test.rb
Changes the payment method so is possible to send an encrypted credit card following the CommerceHub Multi-User [public key methodology.](https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Online-Mobile-Digital/Secure-Data-Capture/Multi-Use-Public-Key/Multi-Use-Public-Key-Encryption.md&branch=main)
SER-555
**Note on the one failing test**: You need the proper account permissions and credentials to use the encrypted credit card.
Finished in 288.325843 seconds.
100% passed
Finished in 38.640945 seconds.
5506 tests, 77384 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> CommerceHub: Enabling multi-use public key encryption

- lib/active_merchant/billing/gateways/borgun.rb
Add support to Borgun for GPB based on [ISO
4217](https://en.wikipedia.org/wiki/ISO_4217)
Unit:
Remote:
> Borgun support for GBP currency

- CHANGELOG
- lib/active_merchant/billing/gateways/worldpay.rb
- test/remote/gateways/remote_worldpay_test.rb
- test/unit/gateways/worldpay_test.rb
Ensure that we don't send cardHolderName if empty and that Google Pay and Apple Pay fall into the network tokenization code path and not the credit card path.
Remote Tests:
100 tests, 416 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Unit Tests:
107 tests, 633 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> Worlpay: Fix Google Pay

- CHANGELOG
- lib/active_merchant/billing/gateways/cyber_source.rb
- test/unit/gateways/cyber_source_test.rb
ECS-2870
Cybersource transactions that fail with a reasonCode of `230` are in a state where the gateway advises the merchant to decline but has not declined it themselves. Instead the transaction is pending capture which can create a mismatch in reporting.
This commit attempts to auto void transactions that have this response code and a flag that indicates the merchants would like to auto void these kinds of transactions. I wasn't able to add a remote test for this because the CYBS sandbox does not have a way to trigger this response code. 
Remote:
121 tests, 611 assertions, 5 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 95.8678% passed
5 test failures on master as well
> Cybersource: auto void r230

- CHANGELOG
- lib/active_merchant/billing/gateways/d_local.rb
- test/remote/gateways/remote_d_local_test.rb
- test/unit/gateways/d_local_test.rb
Add the save field to card object, documentation found [here](https://docs.dlocal.com/docs/saving-cards#save-a-card-on-a-payment)
Local:
5512 tests, 77364 assertions, 0 failures, 19 errors, 0 pendings, 0 omissions, 0 notifications
99.6553% passed
Unit:
44 tests, 191 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
39 tests, 105 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
94.8718% passed
> DLocal: Add save field on card object

- CHANGELOG
- lib/active_merchant/billing/gateways/authorize_net.rb
- test/remote/gateways/remote_authorize_net_test.rb
- test/unit/gateways/authorize_net_test.rb
The API specification requires that the string be no longer than 22 characters; refunds will fail if this limit is exceeded
CER-670
REMOTE
85 tests, 304 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
UNIT
122 tests, 688 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
LOCAL
5525 tests, 77482 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> Authorize.net: truncate nameOnAccount for bank refunds

- lib/active_merchant/billing/gateways/checkout_v2.rb
- test/remote/gateways/remote_checkout_v2_test.rb
- test/unit/gateways/checkout_v2_test.rb
CER-595
Ran into a lot of tricky data collisions and had to do some finagling to make sure existing test cases would pass. I left open two possibilities for passing in the phone number depending on how users would like to pass it in: manually via options or via the phone number that’s attached to credit card billing data on the payment method.
It’s possible to pay with a stored payment method which would be a String. In this case there’s no name data attached so added some guarding against NoMethodErrors that were resulting from trying to call payment_method.name.
Remote Tests:
92 tests, 221 assertions, 3 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 96.7391% passed
*5 remote tests are failing on master but I fixed two of them
Unit Tests:
57 tests, 319 assertions, 0 …
> Checkout: Add support for several customer data fields

- CHANGELOG
- lib/active_merchant/billing/gateways/worldpay.rb
- test/unit/gateways/worldpay_test.rb
The https://github.com/activemerchant/active_merchant/commit/51c1f2d0333c53b89a8fb12189838694e5b09e6b commit resulted in `ActiveMerchant::Billing::WorldpayGateway#payment_details` to handle a payment method as a network token when the payment method responds to `:source`. However, there are payment methods that respond to `:source` but do not behave as a network token.
More specifically, `ActiveMerchant::Billing::WorldpayGateway#add_network_tokenization_card` expects that the payment method responds to `:source`, `:payment_cryptogram` and `:eci`.
Hence, this PR restricts the conditions under which `ActiveMerchant::Billing::WorldpayGateway#payment_details` handles a payment method as a network token to when the payment method responds to `:source`, `:payment_cryptogram` and `:eci` as well. …
> Worldpay: check payment_method responds to payment_cryptogram and eci

- lib/active_merchant/billing/gateways/safe_charge.rb
- test/remote/gateways/remote_safe_charge_test.rb
- test/unit/gateways/safe_charge_test.rb
Local:
5542 tests, 77500 assertions, 0 failures, 19 errors, 0 pendings, 0 omissions, 0 notifications
99.6572% passed
Unit:
25 tests, 144 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
31 tests, 85 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Nuvei (formerly SafeCharge): Add customer details to credit action

- CHANGELOG
- lib/active_merchant/billing/gateways/ipg.rb
- test/remote/gateways/remote_ipg_test.rb
The live_url for IPG was likely always incorrect, this updates it to hit the actual endpoint.
Also changes test data to prevent a scrub test failure.
Remote (same failures on master):
18 tests, 40 assertions, 8 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
Unit:
27 tests, 123 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
> IPG: Update live url to correct endpoint

- CHANGELOG
- lib/active_merchant/billing/credit_card.rb
- lib/active_merchant/billing/credit_card_methods.rb
- lib/active_merchant/billing/gateways/vpos.rb
- test/unit/credit_card_methods_test.rb
Add the Panal credit card type and enables it for VPos gateway
SER-605
Finished in 38.864306 seconds.
5542 tests, 77546 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
*Note*: Remote tests for this change are not present because wasn't possible to get test cards.
> VPos: Adding Panal Credit Card type

- lib/active_merchant/billing/gateways/worldpay.rb
- test/unit/gateways/worldpay_test.rb
Update the xml tag for Credit Cards to be CARD-SSL instead of being specific to card brand.
Remote:
100 tests, 416 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Unit:
109 tests, 637 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> WorldPay: Update xml tag for Credit Cards

- CHANGELOG
- lib/active_merchant/billing/gateways/stripe.rb
- test/unit/gateways/stripe_payment_intents_test.rb
Remote:
Stripe PI
87 tests, 409 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Stripe
77 tests, 362 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Unit:
Stripe PI
51 tests, 252 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Stripe
146 tests, 769 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> Stripe: Update login key validation

- CHANGELOG
- lib/active_merchant/billing/gateways/checkout_v2.rb
The CheckoutV2 gateway had logic in the response parsing method that would limit the scope of parsing to only authorize or purchase. This presents an issue for merchants using `verify-payment` or other methods that may have the AVS and CVV checks in the response.
This commit also updates the AVS and CVV checks to use `dig` to safely try parsing out the values
Test Summary
Remote:
93 tests, 227 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> CheckoutV2: Parse AVS and CVV checks

- CHANGELOG
- lib/active_merchant/billing/gateways/borgun.rb
- test/unit/gateways/borgun_test.rb
Update authorization_from to return nil if the transaction failed or it is a 3DS transaction. Update message_from to return ErrorMessage if present.
Unit:
12 tests, 66 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote:
22 tests, 43 assertions, 6 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 72.7273% passed
> Borgun: Update authorization_from & message_from

- CHANGELOG
- lib/active_merchant/billing/gateways/kushki.rb
- test/remote/gateways/remote_kushki_test.rb
Unit
17 tests, 109 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote
18 tests, 57 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> Kushki: Add Brazil as supported country

- CHANGELOG
- lib/active_merchant/billing/gateways/safe_charge.rb
- test/remote/gateways/remote_safe_charge_test.rb
- test/unit/gateways/safe_charge_test.rb
Note: 
I didn't include a unit test because this fields purpose is to exclude sending the sg_TransactionID and not meant to return anything. 
Local:
5545 tests, 77509 assertions, 0 failures, 19 errors, 0 pendings, 0 omissions, 0 notifications
99.6573% passed
Unit:
25 tests, 144 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
32 tests, 89 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Nuvie/SafeCharge: Add unreferenced refund field

- CHANGELOG
- lib/active_merchant/billing/gateways/cyber_source.rb
- test/unit/gateways/cyber_source_test.rb
This PR adds `paymentSolution` to the purchase and authorization request when the payment is using network tokenization with Apple Pay and Google Pay, as per 
- https://developer.cybersource.com/content/dam/docs/cybs/en-us/apple-pay/developer/fdiglobal/rest/applepay.pdf
- https://developer.cybersource.com/content/dam/docs/cybs/en-us/google-pay/developer/fdiglobal/rest/googlepay.pdf
Schema:
- https://developer.cybersource.com/library/documentation/dev_guides/Simple_Order_API_Clients/html/Topics/Using_XML1.htm
- https://ics2ws.ic3.com/commerce/1.x/transactionProcessor/CyberSourceTransaction_1.211.xsd
```
bundle exec rake test:units TEST=test/unit/gateways/cyber_source_test.rb
136 tests, 640 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
```
Same …
> CyberSource: include `paymentSolution` for ApplePay and GooglePay

- CHANGELOG
- lib/active_merchant/billing/gateways/paysafe.rb
- test/unit/gateways/paysafe_test.rb
If options[:merchant_ref_num] is not supplied, options[:order_id] will be used as the fallback value
CER-683
LOCAL
5559 tests, 77691 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
UNIT
18 tests, 89 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
REMOTE
33 tests, 82 assertions, 8 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 75.7576% passed
Note: the failing tests also occur on the master branch and seem to be related to assertions that involve a token stored at the gateway that is now linked to a card with an invalid expiration date
> Paysafe: Map order_id to merchantRefNum

- CHANGELOG
- lib/active_merchant/billing/gateways/stripe_payment_intents.rb
- test/unit/gateways/stripe_payment_intents_test.rb
Don't send NTID in add_stored_credential if
post[:payment_method_options][:card][:stored_credential_transaction_type] = 'setup_on_session' and setup_future_usage=off_session.
> Stripe PI: Gate sending NTID

- CHANGELOG
- lib/active_merchant/billing/gateways/payment_express.rb
Now that Payment Express has renamed to Windcave, the old endpoints no longer work.
Test Summary
Local: 5543 tests, 77553 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Unit: 37 tests, 263 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote: 17 tests, 79 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> PaymentExpress: correct endpoints

- CHANGELOG
- lib/active_merchant/billing/gateways/adyen.rb
- test/unit/gateways/adyen_test.rb
ECS-3082
A change was made two months ago to provide the MerchantAdviceCode as the error message if available before falling back to the refusalReasonRaw value. Some merchants do not want this change in messaging so this gives them a way to elect which error message they want
Test Summary
Remote:
11 failing tests on master
134 tests, 447 assertions, 11 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 91.791% passed
> Adyen: Support raw refusal reason

- CHANGELOG
- lib/active_merchant/billing/gateways/reach.rb
Full list of countries supported is available in Reach docs: https://docs.withreach.com/v2.22/docs/currencies-and-countries
LOCAL
5559 tests, 77691 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
UNIT
17 tests, 76 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
REMOTE
28 tests, 72 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
CER-741
> Reach: Update list of supported countries

- CHANGELOG
- lib/active_merchant/billing/gateways/paysafe.rb
- test/remote/gateways/remote_paysafe_test.rb
- test/unit/gateways/paysafe_test.rb
Limits the length of address fields, according to Paysafe docs
LOCAL
5560 tests, 77697 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
UNIT
19 tests, 95 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
REMOTE
34 tests, 83 assertions, 8 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
76.4706% passed
CER-746
> Paysafe: Truncate address fields

- CHANGELOG
- Gemfile
- lib/active_merchant/billing/gateways/braintree_blue.rb
- test/remote/gateways/remote_braintree_blue_test.rb
- test/unit/gateways/braintree_blue_test.rb
This PR adds support for network tokens to the Braintree gateway. The gateway class utilizes the Braintree SDK which added support for network tokens in major version 4. This commit updates the logic to add support for tagging NT as per the BT docs but does not require the CI tests to move to the new BT version. 
Question for reviewers: Should we wait for the BT ruby gem to get updated in the repo's CI tests before merging this?
> BT: Add support for network tokens

- CHANGELOG
- lib/active_merchant/billing/gateways/kushki.rb
Unit:
5563 tests, 77665 assertions, 0 failures, 19 errors, 0 pendings, 0 omissions, 0 notifications
99.6585% passed
Local:
17 tests, 109 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
23 tests, 68 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Kushki: fix add amount default method

- CHANGELOG
- lib/active_merchant/billing/gateways/rapyd.rb
- test/remote/gateways/remote_rapyd_test.rb
- test/unit/gateways/rapyd_test.rb
The Rapyd gateway requires the Customer object on multiple payment types now and is optional on all. This commit adds teh customer subhash to requests and updates the remote tests to pass
Remote:
32 tests, 76 assertions, 7 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 78.125% passed
> Rapyd: Add customer object and fix tests

- CHANGELOG
- lib/active_merchant/billing/gateways/cyber_source.rb
- lib/active_merchant/billing/gateways/cyber_source_rest.rb
- test/unit/gateways/cyber_source_rest_test.rb
- test/unit/gateways/cyber_source_test.rb
Set the merchantId filed to options[:merchant_id] instead of @options[:login] if available.
Unit: 136 tests, 641 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> Cybersource: Add merchant_id

- CHANGELOG
- lib/active_merchant/billing/gateway.rb
- lib/active_merchant/billing/gateways/global_collect.rb
- test/remote/gateways/remote_global_collect_test.rb
- test/unit/gateways/global_collect_test.rb
Local:
5563 tests, 77664 assertions, 1 failures, 19 errors, 0 pendings, 0 omissions, 0 notifications
99.6405% passed
Unit:
44 tests, 226 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
51 tests, 133 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Wordline (Global Collect): Add agent numeric code and house number field

- CHANGELOG
- test/remote/gateways/remote_braintree_blue_test.rb
LOCAL
5563 tests, 77715 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
UNIT
94 tests, 207 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
REMOTE
105 tests, 561 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Braintree: Additional tests for credit transactions

- CHANGELOG
- lib/active_merchant/billing/gateways/rapyd.rb
- test/remote/gateways/remote_rapyd_test.rb
- test/unit/gateways/rapyd_test.rb
This maps order_id to the merchant_reference_id field at Rapyd
CER-831
LOCAL
5580 tests, 77776 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
763 files inspected, no offenses detected
UNIT
24 tests, 120 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
REMOTE
31 tests, 89 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Rapyd: Add merchant_reference_id

- CHANGELOG
- lib/active_merchant/billing/gateways/braintree_blue.rb
- test/unit/gateways/braintree_blue_test.rb
Return DIRECT_BANK_ERROR message if credit is attempted using a check
CER-790
LOCAL
5581 tests, 77777 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
763 files inspected, no offenses detected
UNIT
95 tests, 209 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
REMOTE
105 tests, 559 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Braintree: Add check for ACH on credit

- CHANGELOG
- lib/active_merchant/billing/gateways/rapyd.rb
- test/remote/gateways/remote_rapyd_test.rb
- test/unit/gateways/rapyd_test.rb
Changes `ewallet_id` to `ewallet` to match [Rapyd's specifications](https://docs.rapyd.net/en/create-payment.html) 
Adds handling for alternate method of passing `phone_number` in the `billing_address` object
CER-843, CER-844
LOCAL
5581 tests, 77780 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
763 files inspected, no offenses detected
UNIT
25 tests, 124 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
REMOTE
31 tests, 89 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Rapyd: Update handling of `ewallet` and billing address phone

- CHANGELOG
- lib/active_merchant/billing/gateways/ipg.rb
- test/unit/gateways/ipg_test.rb
Refactor IPG credentials to accept a combined user ID/store ID string since this is what is provided to IPG merchants as their user ID.
ECS-2839
Unit: 31 tests, 135 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications, 100% passed
Remote: 18 tests, 42 assertions, 6 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications, 66.6667% passed
> IPG: Refactor Credentials

- CHANGELOG
- lib/active_merchant/billing/gateways/braintree_blue.rb
- test/remote/gateways/remote_braintree_blue_test.rb
This is to allow AM to include the prepaid, debit, and issuing bank fields on the credit card details object for transactions.
Local:
5582 tests, 77736 assertions, 0 failures, 19 errors, 0 pendings, 0 omissions, 0 notifications
99.6596% passed
Unit:
95 tests, 209 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
106 tests, 515 assertions, 4 failures, 4 errors, 0 pendings, 0 omissions, 0 notifications
92.4528% passed (the ones that failed are authentication errors)
> Braintree Blue: Update the credit card details transaction hash

- CHANGELOG
- Gemfile
- lib/active_merchant/billing/gateways/visanet_peru.rb
- test/unit/gateways/visanet_peru_test.rb
Update generate_purchase_number_stamp to always produce unique 12-digit alphanumberic value even if multiple transactions occur at the same time.
Unit:
16 tests, 100 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> VisaNet Peru: Update generate_purchase_number_stamp

- CHANGELOG
- lib/active_merchant/billing/gateways/airwallex.rb
- lib/active_merchant/billing/gateways/alelo.rb
- lib/active_merchant/billing/gateways/checkout_v2.rb
- lib/active_merchant/billing/gateways/pay_trace.rb
- lib/active_merchant/billing/gateways/quickbooks.rb
- lib/active_merchant/billing/gateways/simetrik.rb
- lib/active_merchant/errors.rb
- test/remote/gateways/remote_airwallex_test.rb
- test/remote/gateways/remote_alelo_test.rb
- test/remote/gateways/remote_checkout_v2_test.rb
- test/remote/gateways/remote_pay_trace_test.rb
- test/remote/gateways/remote_quickbooks_test.rb
- test/remote/gateways/remote_simetrik_test.rb
- test/unit/gateways/airwallex_test.rb
- test/unit/gateways/alelo_test.rb
- test/unit/gateways/checkout_v2_test.rb
- test/unit/gateways/pay_trace_test.rb
- test/unit/gateways/quickbooks_test.rb
- test/unit/gateways/simetrik_test.rb
Add new OAuth Response error handling to PayTrace, Quickbooks, Simetrik, Alelo, CheckoutV2 and Airwallex.
> Adding Oauth Response for access tokens

- CHANGELOG
- lib/active_merchant/billing/gateways/cyber_source.rb
- test/remote/gateways/remote_cyber_source_test.rb
- test/unit/gateways/cyber_source_test.rb
Cybersource's legacy gateway supports recurring transactions for Network Tokens. The way
to accomplish this is to not send the `cryptogram` since that is one time use and mark the
`commerce_indicator` as `internet`.
Remote:
123 tests, 619 assertions, 5 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
95.935% passed
5 tests failing on master
> CYBS: Recurring NT

- CHANGELOG
- lib/active_merchant/billing/gateways/braintree_blue.rb
- test/remote/gateways/remote_braintree_blue_test.rb
- test/unit/gateways/braintree_blue_test.rb
To specifiy the SCA exemption that a trasaction will be claming.
Remote:
105 tests, 559 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Unit:
94 tests, 207 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> Braintree: Add sca_exemption

- CHANGELOG
- lib/active_merchant/billing/gateways/securion_pay.rb
- lib/active_merchant/billing/gateways/shift4_v2.rb
- test/fixtures.yml
- test/remote/gateways/remote_securion_pay_test.rb
- test/remote/gateways/remote_shift4_v2_test.rb
- test/unit/gateways/securion_pay_test.rb
- test/unit/gateways/shift4_v2_test.rb
[SER-653](https://spreedly.atlassian.net/browse/SER-653)
[SER-654](https://spreedly.atlassian.net/browse/SER-654)
[SER-655](https://spreedly.atlassian.net/browse/SER-655)
[SER-661](https://spreedly.atlassian.net/browse/SER-661)
[SER-662](https://spreedly.atlassian.net/browse/SER-662)
[SER-663](https://spreedly.atlassian.net/browse/SER-663)
Shift4 purchased Securion Pay and is now using their API, that's why
this commit enables a new shift4_v2 gateway
WIP: Pending to include general credit support
**Unit test**
------------------------------------
Finished in 0.150258 seconds.
34 tests, 191 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
226.28 tests/s, 1271.15 assertions/s
**Remote test**
------------------------------------
Finished in 27.855679 …
> Shift4_v2: Inherit securionPay API to enable Shift4v2

- CHANGELOG
- lib/active_merchant/billing/gateways/cyber_source.rb
- test/remote/gateways/remote_cyber_source_test.rb
- test/unit/gateways/cyber_source_test.rb
Cybersource's legacy gateway supports recurring transactions for Network Tokens. The way to accomplish this is to not send the `cryptogram` since that is one time use and mark the `commerce_indicator` as `internet`.
Remote:
123 tests, 619 assertions, 5 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 95.935% passed
5 tests failing on master
> CYBS: Recurring Apple Pay

- CHANGELOG
- lib/active_merchant/billing/gateways/rapyd.rb
- test/remote/gateways/remote_rapyd_test.rb
- test/unit/gateways/rapyd_test.rb
This change is allow users to manage NTID themselves by adding an option for them to pass in the fields network_reference_id and initiation_type directly.
Local:
5588 tests, 77761 assertions, 0 failures, 19 errors, 0 pendings, 0 omissions, 0 notifications 99.66% passed
Unit:
27 tests, 137 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote:
34 tests, 95 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> Rapyd: Add fields and update stored credential method

- lib/active_merchant/billing/gateways/commerce_hub.rb
- test/unit/gateways/commerce_hub_test.rb
Description
This commit add new headers identifiers: 'x-originator', 'user-agent'. Additionally include a small test to verify the headers presence.
[SER-621](https://spreedly.atlassian.net/browse/SER-621)
Unit test
Finished in 0.033772 seconds.
25 tests, 175 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
740.26 tests/s, 5181.81 assertions/s
Remote test
Finished in 57.0542 seconds.
26 tests, 62 assertions, 5 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 80.7692% passed
0.46 tests/s, 1.09 assertions/s
Rubocop
763 files inspected, no offenses detected
> CommerceHub: Update headers

- lib/active_merchant/billing/gateways/rapyd.rb
- test/remote/gateways/remote_rapyd_test.rb
- test/unit/gateways/rapyd_test.rb
Description
[SER-808](https://spreedly.atlassian.net/browse/SER-808)
This commit validate if the cvv in order to don't allow send empty values to Rapyd.
This commit also include a small update for the previos work made for [3ds Gateway Specific](https://github.com/activemerchant/active_merchant/pull/4876)
Unit test
Finished in 0.183111 seconds.
29 tests, 148 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notificationsomissions, 0 notifications 100% passed
158.37 tests/s, 808.25 assertions/s
Remote test
Finished in 113.329864 seconds.
34 tests, 111 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 97.0588% passed
0.30 tests/s, 0.86 assertions/s
Rubocop …
> Rapyd: Update cvv behavior

- CHANGELOG
- lib/active_merchant/billing/gateways/cyber_source.rb
- test/remote/gateways/remote_cyber_source_test.rb
- test/unit/gateways/cyber_source_test.rb
CyberSource (SOAP): Added support for 3DS exemption request fields
Test Summary
Local: 5591 tests, 77934 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Unit at test/unit/gateways/cyber_source_test.rb: 138 tests, 762 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote at test/remote/gateways/remote_cyber_source_test.rb: 125 tests, 627 assertions, 5 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 96% passed (same as `master`)
> CyberSource (SOAP): Added support for 3DS exemption request fields

- CHANGELOG
- lib/active_merchant/billing/gateways/stripe_payment_intents.rb
- test/remote/gateways/remote_stripe_payment_intents_test.rb
- test/unit/gateways/stripe_payment_intents_test.rb
The `last4` field is the only new `option`, and is added upstream. This work includes fields for one-time use PaymentIntents only.
Test Summary
Local: 5582 tests, 77796 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Unit at test/unit/gateways/stripe_payment_intents_test.rb: 55 tests, 289 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote at test/remote/gateways/remote_stripe_payment_intents_test.rb: 90 tests, 424 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> StripePI: Adding network tokenization fields to Stripe PaymentIntents

- CHANGELOG
- lib/active_merchant/billing/gateways/shift4_v2.rb
- test/unit/gateways/securion_pay_test.rb
- test/unit/gateways/shift4_v2_test.rb
Fixes a bug for Shift4 gateway to ensure that currency code is downcased.
SER-811
Finished in 34.37861 seconds.
34 tests, 121 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Finished in 47.584817 seconds.
5604 tests, 78022 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
766 files inspected, no offenses detected
> Shift4: Fixing currency bug

- CHANGELOG
- lib/active_merchant/billing/gateways/rapyd.rb
- test/remote/gateways/remote_rapyd_test.rb
Fixes a bug for Rapyd where the signature doesn't match the actual body and happens as a consequence of how ActiveSupport encodes some URL parameters.
[ActiveSupport](https://github.com/rails/rails/blob/main/activesupport/lib/active_support/json/encoding.rb#L46)
[SER-813](https://spreedly.atlassian.net/browse/SER-813)
Note: 
A failing test happens due to a reference that needs to be updated every time.
Finished in 108.783668 seconds.
38 tests, 110 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
Finished in 37.178252 seconds.
5604 tests, 78022 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
766 files inspected, no offenses detected
> Rapyd: fixing issue with json encoding and signatures

- CHANGELOG
- lib/active_merchant/billing/gateways/xpay.rb
- test/fixtures.yml
- test/remote/gateways/remote_xpay_test.rb
- test/unit/gateways/xpay_test.rb
Description
[SER-763](https://spreedly.atlassian.net/browse/SER-763)
This commit add the initial setup for the new Xpay gateway
Unit test
Finished in 0.557754 seconds.
2 tests, 4 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
3.59 tests/s, 7.17 assertions/s
Remote test
Finished in 0.557754 seconds.
2 tests, 4 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
3.59 tests/s, 7.17 assertions/s
Rubocop
769 files inspected, no offenses detected
> XpayGateway: initia Setup

- CHANGELOG
- lib/active_merchant/billing/gateways/rapyd.rb
- test/remote/gateways/remote_rapyd_test.rb
- test/unit/gateways/rapyd_test.rb
Description
[SER-826](https://spreedly.atlassian.net/browse/SER-826)
This commit add some validations to not send the `cvv` and `network_reference_id` on recurring transactions if it does not exist
Unit test
Finished in 0.132965 seconds.
34 tests, 163 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote test
Finished in 79.856446 seconds.
40 tests, 115 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
97.5% passed
Rubocop
766 files inspected, no offenses detected
> Rapyd: Add validation to not send cvv and network_reference_id

- lib/active_merchant/billing/gateways/rapyd.rb
- test/remote/gateways/remote_rapyd_test.rb
- test/unit/gateways/rapyd_test.rb
Description
This is a super small commit to update the validations to not send cvv value
Unit test
Finished in 0.132965 seconds.
34 tests, 163 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote test
Finished in 79.856446 seconds.
40 tests, 115 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
97.5% passed
Rubocop
766 files inspected, no offenses detected
> Rapyd: Fix cvv validation

- CHANGELOG
- lib/active_merchant/billing/gateways/decidir.rb
- test/remote/gateways/remote_decidir_test.rb
- test/unit/gateways/decidir_test.rb
This PR adds support for network tokens to the Decidir gateway.
> Decidir: Add support for network tokens

- Gemfile
- lib/active_merchant/billing/gateways/braintree_blue.rb
- test/remote/gateways/remote_braintree_blue_test.rb
CER-868
This field needs to be added to the transaction_hash method to be returned in the response. The Braintree gem required an update to make the `payment_receipt` object available
I did not include a unit test because I'm trying to get something returned in the response and according to the [Braintree docs](https://developer.paypal.com/braintree/docs/reference/response/transaction/ruby#global_id), it does not appear that anything should be passed in the request to trigger this coming back. 
Remote
107 tests, 212 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
31.7757% passed
Unit
95 tests, 110 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
41.0526% passed
Local
5599 tests, 77770 assertions, 0 failures, 56 errors, 0 pendings, 0 …
> Braintree: return global_id in response

- CHANGELOG
- lib/active_merchant/billing/gateways/adyen.rb
- test/remote/gateways/remote_adyen_test.rb
- test/unit/gateways/adyen_test.rb
Remote:
137 tests, 453 assertions, 11 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 91.9708% passed
Unit:
111 tests, 585 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> Adyen: Add payout endpoint

- CHANGELOG
- lib/active_merchant/billing/gateways/braintree/token_nonce.rb
- test/remote/gateways/remote_braintree_token_nonce_test.rb
- test/unit/gateways/braintree_token_nonce_test.rb
In order to enhance the TokenNonce class and enable the token noce generation for CrediCards, this PR adds the graphql query and inputs necessary for CreditCards
> Braintree create credit card nonce

- CHANGELOG
- lib/active_merchant/billing/gateways/adyen.rb
- test/unit/gateways/adyen_test.rb
Move add_shopper_data back to add_extra_data to ensure that shopperEmail is being sent in all transaction types.
Unit:
112 tests, 589 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote:
137 tests, 455 assertions, 11 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 91.9708% passed
> Adyen: Fix bug for shopperEmail

- CHANGELOG
- lib/active_merchant/billing/gateways/kushki.rb
- test/remote/gateways/remote_kushki_test.rb
Fixes a bug for Kushki that fails transactions when 3DS info is passed for VISA Credit Cards.
[SER-830](https://spreedly.atlassian.net/browse/SER-830)
Finished in 87.534566 seconds.
24 tests, 71 assertions, 0 failures, 0 errors,
100% passed
Finished in 37.30761 seconds.
5624 tests, 78070 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
772 files inspected, no offenses detected
> Kushki: Fixing issue with 3DS info on visa cc

- lib/active_merchant/billing/gateways/adyen.rb
- test/remote/gateways/remote_adyen_test.rb
- test/unit/gateways/adyen_test.rb
CER-777
Adyen address fields are more European centric: `houseNumberOrName` and `street`.
`address1` is currently mapped to `street` and `address2` is currently mapped to `houseNumberOrName` which causes AVS errors for users. This may be worth making a permanent change and removing the override in the future.
Remote Tests:
138 tests, 457 assertions, 11 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 92.029% passed
*11 failures are also failing on master
Unit Tests:
113 tests, 595 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Local Tests:
5634 tests, 78165 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> Adyen: Add `address_override` optional field to swap address1 and address2

- CHANGELOG
- lib/active_merchant/billing/gateways/adyen.rb
- test/remote/gateways/remote_adyen_test.rb
- test/unit/gateways/adyen_test.rb
ECS-3158
The existing logic for MIT flagging for any NT card (ApplePay, GooglePay, or NetworkToken) assume that they cannot be used with a `shopperInteraction` of `ContAuth`. This is not true as a merchant can perform MIT transactions with these payment methods if they skip adding MPI data.
This commit updates the `shopper_interaction` logic so that NT payment methods on subsequent transactions will be flagged as `ContAuth` and skip adding MPI data for them.
This commit also comments out Adyen's remote store tests as they are failing. A new ticket, ECS-3205, has been created to fix them.
Remote Tests:
126 tests, 433 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> Adyen: Update MIT flagging for NT

- CHANGELOG
- lib/active_merchant/billing/gateways/rapyd.rb
- test/remote/gateways/remote_rapyd_test.rb
- test/unit/gateways/rapyd_test.rb
Added the recurrence_type field
Local:
5636 tests, 78128 assertions, 0 failures, 19 errors, 0 pendings, 0 omissions, 0 notifications
99.6629% passed
Unit:
35 tests, 166 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
42 tests, 119 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Rapyd: Add recurrence_type field

- CHANGELOG
- lib/active_merchant/billing/gateways/sum_up.rb
- test/remote/gateways/remote_sum_up_test.rb
- test/unit/gateways/sum_up_test.rb
Description
Add Void and Refund calls to SumUp Gateway adapter with the basic information needed
This are the relevant links to review the initial implementation:
- [Deactivate a checkout](https://developer.sumup.com/docs/api/deactivate-a-checkout/)
- [Make a refund](https://developer.sumup.com/docs/online-payments/guides/refund/)
Tickets for Spreedly reference
SER-713
Unit test
Finished in 31.708763 seconds.
5609 tests, 78038 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
Remote test
100% passed
176.89 tests/s, 2461.09 assertions/s
Rubocop
Inspecting 769 files
769 files inspected, no offenses detected
> SumUp - Void and partial refund calls

- CHANGELOG
- lib/active_merchant/billing/gateways/rapyd.rb
- test/unit/gateways/rapyd_test.rb
Introduces a change for authorize/purchase transactions to only include the custome_object for us payment types.
[SER-885](https://spreedly.atlassian.net/browse/SER-885)
Finished in 138.6279 seconds.
42 tests, 118 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
97.619% passed
*Note*: The failure test, fails because is a reference transaction related to a wallet.
Finished in 42.121938 seconds.
5643 tests, 78206 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Rapyd: send customer object on us payment types

- CHANGELOG
- lib/active_merchant/billing/gateways/securion_pay.rb
- test/remote/gateways/remote_securion_pay_test.rb
- test/remote/gateways/remote_shift4_v2_test.rb
- test/unit/gateways/securion_pay_test.rb
Modift the authorization_from when is a unsuccesful transaction, to get the value from chargeId key.
> SecurionPay/Shift4_v2: authorization from.

- CHANGELOG
- lib/active_merchant/billing/gateways/rapyd.rb
- test/remote/gateways/remote_rapyd_test.rb
- test/unit/gateways/rapyd_test.rb
This change is to properly nest the recurrence_type field. 
Local:
5638 tests, 78133 assertions, 0 failures, 19 errors, 0 pendings, 0 omissions, 0 notifications
99.663% passed
Unit:
35 tests, 166 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
41 tests, 117 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Rapyd: fix the recurrence_type field

- CHANGELOG
- lib/active_merchant/billing/gateways/element.rb
- test/remote/gateways/remote_element_test.rb
- test/unit/gateways/element_test.rb
Documentation for this can be found [here](https://developerengine.fisglobal.com/apis/express/express-xml/classes#lodging). I had to add support for a few more fields otherwise the lodging fields cannot be supported (they're extended parameters class). also with the tests files, new credentials were given and I had to clean up the remote tests specs to follow along with the new sandbox configurations. All tests are now passing and updated in this change.
Local:
5625 tests, 78037 assertions, 0 failures, 19 errors, 0 pendings, 0 omissions, 0 notifications
99.6622% passed
Unit:
27 tests, 149 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 
32 tests, 88 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Element Gateway: Add all lodging fields

- CHANGELOG
- lib/active_merchant/billing/gateways/safe_charge.rb
- test/remote/gateways/remote_safe_charge_test.rb
- test/unit/gateways/safe_charge_test.rb
This is to essentially do an override on the sg_CreditType field to send a 2 if unreferenced_refund field is sent as true.
Local:
5636 tests, 78102 assertions, 0 failures, 19 errors, 0 pendings, 0 omissions, 0 notifications
99.6629% passed
Unit:
29 tests, 160 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
33 tests, 92 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> SafeCharge (Nuvei): Fix the credit method for sg_CreditType field

- CHANGELOG
- lib/active_merchant/billing/gateways/rapyd.rb
- test/unit/gateways/rapyd_test.rb
Introduces a change for 3ds transactions when dealing with 3DS gateway specific besides the standard fields a GSF needs to be sent in order to force the 3DS flow, this change is needed because the '3d_require' attribute works as a force flag, not like a feature flag.
[SER-889](https://spreedly.atlassian.net/browse/SER-889)
Finished in 115.583277 seconds.
42 tests, 118 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
97.619% passed
*Note*: The failure test, fails becase is reference transaction related to a wallet.
Finished in 42.100949 seconds.
5643 tests, 78206 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Rapyd: add force_3ds_secure flag

- CHANGELOG
- lib/active_merchant/billing/gateways/beanstream/beanstream_core.rb
- test/unit/gateways/beanstream_test.rb
LOCAL
5639 tests, 78187 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
UNIT
24 tests, 112 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
REMOTE 
45 tests, 201 assertions, 3 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
*Tests also fail on master branch
> Beanstream: add alternate option for passing phone number

- CHANGELOG
- lib/active_merchant/billing/gateways/authorize_net.rb
- test/remote/gateways/remote_authorize_net_test.rb
- test/unit/gateways/authorize_net_test.rb
Update network token payment method to clarify what is being sent.
Remote:
85 tests, 304 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Unit:
122 tests, 684 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> Authorize.NET: Update network token method

- CHANGELOG
- lib/active_merchant/billing/gateways/global_collect.rb
- test/remote/gateways/remote_global_collect_test.rb
- test/unit/gateways/global_collect_test.rb
Remote
53 tests, 121 assertions, 10 failures, 1 errors, 0 pendings, 0 omissions, 0 notifications 79.2453% passed
Unit
46 tests, 234 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> GlobalCollect: Add support for 3DS exemptions

- CHANGELOG
- lib/active_merchant/billing/gateways/adyen.rb
- test/remote/gateways/remote_adyen_test.rb
- test/unit/gateways/adyen_test.rb
LOCAL
5643 tests, 78207 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
UNIT
113 tests, 596 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
REMOTE
139 tests, 459 assertions, 11 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
92.0863% passed
> Adyen: Add mcc field

- CHANGELOG
- lib/active_merchant/billing/gateways/quickbooks.rb
The OAuth response in commit is preventing the transaction from being retried if they failed with AuthenticationFailed because of invalid credentials or expired access tokens.
> Quickbooks: Remove OAuth from commit method

- lib/active_merchant/billing/gateways/kushki.rb
- test/remote/gateways/remote_kushki_test.rb
- test/unit/gateways/kushki_test.rb
This updates the logic to allow a request body to be sent as part of a refund request. Kushki uses the DELETE http method for refunds and voids, which meant that they were truly reference transactions only without a request body. The ssl_invoke method needed to be updated to allow for this, and still be able to send the ticketNumber through in post to be captured and added to the url.
This also updates several remote tests that had `PEN` currency to use credentials that are tied to Peru so they will pass.
Unit Tests:
18 tests, 117 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote Tests:
25 tests, 74 assertions, 3 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 96% passed
*There are 3 tests failing due to credentials issues. Kushki …
> Kushki: Add support for Partial Refunds

- lib/active_merchant/billing/gateways/braintree/token_nonce.rb
- test/unit/gateways/braintree_token_nonce_test.rb
Fix token nonce to support nil billing address
[SER-954](https://spreedly.atlassian.net/browse/SER-954)
> Braintree: 3DS2

- CHANGELOG
- lib/active_merchant/billing/gateways/cecabank/cecabank_json.rb
- test/remote/gateways/remote_cecabank_rest_json_test.rb
Description
Include 3DS2 Global
For Spreedly reference:
SER-817
Unit test
Finished in 21.808339 seconds.
5660 tests, 78301 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote test
259.53 tests/s, 3590.42 assertions/s
Rubocop
Inspecting 778 files
778 files inspected, no offenses detected
> Cecabank: Add 3DS Global to Cecabank REST JSON gateway

- CHANGELOG
- lib/active_merchant/billing/gateways/global_collect.rb
- test/remote/gateways/remote_global_collect_test.rb
Some apple_pay transactions that were through global collect direct (ogone) were being marked as failed despite success. The response from direct was slightly different than the standard global collect so the logic wasn't seeing them as successful.
Spreedly reference ticket: ECS-3197
remote tests:
54 tests, 141 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
unit tests:
45 tests, 230 assertions, 0 failures, 0 errors, 0 pending, 0 omissions, 0 notifications 100% passed
1497.80 tests/s, 7655.44 assertions/s
> GlobalCollect: Fix bug in success_from logic

- CHANGELOG
- lib/active_merchant/billing/gateways/worldpay.rb
- test/remote/gateways/remote_worldpay_test.rb
- test/unit/gateways/worldpay_test.rb
unit tests:
-------------------------------------------------------------------------------------------------------------------------
113 tests, 645 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
--------------------------------------------------------------------------------------------------------------------------426.14 tests/s, 2432.37 assertions/s
remote tests:
--------------------------------------------------------------------------------------------------------------------------
100 tests, 412 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
--------------------------------------------------------------------------------------------------------------------------
ticket for spreedly tracking: ECS-3125
> Worldpay: Update 3ds logic to accept df_reference_id directly

- CHANGELOG
- lib/active_merchant/billing/gateways/orbital.rb
- test/fixtures.yml
- test/remote/gateways/remote_orbital_test.rb
- test/unit/gateways/orbital_test.rb
Description
[SER-782](https://spreedly.atlassian.net/browse/SER-782)
This commit enable third party vaulting for Orbital in this case Orbital needs a flag to enable the store process and it doesn't support unstore function.
Orbital does not have a store and unstore endpoint. We are enabling the store process through a Spreedly store endpoint, but behind the scenes, we are performing a $0 authorization and sending the tokenTxType."
Unit test
Finished in 1.849371 seconds.
147 tests, 831 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
79.49 tests/s, 449.34 assertions/s
Remote test
Finished in 101.551157 seconds.
126 tests, 509 assertions, 9 failures, 0 errors, 0 pendings, 0 …
> Orbital: Enable Third Party Vaulting

- CHANGELOG
- lib/active_merchant/billing/gateways/payeezy.rb
- test/remote/gateways/remote_payeezy_test.rb
- test/unit/gateways/payeezy_test.rb
This adds the customer_ref (top level) field and the reference_3 field.
Local:
5654 tests, 78215 assertions, 0 failures, 19 errors, 0 pendings, 0 omissions, 0 notifications
99.664% passed
Unit:
51 tests, 235 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
52 tests, 213 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Payeezy: Add customer_ref and reference_3 fields

- CHANGELOG
- lib/active_merchant/billing/gateways/redsys_rest.rb
- test/fixtures.yml
- test/remote/gateways/remote_redsys_rest_test.rb
- test/unit/gateways/redsys_rest_test.rb
ECS-3219
This ticket adds a new gateway that serves as an update over the legacy
Redsys integration by moving to the Redsys Rest integration. This commit
adds support for basic functionality including authorize, purchase, scrubbing,
and standardizes responses.
This commit does not include support for:
* Stored Credentials (Ticket not yet created to add this support)
* External 3DS Support (Ticket not yet created to add this support)
* Redsys 3DS Support (Ticket created to add this support)
Co-authored-by: Amit Enand <aenand@spreedly.com>
Co-authored-by: Piers Chambers <piers@varyonic.com>
> Redsys REST

- CHANGELOG
- lib/active_merchant/billing/gateways/cyber_source.rb
- test/remote/gateways/remote_cyber_source_test.rb
- test/unit/gateways/cyber_source_test.rb
This is to help us parse out the second reconciliationID since it is sometimes returned in the second response.
Local:
5651 tests, 78200 assertions, 0 failures, 19 errors, 0 pendings, 0 omissions, 0 notifications
99.6638% passed
Unit:
142 tests, 794 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
128 tests, 639 assertions, 5 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
96.0938% passed
> CyberSource: surface the reconciliationID2 field if present

- lib/active_merchant/billing/gateways/worldpay.rb
- test/remote/gateways/remote_worldpay_test.rb
- test/unit/gateways/worldpay_test.rb
Remote tests:
99 tests, 429 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Unit tests:
116 tests, 658 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Spreedly ticket: ECS-3238
> Worldpay: Update stored credentials logic

- lib/active_merchant/billing/gateways/stripe.rb
- test/remote/gateways/remote_stripe_payment_intents_test.rb
- test/unit/gateways/stripe_payment_intents_test.rb
This adds the ability for StripePI to get the same AVS checks that come with Stripe.
> Ecs 3181 stripe pi checks

- CHANGELOG
- lib/active_merchant/billing/gateways/vantiv_express.rb
- test/remote/gateways/remote_vantiv_express_test.rb
- test/unit/gateways/vantiv_express_test.rb
Unit test:
28 tests, 142 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote tests:
31 tests, 91 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> Vantiv Express: New Xml gateway

- lib/active_merchant/billing/gateways/rapyd.rb
- test/unit/gateways/rapyd_test.rb
Add changes to be more strict on how the `force_3d_secure` is considered true.
[SER-968](https://spreedly.atlassian.net/browse/SER-968)
Finished in 239.011074 seconds.
42 tests, 118 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
97.619% passed
*Note:* The reason for the failing test is aun outdated wallet reference.
Finished in 38.879517 seconds.
5670 tests, 78363 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
778 files inspected, no offenses detected
> Rapyd: update force_3d_secure GSF behavior

- CHANGELOG
- lib/active_merchant/billing/gateways/commerce_hub.rb
- test/remote/gateways/remote_commerce_hub_test.rb
Description
Add 3DS global support to Commerce Hub gateway
Tickets for Spreedly reference
SER-922
Unit test
Finished in 23.891463 seconds.
5671 tests, 78366 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote test
237.37 tests/s, 3280.08 assertions/s
Rubocop
778 files inspected, no offenses detected
> Add 3DS global support to Commerce Hub gateway

- CHANGELOG
- lib/active_merchant/billing/gateways/sum_up.rb
- test/fixtures.yml
- test/remote/gateways/remote_sum_up_test.rb
- test/unit/gateways/sum_up_test.rb
Description
Fix refund method to SumUp Gateway adapter.
This are the relevant links to review the implementation:
- [Refund a transaction](https://developer.sumup.com/docs/api/refund-transaction/)
Tickets for Spreedly reference
SER-836
Note: SumUp has shared with us an account to test with which we can refund a purchase
Unit test
Finished in 32.469516 seconds.
5638 tests, 78183 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote test
173.64 tests/s, 2407.89 assertions/s
Rubocop
> SumUp Gateway: Fix refund method

- CHANGELOG
- lib/active_merchant/billing/gateways/braintree_blue.rb
- test/remote/gateways/remote_braintree_blue_test.rb
- test/unit/gateways/braintree_blue_test.rb
ECS-3194
Braintree has informed us we are not handling stored credentials appropriately in certain cases. This commit adds a new method to handle this new behavior in a controlled manner.
The changes are that if it's the initial_transaction & recurring it is to be marked as `recurring_first`.
If there are any reason_types unrecognized we will mark transaction_source as nil
Test Summary
Remote:
111 tests, 585 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> Braintree: Add new stored credential method

- CHANGELOG
- lib/active_merchant/billing/gateways/cyber_source_rest.rb
- test/unit/gateways/cyber_source_rest_test.rb
Cybersource has updated their API to allow the Signature's request-target header to no longer be enclosed in parentheses, ahead of instating this as a requirement on January 22 2024:
https://community.developer.cybersource.com/t5/cybersource-Developer-Blog/REST-API-Http-Signature-Authentication-Critical-Security-Update/ba-p/87319
ECS-3236
Remote:
47 tests, 157 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Unit:
47 tests, 157 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> Cybersource REST: Remove request-target parens

- CHANGELOG
- lib/active_merchant/billing/gateways/ogone.rb
- test/unit/gateways/ogone_test.rb
Add changes to deal with ogone signature when there are empty fields on the passed params
[SER-965](https://spreedly.atlassian.net/browse/SER-965)
Finished in 135.715931 seconds.
33 tests, 138 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
Finished in 38.938916 seconds.
5733 tests, 78693 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Ogone: Fix signature calulcation for blank fields

- CHANGELOG
- lib/active_merchant/billing/gateways/visanet_peru.rb
- test/unit/gateways/visanet_peru_test.rb
This passes along the generated purchaseNumber in the response as Visanet peru does not echo this back to us.
Note: remote test for this gateway are un-available due to outdated credentials and issues with receiving new ones.
Local:
5732 tests, 78643 assertions, 0 failures, 19 errors, 0 pendings, 0 omissions, 0 notifications
99.6685% passed
Unit:
16 tests, 101 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> VisaNet Peru: Pass the purchaseNumber in response

- CHANGELOG
- lib/active_merchant/billing/gateways/safe_charge.rb
- test/remote/gateways/remote_safe_charge_test.rb
- test/unit/gateways/safe_charge_test.rb
Remote:
34 tests, 96 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Unit:
29 tests, 160 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> SafeCharge: Support tokens

- CHANGELOG
- lib/active_merchant/billing/gateways/worldpay.rb
- test/remote/gateways/remote_worldpay_test.rb
- test/unit/gateways/worldpay_test.rb
Update payment_details and add_network_tokenization_card to accept GooglePay payment methods that are pan only.
Remote:
103 tests, 416 assertions, 7 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 93.2039% passed
Unit:
114 tests, 648 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> WorldPay: Accept GooglePay pan only

- CHANGELOG
- lib/active_merchant/billing/gateways/braintree_blue.rb
- test/unit/gateways/braintree_blue_test.rb
Ensure that MIT unscheduled transactions get mapped to unscheduled at Braintree
Remote:
111 tests, 585 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> Braintree stored creds v2: update unschedule

- CHANGELOG
- lib/active_merchant/billing/gateways/stripe_payment_intents.rb
- test/remote/gateways/remote_stripe_payment_intents_test.rb
- test/unit/gateways/stripe_payment_intents_test.rb
This will add the card brand field for the payment and setup intents
Local:
5733 tests, 78645 assertions, 0 failures, 19 errors, 0 pendings, 0 omissions, 0 notifications
99.6686% passed
Unit
58 tests, 302 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
95 tests, 448 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Stripe PI: add the card brand field

- CHANGELOG
- lib/active_merchant/billing/gateways/rapyd.rb
- test/remote/gateways/remote_rapyd_test.rb
- test/unit/gateways/rapyd_test.rb
Description
[SER-970](https://spreedly.atlassian.net/browse/SER-974)
This commit enable a new mode of authentication for Rapyd. 
This new mode only apply for create payments
Unit test
Finished in 0.189728 seconds.
41 tests, 188 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
216.10 tests/s, 990.89 assertions/s
Remote test
Finished in 208.640892 seconds.
47 tests, 123 assertions, 6 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 87.234% passed
0.23 tests/s, 0.59 assertions/s
Rubocop
> Rapyd: Enable new auth mode payment_redirect

- CHANGELOG
- lib/active_merchant/billing/gateways/cecabank/cecabank_json.rb
- test/remote/gateways/remote_cecabank_rest_json_test.rb
- test/unit/gateways/cecabank_rest_json_test.rb
Cecabank: Fix exemption_type when it is blank and update the error code for some tests
Summary:
Fix `exemption_type` when it is blank
Add `exemption_type` tests to increase the coverage
Update the error code for some tests
Replace `ssl_request` to `ssl_post` in the `commit` method
For Spreedly reference:
[SER-1009](https://spreedly.atlassian.net/browse/SER-1009)
Remote Test:
Finished in 63.024038 seconds.
19 tests, 65 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
0.30 tests/s, 1.03 assertions/s
Unit Tests:
Finished in 31.381399 seconds.
5739 tests, 78700 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
RuboCop: …
> Cecabank: Fix exemption_type when it is blank and update the error code for some tests

- CHANGELOG
- lib/active_merchant/billing/gateways/adyen.rb
- test/remote/gateways/remote_adyen_test.rb
- test/unit/gateways/adyen_test.rb
According to Adyen's documentation, ZZ should be provided as the country code if the country is not known or is not collected from the cardholder:
https://docs.adyen.com/api-explorer/Payment/latest/post/authorise#request-billingAddress-country https://docs.adyen.com/api-explorer/Payment/latest/post/authorise#request-deliveryAddress-country
Sending an empty string or nil value results in a validation error from Adyen's API
CER-979
Local
5741 tests, 78708 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Unit
115 tests, 604 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote
142 tests, 461 assertions, 11 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications …
> Adyen: Provide ZZ as default country code

- CHANGELOG
- lib/active_merchant/billing/gateways/mit.rb
This change provides the option to send test requests to the QA endpoint of the MIT gateway at `https://scqa.mitec.com.mx/ModuloUtilWS/activeCDP.htm`
CER-1066
Local
5740 tests, 78706 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Unit
9 tests, 33 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote
8 tests, 22 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> MIT: Add test_url

- CHANGELOG
- lib/active_merchant/billing/gateways/adyen.rb
- test/remote/gateways/remote_adyen_test.rb
- test/unit/gateways/adyen_test.rb
CER-1082
Metadata is an object that will allow up to 20 KV pairs per request. There are character limitations: Max 20 characters per key, max 80 per value.
Unit Tests:
116 tests, 611 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote Tests:
143 tests, 463 assertions, 11 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 92.3077% passed
* These 11 failing tests also fail on master
Local Tests:
5751 tests, 78745 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> Adyen: Add support for `metadata`

- CHANGELOG
- lib/active_merchant/billing/gateways/rapyd.rb
- test/remote/gateways/remote_rapyd_test.rb
- test/unit/gateways/rapyd_test.rb
Description
[SER-1023](https://spreedly.atlassian.net/browse/SER-1023)
This commit adds an idempotency attribute to headers in order to support idempotent requests, Rapyd manage it, taking into account the idempotency value and the amount to determine if a transaction is idempotent or no.
Unit test
Finished in 0.504217 seconds.
42 tests, 196 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
83.30 tests/s, 388.72 assertions/s
Remote test
49 tests, 142 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 97.9592% passed
Rubocop
> Rapyd: Enable idempotent request support

- CHANGELOG
- lib/active_merchant/billing/gateways/litle.rb
- test/remote/gateways/remote_litle_test.rb
- test/unit/gateways/litle_test.rb
Update account type to also use account_holder_type and safeguard against it being nil.
Unit:
59 tests, 264 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote:
57 tests, 251 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> Litle: Update account type

- CHANGELOG
- lib/active_merchant/billing/gateways/wompi.rb
- test/remote/gateways/remote_wompi_test.rb
- test/unit/gateways/wompi_test.rb
CER-1062
Remote Tests:
14 tests, 27 assertions, 4 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 71.4286% passed
Some remote tests are failing due to a missing email, will address in a different ticket.
Unit Tests:
13 tests, 65 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Local Tests:
5740 tests, 78712 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> Wompi: Add support for `tip_in_cents`

- CHANGELOG
- lib/active_merchant/billing/gateways/hi_pay.rb
- test/fixtures.yml
- test/remote/gateways/remote_hi_pay_test.rb
- test/unit/gateways/hi_pay_test.rb
SER-719
SER-772
------
Summary:
-------
Adding HiPay gateway with support for basic functionality including authorize, purchase, capture, and store calls.
HiPay requires the tokenization of the CreditCards that's why this first implementation includes the tokenization and store methods.
The store and tokenization methods are different in the "multiuse" param. With this a tokenized PM can be used once(tokenization) or several times(store)
Tests
------
Remote Test:
Finished in 6.627757 seconds.
8 tests, 35 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit Tests:
18 tests, 50 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
RuboCop:
> HiPay:  Add Gateway

- CHANGELOG
- lib/active_merchant/billing/gateways/xpay.rb
- test/remote/gateways/remote_xpay_test.rb
- test/unit/gateways/xpay_test.rb
Description
[SER-705](https://spreedly.atlassian.net/browse/SER-705)
This commit add NexiXpay operations, void, refund, verify
> SER-705 Nexi Xpay Void, Refund, Verify

- CHANGELOG
- lib/active_merchant/billing/gateways/braintree_blue.rb
- test/remote/gateways/remote_braintree_blue_test.rb
This adds the apple pay, google pay, and network token details object. Will also surface the payment instrument type so we can know which one was used
Local:
5754 tests, 78658 assertions, 0 failures, 26 errors, 0 pendings, 0 omissions, 0 notifications
99.5481% passed
Unit:
102 tests, 216 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
114 tests, 548 assertions, 6 failures, 4 errors, 0 pendings, 0 omissions, 0 notifications
91.2281% passed
> Braintree Blue: Add more payment detail objects

- CHANGELOG
- lib/active_merchant/billing/gateways/cyber_source.rb
- test/remote/gateways/remote_cyber_source_test.rb
- test/unit/gateways/cyber_source_test.rb
add the first_recurring_payment field to ccAuthService
local:
5755 tests, 78661 assertions, 0 failures, 26 errors, 0 pendings, 0 omissions, 0 notifications
99.5482% passed
Unit:
144 tests, 803 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
128 tests, 639 assertions, 5 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
96.0938% passed
> CyberSource: add the first_recurring_payment auth service field

- CHANGELOG
- lib/active_merchant/billing/gateways/commerce_hub.rb
- test/remote/gateways/remote_commerce_hub_test.rb
- test/unit/gateways/commerce_hub_test.rb
Adds the option to send dynamic descriptors on auth/capture or purchase
https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Resources/Guides/Dynamic-Descriptor.md&branch=main
CER-1077
LOCAL
5758 tests, 78786 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
UNIT
28 tests, 194 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
REMOTE
-> When running the full remote test suite, I see between 16-18 failures each time, each of which has the message `"The transaction limit was exceeded. Please try again!"`
When I run the failing tests individually, all of them pass, with a few exceptions: `test_successful_credit` (merchant account configuration) …
> CommerceHub: Add dynamic descriptors

- CHANGELOG
- lib/active_merchant/billing/gateways/rapyd.rb
- test/unit/gateways/rapyd_test.rb
Description
This commit update the email mapping for purchase, when we have an customer_id and the payment_method is a token we will send receipt_email instead email, otherwise the email will be sent into the customer object .
[SER-1040](https://spreedly.atlassian.net/browse/SER-1040)
Unit test
Finished in 0.186326 seconds.
44 tests, 208 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
236.15 tests/s, 1116.32 assertions/s
Remote test
Finished in 263.428138 seconds.
49 tests, 142 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 97.9592% passed
0.19 tests/s, 0.54 assertions/s
Rubocop
> Rapyd: email mapping update

- CHANGELOG
- lib/active_merchant/billing/gateways/sage_pay.rb
- test/remote/gateways/remote_sage_pay_test.rb
- test/unit/gateways/sage_pay_test.rb
ECS-3323
To de-risk the update of the SagePay gateway integration to move from V3.00 to V4.00 this commit adds the ability to specify an override protocol version via the transaction while also preserving the ability to override
via a gateway class
Remote:
Commented out test also failing on master
37 tests, 108 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> SagePay: Support v4

- CHANGELOG
- lib/active_merchant/billing/gateways/braintree_blue.rb
- test/remote/gateways/remote_braintree_blue_test.rb
- test/unit/gateways/braintree_blue_test.rb
Remote:
112 tests, 589 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Unit:
103 tests, 218 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> Braintree: Send merchant_account_id for creation of client token

- CHANGELOG
- lib/active_merchant/billing/gateways/checkout_v2.rb
- test/unit/gateways/checkout_v2_test.rb
After a redirect from 3DS transactions the verify_payment method is usually called which returns the response_summary inside actions.
Unit:
64 tests, 378 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote:
98 tests, 236 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> Checkout: Update reponse message for 3DS transactions

- CHANGELOG
- lib/active_merchant/billing/gateways/hi_pay.rb
- test/remote/gateways/remote_hi_pay_test.rb
- test/unit/gateways/hi_pay_test.rb
SER-720
SER-721
----
Summary:
----
Adding to the HiPay gateway support for scrub, refund, and void.
HiPay allows partial capture and partial refunds, this commit include the amount to use it.
Tests
----
Remote Test:
Finished in 6.627757 seconds.
15 tests, 62 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Unit Tests:
21 tests, 61 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
RuboCop:
> HiPay: Scrub/Refund/Void

- CHANGELOG
- lib/active_merchant/billing/gateways/hi_pay.rb
- test/remote/gateways/remote_hi_pay_test.rb
- test/unit/gateways/hi_pay_test.rb
SER-772
--------
Summary:
-----------
Adding to the HiPay gateway support for unstore.
Currently, HiPay implementation allows store, this commit includes the unstore method to use it.
Tests
---------
Remote Test:
Finished in 6.627757 seconds.
17 tests, 70 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Unit Tests:
21 tests, 54 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
RuboCop:
> HiPay: Add unstore

- CHANGELOG
- lib/active_merchant/billing/gateways/rapyd.rb
- test/unit/gateways/rapyd_test.rb
Description
[SER-1068](https://spreedly.atlassian.net/browse/SER-1068)
This commit applies a format of two digits in the month and year fields,
Unit test
Finished in 0.383202 seconds.
49 tests, 225 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
127.87 tests/s, 587.16 assertions/s
Remote test
Finished in 216.477122 seconds.
51 tests, 146 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 98.0392% passed
0.24 tests/s, 0.67 assertions/s
Rubocop
> Rapyd: Fix transaction with two digits in month and year

- CHANGELOG
- lib/active_merchant/billing/gateways/sage_pay.rb
- test/remote/gateways/remote_sage_pay_test.rb
- test/unit/gateways/sage_pay_test.rb
Adds support for stored credentials  on
authorize and purchase requests.
Remote:
41 tests, 127 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Unit:
44 tests, 164 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> SagePay: Add support for stored credentials

- CHANGELOG
- lib/active_merchant/billing/gateways/payeezy.rb
- test/unit/gateways/payeezy_test.rb
If payment method doesn't have name then pull it from the billing address for credit card cardholder name.
Remote:
52 tests, 212 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 98.0769% passed
Unit:
51 tests, 235 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> Payeezy: Pull cardholder name from billing address

- lib/active_merchant/billing/gateways/shift4.rb
- test/remote/gateways/remote_shift4_test.rb
- test/unit/gateways/shift4_test.rb
CER_1094
This change updates a few response methods to return more accurate codes and messages instead of the currently existing standard error code mapping. The previously implemented standard error code mapping was not great. It was returning messages not direct from the gateway, which was perhaps an old standard but there have been requests to make the messages returned aligned with the gateway's actual response.
Failed sandbox transactions do not return the `hostResponse`, which is from the card networks, but they do return `responseCode: D`. I've made some extensive updates to test cases and responses to more accurately reflect the gateway's responses in production transactions.
> Shift4: update response mapping

- CHANGELOG
- lib/active_merchant/billing/gateways/cecabank/cecabank_json.rb
Description
[SER-1070](https://spreedly.atlassian.net/browse/SER-1070)
This commit enable the encode_params private method to encode a string or a hash of params, also include a refactor for the scrub method.
Unit test
Finished in 24.094723 seconds.
5797 tests, 78916 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
240.59 tests/s, 3275.24 assertions/s
Remote test
Finished in 53.880651 seconds.
16 tests, 59 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
0.30 tests/s, 1.10 assertions/s
Rubocop
> Cecabank: Fix gateway scrub method

- CHANGELOG
- lib/active_merchant/billing/gateways/pin.rb
- test/remote/gateways/remote_pin_test.rb
- test/unit/gateways/pin_test.rb
This just adds the ability to add the platform_adjustment to charges
Local:
5801 tests, 78838 assertions, 1 failures, 27 errors, 0 pendings, 0 omissions, 0 notifications 99.5346% passed
Unit:
44 tests, 144 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote:
21 tests, 65 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> Pin Gateway: Add the platform_adjustment field

- CHANGELOG
- lib/active_merchant/billing/gateways/priority.rb
- test/remote/gateways/remote_priority_test.rb
- test/unit/gateways/priority_test.rb
This change is to essentially allow the gateway fields to be available on the capture endpoint. Written the remote and unit tests to confirm this. I would note that the failing remote tests return the error message of rapid refund detected, so I'm assuming the sandbox has some rate limit attached.
Local:
5800 tests, 78860 assertions, 0 failures, 26 errors, 0 pendings, 0 omissions, 0 notifications 99.5517% passed
Unit:
21 tests, 145 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote:
31 tests, 84 assertions, 5 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 83.871% passed
> Priority: Allow gateway fields to be available on capture endpoint

- CHANGELOG
- lib/active_merchant/billing/network_tokenization_credit_card.rb
- test/unit/gateways/pin_test.rb
- test/unit/gateways/shift4_test.rb
- test/unit/network_tokenization_credit_card_test.rb
Some gateways required use to send the encrypted payment_data for ApplePay and GooglePay instead of the decrypted data.
Unit:
4 tests, 13 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> Add payment_data to network_tokenization_credit_card

- CHANGELOG
- lib/active_merchant/billing/gateways/ipg.rb
- test/unit/gateways/ipg_test.rb
Instead of sending the amount in cents, the amount should be sent in dollars.
CER-1199
LOCAL
5802 tests, 78968 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
UNIT
31 tests, 134 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
REMOTE
20 tests, 58 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> IPG: Update handling of ChargeTotal

- CHANGELOG
- lib/active_merchant/billing/gateways/plexo.rb
- test/remote/gateways/remote_plexo_test.rb
- test/unit/gateways/plexo_test.rb
This adds the optional invoice_number field and adds more remote and unit tests for the merchant_id field
Local:
5806 tests, 78878 assertions, 1 failures, 27 errors, 0 pendings, 0 omissions, 0 notifications
99.535% passed
Unit:
24 tests, 127 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
31 tests, 53 assertions, 1 failures, 2 errors, 0 pendings, 3 omissions, 0 notifications
89.2857% passed
> Plexo: add the invoice_number field

- CHANGELOG
- lib/active_merchant/billing/gateways/checkout_v2.rb
- test/remote/gateways/remote_checkout_v2_test.rb
Prevent NoMethodError from being thrown when no billing address is present in options
CER-1182
LOCAL
5806 tests, 78980 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
UNIT
64 tests, 384 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
REMOTE
99 tests, 238 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 98.9899% passed
The single failing remote test is test_successful_refund_via_oauth, which is unrelated to this change and is also failing on master
> CheckoutV2: Handle empty address in payout destination data

- CHANGELOG
- lib/active_merchant/billing/gateways/cyber_source.rb
- test/remote/gateways/remote_cyber_source_test.rb
- test/unit/gateways/cyber_source_test.rb
This adds the aggregator_id field
Local:
5807 tests, 78885 assertions, 0 failures, 26 errors, 0 pendings, 0 omissions, 0 notifications
99.5523% passed
Unit:
145 tests, 806 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
129 tests, 636 assertions, 7 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
94.5736% passed
> CyberSource: Add the auth_service aggregator_id field

- CHANGELOG
- lib/active_merchant/billing/gateways/cecabank/cecabank_json.rb
- test/remote/gateways/remote_cecabank_rest_json_test.rb
- test/unit/gateways/cecabank_rest_json_test.rb
This PR excludes the threeds node in the cecabank requests for the non three ds transactions
Finished in 0.033172 seconds.
15 tests, 74 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Finished in 24.858862 seconds.
16 tests, 59 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 93.75% passed
test test_purchase_using_stored_credential_recurring_mit fails due to gateway rules
> SER-1083 Cecabank: exclude 3ds empty parameter 

- CHANGELOG
- lib/active_merchant/billing/gateways/moneris.rb
- test/remote/gateways/remote_moneris_test.rb
- test/unit/gateways/moneris_test.rb
This simply adds the cust_id field for purchase and authorization
Local:
5808 tests, 78890 assertions, 0 failures, 26 errors, 0 pendings, 0 omissions, 0 notifications 99.5523% passed
Unit:
54 tests, 293 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote:
53 tests, 259 assertions, 0 failures, 0 errors, 0 pendings, 1 omissions, 0 notifications 100% passed
> Moneris: Add the customer id field

- CHANGELOG
- lib/active_merchant/billing/gateways/rapyd.rb
- test/remote/gateways/remote_rapyd_test.rb
- test/unit/gateways/rapyd_test.rb
This PR adds changes to handle 400s and 500s errors coming from the Gateway, for that:
- Rescues 500 errors with a proper ActiveMerchant::Response object.
- Structures a hash object in case of 400s that return just a String.
- Selects the error_code and message from the response using what is available.
- Fixes transcript test errors.
[SER-1081](https://spreedly.atlassian.net/browse/SER-1081)
[SER-1045](https://spreedly.atlassian.net/browse/SER-1045)
Finished in 87.534566 seconds.
24 tests, 71 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Finished in 68.736139 seconds.
5808 tests, 78988 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Rapyd: Adding 500 errors handling

- CHANGELOG
- lib/active_merchant/billing/gateways/sum_up.rb
- test/fixtures.yml
- test/remote/gateways/remote_sum_up_test.rb
Description
[SER-798](https://spreedly.atlassian.net/browse/SER-798)
This commit enable the 3DS to retrieve the next_step object.
Unit test
Finished in 27.706081 seconds.
5807 tests, 78983 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
209.59 tests/s, 2850.75 assertions/s
Remote test
Finished in 3.182983 seconds.
1 tests, 3 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
0.31 tests/s, 0.94 assertions/s
Rubocop
> SumUp: Add 3DS fields

- CHANGELOG
- lib/active_merchant/billing/gateways/quickbooks.rb
- test/remote/gateways/remote_quickbooks_test.rb
- test/unit/gateways/quickbooks_test.rb
Update quickbooks scrubbing to include card lengths from 13-19 digits. Update quickbooks scrubbing to include cvc codes from 3-4 digits long.
Remote:
19 tests, 48 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Unit:
23 tests, 120 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> Quickbooks: Update scrubbing logic

- CHANGELOG
- lib/active_merchant/billing/gateways/cecabank/cecabank_json.rb
- test/remote/gateways/remote_cecabank_rest_json_test.rb
- test/unit/gateways/cecabank_rest_json_test.rb
Description
[SER-1084](https://spreedly.atlassian.net/browse/SER-1084)
This commit enables the use of a GSF for network_transaction_id
Additionally, it adds small fix for some remote tests.
Unit test
Finished in 0.032086 seconds.
15 tests, 78 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote test
Finished in 27.137734 seconds.
17 tests, 61 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 94.1176% passed
0.63 tests/s, 2.25 assertions/s
Rubocop
> Cecabank: Enable network_transaction_id as GSF

- CHANGELOG
- lib/active_merchant/billing/gateways/braintree_blue.rb
- test/remote/gateways/remote_braintree_blue_test.rb
This returns the paypal_details in the response object on paypal transaction so that we can surface the payer_id and payer_email fields for Braintree. 
Note: The remote test written requires a separate fixtures set.
Local:
5813 tests, 78910 assertions, 2 failures, 26 errors, 0 pendings, 0 omissions, 0 notifications
99.5183% passed
Unit:
103 tests, 218 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
116 tests, 607 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
98.2759% passed
> Braintree: Surface the paypal_details in response object

- CHANGELOG
- lib/active_merchant/billing/gateways/braintree_blue.rb
- lib/active_merchant/billing/gateways/global_collect.rb
- lib/active_merchant/billing/gateways/stripe.rb
- test/remote/gateways/remote_global_collect_test.rb
- test/unit/gateways/global_collect_test.rb
- test/unit/gateways/stripe_payment_intents_test.rb
Remove support for GooglePay decrypted payment data since they only support encrypted payment data.
Unit:
40 tests, 197 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> GlobalCollect: Remove decrypted payment data

- CHANGELOG
- lib/active_merchant/billing/gateways/stripe.rb
- test/remote/gateways/remote_stripe_payment_intents_test.rb
If the transaction fails with 'Received unexpected 3DS authentication response, but a 3DS initiation flag was not included in the request.' then authorization_from should return response['id']
Unit
59 tests, 308 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote
95 tests, 451 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> StripePI: Update authorization_from

- lib/active_merchant/billing/gateways/stripe.rb
- lib/active_merchant/billing/gateways/stripe_payment_intents.rb
- test/remote/gateways/remote_stripe_payment_intents_test.rb
Stripe Payment Intents: Update expand latest_attempt on create_setup_intent
This expansion allows a user to get the avs and cvc check results from the create_setup_intent call
[ECS-3375](https://spreedly.atlassian.net/browse/ECS-3375)
> Stripe Payment Intents: Update expand latest_attempt on create_setup

- lib/active_merchant/billing/gateways/elavon.rb
- test/remote/gateways/remote_elavon_test.rb
- test/unit/gateways/elavon_test.rb
To satisfy new Elavon API requirements, including recurring_flag, approval_code for non-tokenized PMs, installment_count and _number, and situational par_value and association_token_data fields.
This also now allows Authorize transactions with a token/stored card.
Remote (Same 5 Failures on Master):
39 tests, 162 assertions, 5 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 87.1795% passed
Unit:
53 tests, 298 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> Elavon: Update Stored Credential behavior

- lib/active_merchant/billing/gateways/shift4.rb
- test/unit/gateways/shift4_test.rb
CER-1128
This adds support for avs_result in the gateway's response. The standard ActiveMerchant AVS mapping is used, but varies slightly from Shift4's AVS message language in their docs. This should be taken into consideration during review. No remote test was added because the avs hash is not returned in sandbox transactions. It is returned consistently in the same format in the `transaction` hash in production transcripts.
Unit:
28 tests, 176 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote:
29 tests, 67 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Local:
5814 tests, 79016 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 99.9656% passed
> Shift4: Add support for avs_result

- CHANGELOG
- lib/active_merchant/billing/gateways/braintree_blue.rb
- test/remote/gateways/remote_braintree_blue_test.rb
This refactors a slight portion of the transaction hash regarding the payment details object that is being returned depending on which payment method is used. Also returns the these objects on failing transactions and added small fixes to previously failing tests. Also fixes some rubocop related issues.
Local:
5816 tests, 78913 assertions, 2 failures, 30 errors, 0 pendings, 0 omissions, 0 notifications
99.4498% passed
Unit:
103 tests, 218 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
120 tests, 634 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Braintree Blue: Refactor and add payment details to failed transactions

- CHANGELOG
- lib/active_merchant/billing/gateways/xpay.rb
This commit contains an update for Nexi Xpay to support 3steps API instead of 2steps API endpoints in order to complete 3DS transactions Documents for reference:
https://developer.nexi.it/en/modalita-di-integrazione/server-to-server/pagamento-3-steps
> Update Nexi Xpay to use 3DS 3steps API

- CHANGELOG
- lib/active_merchant/billing/gateways/authorize_net.rb
- test/remote/gateways/remote_authorize_net_test.rb
- test/unit/gateways/authorize_net_test.rb
This adds the surcharge object as an optional field
Local:
5828 tests, 79061 assertions, 4 failures, 27 errors, 0 pendings, 0 omissions, 0 notifications
99.4681% passed
Unit:
123 tests, 694 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
87 tests, 310 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Authorize Net: add the surcharge field

- CHANGELOG
- lib/active_merchant/billing/gateways/paymentez.rb
- test/remote/gateways/remote_paymentez_test.rb
- test/unit/gateways/paymentez_test.rb
directory_server_transaction_id should be used
to populate Paymentez.
Unit
30 tests, 127 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote
34 tests, 85 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> Paymentez: Update field for reference_id

- CHANGELOG
- lib/active_merchant/billing/gateways/xpay.rb
- test/remote/gateways/remote_xpay_test.rb
- test/unit/gateways/xpay_test.rb
This commit contains an update for Nexi Xpay basic transactions (capture, refund, verify)
Documents for reference:
https://developer.nexi.it/en/api/
For Spreedly reference:
[SER-1133](https://spreedly.atlassian.net/browse/SER-1133)
> Update Nexi Xpay basic transactions after implement 3DS 3steps API

- CHANGELOG
- lib/active_merchant/billing/gateways/authorize_net.rb
- test/remote/gateways/remote_authorize_net_test.rb
- test/unit/gateways/authorize_net_test.rb
Remove turn_on_nt_flow so that all network tokens
such as ApplePay fall done to dd_network_token method Unit:
122 tests, 688 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote:
85 tests, 304 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> AuthorizeNet: Remove turn_on_nt_flow

- CHANGELOG
- lib/active_merchant/billing/gateways/adyen.rb
- test/unit/gateways/adyen_test.rb
For v68 and later the network token cryptogram needs to be sent to mpi.tokenAuthenticationVerificationValue
Remote:
143 tests, 463 assertions, 11 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 92.3077% passed
Unit:
116 tests, 613 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> Adyen: Update failed for network token cryptogram

- lib/active_merchant/billing/credit_card.rb
- lib/active_merchant/billing/response.rb
That makes it hard to locate code when profiling etc.
> Avoid anonymous eval

- lib/active_merchant/billing/gateways/redsys_rest.rb
This accounts for the potential scenario where `card` is `CreditCard` rather than `ActiveMerchant::Billing::CreditCard`, and therefore doesn't have access to `verification_value?` as a method
> Redsys Rest: Fix handling of missing CVV

- CHANGELOG
- lib/active_merchant/billing/gateways/merchant_warrior.rb
- test/remote/gateways/remote_merchant_warrior_test.rb
- test/unit/gateways/merchant_warrior_test.rb
Adds the needed fields to support 3DS Global on MerchantWarrior Gateway
[SER-1169](https://spreedly.atlassian.net/browse/SER-1169)
Finished in 70.785752 seconds.
20 tests, 106 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Finished in 37.981802 seconds.
5838 tests, 79224 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> MerchantWarrior: Addding support for 3DS Global fields

- CHANGELOG
- lib/active_merchant/billing/gateways/fat_zebra.rb
- test/remote/gateways/remote_fat_zebra_test.rb
- test/unit/gateways/fat_zebra_test.rb
Adds the needed fields to support 3DS Global on FatZebra Gateway
[SER-1170](https://spreedly.atlassian.net/browse/SER-1170)
Finished in 87.765183 seconds.
29 tests, 101 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
93.1034% passed
*Note Failing Test*: We have to remote tests failing because seems to be a change on the sandbox behavior when a transaction doesn't include a cvv
Finished in 68.736139 seconds.
5808 tests, 78988 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> FatZebra: Adding third-party 3DS params

- CHANGELOG
- lib/active_merchant/billing/gateways/braintree_blue.rb
- test/remote/gateways/remote_braintree_blue_test.rb
- test/unit/gateways/braintree_blue_test.rb
Send merchant_account_id to Verify when it goes through the allow_card_verification == true flow.
Remote:
120 tests, 642 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Unit:
103 tests, 218 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> Braintree: Add merchant_account_id to Verify

- CHANGELOG
- lib/active_merchant/billing/gateways/paymentez.rb
- test/unit/gateways/paymentez_test.rb
[ECS-3370](https://spreedly.atlassian.net/browse/ECS-3370)
This PR updates success_from method on paymentez gateway in order to handle success status on a proper way
Unit tests
Finished in 0.043317 seconds.
30 tests, 127 assertions, 0 failures,
0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote tests
Finished in 140.746551 seconds.
34 tests, 85 assertions, 0 failures,
0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> ECS-3370 Paymentez: Update success_from

- CHANGELOG
- lib/active_merchant/billing/gateways/plexo.rb
- test/remote/gateways/remote_plexo_test.rb
Hardcodes the flow field to be 'direct'.  It is recommended as it could break the payment requests at some point.
Local:
5845 tests, 79178 assertions, 0 failures, 26 errors, 0 pendings, 0 omissions, 0 notifications
99.5552% passed
Unit:
24 tests, 127 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
31 tests, 60 assertions, 0 failures, 0 errors, 0 pendings, 3 omissions, 0 notifications
100% passed
Note: some of the remote tests were experiencing code related errors so I had fixed them in this PR as well.
> Plexo: Add flow field to capture, purchase, and auth

- CHANGELOG
- lib/active_merchant/billing/gateways/pay_trace.rb
- test/unit/gateways/pay_trace_test.rb
If name is present in payment method send even if
billing address is nil.
Unit:
30 tests, 156 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote:
33 tests, 84 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> PayTrace: Always send name in billing_address

- CHANGELOG
- lib/active_merchant/billing/gateways/stripe_payment_intents.rb
- test/remote/gateways/remote_stripe_payment_intents_test.rb
- test/unit/gateways/stripe_payment_intents_test.rb
Update eci format to always be two digits.
Unit:
60 tests, 311 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote:
93 tests, 444 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> StripePI: Update eci format

- CHANGELOG
- lib/active_merchant/billing/gateways/braintree_blue.rb
- test/remote/gateways/remote_braintree_blue_test.rb
ONE-115
The Braintree gateway is a unique AM gateway in that it uses a gateway SDK to transact. The SDK integration maens that all the gateway's params in a given response are not available unless specifically added via the AM adapter.
This commit adds avs_response_code, cvv_response_code, gateway_message, and country_of_issuance to the params in the AM response. This allows for a more standard way of surfacing data for this gateway.
Test Summary
Local:
5841 tests, 79188 assertions, 1 failures, 23 errors, 0 pendings, 0 omissions, 0 notifications 99.5891% passed
Errors/failures related to other gateways
Unit:
103 tests, 218 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote:
120 tests, 646 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, …
> Braintree: Expose data in params

- lib/active_merchant/billing/gateways/datatrans.rb
- test/fixtures.yml
- test/remote/gateways/remote_datatrans_test.rb
- test/unit/gateways/datatrans_test.rb
Summary:
-----
Adding Datatrans gateway with support for basic functionality including authorize, purchase, capture, refund and void. Scrubbing method. Unit and remote tests.
[SER-1193](https://spreedly.atlassian.net/browse/SER-1193)
Tests
-----
Remote Test:
Finished in 18.393965 seconds.
15 tests, 43 assertions, 0 failures, 0 errors, 0 pendings, 1 omissions, 0 notifications 100% passed
Unit Tests:
19 tests, 45 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
RuboCop:
795 files inspected, no offenses detected
> Datatrans: First implementation

- CHANGELOG
- lib/active_merchant/billing/gateways/checkout_v2.rb
- test/remote/gateways/remote_checkout_v2_test.rb
- test/unit/gateways/checkout_v2_test.rb
This changes contains:
- Retain OAuth access token to be used on subsequent transactions and refreshed when it expires
Spreedly reference:
[ECS-2996](https://spreedly.atlassian.net/browse/ECS-2996)
Unit:
66 tests, 403 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
2902.89 tests/s, 17725.19 assertions/s
Remote:
103 tests, 254 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
0.63 tests/s, 1.56 assertions/s
> Checkout V2: Retain and refresh OAuth access token

- lib/active_merchant/billing/gateways/worldpay.rb
- test/remote/gateways/remote_worldpay_test.rb
- test/unit/gateways/worldpay_test.rb
ONE-76
Removes the default ECI value for NT on Worldpay. Per Worldpay's docs on ECI they state
"If you receive an eci value with the token we suggest including in the request". AM should not add a default as that goes against Worldpay's documentation
Docs: https://developerengine.fisglobal.com/apis/wpg/tokenisation/network-payment-tokens
Test Summary
Local:
5840 tests, 79184 assertions, 1 failures, 23 errors, 0 pendings, 0 omissions, 0 notifications 99.589% passed
Tests failing unrelated to this gateway
Remote:
103 tests, 444 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 98.0583% passed
2 errors also failing on master
> Worldpay: Remove default ECI for NT

- CHANGELOG
- lib/active_merchant/billing/gateways/cyber_source.rb
- test/remote/gateways/remote_cyber_source_test.rb
- test/unit/gateways/cyber_source_test.rb
Update NT flow to send cryptogram in networkTokenCryptogram. If it's
a regular transaction commerceIndicator should be internet. If it's a
CIT or MIT commerceIndicator could be installment, recurring or internet
for unscheduled. subsequentAuthStoredCredential should be sent for all
subsequent transactions.
Remote:
136 tests, 676 assertions, 7 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
94.8529% passed
Unit:
158 tests, 941 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Cybersource: Update NT flow

- CHANGELOG
- lib/active_merchant/billing/gateways/litle.rb
- test/unit/gateways/datatrans_test.rb
Ensures we pass a integer to some of the enhanced data fields for visa and mastercard
Local:
5867 tests, 79303 assertions, 0 failures, 7 errors, 0 pendings, 0 omissions, 0 notifications
99.8807% passed
Unit:
59 tests, 264 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
57 tests, 251 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Litle: update the enhanced data field to return integer

- CHANGELOG
- lib/active_merchant/billing/gateways/litle.rb
- test/remote/gateways/remote_litle_test.rb
Local:
5877 tests, 79426 assertions, 0 failures, 7 errors, 0 pendings, 0 omissions, 0 notifications
99.8809% passed
Unit:
59 tests, 264 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
57 tests, 251 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Litle: Fix commodity code placement in enhanced data fields

- CHANGELOG
- lib/active_merchant/billing/gateways/cyber_source_rest.rb
- test/remote/gateways/remote_cyber_source_rest_test.rb
- test/unit/gateways/cyber_source_rest_test.rb
COMP-75
Adds support for Network Tokens on the Cybersource Rest gateway.
Test Summary
Local:
5848 tests, 79228 assertions, 0 failures, 23 errors, 0 pendings, 0 omissions, 0 notifications 99.6067% passed
Errors unrelated to this gateway
Unit:
32 tests, 160 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote:
50 tests, 157 assertions, 7 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 86% passed
Errors also on master
> Cybersource Rest: Support NT

- CHANGELOG
- lib/active_merchant/billing/gateways/decidir.rb
- test/remote/gateways/remote_decidir_test.rb
- test/unit/gateways/decidir_test.rb
This adds support for adding `email` and `id` to the request nested in customer object.
CER-1189
Remote Tests:
26 tests, 92 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 96.1538% passed
*1 remote test also failing on master
Unit Tests:
41 tests, 199 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Local Tests:
5833 tests, 79189 assertions, 4 failures, 1 errors, 0 pendings, 0 omissions, 0 notifications 99.9143% passed
> Decidir: Add support for `customer` object

- lib/active_merchant/billing/gateways/flex_charge.rb
- test/fixtures.yml
- test/remote/gateways/remote_flex_charge_test.rb
- test/unit/gateways/flex_charge_test.rb
This PR adds support for FlexCharge gateway adding the evaluate and refund operations
[SER-1130](https://spreedly.atlassian.net/browse/SER-1130)
Finished in 39.651458 seconds.
12 tests, 40 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
*Note:*
Failing test happens because of account limit on refunds
Finished in 33.453236 seconds.
5855 tests, 79334 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
795 files inspected, no offenses detected
> FlexCharge: Adding support fot FlexCharge gateway

- lib/active_merchant/billing/gateways/securion_pay.rb
- lib/active_merchant/billing/gateways/shift4_v2.rb
- test/remote/gateways/remote_shift4_v2_test.rb
- test/unit/gateways/shift4_v2_test.rb
This PR enables Shift4v2 to implement TPV on Bank accounts and adds support to store CreditCards directly on the 'cards' end-point
[SER-1219](https://spreedly.atlassian.net/browse/SER-1219)
Finished in 52.459288 seconds.
47 tests, 166 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Finished in 40.844376 seconds.
5848 tests, 79304 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Shift4V2: Adding store for bank account and cc

- CHANGELOG
- lib/active_merchant/billing/gateways/worldpay.rb
- test/remote/gateways/remote_worldpay_test.rb
- test/unit/gateways/worldpay_test.rb
COMP-42
Adds tests to ensure stored credentials are passed for network tokens and adds the ability to override the NTID from the standard framework
Test Summary
Local:
5867 tests, 79281 assertions, 0 failures, 23 errors, 0 pendings, 0 omissions, 0 notifications 99.608% passed
Unit:
117 tests, 662 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote:
104 tests, 447 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 98.0769% passed
> Worldpay: Update stored creds

- lib/active_merchant/billing/gateways/datatrans.rb
- test/remote/gateways/remote_datatrans_test.rb
- test/unit/gateways/datatrans_test.rb
Summary:
-----
This PR includes for Datatrans the
NetworkToken, ApplePay and GooglePay code
to perform transactions with that PM
[SER-1195](https://spreedly.atlassian.net/browse/SER-1195)
Tests
-----
Remote Test:
Finished in 23.393965 seconds.
19 tests, 51 assertions, 0 failures, 0 errors, 0 pendings, 1 omissions, 0 notifications 100% passed
Unit Tests:
23 tests, 111 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
RuboCop:
795 files inspected, no offenses detected
> Datatrans: NT, AP, GP support

- CHANGELOG
- lib/active_merchant/billing/gateways/paymentez.rb
- test/unit/gateways/paymentez_test.rb
Update success_from method to take current_status for the first message to evaluate.
If the transaction type is refund the  successful current_status base
on CANCELLED if status is also success
Remote
34 tests, 85 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Unit
33 tests, 137 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> Paymentez: Updates success_from method

- CHANGELOG
- lib/active_merchant/billing/gateways/datatrans.rb
- test/remote/gateways/remote_datatrans_test.rb
- test/unit/gateways/datatrans_test.rb
Summary:
-----
This includes to Datatrans gateway,
the params to required to support
3DS global.
[SER-1197](https://spreedly.atlassian.net/browse/SER-1197)
Tests
-----
Remote Test:
Finished in 24.693965 seconds.
21 tests, 55 assertions, 0 failures, 0 errors, 0 pendings, 1 omissions, 0 notifications 100% passed
Unit Tests:
24 tests, 129 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
RuboCop:
> Datatrans: Add 3DS2 Global

- CHANGELOG
- lib/active_merchant/billing/gateways/flex_charge.rb
- test/remote/gateways/remote_flex_charge_test.rb
- test/unit/gateways/flex_charge_test.rb
Flex Charge: Add support for the TPV store
Test summary:
Local:
5898 tests, 79569 assertions, 0 failures, 17 errors, 0 pendings, 0 omissions, 0 notifications 99.7118% passed
Unit:
12 tests, 58 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote:
13 tests, 34 assertions, 1 failures, 0 errors, 0 pendings, 1 omissions, 0 notifications 91.6667% passed
> Flex Charge: Add support for TPV store

- CHANGELOG
- lib/active_merchant/billing/gateways/checkout_v2.rb
- test/remote/gateways/remote_checkout_v2_test.rb
- test/unit/gateways/checkout_v2_test.rb
This allow us to add the sender object to auth and purchase.
Note: There is a discrepancy with the address fields for recipient and sender. Recipient is expecting address_line1/address_line2. Sender is expecting address1/address2 since sender for for payout is already using those field names. Will have to document this.
Local:
5903 tests, 79624 assertions, 0 failures, 7 errors, 0 pendings, 0 omissions, 0 notifications
99.8814% passed
Unit:
67 tests, 421 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
106 tests, 255 assertions, 4 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
96.2264% passed
> CheckoutV2: add sender object for purchase and auth

- CHANGELOG
- lib/active_merchant/billing/gateways/hi_pay.rb
- test/unit/gateways/hi_pay_test.rb
Description
This commit fixes the parse authorization string when the first value is nil also fixes a issue trying to get the payment_method.brand when the payment method is not a credit card
Unit test
Finished in 0.800901 seconds.
23 tests, 59 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
28.72 tests/s, 73.67 assertions/s
Remote test
Finished in 9.141401 seconds.
1 tests, 6 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
0.11 tests/s, 0.66 assertions/s
Rubocop
795 files inspected, no offenses detected
> HiPay:  Fix parse authorization string

- .rubocop_todo.yml
- CHANGELOG
- lib/active_merchant/billing/gateways/worldpay.rb
- test/remote/gateways/remote_worldpay_test.rb
- test/unit/gateways/worldpay_test.rb
A previous commit removed the default ECI value for NT type payment methods (apple pay, google pay, and network tokens) from the Worldpay integration. This value was previously '07' and added if an ECI was not present. This commit removed the default behavior as this was not compliant with GooglePay standards and Worldpay's documentation indicated it was an option field.
Upon implementing, some merchants have found issues with Mastercard Google Pay transactions lacking an ECI. This is an attempt at an opt-in revert where if a merchant needs to go back to the original commit they can do so by passing in use_default_eci.
Test Summary
Local:
5906 tests, 79606 assertions, 0 failures, 23 errors, 0 pendings, 0 omissions, 0 notifications 99.6106% passed
Unit:
120 tests, 675 assertions, 0 …
> Worldpay: Provide option to use default ECI value

- CHANGELOG
- lib/active_merchant/billing/gateways/cyber_source_rest.rb
- lib/active_merchant/billing/gateways/worldpay.rb
- test/remote/gateways/remote_cyber_source_rest_test.rb
- test/remote/gateways/remote_worldpay_test.rb
- test/unit/gateways/cyber_source_rest_test.rb
- test/unit/gateways/worldpay_test.rb
Worldpay:
Refactor L2/L3 data for Worldpay to be more in line with how active merchant gateways expect this data. It also lowers the burden for what merchants must provide to use L2/L3 data
Test Summary
Local:
5883 tests, 79441 assertions, 0 failures, 23 errors, 0 pendings, 0 omissions, 0 notifications
99.609% passed
Unit:
117 tests, 668 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
103 tests, 444 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
98.0583% passed
Cybersource Rest
Adds support for L2 and L3 data to the Cybersource Rest
Test Summary
Local:
5882 tests, 79430 assertions, 0 failures, 23 errors, 0 pendings, 0 omissions, 0 notifications
99.609% passed
Unit:
36 tests, 189 assertions, 0 failures, 0 errors, 0 …
> Add L2/L3 data for cybersource rest and worldpay

- CHANGELOG
- lib/active_merchant/billing/credit_card.rb
- lib/active_merchant/billing/credit_card_methods.rb
- test/unit/credit_card_methods_test.rb
Description
This commit enable AUTP card type to be used as a valid credit card
Unit test
Finished in 0.041087 seconds.
70 tests, 661 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
1703.70 tests/s, 16087.81 assertions/s
Rubocop
> Add new UATP card type

- CHANGELOG
- lib/active_merchant/version.rb
This is cutting a new version before we update the testing suite to use ruby 3.1
> new version release

- CHANGELOG
- lib/active_merchant/billing/gateways/flex_charge.rb
- test/remote/gateways/remote_flex_charge_test.rb
- test/unit/gateways/flex_charge_test.rb
Changes FlexCharge inquire call to reflect deprecated end-point
[SER-1153](https://spreedly.atlassian.net/browse/SER-1153)
Finished in 38.700031 seconds.
16 tests, 43 assertions, 0 failures, 3 errors, 0 pendings, 1 omissions, 0 notifications
100% passed
Finished in 62.753266 seconds.
5923 tests, 79804 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> FlexCharge: Changes FlexCharge inquire call to reflect deprecated end-point

- CHANGELOG
- lib/active_merchant/billing/gateways/litle.rb
- test/unit/gateways/litle_test.rb
141 and 142 are successful responses for prepaid cards.
Unit:
61 tests, 274 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote:
57 tests, 250 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 98.2456% passed
> Litle: Add 141 and 142 as successful responses

- CHANGELOG
- lib/active_merchant/billing/gateways/braintree_blue.rb
- lib/active_merchant/billing/gateways/worldpay.rb
- test/unit/gateways/braintree_blue_test.rb
- test/unit/gateways/worldpay_test.rb
COMP-160
Adds support for the Braintree Blue and Worldpay gateways for merchants to override and bring their own NTID instead of relying on the standardized NTID framework
Test Summary
Local:
5908 tests, 79610 assertions, 0 failures, 23 errors, 0 pendings, 0 omissions, 0 notifications 99.6107% passed
Unit:
Worldpay:
119 tests, 672 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Braintree:
104 tests, 219 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote:
Worldpay:
104 tests, 447 assertions, 3 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 97.1154% passed
Braintree:
120 tests, 646 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> Braintree and Worldpay: support overriding NTID

- CHANGELOG
- lib/active_merchant/billing/gateways/cyber_source_rest.rb
- test/remote/gateways/remote_cyber_source_rest_test.rb
- test/unit/gateways/cyber_source_rest_test.rb
COMP-78
Refactors the stored credential support for the Cybersource Rest
gateway to be in-line with their documentation. Also repairs test
suite for this gateway by eliminating certain tests and fixing
others.
Test summary:
Local:
5838 tests, 79156 assertions, 2 failures, 23 errors, 0 pendings, 0 omissions, 0 notifications
99.5718% passed
Unit:
30 tests, 144 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
43 tests, 143 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Cybersource Rest: Stored Credential refactor

- CHANGELOG
- lib/active_merchant/billing/gateways/plexo.rb
- test/remote/gateways/remote_plexo_test.rb
- test/unit/gateways/plexo_test.rb
Add support to NetworkToken payments
SER-1240
Test summary:
Local:
5910 tests, 79650 assertions, 0 failures, 17 errors, 0 pendings, 0 omissions, 0 notifications 99.7124% passed
Unit:
25 tests, 134 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote:
32 tests, 36 assertions, 21 failures, 3 errors, 0 pendings, 3 omissions, 0 notifications 17.2414% passed
> Plexo: Add support to NetworkToken payments

- CHANGELOG
- lib/active_merchant/billing/gateways/braintree_blue.rb
- test/remote/gateways/remote_braintree_blue_test.rb
This lets us gracefully return an error code or message from Braintree if the postal zip code is missing.
Local:
5923 tests, 79804 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
103 tests, 218 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
121 tests, 649 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Braintree Blue: Update card verfification payload billing address fields are not present

- CHANGELOG
- lib/active_merchant/billing/gateways/d_local.rb
- test/remote/gateways/remote_d_local_test.rb
- test/unit/gateways/d_local_test.rb
Updates the top level `ip` and `phone` fields to correctly be mapped.
Note: the `onboarding_ip_address` is actually supposed to be within the `addtional_risk_data` object according to [DLocals documention](https://docs.dlocal.com/docs/risk-data-documentation#example-payment-with-additional-risk-data-object). Unsure why we were trying to set it as the `ip` field prior, but it wasn't being used correctly. 
Local:
5932 tests, 79858 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
46 tests, 202 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
40 tests, 110 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> DLocal: update the phone and ip fields

- test/remote/gateways/remote_litle_test.rb
- test/unit/gateways/litle_test.rb
Summary:
Add unit and remote tests for network token
transactions
[SER-1270](https://spreedly.atlassian.net/browse/SER-1270)
Remote Test:
Finished in 88.332434 seconds.
60 tests, 261 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit Test:
Finished in 45.844644 seconds.
5931 tests, 79847 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
RuboCop:
> Litle: Add tests for network tokenization

- lib/active_merchant/billing/gateways/datatrans.rb
- test/remote/gateways/remote_datatrans_test.rb
- test/unit/gateways/datatrans_test.rb
SER-1302
Description
Add support to make verify transactions with authorize and void using a multiresponse thread
Unit test
25 tests, 136 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote test
23 tests, 57 assertions, 2 failures, 0 errors, 0 pendings, 1 omissions, 0 notifications 90.9091% passed
Rubocop
> Datatrans:  Add support for verify transactions

- CHANGELOG
- lib/active_merchant/billing/gateways/checkout_v2.rb
- test/remote/gateways/remote_checkout_v2_test.rb
- test/unit/gateways/checkout_v2_test.rb
This adds the support of sending the risk fields to checkout
Local:
5935 tests, 79871 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
68 tests, 425 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
108 tests, 259 assertions, 4 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
96.2963% passed
> Checkout V2: add support for risk data fields

- CHANGELOG
- lib/active_merchant/billing/gateways/pin.rb
- test/remote/gateways/remote_pin_test.rb
- test/unit/gateways/pin_test.rb
Pin: Update 3DS secure to include new parameters
We have found we cannot use 3DS secure with Pin as the parameters do not match those documented by Pin. This closes #4719. 
Test Summary
Local: 5476 tests, 77236 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit: 44 tests, 145 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 21 tests, 65 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Pin: Update 3DS to include new parameters

- CHANGELOG
- lib/active_merchant/billing/gateways/redsys_rest.rb
- test/remote/gateways/remote_redsys_rest_test.rb
- test/unit/gateways/redsys_rest_test.rb
[ECS-3450](https://spreedly.atlassian.net/browse/ECS-3450)
This PR updates adds stored credendials and 3ds exemptions for redsys rest
Unit tests
Finished in 0.023518 seconds.
28 tests, 118 assertions, 0 failures,
0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote tests
Finished in 33.326868 seconds.
26 tests, 93 assertions, 1 failures,
0 errors, 0 pendings, 0 omissions, 0 notifications 96.1538% passed
0.78 tests/s, 2.79 assertions/s
-> failure not related to changes
> RedsysRest: Add support for stored credentials & 3DS exemptions

- CHANGELOG
- lib/active_merchant/billing/gateways/checkout_v2.rb
- test/remote/gateways/remote_checkout_v2_test.rb
This is to truncate the reference id for Amex auth and purchase transactions. I left the the original add_invoice(post, amount, options) method alone because other types of endpoints utilize it but do not pass the payment_method object. If calling purchase or authorization, and you happen to pass an amex payment method, then the reference id will be overwritten/shortened
Local:
5937 tests, 79881 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
68 tests, 425 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
111 tests, 269 assertions, 4 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
96.3964% passed
> CheckoutV2: truncate the reference id for amex transactions

- lib/active_merchant/billing/gateways/worldpay.rb
- test/remote/gateways/remote_worldpay_test.rb
- test/unit/gateways/worldpay_test.rb
Account Funding Transactions, which Worldpay refers to as "Pull from
Card"
https://staging-developer.fisglobal.com/apis/wpg/manage/pull-from-card
Remote: (10 unrelated failures on master)
110 tests, 443 assertions, 10 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
Unit:
124 tests, 698 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
ECS-3554
> Worldpay: Support AFTs

- CHANGELOG
- lib/active_merchant/billing/gateways/commerce_hub.rb
- test/remote/gateways/remote_commerce_hub_test.rb
This allows us to grab the name from billing address if card holder name is not present. Also fixed apiKey scrubbing and a few tests messages. 2 of the 3 remote test failures were due to "The transaction limit was exceeded. Please try again!" even though i ran the test suite with a sleep of 10 mentioned in the comment.
Local:
5942 tests, 79901 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
28 tests, 194 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
34 tests, 86 assertions, 3 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
91.1765% passed
> CommerceHub: Add billing address name overide

- CHANGELOG
- lib/active_merchant/billing/gateways/stripe_payment_intents.rb
- test/remote/gateways/remote_stripe_payment_intents_test.rb
- test/unit/gateways/stripe_payment_intents_test.rb
This allows us to send the optional moto and confirm on create_setup_intent transactions.
Local:
5945 tests, 79911 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
61 tests, 315 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
94 tests, 425 assertions, 3 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
96.8085% passed
> Stripe PI: add optional ability for 3DS exemption on verify calls

- CHANGELOG
- lib/active_merchant/billing/gateways/orbital.rb
- test/remote/gateways/remote_orbital_test.rb
- test/unit/gateways/orbital_test.rb
If alternate_ucaf_flow is true and the eci value is 4, 6, or 7 then send the ucaf passed in by customer. If alternate_ucaf_flow is not passed then only send ucaf if provided by customer if not pass default of 4.
Remote:
134 tests, 543 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Unit:
152 tests, 892 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> Orbital: Update to accept UCAF Indicator GSF

- lib/active_merchant/billing/gateways/flex_charge.rb
- test/remote/gateways/remote_flex_charge_test.rb
- test/unit/gateways/flex_charge_test.rb
Changes FlexCharge to add support for the authorize and capture operations and also a fix a bug on the `address_names` method
[SER-1337](https://spreedly.atlassian.net/browse/SER-1337) 
[SER-1324](https://spreedly.atlassian.net/browse/SER-1324)
Finished in 72.283834 seconds.
19 tests, 54 assertions, 1 failures, 0 errors, 0 pendings, 1 omissions, 0 notifications
94.4444% passed
Finished in 43.11362 seconds.
5944 tests, 79908 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> FlexCharge: Adding authorize-capture functionality

- CHANGELOG
- lib/active_merchant/billing/gateways/cyber_source.rb
- test/remote/gateways/remote_cyber_source_test.rb
- test/unit/gateways/cyber_source_test.rb
Adds the merchant_descriptor_city and submerchant_id fields
Local:
5944 tests, 79910 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
159 tests, 945 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
136 tests, 675 assertions, 7 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
94.8529% passed
> CyberSource: Add addtional invoiceHeader fields

- lib/active_merchant/billing/gateways/cyber_source.rb
- lib/active_merchant/billing/gateways/cyber_source_rest.rb
- test/unit/gateways/cyber_source_rest_test.rb
- test/unit/gateways/cyber_source_test.rb
CER-1567
Sends code '058' for carnet card type in legacy CyberSource and CyberSource REST gateways
Local Tests
5947 tests, 79917 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
CyberSource Legacy
Unit Tests
160 tests, 946 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote Tests
136 tests, 676 assertions, 7 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
94.8529% passed
*7 tests also failing on master
CyberSource REST
Unit Tests
40 tests, 216 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote Tests
52 tests, 171 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> CyberSource: bugfix - send correct card type/code for carnet

- CHANGELOG
- lib/active_merchant/billing/gateways/merchant_warrior.rb
- test/unit/gateways/merchant_warrior_test.rb
Updae customerPhone to grab phone from phone or phone_number in options. If address doesn't contain ip and email then grab them directly from options. Add new field called storeID.
Unit:
29 tests, 164 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote:
20 tests, 106 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> MerchantWarrior: Update phone, email, ip and store_ID

- CHANGELOG
- lib/active_merchant/billing/gateways/credorax.rb
- test/remote/gateways/remote_credorax_test.rb
- test/unit/gateways/credorax_test.rb
Update so that if a 3DS version starts with 2 it doesn't default to 2.0 but on what is passed in for the three_ds_version field.
Unit:
82 tests, 394 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote:
51 tests, 173 assertions, 6 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 88.2353% passed
> Credorax: Update 3DS version mapping

- lib/active_merchant/billing/gateways/flex_charge.rb
- test/remote/gateways/remote_flex_charge_test.rb
- test/unit/gateways/flex_charge_test.rb
Changes FlexCharge to fix support for the void operation.
[SER-1327](https://spreedly.atlassian.net/browse/SER-1327)
Finished in 70.477035 seconds.
19 tests, 54 assertions, 0 failures, 0 errors, 0 pendings, 1 omissions, 0 notifications
100% passed
Finished in 124.425603 seconds.
5959 tests, 79971 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> FlexCharge: quick fix on void call

- lib/active_merchant/billing/gateways/flex_charge.rb
- test/unit/gateways/flex_charge_test.rb
Fix bug where `add_payment_method` was incorrectly returned early if the payment value was a token
> FlexCharge fix `add_payment_method` bug

- CHANGELOG
- lib/active_merchant/billing/gateways/braintree_blue.rb
- test/remote/gateways/remote_braintree_blue_test.rb
- test/unit/gateways/braintree_blue_test.rb
Update Stored Credential flow to keep v2.
Unit:
104 tests, 219 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote:
123 tests, 661 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> Braintree: Remove stored credential v1

- lib/active_merchant/billing/gateways/plexo.rb
- test/remote/gateways/remote_plexo_test.rb
- test/unit/gateways/plexo_test.rb
Description
[SER-1377](https://spreedly.atlassian.net/browse/SER-1377)
This commit update the previous implementation of NT in order to use network token instead if card
Unit test
Finished in 0.033159 seconds.
25 tests, 137 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
753.94 tests/s, 4131.61 assertions/s
Remote test
32 tests, 50 assertions, 0 failures, 0 errors, 0 pendings, 9 omissions, 0 notifications 100% passed
Rubocop
> Plexo: Update Network Token implementation

- lib/active_merchant/billing/gateways/nmi.rb
- test/remote/gateways/remote_nmi_test.rb
- test/unit/gateways/nmi_test.rb
Description
This commit add support to create transaction with GooglePay and ApplePay.
This payment methods are working for nmi_secure.
[SER-1295](https://spreedly.atlassian.net/browse/SER-1295)
Unit test
Finished in 11.283174 seconds.
59 tests, 475 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
5.23 tests/s, 42.10 assertions/s
Remote test
Finished in 115.513346 seconds.
55 tests, 199 assertions, 12 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
78.1818% passed
0.48 tests/s, 1.72 assertions/s
Rubocop
> NMI: Adding GooglePay and ApplePay

- CHANGELOG
- lib/active_merchant/billing/gateways/braintree/token_nonce.rb
- lib/active_merchant/billing/gateways/braintree_blue.rb
- test/remote/gateways/remote_braintree_token_nonce_test.rb
Summary:
Add merchant_account_id for the Client Token Generate and returns a string which contains all authorization and configuration information that the client needs to initialize the client SDK to communicate with Braintree
[ECS-3617](https://spreedly.atlassian.net/browse/ECS-3617) [ECS-3607](https://spreedly.atlassian.net/browse/ECS-3607)
Remote Test:
Finished in 6.262003 seconds.
7 tests, 15 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
1.12 tests/s, 2.40 assertions/s
Unit Tests:
Finished in 38.744354 seconds.
5956 tests, 79952 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
153.73 tests/s, 2063.58 assertions/s …
> Braintree: Pass overridden mid into client token for GS 3DS

- CHANGELOG
- lib/active_merchant/billing/gateways/moneris.rb
- test/unit/gateways/moneris_test.rb
Update crypt_type to only be one digit by removing leading zero if present.
Unit:
54 tests, 294 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote:
53 tests, 259 assertions, 0 failures, 0 errors, 0 pendings, 1 omissions, 0 notifications 100% passed
> Moneris: Update crypt_type for 3DS

- CHANGELOG
- lib/active_merchant/billing/gateways/checkout_v2.rb
- test/unit/gateways/checkout_v2_test.rb
Update CheckoutV2 3DS message & error code to keep waht was bening threed_response_message
Unit:
67 tests, 420 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote:
111 tests, 274 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> Update CheckoutV2 3DS message & error code

- lib/active_merchant/billing/gateways/flex_charge.rb
- test/remote/gateways/remote_flex_charge_test.rb
- test/unit/gateways/flex_charge_test.rb
FlexCharge: quick fix on void call
[SER-1386](https://spreedly.atlassian.net/browse/SER-1386)
Finished in 70.477035 seconds.
19 tests, 54 assertions, 0 failures, 0 errors, 0 pendings, 1 omissions, 0 notifications
100% passed
Finished in 124.425603 seconds.
5959 tests, 79971 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> SER-1386 add ExtraData and Source GSFs

- lib/active_merchant/billing/gateways/flex_charge.rb
- test/remote/gateways/remote_flex_charge_test.rb
- test/unit/gateways/flex_charge_test.rb
Including shipping address if provided and fix idempotency key to default to random UUID.
[SER-1387](https://spreedly.atlassian.net/browse/SER-1387) 
[SER-1338](https://spreedly.atlassian.net/browse/SER-1338)
Finished in 77.783815 seconds.
20 tests, 56 assertions, 0 failures, 0 errors, 0 pendings, 1 omissions, 0 notifications
100% passed
Finished in 46.32943 seconds.
5963 tests, 79998 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> SER-1387 and SER-1338 fix shipping address and idempotency key

- lib/active_merchant/billing/gateways/datatrans.rb
- test/remote/gateways/remote_datatrans_test.rb
- test/unit/gateways/datatrans_test.rb
Summary:
Include Store and Unstore Methods in Datatrans
gateway to support Third Party Token.
[SER-1395](https://spreedly.atlassian.net/browse/SER-1395)
Tests
Remote Test:
Finished in 31.477035 seconds.
25 tests, 72 assertions, 0 failures, 0 errors, 0 pendings, 1 omissions, 0 notifications
100% passed
Unit Tests:
Finished in 0.115603 seconds.
29 tests, 165 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Rubocop
> Datatrans: Add TPV

- lib/active_merchant/billing/gateways/rapyd.rb
- test/remote/gateways/remote_rapyd_test.rb
- test/unit/gateways/rapyd_test.rb
CER-1613
Top level boolean field that will trigger payment method to be saved.
Remote Tests:
54 tests, 152 assertions, 3 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 94.4444% passed
* I fixed a few failing tests, so less failing on master.
Also, more of them seem fixable but I started to gown down a docs rabbit hole that is not in the scope of this ticket.
> Rapyd: Add support for save_payment_method field

- lib/active_merchant/billing/gateways/datatrans.rb
- test/unit/gateways/datatrans_test.rb
Summary:
Modify the string for store to be separated by '|' instead of '-'.
SER-1395
Tests
Remote Test:
Finished in 31.477035 seconds.
25 tests, 72 assertions, 0 failures, 0 errors, 0 pendings, 1 omissions, 0 notifications 100% passed
Unit Tests:
Finished in 0.115603 seconds.
29 tests, 165 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Rubocop
> Datatrans: Modify authorization_from string for store

- CHANGELOG
- lib/active_merchant/billing/gateways/decidir_plus.rb
- test/unit/gateways/decidir_plus_test.rb
Add safety navigator to error_message to prevent NoMethod errors and create a validation_error_message to construct a new error message.
> DecidirPlus: Update error_message to add safety navigator

- lib/active_merchant/billing/gateways/elavon.rb
- test/unit/gateways/elavon_test.rb
Only skip CVV if stored credentials is being used and it's not an initial transaction.
> Elavon: Update cvv for stored credential

- CHANGELOG
- lib/active_merchant/billing/gateways/adyen.rb
- test/unit/gateways/adyen_test.rb
This adds the header fields and values to the response body object in the parse method. By using the handle_response override, we can set an instance variable of the headers and merge it into the response body. The 12 remote test failures are also the same ones that fail on the master branch. 
Local:
5961 tests, 79980 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
120 tests, 630 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
144 tests, 471 assertions, 12 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
> Adyen: Add header fields to response body

- CHANGELOG
- lib/active_merchant/billing/gateways/stripe.rb
- test/remote/gateways/remote_stripe_payment_intents_test.rb
- test/remote/gateways/remote_stripe_test.rb
- test/unit/gateways/stripe_payment_intents_test.rb
- test/unit/gateways/stripe_test.rb
This adds some of the header fields to the response body object using the handle_response override.
Local:
5962 tests, 79990 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Stripe unit:
146 tests, 769 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Stripe remote:
77 tests, 328 assertions, 10 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
87.013% passed
Stripe PI Unit:
61 tests, 315 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Stripe PI Remote:
95 tests, 427 assertions, 3 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
96.8421% passed
> Stripe and Stripe PI: add headers to response body

- activemerchant.gemspec
- test/unit/gateways/mercury_test.rb
- test/unit/gateways/paypal_test.rb
- test/unit/gateways/trans_first_test.rb
This resolves [CVE-2024-39908 : DoS in REXML](https://www.ruby-lang.org/en/news/2024/07/16/dos-rexml-cve-2024-39908/)
This vulnerability is showing up in bundle-audit. 
```
Name: rexml
Version: 3.2.8
CVE: CVE-2024-39908
Criticality: Unknown
URL: https://github.com/ruby/rexml/security/advisories/GHSA-4xqq-m2hx-25v8
Title: DoS in REXML
Solution: upgrade to '>= 3.3.2'
Name: rexml
Version: 3.3.2
CVE: CVE-2024-41123
Criticality: Unknown
URL: https://www.ruby-lang.org/en/news/2024/08/01/dos-rexml-cve-2024-41123
Title: DoS vulnerabilities in REXML
Solution: upgrade to '>= 3.3.3'
Name: rexml
--
  | Version: 3.2.8
  | CVE: CVE-2024-41946
  | Criticality: Unknown
  | URL: https://www.ruby-lang.org/en/news/2024/08/01/dos-rexml-cve-2024-41946
  | Title: DoS vulnerabilities in REXML
  | Solution: …
```
> Upgrade rexml to 3.3.4 to address CVE-2024-39908, 41123, 41946

- CHANGELOG
- lib/active_merchant/billing/gateways/mercury.rb
- lib/active_merchant/billing/gateways/trans_first.rb
- test/unit/gateways/mercury_test.rb
- test/unit/gateways/trans_first_test.rb
A previous commit broke these gateways after updating REXML. This commit updates the two gateways so that they can process the XML like it used to.
Test Summary
Remote:
No credentials available for Mercury
Could not reach the test server for TransFirst
> Repair Mecury and TransFirst

- CHANGELOG
- lib/active_merchant/billing/gateways/nmi.rb
- test/remote/gateways/remote_nmi_test.rb
- test/unit/gateways/nmi_test.rb
Description
[SER-1402](https://spreedly.atlassian.net/browse/SER-1402)
This commit adds a small fix to send the proper decrypted indicator respectively for Apple Pay and Google Pay.
Additionally, adds some remote tests for successful Apple/Google transactions without sending the billing address.
Unit test
Finished in 0.017629 seconds.
6 tests, 21 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
340.35 tests/s, 1191.22 assertions/s
Remote test
Finished in 30.626119 seconds.
19 tests, 50 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
0.62 tests/s, 1.63 assertions/s
Rubocop
801 files inspected, no offenses …
> NMI: Fix Decrypted indicator for Google/Apple pay

- CHANGELOG
- lib/active_merchant/billing/gateways/braintree_blue.rb
- test/remote/gateways/remote_braintree_blue_test.rb
- test/unit/gateways/braintree_blue_test.rb
Do not add default payment method to customer if prevent_default_payment_method is true. Add paypal_payment_token to transaction_hash.
123 tests, 662 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> BraintreeBlue: Updates to Paypal integration

- CHANGELOG
- lib/active_merchant/billing/gateways/stripe.rb
- test/remote/gateways/remote_stripe_payment_intents_test.rb
- test/remote/gateways/remote_stripe_test.rb
This change swaps the add metadata line for refund and void with the add_metadata helper method. Before, we were just adding the entire options[:metadata] object but skipping the order_id. This corrects that to send order_id
Local:
5981 tests, 80146 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Stripe Unit:
147 tests, 777 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Stripe Remote:
78 tests, 333 assertions, 10 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
87.1795% passed
Stripe PI Unit:
62 tests, 319 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Stripe PI Remote:
95 tests, 430 assertions, 3 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications …
> Stripe/StripePI: update add metadata for refund and void

- CHANGELOG
- lib/active_merchant/billing/gateways/adyen.rb
- test/remote/gateways/remote_adyen_test.rb
This change allows us to return "NA" instead of nil for street address and house or number address if address_override is set to true.
Local:
5985 tests, 80165 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
121 tests, 635 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
144 tests, 465 assertions, 12 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
> Adyen: Fix billing address empty string error

- CHANGELOG
- lib/active_merchant/billing/gateways/adyen.rb
- test/remote/gateways/remote_adyen_test.rb
- test/unit/gateways/adyen_test.rb
[ECS-3530](https://spreedly.atlassian.net/browse/ECS-3530)
This PR fix format error using NT
Unit tests
Finished in 0.126432 seconds.
121 tests, 641 assertions, 0 failures,
0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote tests
Finished in 609.957316 seconds.
143 tests, 464 assertions, 11 failures,
0 errors, 0 pendings, 0 omissions, 0 notifications 92.3077% passed
0.23 tests/s, 0.76 assertions/s
-> failures not related to change
> ECS-3530 Adyen Format error fix

- CHANGELOG
- lib/active_merchant/billing/gateways/hps.rb
- test/remote/gateways/remote_hps_test.rb
- test/unit/gateways/hps_test.rb
Update NetworkTokenizationCreditCArd flow to now be under WalletData.
Remote
58 tests, 155 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 96.5517% passed
Unit
61 tests, 295 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> HPs: Update NetworkTokenizationCreditCard flow

- CHANGELOG
- lib/active_merchant/billing/gateways/braintree_blue.rb
- test/unit/gateways/braintree_blue_test.rb
COMP-266
ActiveMerchant currently uses Class.application_id or @options[:channel] to let merchants pass platform BN codes to gateways to signify that a transaction may be going to one merchant's accounts but it originates from a platform or aggregator.
This poses a problem in that the Class value is assigned at compile time and the @options[:channel] refers to a static value used when initializing the class.
This commit adds support for `override_application_id` which is a way for aggregators to pass in a new BN code at transaction time alongside transaction parameters.
Test Summary
Remote:
123 tests, 661 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Cannot add a remote test because there is no generic `channel` value
> Braintree: Support override_application_id

- CHANGELOG
- lib/active_merchant/billing/gateways/decidir.rb
- test/unit/gateways/decidir_test.rb
This changes will allow CVV, card number, exp month and exp year.
Remote
27 tests, 97 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> Decidir: Pass CVV for NT

- lib/active_merchant/billing/gateways/mercado_pago.rb
- test/remote/gateways/remote_mercado_pago_test.rb
- test/unit/gateways/mercado_pago_test.rb
MercadoPago adding needed fields to mark a transaction to request 3DS flow.
[SER-1226](https://spreedly.atlassian.net/browse/SER-1226)
Finished in 79.263845 seconds.
20 tests, 56 assertions, 0 failures, 0 errors, 0 pendings, 1 omissions, 0 notifications
100% passed
Finished in 43.253318 seconds.
5981 tests, 80141 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> MercadoPago: Adding 3DS gateway specific fields

- CHANGELOG
- lib/active_merchant/billing/gateways/nmi.rb
- test/remote/gateways/remote_nmi_test.rb
- test/unit/gateways/nmi_test.rb
This allows us to send customer vault fields on purchase, authorize, and verify endpoints for securely storing customer's payment information for later use. If customer_vault field is sent with 'add_customer' and no customer_vault_id is present, NMI will auto generate one and echo it back in the response.
Local:
5986 tests, 80170 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
60 tests, 484 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
61 tests, 241 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
98.3607% passed
> NMI: add customer vault fields

- CHANGELOG
- lib/active_merchant/billing/gateways/iveri.rb
- test/remote/gateways/remote_iveri_test.rb
If the transaction to be voided is an Authorization then use AuthReversal instead of Void.
Remote
22 tests, 56 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 95.4545% passed
Unit
16 tests, 67 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> Iveri: Add AuthReversal for Authorizations

- lib/active_merchant/billing/gateways/decidir.rb
- test/remote/gateways/remote_decidir_test.rb
- test/unit/gateways/decidir_test.rb
Update scrubbing cryptogram in Prod since they add / in prod from cryptogram and we only want to scrub
the token in token_card_data
> Decidir: Update scrubbing cryptogram and token

- lib/active_merchant/billing/gateways/nuvei.rb
- test/fixtures.yml
- test/remote/gateways/remote_nuvei_test.rb
- test/unit/gateways/nuvei_test.rb
Description
[SER-1351](https://spreedly.atlassian.net/browse/SER-1351)
This commit add a the basic structure for the new Nuvei Gateway
Unit test
Finished in 0.124334 seconds.
1 tests, 2 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
8.04 tests/s, 16.09 assertions/s
Remote test
Finished in 0.602895 seconds.
1 tests, 2 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
1.66 tests/s, 3.32 assertions/s
Rubocop
> Nuvei: Base Gateway Layout

- CHANGELOG
- lib/active_merchant/billing/gateways/mercado_pago.rb
- test/remote/gateways/remote_mercado_pago_test.rb
- test/unit/gateways/mercado_pago_test.rb
Adds the idempotency key to the headers of a request. Decided to use an instance variable to store the idempotency key (if provided) so that there is less wrangling of the options object and changes to the endpoint methods.
Local:
5995 tests, 80210 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
45 tests, 209 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
45 tests, 107 assertions, 17 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
62.2222% passed
Note: the tests failing are msotly due to payer email related issues.
> Mercado Pago: add idempotency key field

- lib/active_merchant/billing/gateways/nuvei.rb
- test/remote/gateways/remote_nuvei_test.rb
- test/unit/gateways/nuvei_test.rb
Nuvei: Base Gateway Layout
[SER-1349](https://spreedly.atlassian.net/browse/SER-1349) [SER-1350](https://spreedly.atlassian.net/browse/SER-1350) [SER-1348](https://spreedly.atlassian.net/browse/SER-1348)
This commit add the basic operation for Nuvei such as Purchase, refund, void and general credit
Finished in 68.576328 seconds.
6003 tests, 80235 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Finished in 37.911283 seconds.
17 tests, 46 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
0.45 tests/s, 1.21 assertions/s
> Nuvei: Adding basic operations

- CHANGELOG
- lib/active_merchant/billing/gateways/adyen.rb
- test/unit/gateways/adyen_test.rb
Remote
143 tests, 464 assertions, 11 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 92.3077% passed
> Adyen: Remove raw_error_message

- CHANGELOG
- lib/active_merchant/billing/gateways/elavon.rb
- test/remote/gateways/remote_elavon_test.rb
- test/unit/gateways/elavon_test.rb
Remote:
40 tests, 178 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 95% passed
> Elavon: Remove old Stored Credential method

- CHANGELOG
- lib/active_merchant/billing/gateways/pay_trace.rb
- test/remote/gateways/remote_pay_trace_test.rb
Update MulitResponse for Capture to pass
:use_first_response. This will correctly
populate authorization.
> PayTrace: Update MultiResponse for Capture

- CHANGELOG
- lib/active_merchant/billing/gateways/adyen.rb
- test/remote/gateways/remote_adyen_test.rb
- test/unit/gateways/adyen_test.rb
Remote
146 tests, 469 assertions, 12 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 91.7808% passed
If it is a Pan Only GooglePay then pass 'paymentdatasource.type and selectedBrand as googlepay and paymentdatasource.tokenized as false
> Adyen: Add support for Pan Only GooglePay

- CHANGELOG
- lib/active_merchant/billing/gateways/decidir.rb
- test/unit/gateways/decidir_test.rb
Summary:
Decidir - Send expiration_month and expiration_year fields in request for tokenized NT transactions.
Spreedly reference:
[ECS-3682](https://spreedly.atlassian.net/browse/ECS-3682)
[UBI-150](https://spreedly.atlassian.net/browse/UBI-150)
Remote Test:
Loaded suite test/remote/gateways/remote_decidir_test Started
Finished in 49.764098 seconds.
27 tests, 97 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
0.54 tests/s, 1.95 assertions/s
Unit Tests:
Finished in 32.823471 seconds.
5991 tests, 80194 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
182.52 tests/s, 2443.19 assertions/s
RuboCop: …
> Decidir - Send extra fields for tokenized NT transactions

- lib/active_merchant/billing/gateways/adyen.rb
- lib/active_merchant/billing/network_tokenization_credit_card.rb
- test/unit/gateways/adyen_test.rb
unit:
124 tests, 655 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
remote:
143 tests, 462 assertions, 13 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 90.9091% passed (Same store and unstore failures as master branch)
> Updated the Adyen NT and stored credential flow.

- CHANGELOG
- lib/active_merchant/billing/gateways/stripe_payment_intents.rb
- test/remote/gateways/remote_stripe_payment_intents_test.rb
- test/unit/gateways/stripe_payment_intents_test.rb
Summary:
StripePI: Skip add_network_token_cryptogram_and_eci method to accept ApplePay recurring payments and add unit/remote tests
[SER-3618](https://spreedly.atlassian.net/browse/ECS-3618)
Remote Test:
Loaded suite test/remote/gateways/remote_stripe_payment_intents_test
Started
Finished in 255.69074 seconds.
97 tests, 460 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
0.38 tests/s, 1.80 assertions/s
Unit Tests:
Finished in 29.539052 seconds.
5993 tests, 80199 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
202.88 tests/s, 2715.02 assertions/s
RuboCop:
798 files inspected, no offenses …
> StripePI: Skip add_network_token_cryptogram_and_eci method to accept ApplePay recurring payments

- CHANGELOG
- lib/active_merchant/billing/gateways/cyber_source.rb
- lib/active_merchant/billing/gateways/cyber_source_rest.rb
- test/remote/gateways/remote_cyber_source_rest_test.rb
- test/remote/gateways/remote_cyber_source_test.rb
- test/unit/gateways/cyber_source_rest_test.rb
- test/unit/gateways/cyber_source_test.rb
Update code sent for carnet card type
CER-1718
CyberSource
Unit
161 tests, 956 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote
137 tests, 681 assertions, 7 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 94.8905% passed
*7 tests also failing on master
CyberSource REST
Unit
40 tests, 216 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote
53 tests, 176 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> CyberSource and CyberSourceRest: update carnet card type

- CHANGELOG
- lib/active_merchant/billing/gateways/stripe_payment_intents.rb
- test/remote/gateways/remote_stripe_payment_intents_test.rb
- test/unit/gateways/stripe_payment_intents_test.rb
[Stripe changelog entry announcing the new field](https://docs.stripe.com/changelog#december-20,-2023)
CER-1717
LOCAL
6007 tests, 80257 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed;
RUBOCOP
Inspecting 801 files
UNIT
62 tests, 321 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
REMOTE
95 tests, 454 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> Stripe PI: Add challenge as valid value for request_three_d_secure

- lib/active_merchant/billing/gateways/mercado_pago.rb
- test/remote/gateways/remote_mercado_pago_test.rb
- test/unit/gateways/mercado_pago_test.rb
MercadoPago only sending platform/partnership info on production.
Finished in 79.263845 seconds.
20 tests, 56 assertions, 0 failures, 0 errors, 0 pendings, 1 omissions, 0 notifications
100% passed
Finished in 68.455283 seconds.
6012 tests, 80277 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> MercadoPago: Sending sponsor_id only on production

- lib/active_merchant/billing/gateways/plexo.rb
- test/remote/gateways/remote_plexo_test.rb
- test/unit/gateways/plexo_test.rb
Summary:
For NT transactions we must pass the Bin and the last4 digits of the underlying PAN, otherwise we can't pass it currently we where passing those values based in the NT number instead of PAN ones, and due we don't have the underlying PAN, those lines are unnecesary.
Remote Tests:
Finished in 44.017128 seconds.
32 tests, 65 assertions, 0 failures, 0 errors, 0 pendings, 3 omissions, 0 notifications 100% passed
Unit Tests:
Finished in 0.040727 seconds.
25 tests, 140 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Rubocop
798 files, no offenses detected
> Plexo: remove Bin and Last4 fields from NetworkToken

- CHANGELOG
- lib/active_merchant/billing/gateways/stripe_payment_intents.rb
- test/remote/gateways/remote_stripe_payment_intents_test.rb
- test/unit/gateways/stripe_payment_intents_test.rb
Remote:
98 tests, 462 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
If the payment methods is GooglePay FPAN which would be treated as a CreditCard then add metadata.input_method as GooglePay.
> StripePI: Add metadata for GooglePay FPAN

- CHANGELOG
- lib/active_merchant/billing/gateways/paypal/paypal_common_api.rb
- test/remote/gateways/remote_paypal_test.rb
Add inquire method to get the latest status
on a transaction.
Remote
31 tests, 87 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> Paypal: Add inquire method

- CHANGELOG
- lib/active_merchant/billing/gateways/adyen.rb
- test/remote/gateways/remote_adyen_test.rb
- test/unit/gateways/adyen_test.rb
The original implementation of the `leg` field assumes that there will be one `leg` hash provided, but based on [Adyen's documentation](https://docs.adyen.com/payment-methods/cards/enhanced-scheme-data/airline/), the flexibility to send multiple legs (leg1, leg2, etc.) is required
CER-1738
LOCAL
6016 tests, 80319 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
RUBOCOP
UNIT
127 tests, 691 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
REMOTE
147 tests, 471 assertions, 12 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 91.8367% passed
> Adyen: Enable multiple legs within airline data

- CHANGELOG
- lib/active_merchant/billing/gateways/safe_charge.rb
- test/remote/gateways/remote_safe_charge_test.rb
- test/unit/gateways/safe_charge_test.rb
This change adds the optional middle_name and card_holder_verification fields
Local:
6017 tests, 80326 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
31 tests, 176 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
35 tests, 93 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
94.2857% passed
> SafeCharge: add card holder verification fields

- CHANGELOG
- lib/active_merchant/billing/gateways/iveri.rb
- test/remote/gateways/remote_iveri_test.rb
If a Authorization transaction needs to be voided then AuthorisationReversal needs to be used instead of Void.
22 tests, 58 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> Iveri: Add AuthorisationReversal for Auth Void

- CHANGELOG
- lib/active_merchant/billing/gateways/stripe_payment_intents.rb
- test/remote/gateways/remote_stripe_payment_intents_test.rb
- test/unit/gateways/stripe_payment_intents_test.rb
Update Stored Credentials to only send NTID if
stored_credential_transaction_type is
setup_off_session_unscheduled or setup_off_session_recurring.
Remote:
96 tests, 457 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> StripePI: Update Stored Credentials

- lib/active_merchant/billing/gateways/decidir.rb
- test/remote/gateways/remote_decidir_test.rb
- test/unit/gateways/decidir_test.rb
This will allow all NT transactions to pass CVV if present.
Remote
27 tests, 97 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Decidir: Remove pass_cvv_for_nt

- CHANGELOG
- lib/active_merchant/billing/gateways/ebanx.rb
- test/remote/gateways/remote_ebanx_test.rb
- test/unit/gateways/ebanx_test.rb
Remote
39 tests, 95 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 94.8718% passed
> Ebanx: Add support for Stored Credentials

- CHANGELOG
- lib/active_merchant/billing/gateways/nuvei.rb
- test/remote/gateways/remote_nuvei_test.rb
- test/unit/gateways/nuvei_test.rb
Description
This commit add store and stored credentials for Nuvei Gateway
[SER-1357](https://spreedly.atlassian.net/browse/SER-1357)
Unit test
Finished in 0.034584 seconds.
9 tests, 30 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
260.24 tests/s, 867.45 assertions/s
Remote test
Finished in 59.543749 seconds.
23 tests, 69 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
0.39 tests/s, 1.16 assertions/s
Rubocop
> Nuvei: Add store and stored credentials

- CHANGELOG
- lib/active_merchant/billing/gateways/shift4.rb
- test/remote/gateways/remote_shift4_test.rb
- test/unit/gateways/shift4_test.rb
The response object returned from the Shift4 gateway seems to have changed `hostResponse` to `hostresponse` around August 26th, which causes all failed auth/purchase transactions to default to the fallback message of "Transaction declined"
This commit corrects the parsing to account for this change but also leaves `hostResponse` as an option, in case the change is reverted by Shift4 in the future.
Assertions were added to show that the refactoring still provides correct values for both `message` and `error_code` for the various response structures we receive. Shift4 does not return a `host(r/R)esponse` object in sandbox testing, so we have to rely on unit tests here.
CER-1740
LOCAL
6018 tests, 80340 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
801 …
> Shift4: Update response parsing to account for hostresponse

- CHANGELOG
- lib/active_merchant/billing/gateways/nmi.rb
- test/remote/gateways/remote_nmi_test.rb
- test/unit/gateways/nmi_test.rb
Transactions on NMI could fail if this industry field is not provided. This field is not documented publicly on NMI.
Unit: 61 tests, 487 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 62 tests, 247 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
98.3871% passed
> NMI: Add `industry_indicator` field

- CHANGELOG
- lib/active_merchant/billing/gateways/decidir.rb
- test/unit/gateways/decidir_test.rb
Summary:
Map the undocumented error code -1 to processing_error for better formatting in the response.
Remote Test:
27 tests, 97 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Unit Tests:
6017 tests, 80324 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
RuboCop:
> Decidir: Map error code -1 to processing_error

- lib/active_merchant/billing/gateways/sum_up.rb
- test/remote/gateways/remote_sum_up_test.rb
- test/unit/gateways/sum_up_test.rb
For merchants that need to pass an identifier that the source of the transaction originates from their platform, they can pass this value which will be prepended to the `order_id` and passed along as the `checkout_reference`
Unit: 10 tests, 32 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote: 11 tests, 20 assertions, 5 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
54.5455% passed
Note: Some of the remote tests are failing, unrelated to changes in this PR. SumUP echo's back the `checkout_reference` so we can easily validate that the one we pass in the request by checking the response.
> SumUp: Append partner_id to checkout_reference

- CHANGELOG
- lib/active_merchant/billing/gateways/cenpos.rb
Allows test mode transactions to point to https://abistaging.cenpos.net/6/transact.asmx
CER-1772
LOCAL
6039 tests, 80494 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
UNIT
23 tests, 98 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
REMOTE
22 tests, 56 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> CenPOS: Add test_url

- CHANGELOG
- lib/active_merchant/billing/gateways/worldpay.rb
- test/unit/gateways/worldpay_test.rb
[OPPS-8](https://spreedly.atlassian.net/browse/OPPS-8)
Update generate_stored_credential_params function to fix issue on stored credentials reason
Unit tests
Finished in 0.562645 seconds
124 tests, 698 assertions, 0 failures, 
0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed 
220.39 tests/s, 1240.57 assertions/s
Remote tests
Finished in 113.845584 seconds
110 tests, 466 assertions, 2 failures, 
0 errors, 0 pendings, 0 omissions, 0 notifications 98.1818% passed
0.97 tests/s, 4.09 assertions/s
-> failure not related to change
> Worldpay: Fix stored credentials issue

- CHANGELOG
- lib/active_merchant/billing/gateways/stripe.rb
- lib/active_merchant/billing/gateways/stripe_payment_intents.rb
- test/unit/gateways/stripe_payment_intents_test.rb
If the transaction that failes was created through the create_intent or setup_purchase endpoint then we will grab response.dig('error', 'payment_intent', 'id') if present.
99 tests, 469 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> StripePI: Update authorization for failed Payment Intents

- CHANGELOG
- lib/active_merchant/billing/gateways/worldpay.rb
- test/remote/gateways/remote_worldpay_test.rb
- test/unit/gateways/worldpay_test.rb
[COMP-73](https://spreedly.atlassian.net/jira/software/projects/COMP/boards/195?selectedIssue=COMP-73)
Adds support for Apple Pay MIT recurring
**Unit:**
125 tests, 702 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
**Remote:**
111 tests, 479 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
98.1982% passed
> Worldpay: Support apple pay recurring

- CHANGELOG
- lib/active_merchant/billing/gateways/cyber_source_rest.rb
- test/remote/gateways/remote_cyber_source_rest_test.rb
- test/unit/gateways/cyber_source_rest_test.rb
[COMP-72](https://spreedly.atlassian.net/browse/COMP-72)
Adds support for Apple Pay recurring
Test Summary
Remote Test:
Finished in 28.189687 seconds.
6030 tests, 80342 assertions, 0 failures, 23 errors, 0 pendings, 0 omissions, 0 notifications
99.6186% passed
Unit Tests:
Finished in 0.670757 seconds.
41 tests, 223 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
RuboCop:
> CyberSourceRest: Support Apple Pay recurring

- gemfiles/Gemfile.rails_master
This is a temporary fix to allow for our gha tests to run while we work on updating the ruby version of AM to >= 3.2.0.
Hopefully that version update will be fairly simple and we can get back to truly testing rails master shortly, but it doesn't make sense to let not run gha tests on pull requests while we work on that.
> update active support version for rails master test

- CHANGELOG
- lib/active_merchant/billing/gateways/cyber_source_rest.rb
- test/unit/gateways/cyber_source_rest_test.rb
Add dig to message_from and error_code_from to prevent NoMethod errors.
Remote
53 tests, 176 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> CybersourceRest: Update message and error_code

- CHANGELOG
- lib/active_merchant/billing/gateways/paysafe.rb
- test/remote/gateways/remote_paysafe_test.rb
- test/unit/gateways/paysafe_test.rb
This allows a network transaction id obtained from a third party transaction to be passed in and maintain MIT transactions without interruptions.
Remote Tests:
35 tests, 86 assertions, 9 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 74.2857% passed
*I fixed one remote test that was failing due to changed error message, but the rest are failing on master as well
Unit Tests:
20 tests, 101 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> Paysafe: Add `external_initial_transaction_id`

- CHANGELOG
- lib/active_merchant/billing/gateways/worldpay.rb
- test/remote/gateways/remote_worldpay_test.rb
- test/unit/gateways/worldpay_test.rb
These fields are included as part of FraudSightData in auth/purchase requests https://docs.worldpay.com/apis/wpg/fraudsightglobal/fraudsightdirect
CER-1766
LOCAL
6040 tests, 80501 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
UNIT
125 tests, 705 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
REMOTE
112 tests, 473 assertions, 3 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 97.3214% passed
> Worldpay: Add customStringFields

- CHANGELOG
- lib/active_merchant/billing/gateways/d_local.rb
- test/remote/gateways/remote_d_local_test.rb
- test/unit/gateways/d_local_test.rb
Opens up the description field to be also be available on refund as it was only used for auth and purchase
Local:
6046 tests, 80532 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
47 tests, 205 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
41 tests, 115 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> DLocal: add the description field for refund

- CHANGELOG
- lib/active_merchant/billing/gateways/orbital.rb
- test/unit/gateways/orbital_test.rb
Update UCAFInd to only be passed if the ECI value is 4, 6 or 7.
Remote
134 tests, 543 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> Orbital: Update alternate_ucaf_flow

- CHANGELOG
- lib/active_merchant/billing/gateways/cecabank/cecabank_json.rb
- test/remote/gateways/remote_cecabank_rest_json_test.rb
- test/unit/gateways/cecabank_rest_json_test.rb
Summary
This commit implement Apple Pay and Google Pay payment methods the unit and remote tests, and fix few faling tests in current implementation.
[SER-1431](https://spreedly.atlassian.net/browse/SER-1431)
Unit Tests:
Finished in 0.031554 seconds.
20 tests, 106 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote Tests:
Finished in 20.386373 seconds.
20 tests, 69 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 95% passed
Rubocop
> CecabankRest: Add AP/GP

- CHANGELOG
- lib/active_merchant/billing/gateways/d_local.rb
- test/remote/gateways/remote_d_local_test.rb
- test/unit/gateways/d_local_test.rb
Remote
40 tests, 110 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> DLocal: Add X-Dlocal-Payment-Source to header

- CHANGELOG
- lib/active_merchant/billing/gateways/stripe.rb
- lib/active_merchant/billing/gateways/stripe_payment_intents.rb
- lib/active_merchant/billing/gateways/webpay.rb
- test/unit/gateways/stripe_payment_intents_test.rb
Update retrieve_setup_intent to be a GET request and update idempotency_key to only be passed in headers if it for a POST request
Stripe PI
Remote:
99 tests, 469 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Unit:
67 tests, 350 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Stripe
Remote:
79 tests, 377 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Unit:
147 tests, 777 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> StripePI: Update to retrieve_setup_intent and headers

- CHANGELOG
- lib/active_merchant/billing/gateways/nuvei.rb
- test/remote/gateways/remote_nuvei_test.rb
- test/unit/gateways/nuvei_test.rb
Description
[SER-1356](https://spreedly.atlassian.net/browse/SER-1356)
This commit enable partial approval for payment sending a GSF flag
Unit test
Finished in 0.010615 seconds.
1 tests, 3 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
94.21 tests/s, 282.62 assertions/s
Remote test
Finished in 37.737084 seconds.
18 tests, 50 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
0.48 tests/s, 1.32 assertions/s
Rubocop
> Nuvei: Add partial approval feature

- CHANGELOG
- lib/active_merchant/billing/gateways/nuvei.rb
- test/remote/gateways/remote_nuvei_test.rb
- test/unit/gateways/nuvei_test.rb
Description
[SER-1403](https://spreedly.atlassian.net/browse/SER-1403)
This commit add ACH transaction for Nuvei
Unit test
Finished in 0.010487 seconds
10 tests, 34 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
53.56 tests/s, 3242.11 assertions/s
Remote test
Finished in 36.783565 seconds.
18 tests, 48 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
0.49 tests/s, 1.30 assertions/s
Rubocop
> Nuvei: Add ACH support

- CHANGELOG
- lib/active_merchant/billing/gateways/nuvei.rb
- test/remote/gateways/remote_nuvei_test.rb
- test/unit/gateways/nuvei_test.rb
Description
[SER-1462](https://spreedly.atlassian.net/browse/SER-1462)
This commit add authenticationOnlyType as GSF for a verify request
Unit test
Finished in 0.009788 seconds.
18 tests, 99 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
1838.99 tests/s, 10114.43 assertions/s
Remote test
Finished in 121.496082 seconds.
28 tests, 87 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
0.23 tests/s, 0.72 assertions/s
Rubocop
> Nuvei:  Add GSF for verify method

- CHANGELOG
- lib/active_merchant/billing/gateways/adyen.rb
- test/remote/gateways/remote_adyen_test.rb
- test/unit/gateways/adyen_test.rb
This adds the optional manual_capture field for auth and capture
Local:
6063 tests, 80613 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
129 tests, 697 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
147 tests, 470 assertions, 12 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
91.8367% passed
> Adyen: add the manual_capture field

- CHANGELOG
- lib/active_merchant/billing/gateways/adyen.rb
- test/remote/gateways/remote_adyen_test.rb
- test/unit/gateways/adyen_test.rb
Enabling of recurring_detail_reference gateway specific field in other transactions like purchase or refund for Adyen Gateway
[OPPS-9](https://spreedly.atlassian.net/browse/OPPS-9)
Finished in 0.118443 seconds.
130 tests, 701 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Finished in 178.393637 seconds.
148 tests, 498 assertions, 5 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
96.6216% passed
Failure tests not related to changes
> Enabling of recurring_detail_reference gateway specific field in other transactions

- CHANGELOG
- lib/active_merchant/billing/gateways/adyen.rb
- test/remote/gateways/remote_adyen_test.rb
- test/unit/gateways/adyen_test.rb
Update skip_mpi_data to not pass MPI data if it's
a NetworkTokenizationCreditCard and stored_credential_initiator of merchant. It will also be skipped if shopper_interation is ContAuth and recurring_processing_model is Subscription.
Remote
147 tests, 470 assertions, 12 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 91.8367% passed
> Adyen: Update skip_mpi_data

- CHANGELOG
- lib/active_merchant/billing/gateways/cyber_source.rb
- test/remote/gateways/remote_cyber_source_test.rb
- test/unit/gateways/cyber_source_test.rb
Update order of XML fields for add_auth_service with this new order aggregatorID, reconciliationID, firstRecurringPayment and mobileRemotePaymentType can now be passed for NetworkTokenizationCreditCard.
> Cybersource: Update order of XML fields

- lib/active_merchant/billing/gateways/worldpay.rb
- test/unit/gateways/worldpay_test.rb
Fixing a problem when customer initiates transaction with master card and stored credentials, the schemeTransactionIdentifier must not retrieve a value avoiding a possible generated error for this reason
[OPPS-151](https://spreedly.atlassian.net/browse/OPPS-151)
Finished in 0.357197 seconds.
132 tests, 736 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Finished in 250.382481 seconds.
114 tests, 489 assertions, 3 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
Failure tests not related to changes
> Validation added in Worldpay to avoid scheme transaction identifier when customer started transaction

- CHANGELOG
- lib/active_merchant/billing/gateways/stripe.rb
- lib/active_merchant/billing/gateways/stripe_payment_intents.rb
- test/remote/gateways/remote_stripe_payment_intents_test.rb
- test/unit/gateways/stripe_payment_intents_test.rb
This makes it easier to return the 3d secured supported filed especially during multi requests to stripe PI
Local:
6064 tests, 80619 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
68 tests, 356 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
100 tests, 448 assertions, 3 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
97% passed
> This grabs and sets the 3d secured supported field when running a verify

- CHANGELOG
- lib/active_merchant/billing/gateways/stripe_payment_intents.rb
- test/remote/gateways/remote_stripe_payment_intents_test.rb
- test/unit/gateways/stripe_payment_intents_test.rb
For some transactions and payment methods, the `options[:last_4]` will not be prepopluated, so we need to look in the `payment_method` to slice the last 4 from the number
Remote: 100 tests, 472 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit: 68 tests, 357 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Rubocop:
nick-mbp:active_merchant nick$ bundle exec rubocop
Inspecting 804 files
........................................................................................................................................................................................................................................................................................................................................... …
> StripePI: Last4 From Payment Method

- CHANGELOG
- lib/active_merchant/billing/gateways/decidir.rb
- lib/active_merchant/billing/gateways/decidir_plus.rb
- test/remote/gateways/remote_decidir_plus_test.rb
- test/remote/gateways/remote_decidir_test.rb
Add card map for patagonia_365 to pass payment id to gateway
Reference: https://developers.payway.com.ar/docs/gateway/3jw3eiapx1jwu-medios-de-pago
> Decidir: Patagonia365 Card Type Mapping

- CHANGELOG
- lib/active_merchant/billing/gateways/d_local.rb
- test/remote/gateways/remote_d_local_test.rb
- test/unit/gateways/d_local_test.rb
Adds the optional country field override
Local:
6104 tests, 80829 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
8 tests, 209 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
42 tests, 118 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> DLocal: add country override optional field

- CHANGELOG
- lib/active_merchant/billing/gateways/nuvei.rb
- test/remote/gateways/remote_nuvei_test.rb
- test/unit/gateways/nuvei_test.rb
Description
[SER-1457](https://spreedly.atlassian.net/browse/SER-1457)
This commit add Account funding transaction (AFT) for Nuvei
Unit test
Finished in 0.090215 seconds.
19 tests, 104 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
210.61 tests/s, 1152.80 assertions/s
Remote test
Finished in 105.744939 seconds.
29 tests, 90 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
0.27 tests/s, 0.85 assertions/s
Rubocop
> Nuvei:  Adding account founding transaction

- CHANGELOG
- lib/active_merchant/billing/gateways/nuvei.rb
- test/remote/gateways/remote_nuvei_test.rb
- test/unit/gateways/nuvei_test.rb
Description
[SER-1456](https://spreedly.atlassian.net/browse/SER-1456)
This commit add Cardholder name verification for request with transation type "Auth"
Unit test
Finished in 0.082292 seconds.
23 tests, 123 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
279.49 tests/s, 1494.68 assertions/s
Remote test
Finished in 131.369427 seconds.
33 tests, 101 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
0.25 tests/s, 0.77 assertions/s
Rubocop
> Nuvei: Add card holder name verification params

- lib/active_merchant/billing/gateways/commerce_hub.rb
- test/remote/gateways/remote_commerce_hub_test.rb
Making a mapping update mapping from to ~~serviceProviderTransactionId~~ to serverTransactionId
Spreedly reference: OPPS-192
> CommerceHub - Update three_ds_server_trans_id assignation to serverTransactionId field for 3ds_global

- CHANGELOG
- lib/active_merchant/billing/gateways/litle.rb
- test/unit/gateways/litle_test.rb
Add response codes to list of successful transactions
Remote tests
--------------------------------------------------------------------------
60 tests, 207 assertions, 21 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
65% passed --> Failures due to sandbox malfunction
unit tests
--------------------------------------------------------------------------
63 tests, 285 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Litle: Success codes added to valid responses

- CHANGELOG
- lib/active_merchant/billing/gateways/worldpay.rb
- test/unit/gateways/worldpay_test.rb
Update add_stored_credential_using_normalized_fields to
only send usage: 'USED' with merchantInitiatedReason and
only send reason if it's recurring or installment.
Unit:
133 tests, 741 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
114 tests, 489 assertions, 3 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
> Worldpay: Update Stored Credentials

- CHANGELOG
- lib/active_merchant/billing/gateways/redsys_rest.rb
- test/remote/gateways/remote_redsys_rest_test.rb
- test/unit/gateways/redsys_rest_test.rb
Summary
This add suppor for NetworkTokenizedCreditCard with redsys
Enhance Scrubbing method
Unit Tests
Finished in 0.029745 seconds.
28 tests, 124 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote Tests
Finished in 34.288085 seconds.
29 tests, 108 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
96.5517% passed
Rubocop
803 files inspected, no offenses detected
> RedsysRest: add NetworToken

- CHANGELOG
- lib/active_merchant/billing/gateways/d_local.rb
- test/unit/gateways/d_local_test.rb
For Void transaction a successful request would have status_code of 400 and status of Cancelled
Remote
42 tests, 118 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Unit
50 tests, 216 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> DLocal: Update the success_from for Void

- CHANGELOG
- lib/active_merchant/billing/gateways/braintree_blue.rb
- test/remote/gateways/remote_braintree_blue_test.rb
- test/unit/gateways/braintree_blue_test.rb
Description:
We removed the ECI In the BraintreeBlue active merchant adapter, when the stored_credential[:initiator] == 'merchant' in google pay and Apple Pay recurring payments
Rubocop:
Unit:
108 tests, 226 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
125 tests, 670 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> COMP-71 AP recurring braintree_blue

- CHANGELOG
- lib/active_merchant/billing/gateways/flex_charge.rb
- test/unit/gateways/flex_charge_test.rb
Description
This is a small commit to update the homepage url
for FlexCharge Gateway
Unit test
28 tests, 125 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote test
Finished in 75.763065 seconds.
20 tests, 56 assertions, 0 failures, 0 errors, 0 pendings, 1 omissions, 0 notifications 100% passed
Rubocop
> FlexCharge: Update homePage url

- CHANGELOG
- lib/active_merchant/billing/gateways/nuvei.rb
- test/remote/gateways/remote_nuvei_test.rb
- test/unit/gateways/nuvei_test.rb
Description
This commit send by default savePM in false if save_payment_method GSF is not included in the request, only we send true for store request.
[SER-1539](https://spreedly.atlassian.net/browse/SER-1539)
Unit test
28 tests, 143 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote test
42 tests, 136 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Rubocop
803 files inspected, no offenses detected
> Nuvei: Fix send savePM in false by default

- CHANGELOG
- lib/active_merchant/billing/gateways/decidir.rb
- lib/active_merchant/billing/gateways/decidir_plus.rb
- test/remote/gateways/remote_decidir_plus_test.rb
- test/remote/gateways/remote_decidir_test.rb
- test/unit/gateways/decidir_plus_test.rb
- test/unit/gateways/decidir_test.rb
Local:
6119 tests, 80836 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Decidir Unit:
46 tests, 223 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Decidir Remote:
29 tests, 99 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
93.1034% passed
Decidir Plus Unit:
20 tests, 84 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Decidir Plus Remote:
28 tests, 85 assertions, 5 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
82.1429% passed
> Add the wallet_id field for decidir gateways

- Rakefile
- lib/active_merchant/billing/gateways/fortis.rb
- lib/active_merchant/connection.rb
- lib/active_merchant/net_http_ssl_connection.rb
- lib/active_merchant/posts_data.rb
- test/fixtures.yml
- test/remote/gateways/remote_fortis_test.rb
- test/unit/gateways/fortis_test.rb
Summary:
Fortis Gateway initial implementation with support for:
- Authorize
- Purchase
- Void
- Capture
- Refund
- Credit
- Store
- Unstore
There is an issue with the Fortis API because their back-end returns an "invalid credentials" error if the HTTP Request headers are not in lower-case format, but Ruby by default follows the [HTTP 1.1 RFC 2616 ](https://datatracker.ietf.org/doc/html/rfc2616#page-31:~:text=an%0A%20%20%20extra%20CRLF.-,4.2,-Message%20Headers%0A%0A%20%20%20HTTP) on how to handle headers; Ruby camellize all headers from something like 'user-api-key' to 'User-Api-Key', that is performed by [Net::HTTPHeader#capitalize](https://github.com/ruby/net-http/blob/master/lib/net/http/header.rb#L493), so to deal with that we had to find a way to force …
> Fortis: Initial implementation

- CHANGELOG
- lib/active_merchant/billing/gateways/worldpay.rb
- test/remote/gateways/remote_worldpay_test.rb
- test/unit/gateways/worldpay_test.rb
For NetworkTokens shopperIPAddress should be passed after the stored credentials fields. And for Fast Access transactions shopperIPAddress should be passed within paymentDetails
Remote
117 tests, 498 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 98.2906% passed
Unit
134 tests, 743 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> Worldpay: Update where to pass shopperIPAddress

- CHANGELOG
- lib/active_merchant/billing/gateways/braintree_blue.rb
- test/unit/gateways/braintree_blue_test.rb
Take into account Braintree::ErrorResult for add_bank_account_to_customer to prevent NoMethodError
Unit:
108 tests, 231 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed 
Remote:
123 tests, 662 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> Braintree: Account for BraintreeError

- CHANGELOG
- lib/active_merchant/billing/gateways/worldpay.rb
- test/unit/gateways/worldpay_test.rb
Description
Unscheduled reason type should be sent in customer and merchant initiated transactions, except when it's a customer initiated transaction and usage=USED.
Unit tests
6119 tests, 80834 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote tests
114 tests, 489 assertions, 3 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 97.3684% passed
Failures not related to changes.
Rubocop
803 files inspected, no offenses detected
> Worldpay: Fix stored credentials unscheduled reason type

- CHANGELOG
- lib/active_merchant/billing/gateways/stripe.rb
- lib/active_merchant/billing/gateways/stripe_payment_intents.rb
- test/remote/gateways/remote_stripe_payment_intents_test.rb
- test/unit/gateways/stripe_payment_intents_test.rb
Update version to 2022-11-15 and charges to be
latest_charge. latest_charge is no longer
automatically expanded andwill only be expanded
if the repsonse is succesful.
Remote
99 tests, 463 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 98.9899% passed
> StripePI: Update version to 2022-11-15

- CHANGELOG
- lib/active_merchant/billing/gateways/worldpay.rb
- test/remote/gateways/remote_worldpay_test.rb
- test/unit/gateways/worldpay_test.rb
Finished in 0.418613 seconds.
138 tests, 756 assertions, 0 failures, 0 errors, 
100% passed
Finished in 118.498554 seconds.
117 tests, 500 assertions, 0 failures, 0 errors, 
100% passed
> OPPS-225 Worldpay Idempotency key fix

- CHANGELOG
- lib/active_merchant/billing/gateways/hi_pay.rb
- test/remote/gateways/remote_hi_pay_test.rb
Description
When `:execute_threed` was present but `:three_ds_2` wasn't, it would cause an error. This fix makes it return early when `:three_ds_2` is missing.
Relevant docs:
- https://support.hipay.com/hc/en-us/articles/213882649-How-can-I-test-payment-methods
- https://developer.hipay.com/api-explorer/api-online-payments#/payments/requestNewOrder
Unit tests
6120 tests, 80841 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote tests
20 tests, 85 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Rubocop
803 files inspected, no offenses detected
> Hi Pay: Don't add 3ds when :three_ds_2 is missing

- lib/active_merchant/billing/gateways/fortis.rb
- test/remote/gateways/remote_fortis_test.rb
- test/unit/gateways/fortis_test.rb
Add neded changes to support reference authorize/purchase + supporting location_id as GSF for store
Finished in 181.033884 seconds.
25 tests, 58 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Finished in 49.78482 seconds.
6143 tests, 80932 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Fortis: Adding Verify + Reference Purchase

- lib/active_merchant/billing/gateways/nuvei.rb
- test/remote/gateways/remote_nuvei_test.rb
- test/unit/gateways/nuvei_test.rb
Description
[SER-1545](https://spreedly.atlassian.net/browse/SER-1545)
This commit fixes the storedCredentials hash in order to send it under the card object
Unit test
Finished in 1.340614 seconds.
28 tests, 147 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
20.89 tests/s, 109.65 assertions/s
Remote test
Finished in 124.620111 seconds.
43 tests, 139 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
0.35 tests/s, 1.12 assertions/s
Rubocop
> Nuvei: Fix stored credentials hash

- lib/active_merchant/billing/gateways/credorax.rb
- test/remote/gateways/remote_credorax_test.rb
- test/unit/gateways/credorax_test.rb
This change allows the `cardholder_name_inquiry` flag to be sent. If set to true, it will trigger first and last name data to be sent for c22, and c23. $0 auth transactions to validate cards also require the value for a9 to be set to 5.
Remote Tests:
52 tests, 176 assertions, 6 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 88.4615% passed
*6 failing tests also failing on master
Unit Tests
83 tests, 399 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> Credorax: Add support for gateway card validation

- lib/active_merchant/billing/gateways/nuvei.rb
- test/remote/gateways/remote_nuvei_test.rb
- test/unit/gateways/nuvei_test.rb
Description
[SER-1543](https://spreedly.atlassian.net/browse/SER-1543)
This commit update the AFT request to support non-domestic AFT
Unit test
Finished in 1.325061 seconds.
28 tests, 148 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
21.13 tests/s, 111.69 assertions/s
Remote test
Finished in 116.599139 seconds.
42 tests, 136 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
0.36 tests/s, 1.17 assertions/s
Rubocop
> Nuvei: Update AFT request

- CHANGELOG
- lib/active_merchant/billing/gateways/secure_pay_au.rb
- test/remote/gateways/remote_secure_pay_au_test.rb
- test/unit/gateways/secure_pay_au_test.rb
**Changelog:** SecurePayAU: Send order ID for payments with stored cards
Order IDs were being sent for normal payments, but now they are also sent for payments triggered on stored cards as `transactionReference`.
As per XML spec (https://auspost.com.au/payments/docs/securepay/resources/API_Card_Storage_and_Scheduled_Payments.pdf )
Also:
- Fixed broken remote tests
- Send content-type headers for best practice
Unit test results:
test/unit/gateways/secure_pay_au_test.rb
24 tests, 106 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote test results: 
test/remote/gateways/remote_secure_pay_au_test.rb
18 tests, 57 assertions, 0 failures, 0 errors, 0 pendings, 2 omissions, 0 notifications
100% passed
> SecurePayAU: Send order ID for payments with stored card

- lib/active_merchant/billing/gateways/adyen.rb
- test/remote/gateways/remote_adyen_test.rb
- test/unit/gateways/adyen_test.rb
This adds the shopperEmail to fundingSource object and adds the fundingDestination destination field. Previously, we only used fundingSource for payouts but I've added these 2 fields to the authorize endpoint for AFT related transactions
Local:
6145 tests, 80954 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
134 tests, 717 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
149 tests, 474 assertions, 12 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
91.9463% passed
> Add the fundingDestination field and fundingSource to authorize call

- CHANGELOG
- lib/active_merchant/billing/gateways/priority.rb
- test/unit/gateways/priority_test.rb
Description
Send 8 digits for bin lookups instead of 7.
Unit tests
6157 tests, 80984 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote tests
31 tests, 84 assertions, 5 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 83.871% passed
Failures not related to changes
Rubocop
> Priority: fix for bin lookup

- CHANGELOG
- lib/active_merchant/billing/gateways/commerce_hub.rb
- test/remote/gateways/remote_commerce_hub_test.rb
Update merchantTransactionId to be a random number and merchantInvoiceNumber to be the order_id. Remove account_verification, primary_transaction_type and merchant_invoice_number since they are not in use.
Remote 36 tests, 97 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 97.2222% passed
> CommerceHub: Update merchantInvoiceNumber & merchantTransactionId

- CHANGELOG
- lib/active_merchant/billing/gateways/checkout_v2.rb
- lib/active_merchant/billing/response.rb
- test/remote/gateways/remote_checkout_v2_test.rb
- test/unit/gateways/checkout_v2_test.rb
Add metadata to Credit and pending as a field for response. Set pending to true for CheckoutV2 if a Credit returns status of Pending.
Remote 113 tests, 282 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Unit:
67 tests, 420 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> CheckoutV2: Add metadata to Credit

- CHANGELOG
- lib/active_merchant/billing.rb
- lib/active_merchant/billing/gateway.rb
- lib/active_merchant/billing/gateways/adyen.rb
- lib/active_merchant/billing/gateways/braintree_blue.rb
- lib/active_merchant/billing/gateways/global_collect.rb
- lib/active_merchant/versionable.rb
- test/unit/gateways/adyen_test.rb
- test/unit/gateways/braintree_blue_test.rb
- test/unit/gateways/global_collect_test.rb
- test/unit/versionable_test.rb
Summary:
This change centralizes version management at the class level, creating a consistent and reusable way to define and access API versions.
Unit Tests:
6154 tests, 80974 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
RuboCop:
> Normalize API versions

- lib/active_merchant/billing/gateways/nuvei.rb
- test/remote/gateways/remote_nuvei_test.rb
- test/unit/gateways/nuvei_test.rb
Description
[SER-1568](https://spreedly.atlassian.net/browse/SER-1568)
This commit fixes a 3DS transaction issue when three_ds_2 data is null. Additionally, some remote test were failing due some changes in the Nuvei Api, so this commit inlcude a round_down method to fix remote tests.
Unit test
Finished in 1.349927 seconds.
29 tests, 161 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
21.48 tests/s, 119.27 assertions/s
Remote test
Finished in 270.209319 seconds.
43 tests, 139 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
0.16 tests/s, 0.51 assertions/s
Rubocop
> Nuvei: Fix 3ds transaction

- CHANGELOG
- lib/active_merchant/billing/gateways/ebanx.rb
- test/remote/gateways/remote_ebanx_test.rb
- test/unit/gateways/ebanx_test.rb
This change adds the notification_url field to the add_addtional_data helper method for purchase and authorization
local:
6169 tests, 81065 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
29 tests, 148 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
remote:
44 tests, 100 assertions, 7 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
84.0909% passed
Seems like the tests that failed remotely had to do with card types, here are the messages: "Payment type not enabled in full mode for merchant:"
> Ebanx: add the optional notification_url field

- CHANGELOG
- lib/active_merchant/billing/gateways/worldpay.rb
- test/remote/gateways/remote_worldpay_test.rb
- test/unit/gateways/worldpay_test.rb
Remote
118 tests, 504 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> Worldpay: Update passing 3DS data for NT

- CHANGELOG
- lib/active_merchant/billing/gateways/ebanx.rb
- test/remote/gateways/remote_ebanx_test.rb
- test/unit/gateways/ebanx_test.rb
Adds the optional merchant_payment_code override
Local:
6178 tests, 81154 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
33 tests, 163 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
45 tests, 102 assertions, 7 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
84.4444% passed
> Ebanx: Add the merchant_payment_code override

- CHANGELOG
- lib/active_merchant/billing/gateways/credorax.rb
- test/remote/gateways/remote_credorax_test.rb
- test/unit/gateways/credorax_test.rb
Adds the s( sender) field for aft transactions while also re-using the j (recipient)fields for purchase and authorize.
Local:
6168 tests, 81069 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
84 tests, 417 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
55 tests, 195 assertions, 6 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
89.0909% passed
The failing tests are 3ds related. I dont believe its due to my changes.
> Add AFT fields for credorax

- lib/active_merchant/billing/gateways/secure_pay_au.rb
- test/remote/gateways/remote_secure_pay_au_test.rb
- test/unit/gateways/secure_pay_au_test.rb
This is another feature that we've been using, in production since June 2021. 
This method was copied from similar NabTransactGateway, but placed at the top of the file because it contains a default value.
```
rake test TEST=test/unit/gateways/secure_pay_au_test.rb 
26 tests, 112 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 
100% passed
rake test TEST=test/remote/gateways/remote_secure_pay_au_test.rb 
18 tests, 57 assertions, 0 failures, 0 errors, 0 pendings, 2 omissions, 0 notifications 
100% passed
```
~~Although the [wiki says not to](https://github.com/activemerchant/active_merchant/wiki/Submitting-Your-Gateway#best-practices), I've added a CHANGELOG line because that's what was asked for on my [last …
> SecurePayAU: Allow custom request_timeout

- lib/active_merchant/billing/gateways/adyen.rb
- test/remote/gateways/remote_adyen_test.rb
- test/unit/gateways/adyen_test.rb
CER-2023
This field is an object that expects data specific to Japanese branded cards and the ja-Kana character set. If localized shopper statement is not provided it will default to shopper statement in authorize transaction types.
For refund and capture, it is sent through as part of additional data and will likely not display on credit card statements for that reason.
Unit Tests
138 tests, 731 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote Tests
152 tests, 481 assertions, 12 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 92.1053% passed
*12 tests also failing on master
> Adyen: Add support for localized shopper statement

- CHANGELOG
- lib/active_merchant/billing/gateways/cashnet.rb
- test/unit/gateways/cashnet_test.rb
Updating maxx_retries to 1 ensures that retries are not attempt which was the original purpose of setting max_retries in this gateway
Remote
8 tests, 36 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 75% passed
> Cashnet: Update max_retries to 1

- CHANGELOG
- lib/active_merchant/billing/gateways/airwallex.rb
- lib/active_merchant/billing/gateways/credorax.rb
- test/remote/gateways/remote_airwallex_test.rb
- test/unit/gateways/airwallex_test.rb
Local:
6189 tests, 81209 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
36 tests, 196 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
29 tests, 67 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
93.1034% passed
> Update authorization_from method so that refunds will have the payment_intent_id

- lib/active_merchant/billing/gateways/worldpay.rb
- test/remote/gateways/remote_worldpay_test.rb
- test/unit/gateways/worldpay_test.rb
Adds AFT fields to auth and purchase.
CER-2069
Unit Tests
140 tests, 771 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote Tests
122 tests, 490 assertions, 11 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 90.9836% passed
*11 tests also failing on master
> Worldpay: Add AFT support to Authorize and Purchase transaction types

- lib/active_merchant/billing/gateways/adyen.rb
- test/unit/gateways/adyen_test.rb
shopperInteraction should be Ecommerce if
shopper_interaction is in options and
initiator is cardholder.
Remote:
149 tests, 474 assertions, 12 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 91.9463% passed
> Adyen: Update shopperInteraction

- CHANGELOG
- lib/active_merchant/billing/credit_card.rb
- lib/active_merchant/billing/credit_card_methods.rb
- test/unit/credit_card_methods_test.rb
Description
[SER-1604](https://spreedly.atlassian.net/browse/SER-1604)
This commit rename the card type for tarjeta sol
to 'tarjeta_sol' instead 'sol'
Unit test
Finished in 0.155089 seconds.
76 tests, 672 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
490.04 tests/s, 4333.00 assertions/s
Rubocop
> Tarjeta sol: Rename card type name

- lib/active_merchant/billing/gateways/worldpay.rb
- test/remote/gateways/remote_worldpay_test.rb
- test/unit/gateways/worldpay_test.rb
CER-2099
Prevents sending middle name and address2 in request if no values are present. Fields are optional but should not be sent empty.
Unit Tests
141 tests, 778 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote Tests
123 tests, 497 assertions, 11 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 90.9836% passed
*11 tests also failing on master
> Worldpay: AFT middle name address2 bugfix

- CHANGELOG
- lib/active_merchant/billing/gateways/nuvei.rb
- test/remote/gateways/remote_nuvei_test.rb
- test/unit/gateways/nuvei_test.rb
Description
[SER-1617](https://spreedly.atlassian.net/browse/SER-1617)
This commit sends `ísRebilling`  field only for MIT transactions, 
set "0" when is init MIT or "1" for subsequent MIT
Unit test
Finished in 1.482941 seconds.
34 tests, 180 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
22.93 tests/s, 121.38 assertions/s
Remote test
Finished in 601.986719 seconds.
45 tests, 150 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
0.07 tests/s, 0.25 assertions/s
Rubocop
> Nuvei: Fix isRebilling flag for Stored credentials

- lib/active_merchant/billing/gateways/flex_charge.rb
- test/remote/gateways/remote_flex_charge_test.rb
- test/unit/gateways/flex_charge_test.rb
Fixing issue that happend when `token_expires` is store like an string on core:
[UBI-276](https://spreedly.atlassian.net/browse/UBI-276)
Finished in 118.763803 seconds.
21 tests, 64 assertions, 0 failures, 0 errors, 0 pendings, 2 omissions, 0 notifications
100% passed
0.18 tests/s, 0.54 assertions/s
Finished in 60.312398 seconds.
6199 tests, 81237 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> FlexCharge: Fixing bug on session_expire

- CHANGELOG
- lib/active_merchant/billing/gateways/decidir.rb
- lib/active_merchant/billing/gateways/decidir_plus.rb
- test/unit/gateways/decidir_plus_test.rb
- test/unit/gateways/decidir_test.rb
Description
[SER-1607](https://spreedly.atlassian.net/browse/SER-1607)
This commit handles the card type specific values for Tarjeta Sol in Decidir and Decidir Plus gateways.
Unit test
Decidir
-------------
Finished in 0.0462 seconds.
47 tests, 230 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
1017.32 tests/s, 4978.35 assertions/s
Decidir Plus
--------------
Finished in 0.020998 seconds.
21 tests, 88 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
1000.10 tests/s, 4190.88 assertions/s
Remote test
Decidir
-------------
Finished in 53.9379 seconds.
29 tests, 99 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications …
> Tarjeta Sol: Update tarjeta_sol support for Decidir and Decidir plus

- lib/active_merchant/billing/gateways/cecabank/cecabank_json.rb
- test/unit/gateways/cecabank_rest_json_test.rb
Summary
This format the ECI value to return 0#{number} in the case
the number is only 1 digit.
[SER-1619](https://spreedly.atlassian.net/browse/SER-1619)
Unit Tests
Finished in 0.032173 seconds.
21 tests, 111 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote Tests
Finished in 0.168569 seconds.
21 tests, 111 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
Rubocop
> Fix Cecabank ApplePay Eci Error

- CHANGELOG
- lib/active_merchant/billing/gateways/shift4.rb
- test/unit/gateways/shift4_test.rb
Add a interface_name field which will be used
to populate interfaceName.
Remote
29 tests, 67 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> Shift4: Add interface_name field

- lib/active_merchant/billing/gateways/worldpay.rb
- test/remote/gateways/remote_worldpay_test.rb
CER-2099
Update authorize request to include AFT fields when 3DS is invoked.
> Worldpay: update authorize request for AFT

- CHANGELOG
- lib/active_merchant/billing/gateways/stripe_payment_intents.rb
- test/remote/gateways/remote_stripe_payment_intents_test.rb
- test/unit/gateways/stripe_payment_intents_test.rb
This change adds the optional AFT fields, specifically the sender and recipient fields.
Local:
6205 tests, 81261 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
70 tests, 388 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
102 tests, 453 assertions, 3 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
97.0588% passed
Note: I have this implemented to bail out of the helper method if none of the 4 conditions are met. Im thinking that this would make sense but can of course listen to others suggestions. Also im not entirely sure how much of a difference it makes for capture_method to be manual, but its only set that way on authorize calls but i tested a purchase call with this and it returns …
> Stripe PI: Add AFT fields

- CHANGELOG
- lib/active_merchant/billing/gateways/stripe_payment_intents.rb
- test/remote/gateways/remote_stripe_payment_intents_test.rb
- test/unit/gateways/stripe_payment_intents_test.rb
adds the optional request_extended_authorization field for authorization requests
local:
6206 tests, 81265 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
70 tests, 367 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
101 tests, 451 assertions, 3 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
97.0297% passed
A note about tests: I had tried to write a remote test for this and it fails due to account related issues. Here is the error message: "This account is not eligible for the requested card features. See https://stripe.com/docs/payments/flexible-payments for more details."
Given the error message, I do think stripe is acknowledging that this field is valid, but its just that our test …
> Stripe PI: add the request_extended_authorization field

- lib/active_merchant/billing/gateways/flex_charge.rb
- test/unit/gateways/flex_charge_test.rb
This changes the way that flex charge interprets a 'challenge' response depending on the 'async' gsf
Finished in 44.57413 seconds.
6212 tests, 81323 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Finished in 83.457291 seconds.
21 tests, 63 assertions, 1 failures, 0 errors, 0 pendings, 2 omissions, 0 notifications
94.7368% passed
> FlexCharge: Changing response interpretation for Async txns

- CHANGELOG
- lib/active_merchant/billing/gateways/plexo.rb
- test/remote/gateways/remote_plexo_test.rb
- test/unit/gateways/plexo_test.rb
Description
[SER-1592](https://spreedly.atlassian.net/browse/SER-1592)
This commit adds transaction sync for Plexo gateway, 
includes a small code refactoring on the commit method 
and updates the expiration year in the remote test.
Unit test
26 tests, 144 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote test
33 tests, 65 assertions, 3 failures, 0 errors, 0 pendings, 3 omissions, 0 notifications 90% passed
Rubocop
> Plexo: Add transaction Sync

- lib/active_merchant/billing/gateways/flex_charge.rb
- test/remote/gateways/remote_flex_charge_test.rb
- test/unit/gateways/flex_charge_test.rb
Adding `verificationValue` to `purchase` transaction
> FlexCharge: Include CVV in transactions

- lib/active_merchant/billing/gateways/commerce_hub.rb
- test/remote/gateways/remote_commerce_hub_test.rb
- test/unit/gateways/commerce_hub_test.rb
Spreedly reference: [OPPS-372](https://spreedly.atlassian.net/browse/OPPS-372)
Remote tests
Finished in 70.933066 seconds.
36 tests, 97 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
97.2222% passed
0.51 tests/s, 1.37 assertions/s
Unit tests
Finished in 50.661584 seconds.
6228 tests, 81395 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
122.93 tests/s, 1606.64 assertions/s
Rubocop
> Change Client-Request-Id from rand number to UUIDv4

- CHANGELOG
- lib/active_merchant/billing/gateways/nuvei.rb
- test/remote/gateways/remote_nuvei_test.rb
- test/unit/gateways/nuvei_test.rb
According to visa mandate we will need to send the DOB on both payout and aft transactions. This change adds and opens up the user_details object to allow for additional optional fields for both endpoints. Payouts and AFT transactions have the same field names, though /Payout does not have the language, county, and streetNumber fields. Nuvei expects 'birthdate' for payout transactions and 'dateOfBirth' for the purchase/auth endpoint.
You will have to follow the convention of also sending 'is_aft' or 'is_payout' as well as the correct corresponding 'user_details' fields.
Note: I know that the add_user_details is well guarded but for some extra measures, I wanted to ensure that if you were to initiate an AFT transaction, but sent the 'birthdate' instead, it will not add it in the if clause. …
> Nuvei: add addtional oct and aft user_details fields

- CHANGELOG
- lib/active_merchant/billing/gateways/checkout_v2.rb
- test/remote/gateways/remote_checkout_v2_test.rb
- test/unit/gateways/checkout_v2_test.rb
Adds the optional partial_authorization field
Local:
6228 tests, 81395 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
75 tests, 510 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
119 tests, 198 assertions, 68 failures, 4 errors, 0 pendings, 0 omissions, 0 notifications
39.4958% passed
Note: A lot of remote tests are failing and that’s kind of the expected and known behavior prior to approval of account fix. I was able to successfully get write a passing remote test for my change after using a UK processing ID to get the expected related response back for partial authorization.
> CheckoutV2: Add partial authorization field

- lib/active_merchant/billing/gateways/hi_pay.rb
- test/remote/gateways/remote_hi_pay_test.rb
Spreedly reference: [OPPS-377](https://spreedly.atlassian.net/browse/OPPS-377)
Add American Express credit card support to HiPay gateway
Disclaimer: Added a frictionless test because we only found this test card in [this](https://support.hipay.com/hc/en-us/articles/213882649-How-can-I-test-payment-methods) guide
> Add american express credit card support to HiPay gateway

- CHANGELOG
- lib/active_merchant/billing/gateways/datatrans.rb
- test/remote/gateways/remote_datatrans_test.rb
Populate the authorization in the capture response by the transaction_id used in the request.
Remote
27 tests, 76 assertions, 0 failures, 0 errors, 0 pendings, 1 omissions, 0 notifications 100% passed
> Datatrans: Update the authorization for Capture responses

- CHANGELOG
- lib/active_merchant/billing/gateways/cyber_source.rb
- test/remote/gateways/remote_cyber_source_test.rb
- test/unit/gateways/cyber_source_test.rb
Summary
Improve void request to handle cases where we
don't receive an authorization, (timeOuts cases)
[SER-1636](https://spreedly.atlassian.net/browse/SER-1636)
Unit Tests
Finished in 3.532173 seconds.
167 tests, 981 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote Tests
Finished in 127.168569 seconds.
143 tests, 730 assertions, 3 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 97.9021% passed
Rubocop
> CyberSource: Void Acepts nil values

- CHANGELOG
- lib/active_merchant/billing/gateways/datatrans.rb
- test/remote/gateways/remote_datatrans_test.rb
This adds an additional scrub for `pan` when the transaction is a `store`
> Include additional scrub on store call

- CHANGELOG
- lib/active_merchant/billing/gateways/decidir.rb
- lib/active_merchant/billing/gateways/decidir_plus.rb
- test/unit/gateways/decidir_plus_test.rb
- test/unit/gateways/decidir_test.rb
This adds the discover PM ID to decidir and decidir plus. @naashton I tagged you on here with a hopefully simple question. I noticed you had done a similar thing for patagonia_365 in this [PR](https://github.com/activemerchant/active_merchant/pull/5324) and said your remote test was not passing until the other PR was merged (which i think it was). However the remote test you wrote still failed for me, did you ever get it to work? I tried writing one for my changes and it gives me the same failure/error as yours, thanks!
Local:
6241 tests, 81487 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Decidir Unit:
48 tests, 237 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Decidir Remote:
29 tests, 99 assertions, 2 …
> Decidir/Decidir Plus: Add the discover payment method ID

- lib/active_merchant/billing/gateways/checkout_v2.rb
- test/remote/gateways/remote_checkout_v2_test.rb
- test/unit/gateways/checkout_v2_test.rb
Update field in sender object for AFT transactions to date_of_birth. This is what is now stated in their docs.
Unit Tests
75 tests, 510 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
Remote Tests
Hot Mess Express
Credentials issues, working to fix. The remote test I updated passes.
> Checkout: Bug fix for AFT date_of_birth

- CHANGELOG
- lib/active_merchant/billing/gateways/cyber_source.rb
- test/remote/gateways/remote_cyber_source_test.rb
- test/unit/gateways/cyber_source_test.rb
Adds the optional merchant reference number override on the capture endpoint.
Note: Im having issues running the remote tests for this since the introduction of line number 9 in the remote spec file:
@gateway_certificate = CyberSourceGateway.new({ nexus: 'NC' }.merge(fixtures(:cyber_source_certificate)))
Though hen i comment it out my remote spec will pass. I checked that the fixture is properly in place but still run into an argument error.
> CyberSource: Add the optional merchant reference number for capture

- CHANGELOG
- Gemfile
Remote
103 tests, 550 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> Braintree: Update gem to 4.26.0

- CHANGELOG
- lib/active_merchant/billing/gateways/payeezy.rb
- test/unit/gateways/payeezy_test.rb
If transaction_id in response has a extra space then use delete will be used to remove the spaces. This will prevent issues such as URI::InvalidURIError.
> Payeezy: Update authorization when extra space

- CHANGELOG
- lib/active_merchant/billing/gateways/worldpay.rb
- test/remote/gateways/remote_worldpay_test.rb
- test/unit/gateways/worldpay_test.rb
For the success_criteria in inquire now the options needs a original_action in order for inquire to have a proper state.
> Worldpay: Update inquire success_criteria

- CHANGELOG
- lib/active_merchant/billing/gateways/credorax.rb
- test/remote/gateways/remote_credorax_test.rb
- test/unit/gateways/credorax_test.rb
This supports the optional zero dollar verify for the credorax gateway. Per documentation when doing a zero $0 verify, we should be sending the a9 field set to the value 5, while skipping the subsequent void request. This change will also require the additional optional field of zero_dollar_auth to trigger said verify request. Also updated the remote test file to fix a handful of the failing tests
Local:
6244 tests, 81498 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
85 tests, 422 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
56 tests, 197 assertions, 6 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
89.2857% passed
The 6 failing remote tests are 3ds related and the error message …
> Credorax: support zero dollar verify

- CHANGELOG
- lib/active_merchant/billing/gateways/credorax.rb
- test/remote/gateways/remote_credorax_test.rb
- test/unit/gateways/credorax_test.rb
Adds the optional cryto_currency_field. 
The remote tests are failing as usual but a different PR (once merged) will address this.
Local:
6244 tests, 81497 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
85 tests, 421 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Credorax: Add optional crypto currency type field

- CHANGELOG
- lib/active_merchant/billing/gateways/commerce_hub.rb
- test/unit/gateways/commerce_hub_test.rb
Map ecommerce_indicator value from additionalData3DS to CommerceHub eciIndicator
[OPPS-414](https://spreedly.atlassian.net/browse/OPPS-414)
30 tests, 209 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
37 tests, 100 assertions, 3 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
91.8919% passed
809 files inspected, no offenses detected
> OPPS-414 - Mapped ecommerce_indicator value

- CHANGELOG
- lib/active_merchant/billing/gateways/stripe_payment_intents.rb
- test/remote/gateways/remote_stripe_payment_intents_test.rb
- test/unit/gateways/stripe_payment_intents_test.rb
Adds optional fields to enable compliant card statement descriptors for merchants operating in Japan.[ Stripe PI documentation](https://docs.stripe.com/get-started/account/statement-descriptors#set-japanese-statement-descriptors)
Local:
6244 tests, 81499 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
72 tests, 399 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
104 tests, 465 assertions, 3 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
97.1154% passed
> StripePI: add the optional kana_and_kanji_descriptor_suffix fields

- CHANGELOG
- lib/active_merchant/billing/gateways/credorax.rb
- test/remote/gateways/remote_credorax_test.rb
- test/unit/gateways/credorax_test.rb
Credorax: Add Sender Birth Date for AFT
Remote:
56 tests, 192 assertions, 9 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 
83.9286% passed
Unit
87 tests, 445 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Credorax: Add Sender Birth Date for AFT

- lib/active_merchant/billing/gateways/card_stream.rb
- test/unit/gateways/card_stream_test.rb
Cardstream: Accept custom API URL
Description
[OPPS-305](https://spreedly.atlassian.net/browse/OPPS-305)
Allow customers to pass customer API URL to use in their transactions
Unit test
Finished in 0.013669 seconds.
31 tests, 159 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
2267.91 tests/s, 11632.16 assertions/s
Rubocop
809 files inspected, no offenses detected
> Cardstream: Accept custom API URL

- CHANGELOG
- lib/active_merchant/billing/gateways/payflow.rb
- test/unit/gateways/payflow_test.rb
Payflow: send ds_trans_id as xid  if xid is not present
Remote Test
39 tests, 175 assertions, 9 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
76.9231% passed
Unit Test
59 tests, 367 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Payflow: send ds_trans_id as xid  if xid is not present

- CHANGELOG
- lib/active_merchant/billing/gateways/iveri.rb
- lib/active_merchant/billing/gateways/jetpay_v2.rb
- lib/active_merchant/billing/gateways/kushki.rb
- test/remote/gateways/remote_jetpay_v2_test.rb
- test/unit/gateways/iveri_test.rb
- test/unit/gateways/jetpay_v2_test.rb
- test/unit/gateways/kushki_test.rb
Summary:
Normalize the use of API_VERSION for some gateways (iVeri, JetypayV2 and Kushki)
Remote Tests: 
Jetpay_v2
20 tests, 93 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
iveri (Don’t have credential )
22 tests, 31 assertions, 19 failures, 1 errors, 0 pendings, 0 omissions, 0 notifications
9.09091% passed
Kushki (Don’t have credential )
25 tests, 0 assertions, 0 failures, 25 errors, 0 pendings, 0 omissions, 0 notifications
Unit Tests:
6246 tests, 81490 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Rubocop:
> Opps 198 normalize api versions

- CHANGELOG
- lib/active_merchant/billing/gateways/checkout_v2.rb
- test/remote/gateways/remote_checkout_v2_test.rb
- test/unit/gateways/checkout_v2_test.rb
CheckoutV2: Send payment type as Regular instead of unscheduled if initiator is cardholder
Remote:
120 tests, 293 assertions, 9 failures, 0 errors, 0 pendings, 1 omissions, 0 notifications
Unit:
77 tests, 517 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> CheckoutV2: Send payment type as Regular instead of unscheduled if initiator is cardholder

- CHANGELOG
- lib/active_merchant/billing/gateways/commerce_hub.rb
- test/unit/gateways/commerce_hub_test.rb
This updates now populates merchantOrderId & merchantInvoiceNumber with order_id for Verify.
Remote
37 tests, 100 assertions, 3 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 91.8919% passed
> CommerceHub: Pass order_id for Verify

- CHANGELOG
- lib/active_merchant/billing/gateways/orbital.rb
- test/remote/gateways/remote_orbital_test.rb
- test/unit/gateways/orbital_test.rb
If override_exp_data is in options pass it for Exp instead of the CreditCard expiration date.
Remote:
139 tests, 557 assertions, 0 failures, 1 errors, 0 pendings, 0 omissions, 1 notifications 99.2806% passed
> Orbital: Pass override_exp_date if provided

- CHANGELOG
- lib/active_merchant/billing/gateways/nuvei.rb
- test/remote/gateways/remote_nuvei_test.rb
[OPPS-440](https://spreedly.atlassian.net/browse/OPPS-440)
Map order_id to Nuvei clientUniqueId field on refund/credit transactions
Unit Tests:
---
Finished in 2.793984 seconds.
38 tests, 225 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
13.60 tests/s, 80.53 assertions/s
Remote Tests:
---
Finished in 170.526509 seconds.
48 tests, 159 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 
97.9167% passed
0.28 tests/s, 0.93 assertions/s
> Map order_id to Nuvei clientUniqueId field on refund/credit transactions

- CHANGELOG
- lib/active_merchant/billing/gateways/credorax.rb
- test/unit/gateways/credorax_test.rb
Fixed - `At least one of input parameters is malformed. Package has not been authorized.` due to invalid request sign
Ticket: [OPPS-400](https://spreedly.atlassian.net/browse/OPPS-400)
85 tests, 420 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
59 tests, 210 assertions, 6 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
89.8305% passed
809 files inspected, no offenses detected
> Fixed sign_request for Credorax gateway

- CHANGELOG
- lib/active_merchant/billing/gateway.rb
- lib/active_merchant/billing/gateways/mercado_pago.rb
- lib/active_merchant/billing/gateways/orbital.rb
- test/remote/gateways/remote_mercado_pago_test.rb
- test/unit/gateways/gateway_test.rb
- test/unit/gateways/orbital_test.rb
Update clean_emoji_emoticons_and_accent used in MercadoPago & Orbital to remove any non-word characters. Rename method to be format_name.
Remote Tests
Orbital:
140 tests, 563 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
MercadoPago:
45 tests, 131 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 95.5556% passed
> Update clean_emoji_emoticons_and_accent method

- CHANGELOG
- lib/active_merchant/billing/gateways/elavon.rb
- test/unit/gateways/elavon_test.rb
Pass through ssl_email for verify transactions.
Elavon Unit Test
61 tests, 358 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
> OPPS-482: Elavon: Verify - support for ssl_email

- CHANGELOG
- lib/active_merchant/billing/gateways/ebanx.rb
This change fixes the proper field nesting for a handful of optional fields. Currently they're being ignored and this will correct  that.
Local:
6298 tests, 81751 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
35 tests, 172 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
46 tests, 113 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> Ebanx: fix field nesting

- lib/active_merchant/billing/gateways/loan_payment_pro_ach.rb
Minor version bump and remove the `test` field from being passed
> LoanPaymentPro: Version bump and remove test field

- CHANGELOG
- lib/active_merchant/billing/gateways/litle.rb
- test/unit/gateways/litle_test.rb
Remove 141 & 141 from the successful codes since
Worldpay moved this back to 000.
> Litle: Remove 141 & 142

- CHANGELOG
- lib/active_merchant/billing/gateways/cyber_source_rest.rb
- lib/active_merchant/billing/gateways/datatrans.rb
- lib/active_merchant/billing/gateways/flex_charge.rb
- test/unit/gateways/cyber_source_rest_test.rb
- test/unit/gateways/datatrans_test.rb
- test/unit/gateways/flex_charge_test.rb
Normalizes API version handling across three payment gateways .This change enables runtime API version overrides and standardizes version management.
Tests:
Datatrans: 47 tests ✅ (100% pass)
CyberSource REST: 46 tests ✅ (100% pass)
FlexCharge: 36 tests ✅ (100% pass)
> Normalize API version for CyberSourceRest, Datatrans, and FlexCharge.

- CHANGELOG
- lib/active_merchant/billing/gateways/commerce_hub.rb
- lib/active_merchant/billing/gateways/wepay.rb
- lib/active_merchant/billing/gateways/wompi.rb
- test/unit/gateways/commerce_hub_test.rb
- test/unit/gateways/wepay_test.rb
- test/unit/gateways/wompi_test.rb
Normalizes API version handling across three payment gateways .This change enables runtime API version overrides and standardizes version management.
Remote Test Results:
wepay
27 tests, 45 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
96.2963% passed
wompi
14 tests, 27 assertions, 4 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
71.4286% passed
commerce_hub
37 tests, 100 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
94.5946% passed
> Normalize api versions for wepay, wompi and commerce hub

- CHANGELOG
- lib/active_merchant/billing/gateways/d_local.rb
- test/remote/gateways/remote_d_local_test.rb
- test/unit/gateways/d_local_test.rb
DLocal: Add issuer_identification_number as bin in Card object.
Remote Tests:
43 tests, 119 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 
100% passed
> DLocal: Add issuer_identification_number as bin in Card object.

- CHANGELOG
- lib/active_merchant/billing/gateways/litle.rb
- lib/active_merchant/billing/gateways/mercado_pago.rb
- lib/active_merchant/billing/gateways/mundipagg.rb
- test/unit/gateways/litle_test.rb
- test/unit/gateways/mercado_pago_test.rb
- test/unit/gateways/mundipagg_test.rb
Normalize API Versions for litle, mercado_pago and mundipagg gateways
**Remote**
Mercado pago
45 tests, 71 assertions, 29 failures, 2 errors, 0 pendings, 0 omissions, 0 notifications
31.1111% passed
Mundipagg
41 tests, 55 assertions, 38 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
7.31707% passed
Litle
60 tests, 207 assertions, 21 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
65% passed
> Normalize API Versions for litle, mercado_pago and mundipagg

- CHANGELOG
- lib/active_merchant/billing/gateways/barclaycard_smartpay.rb
- lib/active_merchant/billing/gateways/fat_zebra.rb
- lib/active_merchant/billing/gateways/forte.rb
- test/unit/gateways/barclaycard_smartpay_test.rb
- test/unit/gateways/fat_zebra_test.rb
- test/unit/gateways/forte_test.rb
Normalize API Versions for Barclay card Smart pay, Fat Zebra and Forte gateways
**Remote**
Forte Gateway
24 tests, 74 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Fat Zebra
30 tests, 104 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
93.3333% passed
Barclaycard Smartpay
38 tests, 0 assertions, 0 failures, 37 errors, 0 pendings, 0 omissions, 0 notifications
2.63158% passed
> Normalize API Versions for Barclay card Smart pay, Fat Zebra and Forte

- CHANGELOG
- lib/active_merchant/billing/gateways/worldpay.rb
- test/remote/gateways/remote_worldpay_test.rb
- test/unit/gateways/worldpay_test.rb
Adds the optional refund reference field.
Local:
6326 tests, 81841 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Unit:
147 tests, 802 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
128 tests, 550 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
> worldpay: add refund reference field

- CHANGELOG
- lib/active_merchant/billing/gateways/paysafe.rb
- test/remote/gateways/remote_paysafe_test.rb
- test/unit/gateways/paysafe_test.rb
If profile_id is provided in options then save the card to that exisiting profile.
Remote Tests:
36 tests, 107 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed
> Paysafe: Save cards to exisiting profiles

- CHANGELOG
- test/remote/gateways/remote_credorax_test.rb
credorax: fix spec for updated processor name
Remote Test:
59 tests, 210 assertions, 6 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
89.8305% passed
> credorax: fix spec for updated processor name

- CHANGELOG
- lib/active_merchant/billing/gateways/rapyd.rb
- lib/active_merchant/billing/gateways/safe_charge.rb
- lib/active_merchant/billing/gateways/secure_net.rb
- test/remote/gateways/remote_rapyd_test.rb
- test/unit/gateways/rapyd_test.rb
- test/unit/gateways/safe_charge_test.rb
Normalize API  for Rapyd, SafeCharge and SecureNet
Ticket : https://spreedly.atlassian.net/browse/OPPS-244
>  Normalize API  for Rapyd, SafeCharge and SecureNet

- CHANGELOG
- lib/active_merchant/billing/gateways/hps.rb
- lib/active_merchant/billing/gateways/pay_arc.rb
- lib/active_merchant/billing/gateways/pay_conex.rb
- test/unit/gateways/hps_test.rb
- test/unit/gateways/pay_arc_test.rb
- test/unit/gateways/pay_conex_test.rb
Normalized the use of API_VERSION across PayArc, PayConex, and HPS gateways in ActiveMerchant.
Remote Test Results:
PayArc
24 tests, 58 assertions, 11 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 54.1667% passed
PayConex
25 tests, 41 assertions, 16 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 36% passed
HPS
54 tests, 143 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 96.2963% passed
> PayArc/PayConex/HPS: Normalize the use of API_VERSION for some gateways

- CHANGELOG
- lib/active_merchant/billing/gateways/vantiv_express.rb
- test/remote/gateways/remote_vantiv_express_test.rb
- test/unit/gateways/vantiv_express_test.rb
Vantiv Express: Add support of level 2 and 3 data
reference link - https://docs.worldpay.com/apis/express/features/level-2-data
Remote Tests:
35 tests, 91 assertions, 4 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 88.5714% passed
Note - For now the the level 3 data is supported by capture only we can implement `CreditCardAdjustment` as well.
> Vantiv Express: Add support of level 2 and 3 data

- CHANGELOG
- lib/active_merchant/billing/gateways/paypal.rb
- lib/active_merchant/billing/gateways/paypal/paypal_common_api.rb
- lib/active_merchant/billing/gateways/paypal_express.rb
- lib/active_merchant/billing/gateways/paysafe.rb
- lib/active_merchant/billing/gateways/payu_latam.rb
- test/unit/gateways/paypal_express_test.rb
- test/unit/gateways/paypal_test.rb
- test/unit/gateways/paysafe_test.rb
- test/unit/gateways/payu_latam_test.rb
Normalize API versions for paypal, paysafe, and payu_latam
**Remote test result**
Paysafe:
33 tests, 98 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
Paypal:
31 tests, 86 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
96.7742% passed
Payu Latam:
39 tests, 59 assertions, 26 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
33.3333% passed
> Normalize API versions for paypal, paysafe, and payu_latam

- CHANGELOG
- lib/active_merchant/billing/gateways/pin.rb
- lib/active_merchant/billing/gateways/plexo.rb
- lib/active_merchant/billing/gateways/priority.rb
- test/unit/gateways/pin_test.rb
- test/unit/gateways/plexo_test.rb
- test/unit/gateways/priority_test.rb
Plexo:
> Remote:
>   34 tests, 70 assertions, 7 failures, 0 errors, 0 pendings, 3 omissions, 0 notifications
>   77.4194% passed
> Unit:
>   27 tests, 147 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
>   100% passed
> 
Pin:
> Remote:
>       25 tests, 74 assertions, 0 failures, 1 errors, 0 pendings, 0 omissions, 0 notifications
>       96% passed
>     Unit:
>       49 tests, 164 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
>       100% passed
Priority:
> Remote:
>       31 tests, 84 assertions, 6 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
>       80.6452% passed
>     Unit:
>       27 tests, 163 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
>       100% passed
> Normalize API versions for Priority, Pin and Plexo
